package tr.com.innova.akis.security;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.sql.DataSource;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

@Testcontainers
class V055RemoveExternalIdentityIT {

    private static final DockerImageName POSTGRES = DockerImageName.parse("postgres:17-alpine");

    @Container
    static final PostgreSQLContainer<?> POSTGRESQL = new PostgreSQLContainer<>(POSTGRES)
            .withDatabaseName("akis_test")
            .withUsername("akis")
            .withPassword("akis");

    private DataSource dataSource;

    @BeforeEach
    void connect() {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl(POSTGRESQL.getJdbcUrl());
        config.setUsername(POSTGRESQL.getUsername());
        config.setPassword(POSTGRESQL.getPassword());
        config.setMaximumPoolSize(2);
        dataSource = new HikariDataSource(config);
        runSql("drop schema if exists akis cascade");
        runSql("create schema akis");
    }

    @Test
    void dropsExternalIdentityWhenLocalRowsAreMigratedAndNoReferencesExist() {
        baselineThroughV054();
        seedLocalOnly();

        migrateV055();

        assertFalse(tableExists("harici_kimlik"));
        assertTrue(tableExists("harici_kimlik_drop_backup"));
    }

    @Test
    void rejectsWhenNonLocalExternalIdentityRemains() {
        baselineThroughV054();
        seedLocalOnly();
        runSql("""
                insert into akis.harici_kimlik(
                    kullanici_id, saglayici_turu, harici_kullanici_anahtari, yayinlayici)
                values ((select id from akis.kullanici limit 1), 'OIDC', 'oidc.user', 'corp-oidc')
                """);

        FlywayException thrown = assertThrows(FlywayException.class, this::migrateV055);
        assertTrue(thrown.getMessage().contains("Yerel dışı harici kimlik kayıtları mevcut"));
        assertTrue(tableExists("harici_kimlik"));
    }

    @Test
    void rejectsWhenCanonicalUserCodeDoesNotMatchExternalIdentity() {
        baselineThroughV054();
        runSql("""
                insert into akis.kullanici(
                    uuid, kullanici_kodu, ad, gorunen_ad, durum,
                    parola, parola_degistirilme_zamani)
                values (
                    '11111111-1111-1111-1111-111111111111', 'canonical', 'A', 'A', 'AKTIF',
                    '{argon2}test', current_timestamp)
                """);
        runSql("""
                insert into akis.harici_kimlik(
                    kullanici_id, saglayici_turu, harici_kullanici_anahtari)
                values ((select id from akis.kullanici where kullanici_kodu = 'canonical'), 'YEREL', 'canonical')
                """);
        runSql("update akis.kullanici set kullanici_kodu = 'different' where kullanici_kodu = 'canonical'");

        FlywayException thrown = assertThrows(FlywayException.class, this::migrateV055);
        assertTrue(thrown.getMessage().contains("yerel harici kimlikler kanonik kullanici kaydıyla eşleşmiyor"));
        assertTrue(tableExists("harici_kimlik"));
    }

    @Test
    void rejectsWhenExternalForeignKeyReferencesExist() {
        baselineThroughV054();
        seedLocalOnly();
        runSql("""
                create table akis.external_identity_reference (
                    id bigint generated by default as identity primary key,
                    harici_kimlik_id bigint not null references akis.harici_kimlik(id)
                )
                """);

        FlywayException thrown = assertThrows(FlywayException.class, this::migrateV055);
        assertTrue(thrown.getMessage().contains("harici_kimlik tablosuna dış referanslar mevcut"));
        assertTrue(tableExists("harici_kimlik"));
    }

    private void baselineThroughV054() {
        Flyway flyway = Flyway.configure()
                .dataSource(dataSource)
                .locations("classpath:db/akis")
                .schemas("akis")
                .defaultSchema("akis")
                .createSchemas(true)
                .target("54")
                .load();
        flyway.migrate();
    }

    private void migrateV055() {
        Flyway flyway = Flyway.configure()
                .dataSource(dataSource)
                .locations("classpath:db/akis")
                .schemas("akis")
                .defaultSchema("akis")
                .target("55")
                .load();
        flyway.migrate();
    }

    private void seedLocalOnly() {
        runSql("""
                insert into akis.kullanici(
                    uuid, kullanici_kodu, ad, gorunen_ad, durum,
                    parola, parola_degistirilme_zamani)
                values (
                    '22222222-2222-2222-2222-222222222222', 'local.user', 'Local', 'Local User', 'AKTIF',
                    '{argon2}test', current_timestamp)
                """);
        runSql("""
                insert into akis.harici_kimlik(
                    kullanici_id, saglayici_turu, harici_kullanici_anahtari)
                values ((select id from akis.kullanici where kullanici_kodu = 'local.user'), 'YEREL', 'local.user')
                """);
    }

    private void runSql(String sql) {
        try (Connection connection = dataSource.getConnection();
             var statement = connection.createStatement()) {
            statement.execute(sql);
        }
        catch (SQLException exception) {
            throw new IllegalStateException("Test SQL failed: " + sql, exception);
        }
    }

    private boolean tableExists(String tableName) {
        try (Connection connection = dataSource.getConnection();
             var statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("""
                     select 1 from information_schema.tables
                     where table_schema = 'akis' and table_name = '%s'
                     """.formatted(tableName))) {
            return rs.next();
        }
        catch (SQLException exception) {
            throw new IllegalStateException("Failed to check table existence", exception);
        }
    }
}
