CREATE OR REPLACE PACKAGE ETL_KANIT_PKG AUTHID DEFINER AS
    PROCEDURE ACQUIRE_FENCE(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_FENCE_TOKEN IN NUMBER,
        P_JOB_UUID IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2);

    PROCEDURE LOCK_FENCE(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_FENCE_TOKEN IN NUMBER,
        P_JOB_UUID IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2);

    PROCEDURE READ_FENCE(
        P_TARGET_KEY_HASH IN VARCHAR2,
        O_FOUND OUT NUMBER,
        O_FENCE_TOKEN OUT NUMBER,
        O_JOB_UUID OUT VARCHAR2,
        O_RUN_UUID OUT VARCHAR2,
        O_ATTEMPT_NO OUT NUMBER,
        O_RELEASE_HASH OUT VARCHAR2,
        O_PLAN_HASH OUT VARCHAR2,
        O_UPDATED_AT OUT TIMESTAMP WITH TIME ZONE);

    PROCEDURE PREPARE_BATCH(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PARTITION_CODE IN VARCHAR2,
        P_BATCH_KEY_HASH IN VARCHAR2,
        P_BATCH_NO IN NUMBER,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_PAYLOAD_HASH IN VARCHAR2,
        P_ROW_COUNT IN NUMBER,
        P_BYTE_COUNT IN NUMBER,
        O_TX_GUARD OUT VARCHAR2,
        O_ALREADY_RECORDED OUT NUMBER);

    PROCEDURE RECORD_BATCH(
        P_TX_GUARD IN VARCHAR2,
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PARTITION_CODE IN VARCHAR2,
        P_BATCH_KEY_HASH IN VARCHAR2,
        P_BATCH_NO IN NUMBER,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_PAYLOAD_HASH IN VARCHAR2,
        P_ROW_COUNT IN NUMBER,
        P_BYTE_COUNT IN NUMBER);

    PROCEDURE VERIFY_BATCH(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PARTITION_CODE IN VARCHAR2,
        P_BATCH_KEY_HASH IN VARCHAR2,
        P_BATCH_NO IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_PAYLOAD_HASH IN VARCHAR2,
        P_ROW_COUNT IN NUMBER,
        P_BYTE_COUNT IN NUMBER,
        O_MATCH OUT NUMBER,
        O_RECORDED_RUN_UUID OUT VARCHAR2,
        O_RECORDED_ATTEMPT_NO OUT NUMBER,
        O_RECORDED_FENCE_TOKEN OUT NUMBER,
        O_EVIDENCE_AT OUT TIMESTAMP WITH TIME ZONE);

    PROCEDURE PREPARE_PUBLISH(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PUBLISH_KEY_HASH IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_STAGE_HASH IN VARCHAR2,
        P_STAGE_ROW_COUNT IN NUMBER,
        P_PUBLISHED_ROW_COUNT IN NUMBER,
        P_REJECTED_ROW_COUNT IN NUMBER,
        P_LOWER_WATERMARK IN VARCHAR2,
        P_UPPER_WATERMARK IN VARCHAR2,
        O_TX_GUARD OUT VARCHAR2,
        O_ALREADY_RECORDED OUT NUMBER);

    PROCEDURE RECORD_PUBLISH(
        P_TX_GUARD IN VARCHAR2,
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PUBLISH_KEY_HASH IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_STAGE_HASH IN VARCHAR2,
        P_STAGE_ROW_COUNT IN NUMBER,
        P_PUBLISHED_ROW_COUNT IN NUMBER,
        P_REJECTED_ROW_COUNT IN NUMBER,
        P_LOWER_WATERMARK IN VARCHAR2,
        P_UPPER_WATERMARK IN VARCHAR2);

    PROCEDURE VERIFY_PUBLISH(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PUBLISH_KEY_HASH IN VARCHAR2,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_STAGE_HASH IN VARCHAR2,
        P_STAGE_ROW_COUNT IN NUMBER,
        P_PUBLISHED_ROW_COUNT IN NUMBER,
        P_REJECTED_ROW_COUNT IN NUMBER,
        P_LOWER_WATERMARK IN VARCHAR2,
        P_UPPER_WATERMARK IN VARCHAR2,
        O_MATCH OUT NUMBER,
        O_RECORDED_RUN_UUID OUT VARCHAR2,
        O_RECORDED_ATTEMPT_NO OUT NUMBER,
        O_RECORDED_FENCE_TOKEN OUT NUMBER,
        O_EVIDENCE_AT OUT TIMESTAMP WITH TIME ZONE);
END ETL_KANIT_PKG;
/

CREATE OR REPLACE PACKAGE BODY ETL_KANIT_PKG AS
    C_MAX_TOKEN CONSTANT NUMBER := 9223372036854775807;

    G_BATCH_GUARD VARCHAR2(32);
    G_BATCH_TX_ID VARCHAR2(128);
    G_BATCH_SIGNATURE VARCHAR2(32767);
    G_PUBLISH_GUARD VARCHAR2(32);
    G_PUBLISH_TX_ID VARCHAR2(128);
    G_PUBLISH_SIGNATURE VARCHAR2(32767);

    FUNCTION ENCODE_PART(P_VALUE IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        IF P_VALUE IS NULL THEN
            RETURN '-:';
        END IF;
        RETURN TO_CHAR(LENGTHB(P_VALUE), 'TM9') || ':' || P_VALUE;
    END;

    FUNCTION ENCODE_NUMBER(P_VALUE IN NUMBER) RETURN VARCHAR2 IS
    BEGIN
        IF P_VALUE IS NULL THEN
            RETURN '-:';
        END IF;
        RETURN ENCODE_PART(TO_CHAR(
            P_VALUE, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,'''));
    END;

    FUNCTION SAME_TEXT(P_LEFT IN VARCHAR2, P_RIGHT IN VARCHAR2)
        RETURN BOOLEAN IS
    BEGIN
        IF P_LEFT IS NULL AND P_RIGHT IS NULL THEN
            RETURN TRUE;
        ELSIF P_LEFT IS NULL OR P_RIGHT IS NULL THEN
            RETURN FALSE;
        END IF;
        RETURN P_LEFT = P_RIGHT;
    END;

    PROCEDURE ASSERT_HASH(P_VALUE IN VARCHAR2, P_NAME IN VARCHAR2) IS
    BEGIN
        IF P_VALUE IS NULL OR LENGTH(P_VALUE) <> 64 OR
           NOT REGEXP_LIKE(P_VALUE, '^[0-9a-f]{64}$', 'c') THEN
            RAISE_APPLICATION_ERROR(-20001, P_NAME || ' must be lowercase SHA-256');
        END IF;
    END;

    PROCEDURE ASSERT_UUID(P_VALUE IN VARCHAR2, P_NAME IN VARCHAR2) IS
    BEGIN
        IF P_VALUE IS NULL OR LENGTH(P_VALUE) <> 36 OR
           NOT REGEXP_LIKE(
               P_VALUE,
               '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
               'c') THEN
            RAISE_APPLICATION_ERROR(-20002, P_NAME || ' must be a canonical lowercase UUID');
        END IF;
    END;

    PROCEDURE ASSERT_CODE(P_VALUE IN VARCHAR2, P_NAME IN VARCHAR2) IS
    BEGIN
        IF P_VALUE IS NULL OR LENGTHB(P_VALUE) > 128 OR
           NOT REGEXP_LIKE(P_VALUE, '^[A-Za-z0-9_.:-]+$', 'c') THEN
            RAISE_APPLICATION_ERROR(-20003, P_NAME || ' is not a canonical code');
        END IF;
    END;

    PROCEDURE ASSERT_POSITIVE(P_VALUE IN NUMBER, P_NAME IN VARCHAR2) IS
    BEGIN
        IF P_VALUE IS NULL OR P_VALUE <= 0 OR P_VALUE <> TRUNC(P_VALUE) THEN
            RAISE_APPLICATION_ERROR(-20004, P_NAME || ' must be a positive integer');
        END IF;
    END;

    PROCEDURE ASSERT_NONNEGATIVE(P_VALUE IN NUMBER, P_NAME IN VARCHAR2) IS
    BEGIN
        IF P_VALUE IS NULL OR P_VALUE < 0 OR P_VALUE <> TRUNC(P_VALUE) OR
           P_VALUE > C_MAX_TOKEN THEN
            RAISE_APPLICATION_ERROR(-20005, P_NAME || ' must be a nonnegative integer');
        END IF;
    END;

    PROCEDURE ASSERT_TOKEN(P_VALUE IN NUMBER) IS
    BEGIN
        ASSERT_POSITIVE(P_VALUE, 'fence token');
        IF P_VALUE > C_MAX_TOKEN THEN
            RAISE_APPLICATION_ERROR(-20006, 'fence token exceeds signed 64-bit range');
        END IF;
    END;

    -- V2 entry-point guard. Fence acquisition and every new write/publish
    -- transaction must start on a connection with no pre-existing Oracle local
    -- transaction. This is private so a runtime account still needs only EXECUTE
    -- on ETL_KANIT_PKG.
    PROCEDURE ASSERT_CLEAN_TRANSACTION IS
        V_TX_ID VARCHAR2(128) := DBMS_TRANSACTION.LOCAL_TRANSACTION_ID(FALSE);
    BEGIN
        IF V_TX_ID IS NOT NULL THEN
            RAISE_APPLICATION_ERROR(
                -20026,
                'operation requires a clean Oracle transaction boundary');
        END IF;
    END;

    PROCEDURE ASSERT_OWNER(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_FENCE_TOKEN IN NUMBER,
        P_JOB_UUID IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2) IS
    BEGIN
        ASSERT_HASH(P_TARGET_KEY_HASH, 'target key hash');
        ASSERT_TOKEN(P_FENCE_TOKEN);
        ASSERT_UUID(P_JOB_UUID, 'job UUID');
        ASSERT_UUID(P_RUN_UUID, 'run UUID');
        ASSERT_POSITIVE(P_ATTEMPT_NO, 'attempt number');
        ASSERT_HASH(P_RELEASE_HASH, 'release hash');
        ASSERT_HASH(P_PLAN_HASH, 'plan hash');
    END;

    PROCEDURE LOCK_AND_VERIFY_FENCE(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_FENCE_TOKEN IN NUMBER,
        P_JOB_UUID IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2) IS
        V_TOKEN NUMBER;
        V_JOB VARCHAR2(36);
        V_RUN VARCHAR2(36);
        V_ATTEMPT NUMBER;
        V_RELEASE VARCHAR2(64);
        V_PLAN VARCHAR2(64);
    BEGIN
        ASSERT_OWNER(
            P_TARGET_KEY_HASH, P_FENCE_TOKEN, P_JOB_UUID, P_RUN_UUID,
            P_ATTEMPT_NO, P_RELEASE_HASH, P_PLAN_HASH);
        BEGIN
            SELECT FENCE_TOKEN, OWNER_JOB_UUID, OWNER_RUN_UUID,
                   OWNER_ATTEMPT_NO, RELEASE_HASH, PLAN_HASH
              INTO V_TOKEN, V_JOB, V_RUN, V_ATTEMPT, V_RELEASE, V_PLAN
              FROM ETL_YUKLEME_KILIDI
             WHERE TARGET_KEY_HASH = P_TARGET_KEY_HASH
               FOR UPDATE;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20010, 'target fence does not exist');
        END;

        IF V_TOKEN <> P_FENCE_TOKEN OR V_JOB <> P_JOB_UUID OR
           V_RUN <> P_RUN_UUID OR V_ATTEMPT <> P_ATTEMPT_NO OR
           V_RELEASE <> P_RELEASE_HASH OR V_PLAN <> P_PLAN_HASH THEN
            RAISE_APPLICATION_ERROR(-20011, 'target fence ownership does not match');
        END IF;
    END;

    FUNCTION BATCH_SIGNATURE(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PARTITION_CODE IN VARCHAR2,
        P_BATCH_KEY_HASH IN VARCHAR2,
        P_BATCH_NO IN NUMBER,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_PAYLOAD_HASH IN VARCHAR2,
        P_ROW_COUNT IN NUMBER,
        P_BYTE_COUNT IN NUMBER) RETURN VARCHAR2 IS
    BEGIN
        RETURN ENCODE_PART(P_TARGET_KEY_HASH) || ENCODE_PART(P_JOB_UUID) ||
            ENCODE_PART(P_STEP_CODE) || ENCODE_PART(P_PARTITION_CODE) ||
            ENCODE_PART(P_BATCH_KEY_HASH) || ENCODE_NUMBER(P_BATCH_NO) ||
            ENCODE_PART(P_RUN_UUID) || ENCODE_NUMBER(P_ATTEMPT_NO) ||
            ENCODE_NUMBER(P_FENCE_TOKEN) || ENCODE_PART(P_RELEASE_HASH) ||
            ENCODE_PART(P_PLAN_HASH) || ENCODE_PART(P_PAYLOAD_HASH) ||
            ENCODE_NUMBER(P_ROW_COUNT) || ENCODE_NUMBER(P_BYTE_COUNT);
    END;

    FUNCTION PUBLISH_SIGNATURE(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PUBLISH_KEY_HASH IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_STAGE_HASH IN VARCHAR2,
        P_STAGE_ROW_COUNT IN NUMBER,
        P_PUBLISHED_ROW_COUNT IN NUMBER,
        P_REJECTED_ROW_COUNT IN NUMBER,
        P_LOWER_WATERMARK IN VARCHAR2,
        P_UPPER_WATERMARK IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN ENCODE_PART(P_TARGET_KEY_HASH) || ENCODE_PART(P_JOB_UUID) ||
            ENCODE_PART(P_STEP_CODE) || ENCODE_PART(P_PUBLISH_KEY_HASH) ||
            ENCODE_PART(P_RUN_UUID) || ENCODE_NUMBER(P_ATTEMPT_NO) ||
            ENCODE_NUMBER(P_FENCE_TOKEN) || ENCODE_PART(P_RELEASE_HASH) ||
            ENCODE_PART(P_PLAN_HASH) || ENCODE_PART(P_STAGE_HASH) ||
            ENCODE_NUMBER(P_STAGE_ROW_COUNT) ||
            ENCODE_NUMBER(P_PUBLISHED_ROW_COUNT) ||
            ENCODE_NUMBER(P_REJECTED_ROW_COUNT) ||
            ENCODE_PART(P_LOWER_WATERMARK) || ENCODE_PART(P_UPPER_WATERMARK);
    END;

    PROCEDURE CLEAR_STALE_GUARDS IS
        V_TX_ID VARCHAR2(128) := DBMS_TRANSACTION.LOCAL_TRANSACTION_ID(FALSE);
    BEGIN
        IF G_BATCH_GUARD IS NOT NULL AND
           (V_TX_ID IS NULL OR V_TX_ID <> G_BATCH_TX_ID) THEN
            G_BATCH_GUARD := NULL;
            G_BATCH_TX_ID := NULL;
            G_BATCH_SIGNATURE := NULL;
        END IF;
        IF G_PUBLISH_GUARD IS NOT NULL AND
           (V_TX_ID IS NULL OR V_TX_ID <> G_PUBLISH_TX_ID) THEN
            G_PUBLISH_GUARD := NULL;
            G_PUBLISH_TX_ID := NULL;
            G_PUBLISH_SIGNATURE := NULL;
        END IF;
    END;

    PROCEDURE ACQUIRE_FENCE(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_FENCE_TOKEN IN NUMBER,
        P_JOB_UUID IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2) IS
        V_TOKEN NUMBER;
        V_JOB VARCHAR2(36);
        V_RUN VARCHAR2(36);
        V_ATTEMPT NUMBER;
        V_RELEASE VARCHAR2(64);
        V_PLAN VARCHAR2(64);
    BEGIN
        ASSERT_CLEAN_TRANSACTION;
        ASSERT_OWNER(
            P_TARGET_KEY_HASH, P_FENCE_TOKEN, P_JOB_UUID, P_RUN_UUID,
            P_ATTEMPT_NO, P_RELEASE_HASH, P_PLAN_HASH);
        BEGIN
            SELECT FENCE_TOKEN, OWNER_JOB_UUID, OWNER_RUN_UUID,
                   OWNER_ATTEMPT_NO, RELEASE_HASH, PLAN_HASH
              INTO V_TOKEN, V_JOB, V_RUN, V_ATTEMPT, V_RELEASE, V_PLAN
              FROM ETL_YUKLEME_KILIDI
             WHERE TARGET_KEY_HASH = P_TARGET_KEY_HASH
               FOR UPDATE;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                BEGIN
                    INSERT INTO ETL_YUKLEME_KILIDI(
                        TARGET_KEY_HASH, FENCE_TOKEN, OWNER_JOB_UUID,
                        OWNER_RUN_UUID, OWNER_ATTEMPT_NO,
                        RELEASE_HASH, PLAN_HASH, UPDATED_AT)
                    VALUES (
                        P_TARGET_KEY_HASH, P_FENCE_TOKEN, P_JOB_UUID,
                        P_RUN_UUID, P_ATTEMPT_NO,
                        P_RELEASE_HASH, P_PLAN_HASH, SYSTIMESTAMP);
                    RETURN;
                EXCEPTION
                    WHEN DUP_VAL_ON_INDEX THEN
                        SELECT FENCE_TOKEN, OWNER_JOB_UUID, OWNER_RUN_UUID,
                               OWNER_ATTEMPT_NO, RELEASE_HASH, PLAN_HASH
                          INTO V_TOKEN, V_JOB, V_RUN, V_ATTEMPT, V_RELEASE, V_PLAN
                          FROM ETL_YUKLEME_KILIDI
                         WHERE TARGET_KEY_HASH = P_TARGET_KEY_HASH
                           FOR UPDATE;
                END;
        END;

        IF P_FENCE_TOKEN < V_TOKEN THEN
            RAISE_APPLICATION_ERROR(-20012, 'stale target fence token');
        ELSIF P_FENCE_TOKEN = V_TOKEN THEN
            IF V_JOB <> P_JOB_UUID OR V_RUN <> P_RUN_UUID OR
               V_ATTEMPT <> P_ATTEMPT_NO OR V_RELEASE <> P_RELEASE_HASH OR
               V_PLAN <> P_PLAN_HASH THEN
                RAISE_APPLICATION_ERROR(-20013, 'same fence token has a different owner');
            END IF;
            RETURN;
        END IF;

        UPDATE ETL_YUKLEME_KILIDI
           SET FENCE_TOKEN = P_FENCE_TOKEN,
               OWNER_JOB_UUID = P_JOB_UUID,
               OWNER_RUN_UUID = P_RUN_UUID,
               OWNER_ATTEMPT_NO = P_ATTEMPT_NO,
               RELEASE_HASH = P_RELEASE_HASH,
               PLAN_HASH = P_PLAN_HASH,
               UPDATED_AT = SYSTIMESTAMP
         WHERE TARGET_KEY_HASH = P_TARGET_KEY_HASH;
    END;

    PROCEDURE LOCK_FENCE(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_FENCE_TOKEN IN NUMBER,
        P_JOB_UUID IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2) IS
    BEGIN
        ASSERT_CLEAN_TRANSACTION;
        LOCK_AND_VERIFY_FENCE(
            P_TARGET_KEY_HASH, P_FENCE_TOKEN, P_JOB_UUID, P_RUN_UUID,
            P_ATTEMPT_NO, P_RELEASE_HASH, P_PLAN_HASH);
    END;

    PROCEDURE READ_FENCE(
        P_TARGET_KEY_HASH IN VARCHAR2,
        O_FOUND OUT NUMBER,
        O_FENCE_TOKEN OUT NUMBER,
        O_JOB_UUID OUT VARCHAR2,
        O_RUN_UUID OUT VARCHAR2,
        O_ATTEMPT_NO OUT NUMBER,
        O_RELEASE_HASH OUT VARCHAR2,
        O_PLAN_HASH OUT VARCHAR2,
        O_UPDATED_AT OUT TIMESTAMP WITH TIME ZONE) IS
    BEGIN
        ASSERT_HASH(P_TARGET_KEY_HASH, 'target key hash');
        O_FOUND := 0;
        O_FENCE_TOKEN := NULL;
        O_JOB_UUID := NULL;
        O_RUN_UUID := NULL;
        O_ATTEMPT_NO := NULL;
        O_RELEASE_HASH := NULL;
        O_PLAN_HASH := NULL;
        O_UPDATED_AT := NULL;
        BEGIN
            SELECT FENCE_TOKEN, OWNER_JOB_UUID, OWNER_RUN_UUID,
                   OWNER_ATTEMPT_NO, RELEASE_HASH, PLAN_HASH, UPDATED_AT
              INTO O_FENCE_TOKEN, O_JOB_UUID, O_RUN_UUID,
                   O_ATTEMPT_NO, O_RELEASE_HASH, O_PLAN_HASH, O_UPDATED_AT
              FROM ETL_YUKLEME_KILIDI
             WHERE TARGET_KEY_HASH = P_TARGET_KEY_HASH;
            O_FOUND := 1;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN NULL;
        END;
    END;

    PROCEDURE ASSERT_BATCH_INPUTS(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PARTITION_CODE IN VARCHAR2,
        P_BATCH_KEY_HASH IN VARCHAR2,
        P_BATCH_NO IN NUMBER,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_PAYLOAD_HASH IN VARCHAR2,
        P_ROW_COUNT IN NUMBER,
        P_BYTE_COUNT IN NUMBER) IS
    BEGIN
        ASSERT_OWNER(
            P_TARGET_KEY_HASH, P_FENCE_TOKEN, P_JOB_UUID, P_RUN_UUID,
            P_ATTEMPT_NO, P_RELEASE_HASH, P_PLAN_HASH);
        ASSERT_CODE(P_STEP_CODE, 'step code');
        ASSERT_CODE(P_PARTITION_CODE, 'partition code');
        ASSERT_HASH(P_BATCH_KEY_HASH, 'batch key hash');
        ASSERT_NONNEGATIVE(P_BATCH_NO, 'batch number');
        ASSERT_HASH(P_PAYLOAD_HASH, 'payload hash');
        ASSERT_NONNEGATIVE(P_ROW_COUNT, 'row count');
        ASSERT_NONNEGATIVE(P_BYTE_COUNT, 'byte count');
    END;

    PROCEDURE PREPARE_BATCH(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PARTITION_CODE IN VARCHAR2,
        P_BATCH_KEY_HASH IN VARCHAR2,
        P_BATCH_NO IN NUMBER,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_PAYLOAD_HASH IN VARCHAR2,
        P_ROW_COUNT IN NUMBER,
        P_BYTE_COUNT IN NUMBER,
        O_TX_GUARD OUT VARCHAR2,
        O_ALREADY_RECORDED OUT NUMBER) IS
        V_BATCH_NO NUMBER;
        V_RELEASE VARCHAR2(64);
        V_PLAN VARCHAR2(64);
        V_PAYLOAD VARCHAR2(64);
        V_ROWS NUMBER;
        V_BYTES NUMBER;
        V_BATCH_NO_COLLISION NUMBER;
    BEGIN
        ASSERT_CLEAN_TRANSACTION;
        O_TX_GUARD := NULL;
        O_ALREADY_RECORDED := 0;
        CLEAR_STALE_GUARDS;
        IF G_BATCH_GUARD IS NOT NULL THEN
            RAISE_APPLICATION_ERROR(-20014, 'a batch guard is already active in this transaction');
        END IF;
        ASSERT_BATCH_INPUTS(
            P_TARGET_KEY_HASH, P_JOB_UUID, P_STEP_CODE, P_PARTITION_CODE,
            P_BATCH_KEY_HASH, P_BATCH_NO, P_RUN_UUID, P_ATTEMPT_NO,
            P_FENCE_TOKEN, P_RELEASE_HASH, P_PLAN_HASH, P_PAYLOAD_HASH,
            P_ROW_COUNT, P_BYTE_COUNT);
        LOCK_AND_VERIFY_FENCE(
            P_TARGET_KEY_HASH, P_FENCE_TOKEN, P_JOB_UUID, P_RUN_UUID,
            P_ATTEMPT_NO, P_RELEASE_HASH, P_PLAN_HASH);

        BEGIN
            SELECT BATCH_NO, RELEASE_HASH, PLAN_HASH, PAYLOAD_HASH,
                   ROW_COUNT, BYTE_COUNT
              INTO V_BATCH_NO, V_RELEASE, V_PLAN, V_PAYLOAD, V_ROWS, V_BYTES
              FROM ETL_YUKLEME_DEFTERI
             WHERE TARGET_KEY_HASH = P_TARGET_KEY_HASH
               AND JOB_UUID = P_JOB_UUID
               AND STEP_CODE = P_STEP_CODE
               AND PARTITION_CODE = P_PARTITION_CODE
               AND BATCH_KEY_HASH = P_BATCH_KEY_HASH;
            IF V_BATCH_NO <> P_BATCH_NO OR V_RELEASE <> P_RELEASE_HASH OR
               V_PLAN <> P_PLAN_HASH OR V_PAYLOAD <> P_PAYLOAD_HASH OR
               V_ROWS <> P_ROW_COUNT OR V_BYTES <> P_BYTE_COUNT THEN
                RAISE_APPLICATION_ERROR(-20015, 'batch evidence conflicts with existing marker');
            END IF;
            O_ALREADY_RECORDED := 1;
            RETURN;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN NULL;
        END;

        SELECT COUNT(*) INTO V_BATCH_NO_COLLISION
          FROM ETL_YUKLEME_DEFTERI
         WHERE TARGET_KEY_HASH = P_TARGET_KEY_HASH
           AND JOB_UUID = P_JOB_UUID
           AND STEP_CODE = P_STEP_CODE
           AND PARTITION_CODE = P_PARTITION_CODE
           AND BATCH_NO = P_BATCH_NO;
        IF V_BATCH_NO_COLLISION <> 0 THEN
            RAISE_APPLICATION_ERROR(-20016, 'batch number maps to a different batch key');
        END IF;

        G_BATCH_GUARD := LOWER(RAWTOHEX(SYS_GUID()));
        G_BATCH_TX_ID := DBMS_TRANSACTION.LOCAL_TRANSACTION_ID(TRUE);
        G_BATCH_SIGNATURE := BATCH_SIGNATURE(
            P_TARGET_KEY_HASH, P_JOB_UUID, P_STEP_CODE, P_PARTITION_CODE,
            P_BATCH_KEY_HASH, P_BATCH_NO, P_RUN_UUID, P_ATTEMPT_NO,
            P_FENCE_TOKEN, P_RELEASE_HASH, P_PLAN_HASH, P_PAYLOAD_HASH,
            P_ROW_COUNT, P_BYTE_COUNT);
        IF G_BATCH_TX_ID IS NULL THEN
            RAISE_APPLICATION_ERROR(-20017, 'batch preparation has no local transaction');
        END IF;
        O_TX_GUARD := G_BATCH_GUARD;
    END;

    PROCEDURE RECORD_BATCH(
        P_TX_GUARD IN VARCHAR2,
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PARTITION_CODE IN VARCHAR2,
        P_BATCH_KEY_HASH IN VARCHAR2,
        P_BATCH_NO IN NUMBER,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_PAYLOAD_HASH IN VARCHAR2,
        P_ROW_COUNT IN NUMBER,
        P_BYTE_COUNT IN NUMBER) IS
        V_SIGNATURE VARCHAR2(32767);
        V_TX_ID VARCHAR2(128);
    BEGIN
        ASSERT_BATCH_INPUTS(
            P_TARGET_KEY_HASH, P_JOB_UUID, P_STEP_CODE, P_PARTITION_CODE,
            P_BATCH_KEY_HASH, P_BATCH_NO, P_RUN_UUID, P_ATTEMPT_NO,
            P_FENCE_TOKEN, P_RELEASE_HASH, P_PLAN_HASH, P_PAYLOAD_HASH,
            P_ROW_COUNT, P_BYTE_COUNT);
        V_TX_ID := DBMS_TRANSACTION.LOCAL_TRANSACTION_ID(FALSE);
        V_SIGNATURE := BATCH_SIGNATURE(
            P_TARGET_KEY_HASH, P_JOB_UUID, P_STEP_CODE, P_PARTITION_CODE,
            P_BATCH_KEY_HASH, P_BATCH_NO, P_RUN_UUID, P_ATTEMPT_NO,
            P_FENCE_TOKEN, P_RELEASE_HASH, P_PLAN_HASH, P_PAYLOAD_HASH,
            P_ROW_COUNT, P_BYTE_COUNT);
        IF P_TX_GUARD IS NULL OR G_BATCH_GUARD IS NULL OR
           P_TX_GUARD <> G_BATCH_GUARD OR
           V_TX_ID IS NULL OR V_TX_ID <> G_BATCH_TX_ID OR
           V_SIGNATURE <> G_BATCH_SIGNATURE THEN
            RAISE_APPLICATION_ERROR(-20018, 'batch record is not owned by its preparation transaction');
        END IF;
        LOCK_AND_VERIFY_FENCE(
            P_TARGET_KEY_HASH, P_FENCE_TOKEN, P_JOB_UUID, P_RUN_UUID,
            P_ATTEMPT_NO, P_RELEASE_HASH, P_PLAN_HASH);
        BEGIN
            INSERT INTO ETL_YUKLEME_DEFTERI(
                TARGET_KEY_HASH, JOB_UUID, STEP_CODE, PARTITION_CODE,
                BATCH_KEY_HASH, BATCH_NO, RUN_UUID, ATTEMPT_NO,
                FENCE_TOKEN, RELEASE_HASH, PLAN_HASH, PAYLOAD_HASH,
                ROW_COUNT, BYTE_COUNT, EVIDENCE_AT)
            VALUES (
                P_TARGET_KEY_HASH, P_JOB_UUID, P_STEP_CODE, P_PARTITION_CODE,
                P_BATCH_KEY_HASH, P_BATCH_NO, P_RUN_UUID, P_ATTEMPT_NO,
                P_FENCE_TOKEN, P_RELEASE_HASH, P_PLAN_HASH, P_PAYLOAD_HASH,
                P_ROW_COUNT, P_BYTE_COUNT, SYSTIMESTAMP);
        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
                RAISE_APPLICATION_ERROR(-20019, 'batch marker uniqueness changed after preparation');
        END;
        G_BATCH_GUARD := NULL;
        G_BATCH_TX_ID := NULL;
        G_BATCH_SIGNATURE := NULL;
    END;

    PROCEDURE VERIFY_BATCH(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PARTITION_CODE IN VARCHAR2,
        P_BATCH_KEY_HASH IN VARCHAR2,
        P_BATCH_NO IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_PAYLOAD_HASH IN VARCHAR2,
        P_ROW_COUNT IN NUMBER,
        P_BYTE_COUNT IN NUMBER,
        O_MATCH OUT NUMBER,
        O_RECORDED_RUN_UUID OUT VARCHAR2,
        O_RECORDED_ATTEMPT_NO OUT NUMBER,
        O_RECORDED_FENCE_TOKEN OUT NUMBER,
        O_EVIDENCE_AT OUT TIMESTAMP WITH TIME ZONE) IS
        V_BATCH_NO NUMBER;
        V_RELEASE VARCHAR2(64);
        V_PLAN VARCHAR2(64);
        V_PAYLOAD VARCHAR2(64);
        V_ROWS NUMBER;
        V_BYTES NUMBER;
    BEGIN
        ASSERT_HASH(P_TARGET_KEY_HASH, 'target key hash');
        ASSERT_UUID(P_JOB_UUID, 'job UUID');
        ASSERT_CODE(P_STEP_CODE, 'step code');
        ASSERT_CODE(P_PARTITION_CODE, 'partition code');
        ASSERT_HASH(P_BATCH_KEY_HASH, 'batch key hash');
        ASSERT_NONNEGATIVE(P_BATCH_NO, 'batch number');
        ASSERT_HASH(P_RELEASE_HASH, 'release hash');
        ASSERT_HASH(P_PLAN_HASH, 'plan hash');
        ASSERT_HASH(P_PAYLOAD_HASH, 'payload hash');
        ASSERT_NONNEGATIVE(P_ROW_COUNT, 'row count');
        ASSERT_NONNEGATIVE(P_BYTE_COUNT, 'byte count');
        O_MATCH := 0;
        O_RECORDED_RUN_UUID := NULL;
        O_RECORDED_ATTEMPT_NO := NULL;
        O_RECORDED_FENCE_TOKEN := NULL;
        O_EVIDENCE_AT := NULL;
        BEGIN
            SELECT BATCH_NO, RELEASE_HASH, PLAN_HASH, PAYLOAD_HASH,
                   ROW_COUNT, BYTE_COUNT, RUN_UUID, ATTEMPT_NO,
                   FENCE_TOKEN, EVIDENCE_AT
              INTO V_BATCH_NO, V_RELEASE, V_PLAN, V_PAYLOAD,
                   V_ROWS, V_BYTES, O_RECORDED_RUN_UUID,
                   O_RECORDED_ATTEMPT_NO, O_RECORDED_FENCE_TOKEN,
                   O_EVIDENCE_AT
              FROM ETL_YUKLEME_DEFTERI
             WHERE TARGET_KEY_HASH = P_TARGET_KEY_HASH
               AND JOB_UUID = P_JOB_UUID
               AND STEP_CODE = P_STEP_CODE
               AND PARTITION_CODE = P_PARTITION_CODE
               AND BATCH_KEY_HASH = P_BATCH_KEY_HASH;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN RETURN;
        END;
        IF V_BATCH_NO <> P_BATCH_NO OR V_RELEASE <> P_RELEASE_HASH OR
           V_PLAN <> P_PLAN_HASH OR V_PAYLOAD <> P_PAYLOAD_HASH OR
           V_ROWS <> P_ROW_COUNT OR V_BYTES <> P_BYTE_COUNT THEN
            RAISE_APPLICATION_ERROR(-20015, 'batch evidence conflicts with existing marker');
        END IF;
        O_MATCH := 1;
    END;

    PROCEDURE ASSERT_PUBLISH_INPUTS(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PUBLISH_KEY_HASH IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_STAGE_HASH IN VARCHAR2,
        P_STAGE_ROW_COUNT IN NUMBER,
        P_PUBLISHED_ROW_COUNT IN NUMBER,
        P_REJECTED_ROW_COUNT IN NUMBER,
        P_LOWER_WATERMARK IN VARCHAR2,
        P_UPPER_WATERMARK IN VARCHAR2) IS
    BEGIN
        ASSERT_OWNER(
            P_TARGET_KEY_HASH, P_FENCE_TOKEN, P_JOB_UUID, P_RUN_UUID,
            P_ATTEMPT_NO, P_RELEASE_HASH, P_PLAN_HASH);
        ASSERT_CODE(P_STEP_CODE, 'step code');
        ASSERT_HASH(P_PUBLISH_KEY_HASH, 'publish key hash');
        ASSERT_HASH(P_STAGE_HASH, 'stage hash');
        ASSERT_NONNEGATIVE(P_STAGE_ROW_COUNT, 'stage row count');
        ASSERT_NONNEGATIVE(P_PUBLISHED_ROW_COUNT, 'published row count');
        ASSERT_NONNEGATIVE(P_REJECTED_ROW_COUNT, 'rejected row count');
        IF (P_LOWER_WATERMARK IS NULL AND P_UPPER_WATERMARK IS NOT NULL) OR
           (P_LOWER_WATERMARK IS NOT NULL AND P_UPPER_WATERMARK IS NULL) OR
           LENGTHB(P_LOWER_WATERMARK) > 1000 OR
           LENGTHB(P_UPPER_WATERMARK) > 1000 THEN
            RAISE_APPLICATION_ERROR(-20020, 'watermarks must be a bounded pair');
        END IF;
    END;

    PROCEDURE PREPARE_PUBLISH(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PUBLISH_KEY_HASH IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_STAGE_HASH IN VARCHAR2,
        P_STAGE_ROW_COUNT IN NUMBER,
        P_PUBLISHED_ROW_COUNT IN NUMBER,
        P_REJECTED_ROW_COUNT IN NUMBER,
        P_LOWER_WATERMARK IN VARCHAR2,
        P_UPPER_WATERMARK IN VARCHAR2,
        O_TX_GUARD OUT VARCHAR2,
        O_ALREADY_RECORDED OUT NUMBER) IS
        V_RELEASE VARCHAR2(64);
        V_PLAN VARCHAR2(64);
        V_STAGE VARCHAR2(64);
        V_STAGE_ROWS NUMBER;
        V_PUBLISHED_ROWS NUMBER;
        V_REJECTED_ROWS NUMBER;
        V_LOWER VARCHAR2(1000);
        V_UPPER VARCHAR2(1000);
    BEGIN
        ASSERT_CLEAN_TRANSACTION;
        O_TX_GUARD := NULL;
        O_ALREADY_RECORDED := 0;
        CLEAR_STALE_GUARDS;
        IF G_PUBLISH_GUARD IS NOT NULL THEN
            RAISE_APPLICATION_ERROR(-20021, 'a publish guard is already active in this transaction');
        END IF;
        ASSERT_PUBLISH_INPUTS(
            P_TARGET_KEY_HASH, P_JOB_UUID, P_STEP_CODE, P_PUBLISH_KEY_HASH,
            P_RUN_UUID, P_ATTEMPT_NO, P_FENCE_TOKEN, P_RELEASE_HASH,
            P_PLAN_HASH, P_STAGE_HASH, P_STAGE_ROW_COUNT,
            P_PUBLISHED_ROW_COUNT, P_REJECTED_ROW_COUNT,
            P_LOWER_WATERMARK, P_UPPER_WATERMARK);
        LOCK_AND_VERIFY_FENCE(
            P_TARGET_KEY_HASH, P_FENCE_TOKEN, P_JOB_UUID, P_RUN_UUID,
            P_ATTEMPT_NO, P_RELEASE_HASH, P_PLAN_HASH);

        BEGIN
            SELECT RELEASE_HASH, PLAN_HASH, STAGE_HASH, STAGE_ROW_COUNT,
                   PUBLISHED_ROW_COUNT, REJECTED_ROW_COUNT,
                   LOWER_WATERMARK, UPPER_WATERMARK
              INTO V_RELEASE, V_PLAN, V_STAGE, V_STAGE_ROWS,
                   V_PUBLISHED_ROWS, V_REJECTED_ROWS, V_LOWER, V_UPPER
              FROM ETL_YAYIN_DEFTERI
             WHERE TARGET_KEY_HASH = P_TARGET_KEY_HASH
               AND JOB_UUID = P_JOB_UUID
               AND STEP_CODE = P_STEP_CODE
               AND PUBLISH_KEY_HASH = P_PUBLISH_KEY_HASH;
            IF V_RELEASE <> P_RELEASE_HASH OR V_PLAN <> P_PLAN_HASH OR
               V_STAGE <> P_STAGE_HASH OR V_STAGE_ROWS <> P_STAGE_ROW_COUNT OR
               V_PUBLISHED_ROWS <> P_PUBLISHED_ROW_COUNT OR
               V_REJECTED_ROWS <> P_REJECTED_ROW_COUNT OR
               NOT SAME_TEXT(V_LOWER, P_LOWER_WATERMARK) OR
               NOT SAME_TEXT(V_UPPER, P_UPPER_WATERMARK) THEN
                RAISE_APPLICATION_ERROR(-20022, 'publish evidence conflicts with existing marker');
            END IF;
            O_ALREADY_RECORDED := 1;
            RETURN;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN NULL;
        END;

        G_PUBLISH_GUARD := LOWER(RAWTOHEX(SYS_GUID()));
        G_PUBLISH_TX_ID := DBMS_TRANSACTION.LOCAL_TRANSACTION_ID(TRUE);
        G_PUBLISH_SIGNATURE := PUBLISH_SIGNATURE(
            P_TARGET_KEY_HASH, P_JOB_UUID, P_STEP_CODE, P_PUBLISH_KEY_HASH,
            P_RUN_UUID, P_ATTEMPT_NO, P_FENCE_TOKEN, P_RELEASE_HASH,
            P_PLAN_HASH, P_STAGE_HASH, P_STAGE_ROW_COUNT,
            P_PUBLISHED_ROW_COUNT, P_REJECTED_ROW_COUNT,
            P_LOWER_WATERMARK, P_UPPER_WATERMARK);
        IF G_PUBLISH_TX_ID IS NULL THEN
            RAISE_APPLICATION_ERROR(-20023, 'publish preparation has no local transaction');
        END IF;
        O_TX_GUARD := G_PUBLISH_GUARD;
    END;

    PROCEDURE RECORD_PUBLISH(
        P_TX_GUARD IN VARCHAR2,
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PUBLISH_KEY_HASH IN VARCHAR2,
        P_RUN_UUID IN VARCHAR2,
        P_ATTEMPT_NO IN NUMBER,
        P_FENCE_TOKEN IN NUMBER,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_STAGE_HASH IN VARCHAR2,
        P_STAGE_ROW_COUNT IN NUMBER,
        P_PUBLISHED_ROW_COUNT IN NUMBER,
        P_REJECTED_ROW_COUNT IN NUMBER,
        P_LOWER_WATERMARK IN VARCHAR2,
        P_UPPER_WATERMARK IN VARCHAR2) IS
        V_SIGNATURE VARCHAR2(32767);
        V_TX_ID VARCHAR2(128);
    BEGIN
        ASSERT_PUBLISH_INPUTS(
            P_TARGET_KEY_HASH, P_JOB_UUID, P_STEP_CODE, P_PUBLISH_KEY_HASH,
            P_RUN_UUID, P_ATTEMPT_NO, P_FENCE_TOKEN, P_RELEASE_HASH,
            P_PLAN_HASH, P_STAGE_HASH, P_STAGE_ROW_COUNT,
            P_PUBLISHED_ROW_COUNT, P_REJECTED_ROW_COUNT,
            P_LOWER_WATERMARK, P_UPPER_WATERMARK);
        V_TX_ID := DBMS_TRANSACTION.LOCAL_TRANSACTION_ID(FALSE);
        V_SIGNATURE := PUBLISH_SIGNATURE(
            P_TARGET_KEY_HASH, P_JOB_UUID, P_STEP_CODE, P_PUBLISH_KEY_HASH,
            P_RUN_UUID, P_ATTEMPT_NO, P_FENCE_TOKEN, P_RELEASE_HASH,
            P_PLAN_HASH, P_STAGE_HASH, P_STAGE_ROW_COUNT,
            P_PUBLISHED_ROW_COUNT, P_REJECTED_ROW_COUNT,
            P_LOWER_WATERMARK, P_UPPER_WATERMARK);
        IF P_TX_GUARD IS NULL OR G_PUBLISH_GUARD IS NULL OR
           P_TX_GUARD <> G_PUBLISH_GUARD OR
           V_TX_ID IS NULL OR V_TX_ID <> G_PUBLISH_TX_ID OR
           V_SIGNATURE <> G_PUBLISH_SIGNATURE THEN
            RAISE_APPLICATION_ERROR(-20024, 'publish record is not owned by its preparation transaction');
        END IF;
        LOCK_AND_VERIFY_FENCE(
            P_TARGET_KEY_HASH, P_FENCE_TOKEN, P_JOB_UUID, P_RUN_UUID,
            P_ATTEMPT_NO, P_RELEASE_HASH, P_PLAN_HASH);
        BEGIN
            INSERT INTO ETL_YAYIN_DEFTERI(
                TARGET_KEY_HASH, JOB_UUID, STEP_CODE, PUBLISH_KEY_HASH,
                RUN_UUID, ATTEMPT_NO, FENCE_TOKEN, RELEASE_HASH, PLAN_HASH,
                STAGE_HASH, STAGE_ROW_COUNT, PUBLISHED_ROW_COUNT,
                REJECTED_ROW_COUNT, LOWER_WATERMARK, UPPER_WATERMARK,
                EVIDENCE_AT)
            VALUES (
                P_TARGET_KEY_HASH, P_JOB_UUID, P_STEP_CODE, P_PUBLISH_KEY_HASH,
                P_RUN_UUID, P_ATTEMPT_NO, P_FENCE_TOKEN, P_RELEASE_HASH,
                P_PLAN_HASH, P_STAGE_HASH, P_STAGE_ROW_COUNT,
                P_PUBLISHED_ROW_COUNT, P_REJECTED_ROW_COUNT,
                P_LOWER_WATERMARK, P_UPPER_WATERMARK, SYSTIMESTAMP);
        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
                RAISE_APPLICATION_ERROR(-20025, 'publish marker uniqueness changed after preparation');
        END;
        G_PUBLISH_GUARD := NULL;
        G_PUBLISH_TX_ID := NULL;
        G_PUBLISH_SIGNATURE := NULL;
    END;

    PROCEDURE VERIFY_PUBLISH(
        P_TARGET_KEY_HASH IN VARCHAR2,
        P_JOB_UUID IN VARCHAR2,
        P_STEP_CODE IN VARCHAR2,
        P_PUBLISH_KEY_HASH IN VARCHAR2,
        P_RELEASE_HASH IN VARCHAR2,
        P_PLAN_HASH IN VARCHAR2,
        P_STAGE_HASH IN VARCHAR2,
        P_STAGE_ROW_COUNT IN NUMBER,
        P_PUBLISHED_ROW_COUNT IN NUMBER,
        P_REJECTED_ROW_COUNT IN NUMBER,
        P_LOWER_WATERMARK IN VARCHAR2,
        P_UPPER_WATERMARK IN VARCHAR2,
        O_MATCH OUT NUMBER,
        O_RECORDED_RUN_UUID OUT VARCHAR2,
        O_RECORDED_ATTEMPT_NO OUT NUMBER,
        O_RECORDED_FENCE_TOKEN OUT NUMBER,
        O_EVIDENCE_AT OUT TIMESTAMP WITH TIME ZONE) IS
        V_RELEASE VARCHAR2(64);
        V_PLAN VARCHAR2(64);
        V_STAGE VARCHAR2(64);
        V_STAGE_ROWS NUMBER;
        V_PUBLISHED_ROWS NUMBER;
        V_REJECTED_ROWS NUMBER;
        V_LOWER VARCHAR2(1000);
        V_UPPER VARCHAR2(1000);
    BEGIN
        ASSERT_HASH(P_TARGET_KEY_HASH, 'target key hash');
        ASSERT_UUID(P_JOB_UUID, 'job UUID');
        ASSERT_CODE(P_STEP_CODE, 'step code');
        ASSERT_HASH(P_PUBLISH_KEY_HASH, 'publish key hash');
        ASSERT_HASH(P_RELEASE_HASH, 'release hash');
        ASSERT_HASH(P_PLAN_HASH, 'plan hash');
        ASSERT_HASH(P_STAGE_HASH, 'stage hash');
        ASSERT_NONNEGATIVE(P_STAGE_ROW_COUNT, 'stage row count');
        ASSERT_NONNEGATIVE(P_PUBLISHED_ROW_COUNT, 'published row count');
        ASSERT_NONNEGATIVE(P_REJECTED_ROW_COUNT, 'rejected row count');
        IF (P_LOWER_WATERMARK IS NULL AND P_UPPER_WATERMARK IS NOT NULL) OR
           (P_LOWER_WATERMARK IS NOT NULL AND P_UPPER_WATERMARK IS NULL) OR
           LENGTHB(P_LOWER_WATERMARK) > 1000 OR
           LENGTHB(P_UPPER_WATERMARK) > 1000 THEN
            RAISE_APPLICATION_ERROR(-20020, 'watermarks must be a bounded pair');
        END IF;
        O_MATCH := 0;
        O_RECORDED_RUN_UUID := NULL;
        O_RECORDED_ATTEMPT_NO := NULL;
        O_RECORDED_FENCE_TOKEN := NULL;
        O_EVIDENCE_AT := NULL;
        BEGIN
            SELECT RELEASE_HASH, PLAN_HASH, STAGE_HASH, STAGE_ROW_COUNT,
                   PUBLISHED_ROW_COUNT, REJECTED_ROW_COUNT,
                   LOWER_WATERMARK, UPPER_WATERMARK,
                   RUN_UUID, ATTEMPT_NO, FENCE_TOKEN, EVIDENCE_AT
              INTO V_RELEASE, V_PLAN, V_STAGE, V_STAGE_ROWS,
                   V_PUBLISHED_ROWS, V_REJECTED_ROWS, V_LOWER, V_UPPER,
                   O_RECORDED_RUN_UUID, O_RECORDED_ATTEMPT_NO,
                   O_RECORDED_FENCE_TOKEN, O_EVIDENCE_AT
              FROM ETL_YAYIN_DEFTERI
             WHERE TARGET_KEY_HASH = P_TARGET_KEY_HASH
               AND JOB_UUID = P_JOB_UUID
               AND STEP_CODE = P_STEP_CODE
               AND PUBLISH_KEY_HASH = P_PUBLISH_KEY_HASH;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN RETURN;
        END;
        IF V_RELEASE <> P_RELEASE_HASH OR V_PLAN <> P_PLAN_HASH OR
           V_STAGE <> P_STAGE_HASH OR V_STAGE_ROWS <> P_STAGE_ROW_COUNT OR
           V_PUBLISHED_ROWS <> P_PUBLISHED_ROW_COUNT OR
           V_REJECTED_ROWS <> P_REJECTED_ROW_COUNT OR
           NOT SAME_TEXT(V_LOWER, P_LOWER_WATERMARK) OR
           NOT SAME_TEXT(V_UPPER, P_UPPER_WATERMARK) THEN
            RAISE_APPLICATION_ERROR(-20022, 'publish evidence conflicts with existing marker');
        END IF;
        O_MATCH := 1;
    END;
END ETL_KANIT_PKG;
/

SHOW ERRORS PACKAGE ETL_KANIT_PKG
SHOW ERRORS PACKAGE BODY ETL_KANIT_PKG
