CREATE OR REPLACE TRIGGER ETL_KS_IMM_TRG
BEFORE UPDATE OR DELETE ON ETL_KURULUM_SURUMU
BEGIN
    RAISE_APPLICATION_ERROR(-20080, 'ETL installation marker is immutable');
END;
/

CREATE OR REPLACE TRIGGER ETL_YD_IMM_TRG
BEFORE UPDATE OR DELETE ON ETL_YUKLEME_DEFTERI
BEGIN
    RAISE_APPLICATION_ERROR(-20081, 'ETL batch ledger is append-only');
END;
/

CREATE OR REPLACE TRIGGER ETL_YYD_IMM_TRG
BEFORE UPDATE OR DELETE ON ETL_YAYIN_DEFTERI
BEGIN
    RAISE_APPLICATION_ERROR(-20082, 'ETL publish ledger is append-only');
END;
/

INSERT INTO ETL_KURULUM_SURUMU(
    COMPONENT_CODE, SCHEMA_VERSION, CONTRACT_HASH, INSTALLED_BY)
SELECT
    'AKIS_LEDGER', 1,
    '6fce5297df31bd700711a62af2e37a5305fdfb573f0828db83aa4e407f401c9c',
    SYS_CONTEXT('USERENV', 'SESSION_USER')
  FROM DUAL
 WHERE NOT EXISTS (
       SELECT 1
         FROM ETL_KURULUM_SURUMU
        WHERE COMPONENT_CODE = 'AKIS_LEDGER');

COMMIT;
