CREATE OR REPLACE TRIGGER ETL_KS_IMM_TRG
BEFORE UPDATE OR DELETE ON ETL_KURULUM_SURUMU
BEGIN
    RAISE_APPLICATION_ERROR(-20080, 'ETL installation marker is immutable');
END;
/

CREATE OR REPLACE TRIGGER ETL_YD_IMM_TRG
BEFORE UPDATE OR DELETE ON ETL_YUKLEME_DEFTERI
BEGIN
    RAISE_APPLICATION_ERROR(-20081, 'ETL batch ledger is append-only');
END;
/

CREATE OR REPLACE TRIGGER ETL_YYD_IMM_TRG
BEFORE UPDATE OR DELETE ON ETL_YAYIN_DEFTERI
BEGIN
    RAISE_APPLICATION_ERROR(-20082, 'ETL publish ledger is append-only');
END;
/

INSERT INTO ETL_KURULUM_SURUMU(
    COMPONENT_CODE, SCHEMA_VERSION, CONTRACT_HASH, INSTALLED_BY)
SELECT
    'AKIS_LEDGER', 2,
    '05229dc78ea243a2904f4e170dc814d7852fb786cd44732fb71f7819ada3a68a',
    SYS_CONTEXT('USERENV', 'SESSION_USER')
  FROM DUAL
 WHERE NOT EXISTS (
       SELECT 1
         FROM ETL_KURULUM_SURUMU
        WHERE COMPONENT_CODE = 'AKIS_LEDGER');

COMMIT;
