-- Destructive-to-test-data contract test. Run only after DBA approval in a
-- disposable/test owner. It does not touch any business or staging table.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SERVEROUTPUT ON
SET DEFINE OFF

DECLARE
    C_TARGET CONSTANT VARCHAR2(64) := RPAD('f', 64, 'f');
    C_JOB CONSTANT VARCHAR2(36) := '11111111-1111-1111-1111-111111111111';
    C_RUN CONSTANT VARCHAR2(36) := '22222222-2222-2222-2222-222222222222';
    C_RELEASE CONSTANT VARCHAR2(64) := RPAD('a', 64, 'a');
    C_PLAN CONSTANT VARCHAR2(64) := RPAD('b', 64, 'b');
BEGIN
    ETL_KANIT_PKG.ACQUIRE_FENCE(
        C_TARGET, 101, C_JOB, C_RUN, 1, C_RELEASE, C_PLAN);
END;
/
COMMIT;

VARIABLE STALE_GUARD VARCHAR2(32)
VARIABLE STALE_ALREADY NUMBER

BEGIN
    ETL_KANIT_PKG.PREPARE_BATCH(
        RPAD('f', 64, 'f'),
        '11111111-1111-1111-1111-111111111111',
        'ROLLBACK_TEST', 'FULL', RPAD('7', 64, '7'), 99,
        '22222222-2222-2222-2222-222222222222', 1, 101,
        RPAD('a', 64, 'a'), RPAD('b', 64, 'b'), RPAD('6', 64, '6'),
        0, 0, :STALE_GUARD, :STALE_ALREADY);
    IF :STALE_ALREADY <> 0 OR :STALE_GUARD IS NULL THEN
        RAISE_APPLICATION_ERROR(-20899, 'rollback guard fixture was not prepared');
    END IF;
END;
/
ROLLBACK;

BEGIN
    BEGIN
        ETL_KANIT_PKG.RECORD_BATCH(
            :STALE_GUARD, RPAD('f', 64, 'f'),
            '11111111-1111-1111-1111-111111111111',
            'ROLLBACK_TEST', 'FULL', RPAD('7', 64, '7'), 99,
            '22222222-2222-2222-2222-222222222222', 1, 101,
            RPAD('a', 64, 'a'), RPAD('b', 64, 'b'), RPAD('6', 64, '6'),
            0, 0);
        RAISE_APPLICATION_ERROR(-20900, 'guard survived a closed transaction');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20018 THEN RAISE; END IF;
    END;
END;
/

DECLARE
    C_TARGET CONSTANT VARCHAR2(64) := RPAD('f', 64, 'f');
    C_JOB CONSTANT VARCHAR2(36) := '11111111-1111-1111-1111-111111111111';
    C_RUN CONSTANT VARCHAR2(36) := '22222222-2222-2222-2222-222222222222';
    C_OTHER_RUN CONSTANT VARCHAR2(36) := '33333333-3333-3333-3333-333333333333';
    C_RELEASE CONSTANT VARCHAR2(64) := RPAD('a', 64, 'a');
    C_PLAN CONSTANT VARCHAR2(64) := RPAD('b', 64, 'b');
    C_PAYLOAD CONSTANT VARCHAR2(64) := RPAD('c', 64, 'c');
    C_BATCH_KEY CONSTANT VARCHAR2(64) := RPAD('d', 64, 'd');
    C_PUBLISH_KEY CONSTANT VARCHAR2(64) := RPAD('e', 64, 'e');
    C_STAGE CONSTANT VARCHAR2(64) := RPAD('0', 64, '0');
    V_GUARD VARCHAR2(32);
    V_ALREADY NUMBER;
    V_COUNT NUMBER;
    V_MATCH NUMBER;
    V_RECORDED_RUN VARCHAR2(36);
    V_RECORDED_ATTEMPT NUMBER;
    V_RECORDED_TOKEN NUMBER;
    V_EVIDENCE_AT TIMESTAMP WITH TIME ZONE;
    V_READ_JOB VARCHAR2(36);
    V_READ_RELEASE VARCHAR2(64);
    V_READ_PLAN VARCHAR2(64);
BEGIN
    ETL_KANIT_PKG.READ_FENCE(
        C_TARGET, V_MATCH, V_RECORDED_TOKEN, V_READ_JOB, V_RECORDED_RUN,
        V_RECORDED_ATTEMPT, V_READ_RELEASE, V_READ_PLAN, V_EVIDENCE_AT);
    IF V_MATCH <> 1 OR V_RECORDED_TOKEN <> 101 OR V_READ_JOB <> C_JOB OR
       V_RECORDED_RUN <> C_RUN OR V_RECORDED_ATTEMPT <> 1 OR
       V_READ_RELEASE <> C_RELEASE OR V_READ_PLAN <> C_PLAN OR
       V_EVIDENCE_AT IS NULL THEN
        RAISE_APPLICATION_ERROR(-20918, 'read fence evidence mismatch');
    END IF;

    BEGIN
        ETL_KANIT_PKG.ACQUIRE_FENCE(
            C_TARGET, 100, C_JOB, C_RUN, 1, C_RELEASE, C_PLAN);
        RAISE_APPLICATION_ERROR(-20901, 'lower fence token was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20012 THEN RAISE; END IF;
    END;

    BEGIN
        ETL_KANIT_PKG.ACQUIRE_FENCE(
            C_TARGET, 101, C_JOB, C_OTHER_RUN, 1, C_RELEASE, C_PLAN);
        RAISE_APPLICATION_ERROR(-20902, 'same token with another owner was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20013 THEN RAISE; END IF;
    END;

    ETL_KANIT_PKG.PREPARE_BATCH(
        C_TARGET, C_JOB, 'TRANSFER_1', 'FULL', C_BATCH_KEY, 0,
        C_RUN, 1, 101, C_RELEASE, C_PLAN, C_PAYLOAD, 10, 1000,
        V_GUARD, V_ALREADY);
    IF V_ALREADY <> 0 OR V_GUARD IS NULL THEN
        RAISE_APPLICATION_ERROR(-20903, 'new batch was not prepared');
    END IF;

    BEGIN
        ETL_KANIT_PKG.RECORD_BATCH(
            NULL, C_TARGET, C_JOB, 'TRANSFER_1', 'FULL', C_BATCH_KEY, 0,
            C_RUN, 1, 101, C_RELEASE, C_PLAN, C_PAYLOAD, 10, 1000);
        RAISE_APPLICATION_ERROR(-20916, 'null batch transaction guard was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20018 THEN RAISE; END IF;
    END;

    BEGIN
        ETL_KANIT_PKG.RECORD_BATCH(
            RPAD('0', 32, '0'), C_TARGET, C_JOB, 'TRANSFER_1', 'FULL',
            C_BATCH_KEY, 0, C_RUN, 1, 101, C_RELEASE, C_PLAN,
            C_PAYLOAD, 10, 1000);
        RAISE_APPLICATION_ERROR(-20904, 'foreign transaction guard was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20018 THEN RAISE; END IF;
    END;

    -- Business DML belongs here in the product flow. This contract test has no
    -- business table and records only the marker in the same local transaction.
    ETL_KANIT_PKG.RECORD_BATCH(
        V_GUARD, C_TARGET, C_JOB, 'TRANSFER_1', 'FULL', C_BATCH_KEY, 0,
        C_RUN, 1, 101, C_RELEASE, C_PLAN, C_PAYLOAD, 10, 1000);

    ETL_KANIT_PKG.VERIFY_BATCH(
        C_TARGET, C_JOB, 'TRANSFER_1', 'FULL', C_BATCH_KEY, 0,
        C_RELEASE, C_PLAN, C_PAYLOAD, 10, 1000,
        V_MATCH, V_RECORDED_RUN, V_RECORDED_ATTEMPT,
        V_RECORDED_TOKEN, V_EVIDENCE_AT);
    IF V_MATCH <> 1 OR V_RECORDED_RUN <> C_RUN OR
       V_RECORDED_ATTEMPT <> 1 OR V_RECORDED_TOKEN <> 101 OR
       V_EVIDENCE_AT IS NULL THEN
        RAISE_APPLICATION_ERROR(-20919, 'verified batch evidence mismatch');
    END IF;

    ETL_KANIT_PKG.VERIFY_BATCH(
        C_TARGET, C_JOB, 'TRANSFER_1', 'FULL', RPAD('5', 64, '5'), 1,
        C_RELEASE, C_PLAN, C_PAYLOAD, 1, 1,
        V_MATCH, V_RECORDED_RUN, V_RECORDED_ATTEMPT,
        V_RECORDED_TOKEN, V_EVIDENCE_AT);
    IF V_MATCH <> 0 THEN
        RAISE_APPLICATION_ERROR(-20920, 'absent batch evidence reported as present');
    END IF;

    BEGIN
        ETL_KANIT_PKG.VERIFY_BATCH(
            C_TARGET, C_JOB, 'TRANSFER_1', 'FULL', C_BATCH_KEY, 0,
            C_RELEASE, C_PLAN, RPAD('9', 64, '9'), 10, 1000,
            V_MATCH, V_RECORDED_RUN, V_RECORDED_ATTEMPT,
            V_RECORDED_TOKEN, V_EVIDENCE_AT);
        RAISE_APPLICATION_ERROR(-20921, 'verify batch accepted conflicting evidence');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20015 THEN RAISE; END IF;
    END;

    ETL_KANIT_PKG.PREPARE_BATCH(
        C_TARGET, C_JOB, 'TRANSFER_1', 'FULL', C_BATCH_KEY, 0,
        C_RUN, 1, 101, C_RELEASE, C_PLAN, C_PAYLOAD, 10, 1000,
        V_GUARD, V_ALREADY);
    IF V_ALREADY <> 1 OR V_GUARD IS NOT NULL THEN
        RAISE_APPLICATION_ERROR(-20905, 'matching batch replay was not detected');
    END IF;

    BEGIN
        ETL_KANIT_PKG.PREPARE_BATCH(
            C_TARGET, C_JOB, 'TRANSFER_1', 'FULL', C_BATCH_KEY, 0,
            C_RUN, 1, 101, C_RELEASE, C_PLAN, RPAD('9', 64, '9'), 10, 1000,
            V_GUARD, V_ALREADY);
        RAISE_APPLICATION_ERROR(-20906, 'conflicting payload was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20015 THEN RAISE; END IF;
    END;

    BEGIN
        ETL_KANIT_PKG.PREPARE_BATCH(
            C_TARGET, C_JOB, 'TRANSFER_2', 'FULL', RPAD('8', 64, '8'), 1,
            C_RUN, 1, 101, C_RELEASE, C_PLAN, C_PAYLOAD, -1, 1000,
            V_GUARD, V_ALREADY);
        RAISE_APPLICATION_ERROR(-20907, 'negative row count was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20005 THEN RAISE; END IF;
    END;

    BEGIN
        UPDATE ETL_YUKLEME_DEFTERI SET ROW_COUNT = 11
         WHERE TARGET_KEY_HASH = C_TARGET;
        RAISE_APPLICATION_ERROR(-20908, 'batch ledger update was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20081 THEN RAISE; END IF;
    END;

    BEGIN
        DELETE FROM ETL_YUKLEME_DEFTERI WHERE TARGET_KEY_HASH = C_TARGET;
        RAISE_APPLICATION_ERROR(-20909, 'batch ledger delete was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20081 THEN RAISE; END IF;
    END;

    ETL_KANIT_PKG.PREPARE_PUBLISH(
        C_TARGET, C_JOB, 'PUBLISH_1', C_PUBLISH_KEY, C_RUN, 1, 101,
        C_RELEASE, C_PLAN, C_STAGE, 10, 10, 0, '0001', '0010',
        V_GUARD, V_ALREADY);
    IF V_ALREADY <> 0 OR V_GUARD IS NULL THEN
        RAISE_APPLICATION_ERROR(-20910, 'new publish was not prepared');
    END IF;

    BEGIN
        ETL_KANIT_PKG.RECORD_PUBLISH(
            NULL, C_TARGET, C_JOB, 'PUBLISH_1', C_PUBLISH_KEY,
            C_RUN, 1, 101, C_RELEASE, C_PLAN, C_STAGE, 10, 10, 0,
            '0001', '0010');
        RAISE_APPLICATION_ERROR(-20917, 'null publish transaction guard was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20024 THEN RAISE; END IF;
    END;

    ETL_KANIT_PKG.RECORD_PUBLISH(
        V_GUARD, C_TARGET, C_JOB, 'PUBLISH_1', C_PUBLISH_KEY,
        C_RUN, 1, 101, C_RELEASE, C_PLAN, C_STAGE, 10, 10, 0,
        '0001', '0010');

    ETL_KANIT_PKG.VERIFY_PUBLISH(
        C_TARGET, C_JOB, 'PUBLISH_1', C_PUBLISH_KEY,
        C_RELEASE, C_PLAN, C_STAGE, 10, 10, 0, '0001', '0010',
        V_MATCH, V_RECORDED_RUN, V_RECORDED_ATTEMPT,
        V_RECORDED_TOKEN, V_EVIDENCE_AT);
    IF V_MATCH <> 1 OR V_RECORDED_RUN <> C_RUN OR
       V_RECORDED_ATTEMPT <> 1 OR V_RECORDED_TOKEN <> 101 OR
       V_EVIDENCE_AT IS NULL THEN
        RAISE_APPLICATION_ERROR(-20922, 'verified publish evidence mismatch');
    END IF;

    ETL_KANIT_PKG.VERIFY_PUBLISH(
        C_TARGET, C_JOB, 'PUBLISH_1', RPAD('4', 64, '4'),
        C_RELEASE, C_PLAN, C_STAGE, 0, 0, 0, NULL, NULL,
        V_MATCH, V_RECORDED_RUN, V_RECORDED_ATTEMPT,
        V_RECORDED_TOKEN, V_EVIDENCE_AT);
    IF V_MATCH <> 0 THEN
        RAISE_APPLICATION_ERROR(-20923, 'absent publish evidence reported as present');
    END IF;

    BEGIN
        ETL_KANIT_PKG.VERIFY_PUBLISH(
            C_TARGET, C_JOB, 'PUBLISH_1', C_PUBLISH_KEY,
            C_RELEASE, C_PLAN, C_STAGE, 10, 9, 0, '0001', '0010',
            V_MATCH, V_RECORDED_RUN, V_RECORDED_ATTEMPT,
            V_RECORDED_TOKEN, V_EVIDENCE_AT);
        RAISE_APPLICATION_ERROR(-20924, 'verify publish accepted conflicting evidence');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20022 THEN RAISE; END IF;
    END;

    ETL_KANIT_PKG.PREPARE_PUBLISH(
        C_TARGET, C_JOB, 'PUBLISH_1', C_PUBLISH_KEY, C_RUN, 1, 101,
        C_RELEASE, C_PLAN, C_STAGE, 10, 10, 0, '0001', '0010',
        V_GUARD, V_ALREADY);
    IF V_ALREADY <> 1 OR V_GUARD IS NOT NULL THEN
        RAISE_APPLICATION_ERROR(-20911, 'matching publish replay was not detected');
    END IF;

    BEGIN
        UPDATE ETL_YAYIN_DEFTERI SET PUBLISHED_ROW_COUNT = 11
         WHERE TARGET_KEY_HASH = C_TARGET;
        RAISE_APPLICATION_ERROR(-20912, 'publish ledger update was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20082 THEN RAISE; END IF;
    END;

    BEGIN
        DELETE FROM ETL_YAYIN_DEFTERI WHERE TARGET_KEY_HASH = C_TARGET;
        RAISE_APPLICATION_ERROR(-20913, 'publish ledger delete was accepted');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE <> -20082 THEN RAISE; END IF;
    END;

    SELECT COUNT(*) INTO V_COUNT FROM ETL_YUKLEME_DEFTERI
     WHERE TARGET_KEY_HASH = C_TARGET;
    IF V_COUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(-20914, 'batch marker count mismatch');
    END IF;
    SELECT COUNT(*) INTO V_COUNT FROM ETL_YAYIN_DEFTERI
     WHERE TARGET_KEY_HASH = C_TARGET;
    IF V_COUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(-20915, 'publish marker count mismatch');
    END IF;

    DBMS_OUTPUT.PUT_LINE('AKIS Oracle ledger negative test: PASS');
END;
/

ROLLBACK;

DELETE FROM ETL_YUKLEME_KILIDI
 WHERE TARGET_KEY_HASH = RPAD('f', 64, 'f')
   AND FENCE_TOKEN = 101
   AND OWNER_JOB_UUID = '11111111-1111-1111-1111-111111111111'
   AND OWNER_RUN_UUID = '22222222-2222-2222-2222-222222222222';
COMMIT;
