-- Read-only installation validation. Safe to run independently.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SERVEROUTPUT ON
SET DEFINE OFF

DECLARE
    C_HASH CONSTANT VARCHAR2(64) :=
        '05229dc78ea243a2904f4e170dc814d7852fb786cd44732fb71f7819ada3a68a';
    V_COUNT NUMBER;

    PROCEDURE ASSERT_COUNT(
        P_ACTUAL IN NUMBER,
        P_EXPECTED IN NUMBER,
        P_MESSAGE IN VARCHAR2) IS
    BEGIN
        IF P_ACTUAL <> P_EXPECTED THEN
            RAISE_APPLICATION_ERROR(
                -20090,
                P_MESSAGE || ' (expected ' || P_EXPECTED || ', found ' || P_ACTUAL || ')');
        END IF;
    END;

    PROCEDURE ASSERT_VARCHAR(
        P_TABLE IN VARCHAR2,
        P_COLUMN IN VARCHAR2,
        P_LENGTH IN NUMBER,
        P_NULLABLE IN VARCHAR2) IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT
          FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = P_TABLE
           AND COLUMN_NAME = P_COLUMN
           AND DATA_TYPE = 'VARCHAR2'
           AND CHAR_LENGTH = P_LENGTH
           AND CHAR_USED = 'B'
           AND NULLABLE = P_NULLABLE;
        ASSERT_COUNT(V_COUNT, 1, P_TABLE || '.' || P_COLUMN || ' shape mismatch');
    END;

    PROCEDURE ASSERT_NUMBER(
        P_TABLE IN VARCHAR2,
        P_COLUMN IN VARCHAR2,
        P_PRECISION IN NUMBER,
        P_NULLABLE IN VARCHAR2) IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT
          FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = P_TABLE
           AND COLUMN_NAME = P_COLUMN
           AND DATA_TYPE = 'NUMBER'
           AND DATA_PRECISION = P_PRECISION
           AND DATA_SCALE = 0
           AND NULLABLE = P_NULLABLE;
        ASSERT_COUNT(V_COUNT, 1, P_TABLE || '.' || P_COLUMN || ' shape mismatch');
    END;

    PROCEDURE ASSERT_TIMESTAMP(
        P_TABLE IN VARCHAR2,
        P_COLUMN IN VARCHAR2) IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_COUNT
          FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = P_TABLE
           AND COLUMN_NAME = P_COLUMN
           AND DATA_TYPE LIKE 'TIMESTAMP%WITH TIME ZONE'
           AND NULLABLE = 'N';
        ASSERT_COUNT(V_COUNT, 1, P_TABLE || '.' || P_COLUMN || ' shape mismatch');
    END;

BEGIN
    IF DBMS_DB_VERSION.VERSION <> 19 THEN
        RAISE_APPLICATION_ERROR(-20089, 'validation requires Oracle Database 19c');
    END IF;

    SELECT COUNT(*) INTO V_COUNT
      FROM ETL_KURULUM_SURUMU
     WHERE COMPONENT_CODE = 'AKIS_LEDGER'
       AND SCHEMA_VERSION = 2
       AND CONTRACT_HASH = C_HASH;
    ASSERT_COUNT(V_COUNT, 1, 'version marker mismatch');

    SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ETL_KURULUM_SURUMU';
    ASSERT_COUNT(V_COUNT, 5, 'version table column count mismatch');
    SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ETL_YUKLEME_KILIDI';
    ASSERT_COUNT(V_COUNT, 8, 'fence table column count mismatch');
    SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ETL_YUKLEME_DEFTERI';
    ASSERT_COUNT(V_COUNT, 15, 'batch ledger column count mismatch');
    SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ETL_YAYIN_DEFTERI';
    ASSERT_COUNT(V_COUNT, 16, 'publish ledger column count mismatch');

    ASSERT_VARCHAR('ETL_KURULUM_SURUMU', 'COMPONENT_CODE', 30, 'N');
    ASSERT_NUMBER('ETL_KURULUM_SURUMU', 'SCHEMA_VERSION', 10, 'N');
    ASSERT_VARCHAR('ETL_KURULUM_SURUMU', 'CONTRACT_HASH', 64, 'N');
    ASSERT_TIMESTAMP('ETL_KURULUM_SURUMU', 'INSTALLED_AT');
    ASSERT_VARCHAR('ETL_KURULUM_SURUMU', 'INSTALLED_BY', 128, 'N');

    ASSERT_VARCHAR('ETL_YUKLEME_KILIDI', 'TARGET_KEY_HASH', 64, 'N');
    ASSERT_NUMBER('ETL_YUKLEME_KILIDI', 'FENCE_TOKEN', 19, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_KILIDI', 'OWNER_JOB_UUID', 36, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_KILIDI', 'OWNER_RUN_UUID', 36, 'N');
    ASSERT_NUMBER('ETL_YUKLEME_KILIDI', 'OWNER_ATTEMPT_NO', 10, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_KILIDI', 'RELEASE_HASH', 64, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_KILIDI', 'PLAN_HASH', 64, 'N');
    ASSERT_TIMESTAMP('ETL_YUKLEME_KILIDI', 'UPDATED_AT');

    ASSERT_VARCHAR('ETL_YUKLEME_DEFTERI', 'TARGET_KEY_HASH', 64, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_DEFTERI', 'JOB_UUID', 36, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_DEFTERI', 'STEP_CODE', 128, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_DEFTERI', 'PARTITION_CODE', 128, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_DEFTERI', 'BATCH_KEY_HASH', 64, 'N');
    ASSERT_NUMBER('ETL_YUKLEME_DEFTERI', 'BATCH_NO', 19, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_DEFTERI', 'RUN_UUID', 36, 'N');
    ASSERT_NUMBER('ETL_YUKLEME_DEFTERI', 'ATTEMPT_NO', 10, 'N');
    ASSERT_NUMBER('ETL_YUKLEME_DEFTERI', 'FENCE_TOKEN', 19, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_DEFTERI', 'RELEASE_HASH', 64, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_DEFTERI', 'PLAN_HASH', 64, 'N');
    ASSERT_VARCHAR('ETL_YUKLEME_DEFTERI', 'PAYLOAD_HASH', 64, 'N');
    ASSERT_NUMBER('ETL_YUKLEME_DEFTERI', 'ROW_COUNT', 19, 'N');
    ASSERT_NUMBER('ETL_YUKLEME_DEFTERI', 'BYTE_COUNT', 19, 'N');
    ASSERT_TIMESTAMP('ETL_YUKLEME_DEFTERI', 'EVIDENCE_AT');

    ASSERT_VARCHAR('ETL_YAYIN_DEFTERI', 'TARGET_KEY_HASH', 64, 'N');
    ASSERT_VARCHAR('ETL_YAYIN_DEFTERI', 'JOB_UUID', 36, 'N');
    ASSERT_VARCHAR('ETL_YAYIN_DEFTERI', 'STEP_CODE', 128, 'N');
    ASSERT_VARCHAR('ETL_YAYIN_DEFTERI', 'PUBLISH_KEY_HASH', 64, 'N');
    ASSERT_VARCHAR('ETL_YAYIN_DEFTERI', 'RUN_UUID', 36, 'N');
    ASSERT_NUMBER('ETL_YAYIN_DEFTERI', 'ATTEMPT_NO', 10, 'N');
    ASSERT_NUMBER('ETL_YAYIN_DEFTERI', 'FENCE_TOKEN', 19, 'N');
    ASSERT_VARCHAR('ETL_YAYIN_DEFTERI', 'RELEASE_HASH', 64, 'N');
    ASSERT_VARCHAR('ETL_YAYIN_DEFTERI', 'PLAN_HASH', 64, 'N');
    ASSERT_VARCHAR('ETL_YAYIN_DEFTERI', 'STAGE_HASH', 64, 'N');
    ASSERT_NUMBER('ETL_YAYIN_DEFTERI', 'STAGE_ROW_COUNT', 19, 'N');
    ASSERT_NUMBER('ETL_YAYIN_DEFTERI', 'PUBLISHED_ROW_COUNT', 19, 'N');
    ASSERT_NUMBER('ETL_YAYIN_DEFTERI', 'REJECTED_ROW_COUNT', 19, 'N');
    ASSERT_VARCHAR('ETL_YAYIN_DEFTERI', 'LOWER_WATERMARK', 1000, 'Y');
    ASSERT_VARCHAR('ETL_YAYIN_DEFTERI', 'UPPER_WATERMARK', 1000, 'Y');
    ASSERT_TIMESTAMP('ETL_YAYIN_DEFTERI', 'EVIDENCE_AT');

    SELECT COUNT(*) INTO V_COUNT
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_NAME IN (
               'ETL_KS_PK', 'ETL_KS_COMP_CK', 'ETL_KS_VER_CK', 'ETL_KS_HASH_CK',
               'ETL_YK_PK', 'ETL_YK_TARGET_CK', 'ETL_YK_TOKEN_CK',
               'ETL_YK_JOB_CK', 'ETL_YK_RUN_CK', 'ETL_YK_ATT_CK',
               'ETL_YK_REL_CK', 'ETL_YK_PLAN_CK',
               'ETL_YD_PK', 'ETL_YD_BATCH_UQ', 'ETL_YD_TARGET_CK',
               'ETL_YD_JOB_CK', 'ETL_YD_RUN_CK', 'ETL_YD_STEP_CK',
               'ETL_YD_PART_CK', 'ETL_YD_BKEY_CK', 'ETL_YD_BATCHNO_CK',
               'ETL_YD_ATT_CK', 'ETL_YD_TOKEN_CK', 'ETL_YD_REL_CK',
               'ETL_YD_PLAN_CK', 'ETL_YD_PAY_CK', 'ETL_YD_ROWS_CK',
               'ETL_YD_BYTES_CK',
               'ETL_YYD_PK', 'ETL_YYD_TARGET_CK', 'ETL_YYD_JOB_CK',
               'ETL_YYD_RUN_CK', 'ETL_YYD_STEP_CK', 'ETL_YYD_PKEY_CK',
               'ETL_YYD_ATT_CK', 'ETL_YYD_TOKEN_CK', 'ETL_YYD_REL_CK',
               'ETL_YYD_PLAN_CK', 'ETL_YYD_STAGE_CK', 'ETL_YYD_SROWS_CK',
               'ETL_YYD_PROWS_CK', 'ETL_YYD_RROWS_CK', 'ETL_YYD_WM_CK')
       AND STATUS = 'ENABLED'
       AND VALIDATED = 'VALIDATED';
    ASSERT_COUNT(V_COUNT, 43, 'constraint set mismatch');

    SELECT COUNT(*) INTO V_COUNT
      FROM USER_TRIGGERS
     WHERE (
               (TRIGGER_NAME = 'ETL_KS_IMM_TRG' AND
                TABLE_NAME = 'ETL_KURULUM_SURUMU') OR
               (TRIGGER_NAME = 'ETL_YD_IMM_TRG' AND
                TABLE_NAME = 'ETL_YUKLEME_DEFTERI') OR
               (TRIGGER_NAME = 'ETL_YYD_IMM_TRG' AND
                TABLE_NAME = 'ETL_YAYIN_DEFTERI'))
       AND TRIGGER_TYPE = 'BEFORE STATEMENT'
       AND TRIGGERING_EVENT = 'UPDATE OR DELETE'
       AND STATUS = 'ENABLED';
    ASSERT_COUNT(V_COUNT, 3, 'append-only trigger set mismatch');

    SELECT COUNT(*) INTO V_COUNT
      FROM USER_OBJECTS
     WHERE OBJECT_NAME IN ('ETL_KS_IMM_TRG', 'ETL_YD_IMM_TRG', 'ETL_YYD_IMM_TRG')
       AND OBJECT_TYPE = 'TRIGGER'
       AND STATUS = 'VALID';
    ASSERT_COUNT(V_COUNT, 3, 'append-only trigger compilation failed');

    SELECT COUNT(*) INTO V_COUNT
      FROM USER_PROCEDURES
     WHERE OBJECT_NAME = 'ETL_KANIT_PKG'
       AND PROCEDURE_NAME IS NULL
       AND AUTHID = 'DEFINER';
    ASSERT_COUNT(V_COUNT, 1, 'package must use definer rights');

    SELECT COUNT(*) INTO V_COUNT
      FROM USER_PROCEDURES
     WHERE OBJECT_NAME = 'ETL_KANIT_PKG'
       AND PROCEDURE_NAME IN (
           'ACQUIRE_FENCE', 'LOCK_FENCE', 'READ_FENCE',
           'PREPARE_BATCH', 'RECORD_BATCH', 'VERIFY_BATCH',
           'PREPARE_PUBLISH', 'RECORD_PUBLISH', 'VERIFY_PUBLISH');
    ASSERT_COUNT(V_COUNT, 9, 'package API mismatch');

    SELECT COUNT(*) INTO V_COUNT
      FROM USER_OBJECTS
     WHERE OBJECT_NAME = 'ETL_KANIT_PKG'
       AND OBJECT_TYPE IN ('PACKAGE', 'PACKAGE BODY')
       AND STATUS = 'VALID';
    ASSERT_COUNT(V_COUNT, 2, 'package compilation failed');

    SELECT COUNT(*) INTO V_COUNT
      FROM USER_ERRORS
     WHERE NAME = 'ETL_KANIT_PKG'
       AND TYPE IN ('PACKAGE', 'PACKAGE BODY');
    ASSERT_COUNT(V_COUNT, 0, 'package compiler error scan failed');

    SELECT COUNT(*) INTO V_COUNT
      FROM USER_SOURCE
     WHERE NAME = 'ETL_KANIT_PKG'
       AND TYPE = 'PACKAGE BODY'
       AND REGEXP_LIKE(TEXT, 'RAISE_APPLICATION_ERROR[[:space:]]*\(', 'i')
       AND LINE BETWEEN (
           SELECT MIN(LINE) FROM USER_SOURCE
            WHERE NAME = 'ETL_KANIT_PKG' AND TYPE = 'PACKAGE BODY'
              AND REGEXP_LIKE(TEXT, 'PROCEDURE ASSERT_CLEAN_TRANSACTION', 'i'))
                    AND (
           SELECT MIN(LINE) FROM USER_SOURCE
            WHERE NAME = 'ETL_KANIT_PKG' AND TYPE = 'PACKAGE BODY'
              AND LINE > (
                  SELECT MIN(LINE) FROM USER_SOURCE
                   WHERE NAME = 'ETL_KANIT_PKG' AND TYPE = 'PACKAGE BODY'
                     AND REGEXP_LIKE(TEXT, 'PROCEDURE ASSERT_CLEAN_TRANSACTION', 'i'))
              AND REGEXP_LIKE(TEXT, '^[[:space:]]*END;', 'i'));
    ASSERT_COUNT(V_COUNT, 1, 'clean transaction guard implementation mismatch');

    SELECT COUNT(*) INTO V_COUNT
      FROM USER_SOURCE
     WHERE NAME = 'ETL_KANIT_PKG'
       AND TYPE = 'PACKAGE BODY'
       AND REGEXP_LIKE(TEXT, '^[[:space:]]*ASSERT_CLEAN_TRANSACTION;[[:space:]]*$', 'i');
    ASSERT_COUNT(V_COUNT, 4, 'clean transaction entry-point coverage mismatch');

    SELECT COUNT(*) INTO V_COUNT
      FROM USER_SOURCE
     WHERE NAME = 'ETL_KANIT_PKG'
       AND TYPE = 'PACKAGE BODY'
       AND (
           REGEXP_LIKE(TEXT, '(^|[^A-Z_])(COMMIT|ROLLBACK)([^A-Z_]|$)', 'i') OR
           REGEXP_LIKE(TEXT, 'AUTONOMOUS_TRANSACTION', 'i') OR
           REGEXP_LIKE(TEXT, 'EXECUTE[[:space:]]+IMMEDIATE', 'i'));
    ASSERT_COUNT(V_COUNT, 0, 'package contains forbidden transaction or dynamic SQL control');

    DBMS_OUTPUT.PUT_LINE('AKIS Oracle ledger validation: PASS');
END;
/
