import { ArrowLeft, Database, Download, Search } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useParams } from 'react-router-dom'
import { useCurrentProjectUuid } from '../projects/CurrentProjectContext'
import { AsyncState, Button, PageHeader } from '../../core/ui'
import { MetadataDiff } from './MetadataDiff'
import { compareMetadata } from './metadataComparison'
import { topologyApi, type Connection, type ConnectionVersion, type DataObject, type DiscoveryResult, type DiscoveryTable, type Environment, type Model, type PhysicalSchema, type SchemaBinding, type SchemaSnapshot } from '../topology/api'
import './models.css'

export function MetadataImportPage() {
  const { modelUuid = '' } = useParams(); const projectUuid = useCurrentProjectUuid(); const { t } = useTranslation()
  const [model, setModel] = useState<Model | null>(null); const [environments, setEnvironments] = useState<Environment[]>([]); const [bindings, setBindings] = useState<SchemaBinding[]>([]); const [physical, setPhysical] = useState<PhysicalSchema[]>([]); const [connections, setConnections] = useState<Connection[]>([]); const [versions, setVersions] = useState<ConnectionVersion[]>([]); const [objects, setObjects] = useState<DataObject[]>([])
  const [environmentUuid, setEnvironmentUuid] = useState(''); const [scope, setScope] = useState(''); const [result, setResult] = useState<DiscoveryResult | null>(null); const [selected, setSelected] = useState<Set<string>>(new Set()); const [preview, setPreview] = useState<DiscoveryTable | null>(null); const [previous, setPrevious] = useState<SchemaSnapshot | null>(null)
  const [loading, setLoading] = useState(true); const [discovering, setDiscovering] = useState(false); const [importing, setImporting] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [nextModel, nextEnvironments, nextBindings, nextPhysical, nextConnections, nextObjects] = await Promise.all([topologyApi.getModel(projectUuid, modelUuid), topologyApi.listEnvironments(projectUuid), topologyApi.listBindings(projectUuid), topologyApi.listPhysicalSchemas(projectUuid), topologyApi.listConnections(projectUuid), topologyApi.listDataObjects(projectUuid, modelUuid)]); setModel(nextModel); setEnvironments(nextEnvironments); setBindings(nextBindings); setPhysical(nextPhysical); setConnections(nextConnections); setObjects(nextObjects); setEnvironmentUuid((value) => value || nextEnvironments[0]?.uuid || '') } catch { setError(t('common.loadError')) } finally { setLoading(false) } }, [modelUuid, projectUuid, t])
  useEffect(() => { void load() }, [load])
  const binding = useMemo(() => bindings.find((item) => item.logicalSchemaUuid === model?.logicalSchemaUuid && item.environmentUuid === environmentUuid), [bindings, environmentUuid, model?.logicalSchemaUuid])
  const physicalSchema = physical.find((item) => item.uuid === binding?.physicalSchemaUuid); const connection = connections.find((item) => item.uuid === physicalSchema?.connectionUuid); const version = versions.find((item) => item.uuid === binding?.connectionVersionUuid)
  useEffect(() => { if (!connection) { setVersions([]); return } let active = true; void topologyApi.listVersions(projectUuid, connection.uuid).then((rows) => { if (active) setVersions(rows) }).catch(() => { if (active) setVersions([]) }); return () => { active = false } }, [connection, projectUuid])
  useEffect(() => { if (!preview) { setPrevious(null); return } const existing = objects.find((item) => item.objectReference.toLocaleUpperCase() === preview.name.toLocaleUpperCase()); if (!existing) { setPrevious(null); return } let active = true; void topologyApi.listSchemaSnapshots(projectUuid, existing.uuid).then((rows) => { if (active) setPrevious(rows[0] ?? null) }).catch(() => { if (active) setPrevious(null) }); return () => { active = false } }, [objects, preview, projectUuid])
  async function discover() { if (!binding || !physicalSchema || !connection) return; setDiscovering(true); setError(''); setNotice(''); try { const next = await topologyApi.discoverOracle(projectUuid, connection.uuid, binding.connectionVersionUuid, physicalSchema.uuid, { tableName: scope.trim() || undefined, limit: 100 }); setResult(next); setSelected(new Set()); setPreview(next.tables[0] ?? null) } catch (reason) { setError(reason instanceof Error ? reason.message : t('models.discoveryFailed')) } finally { setDiscovering(false) } }
  const toggle = (table: DiscoveryTable) => setSelected((current) => { const key = `${table.owner}.${table.name}`; const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next })
  async function importSelected() { if (!binding || !physicalSchema || !connection || !result) return; setImporting(true); setError(''); setNotice(''); let count = 0; try { for (const table of result.tables) { const selectionKey = `${table.owner}.${table.name}`; if (!selected.has(selectionKey)) continue; const reference = table.name; let object = objects.find((item) => item.objectReference.toLocaleUpperCase() === reference.toLocaleUpperCase()); if (!object) object = await topologyApi.createDataObject(projectUuid, modelUuid, { code: `${table.owner}_${table.name}`.replace(/[^A-Za-z0-9_]/g, '_').slice(0, 100).toUpperCase(), name: table.name, objectReference: reference, type: table.type === 'VIEW' ? 'VIEW' : 'TABLO' }); await topologyApi.captureOracleSchemaSnapshot(projectUuid, connection.uuid, binding.connectionVersionUuid, physicalSchema.uuid, object.uuid); count += 1 } setNotice(t('models.importedCount', { count })); await load(); setSelected(new Set()) } catch (reason) { setError(reason instanceof Error ? reason.message : t('models.importFailed')) } finally { setImporting(false) } }
  if (loading) return <AsyncState state="loading" title={t('common.loading')} />
  if (!model) return <AsyncState state="error" title={error || t('common.loadError')} retryLabel={t('common.retry')} onRetry={() => void load()} />
  const changes = preview ? compareMetadata(previous?.columns ?? [], preview.columns) : []
  return <section className="page-stack models-page"><Link className="connection-back-link" to={`/projects/${projectUuid}/models/${modelUuid}`}><ArrowLeft size={16} />{model.name}</Link><PageHeader eyebrow={t('models.discoveryEyebrow')} title={t('models.importMetadata')} description={t('models.importDescription')} />
    {error ? <div className="error-banner" role="alert">{error}</div> : null}{notice ? <div className="success-banner" role="status">{notice}</div> : null}
    <section className="metadata-context"><label>{t('models.environment')}<select value={environmentUuid} onChange={(event) => { setEnvironmentUuid(event.target.value); setResult(null) }}>{environments.map((item) => <option key={item.uuid} value={item.uuid}>{item.name}</option>)}</select></label>{binding && physicalSchema && connection ? <dl><div><dt>{t('models.connection')}</dt><dd>{connection.name}</dd></div><div><dt>{t('models.physicalSchema')}</dt><dd>{physicalSchema.schemaReference}</dd></div><div><dt>{t('models.capability')}</dt><dd>{version?.runtimeCapability === 'EXECUTABLE' ? t('models.executable') : t('models.discoveryOnly')}</dd></div></dl> : <div className="metadata-binding-missing"><strong>{t('models.bindingMissing')}</strong><Link to={`/projects/${projectUuid}/schema-bindings`}>{t('models.openBindings')}</Link></div>}</section>
    {binding && physicalSchema && connection ? <section className="metadata-discovery-controls"><label><span>{t('models.discoveryScope')}</span><div><Search size={16} /><input value={scope} onChange={(event) => setScope(event.target.value.toUpperCase())} placeholder={t('models.scopePlaceholder')} /></div></label><Button tone="primary" icon={<Database size={16} />} busy={discovering} onClick={() => void discover()}>{t('models.discover')}</Button><p>{t('models.metadataOnly')}</p></section> : null}
    {result ? <><div className="discovery-summary"><strong>{t('models.discoveryResult', { count: result.tables.length })}</strong><span>{result.owner}</span><span>{result.truncated ? t('models.partialResult') : t('models.completeScope')}</span></div><div className="metadata-results-layout"><div className="model-table-wrap"><table><thead><tr><th><span className="sr-only">{t('models.select')}</span></th><th>{t('models.object')}</th><th>{t('models.type')}</th><th>{t('models.columnCount')}</th></tr></thead><tbody>{result.tables.map((table) => { const key = `${table.owner}.${table.name}`; return <tr key={key} className={preview === table ? 'is-selected' : ''} onClick={() => setPreview(table)}><td><input type="checkbox" checked={selected.has(key)} aria-label={t('models.selectObject', { name: table.name })} onClick={(event) => event.stopPropagation()} onChange={() => toggle(table)} /></td><td><strong>{table.name}</strong><small>{table.owner}</small></td><td>{table.type}</td><td>{table.columns.length}</td></tr> })}</tbody></table></div><aside className="metadata-preview">{preview ? <><header><strong>{preview.name}</strong><span>{previous ? t('models.existingObject') : t('models.newObject')}</span></header><MetadataDiff changes={changes} /></> : null}</aside></div><div className="metadata-import-actions"><span>{t('models.selectedCount', { count: selected.size })}</span><Button tone="primary" icon={<Download size={16} />} disabled={selected.size === 0} busy={importing} onClick={() => void importSelected()}>{t('models.importSelected')}</Button></div></> : null}
  </section>
}
