CREATE SCHEMA IF NOT EXISTS entegrasyon;
SET search_path TO entegrasyon, public;

CREATE TABLE kullanici (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    oidc_saglayici TEXT NOT NULL,
    oidc_ozne TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    son_giris_zamani TIMESTAMPTZ,
    ad TEXT NOT NULL,
    eposta TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT,
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT,
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_kullanici PRIMARY KEY (id),
    CONSTRAINT uq_kullanici_uuid UNIQUE (uuid),
    CONSTRAINT uq_kullanici_oidc UNIQUE (oidc_saglayici, oidc_ozne),
    CONSTRAINT ck_kullanici_durum CHECK (durum_kodu IN ('AKTIF', 'PASIF')),
    CONSTRAINT ck_kullanici_audit CHECK (versiyon_no > 0 AND
        (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani))
);

ALTER TABLE kullanici
    ADD CONSTRAINT fk_kullanici_olusturan FOREIGN KEY (olusturan_kullanici_id) REFERENCES kullanici(id),
    ADD CONSTRAINT fk_kullanici_guncelleyen FOREIGN KEY (guncelleyen_kullanici_id) REFERENCES kullanici(id);

CREATE TABLE sistem_rolu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kod TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    ad TEXT NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_sistem_rolu PRIMARY KEY (id),
    CONSTRAINT uq_sistem_rolu_uuid UNIQUE (uuid),
    CONSTRAINT uq_sistem_rolu_kod UNIQUE (kod),
    CONSTRAINT ck_sistem_rolu_durum CHECK (durum_kodu IN ('AKTIF', 'PASIF')),
    CONSTRAINT ck_sistem_rolu_audit CHECK (versiyon_no > 0)
);

CREATE TABLE yetki (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kod TEXT NOT NULL,
    kapsam_kodu TEXT NOT NULL,
    ad TEXT NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_yetki PRIMARY KEY (id),
    CONSTRAINT uq_yetki_uuid UNIQUE (uuid),
    CONSTRAINT uq_yetki_kod UNIQUE (kod),
    CONSTRAINT ck_yetki_kapsam CHECK (kapsam_kodu IN ('SISTEM', 'PROJE', 'KAYNAK', 'URETIM')),
    CONSTRAINT ck_yetki_audit CHECK (versiyon_no > 0)
);

CREATE TABLE sistem_rolu_yetkisi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sistem_rolu_id BIGINT NOT NULL REFERENCES sistem_rolu(id),
    yetki_id BIGINT NOT NULL REFERENCES yetki(id),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_sistem_rolu_yetkisi PRIMARY KEY (id),
    CONSTRAINT uq_sistem_rolu_yetkisi_uuid UNIQUE (uuid),
    CONSTRAINT uq_sistem_rolu_yetkisi UNIQUE (sistem_rolu_id, yetki_id)
);

CREATE TABLE kullanici_sistem_rolu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kullanici_id BIGINT NOT NULL REFERENCES kullanici(id),
    sistem_rolu_id BIGINT NOT NULL REFERENCES sistem_rolu(id),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_kullanici_sistem_rolu PRIMARY KEY (id),
    CONSTRAINT uq_kullanici_sistem_rolu_uuid UNIQUE (uuid),
    CONSTRAINT uq_kullanici_sistem_rolu UNIQUE (kullanici_id, sistem_rolu_id)
);

CREATE TABLE proje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kod TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    ad TEXT NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_proje PRIMARY KEY (id),
    CONSTRAINT uq_proje_uuid UNIQUE (uuid),
    CONSTRAINT uq_proje_kod UNIQUE (kod),
    CONSTRAINT ck_proje_durum CHECK (durum_kodu IN ('AKTIF', 'ARSIV')),
    CONSTRAINT ck_proje_audit CHECK (versiyon_no > 0)
);

CREATE TABLE proje_rolu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kod TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    ad TEXT NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_proje_rolu PRIMARY KEY (id),
    CONSTRAINT uq_proje_rolu_uuid UNIQUE (uuid),
    CONSTRAINT uq_proje_rolu_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_proje_rolu_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT ck_proje_rolu_durum CHECK (durum_kodu IN ('AKTIF', 'PASIF'))
);

CREATE TABLE proje_rolu_yetkisi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    proje_rolu_id BIGINT NOT NULL,
    yetki_id BIGINT NOT NULL REFERENCES yetki(id),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_proje_rolu_yetkisi PRIMARY KEY (id),
    CONSTRAINT uq_proje_rolu_yetkisi_uuid UNIQUE (uuid),
    CONSTRAINT uq_proje_rolu_yetkisi UNIQUE (proje_rolu_id, yetki_id),
    CONSTRAINT fk_proje_rolu_yetkisi_rol FOREIGN KEY (proje_id, proje_rolu_id)
        REFERENCES proje_rolu(proje_id, id)
);

CREATE TABLE proje_uyeligi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kullanici_id BIGINT NOT NULL REFERENCES kullanici(id),
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    baslangic_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bitis_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_proje_uyeligi PRIMARY KEY (id),
    CONSTRAINT uq_proje_uyeligi_uuid UNIQUE (uuid),
    CONSTRAINT uq_proje_uyeligi UNIQUE (proje_id, kullanici_id),
    CONSTRAINT uq_proje_uyeligi_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT ck_proje_uyeligi_durum CHECK (durum_kodu IN ('AKTIF', 'ASKIDA', 'SONLANDI')),
    CONSTRAINT ck_proje_uyeligi_zaman CHECK (bitis_zamani IS NULL OR bitis_zamani >= baslangic_zamani)
);

CREATE TABLE proje_uyeligi_rolu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    proje_uyeligi_id BIGINT NOT NULL,
    proje_rolu_id BIGINT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_proje_uyeligi_rolu PRIMARY KEY (id),
    CONSTRAINT uq_proje_uyeligi_rolu_uuid UNIQUE (uuid),
    CONSTRAINT uq_proje_uyeligi_rolu UNIQUE (proje_uyeligi_id, proje_rolu_id),
    CONSTRAINT fk_proje_uyeligi_rolu_uyelik FOREIGN KEY (proje_id, proje_uyeligi_id)
        REFERENCES proje_uyeligi(proje_id, id),
    CONSTRAINT fk_proje_uyeligi_rolu_rol FOREIGN KEY (proje_id, proje_rolu_id)
        REFERENCES proje_rolu(proje_id, id)
);

CREATE TABLE secret_referansi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kod TEXT NOT NULL,
    referans_yolu TEXT NOT NULL,
    surum_referansi TEXT,
    saglayici_kodu TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_secret_referansi PRIMARY KEY (id),
    CONSTRAINT uq_secret_referansi_uuid UNIQUE (uuid),
    CONSTRAINT uq_secret_referansi_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_secret_referansi_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT ck_secret_referansi_saglayici CHECK (saglayici_kodu IN ('ENV', 'VAULT', 'KUBERNETES')),
    CONSTRAINT ck_secret_referansi_durum CHECK (durum_kodu IN ('AKTIF', 'PASIF'))
);

CREATE TABLE baglanti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kod TEXT NOT NULL,
    veritabani_turu TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'TASLAK',
    ad TEXT NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_baglanti PRIMARY KEY (id),
    CONSTRAINT uq_baglanti_uuid UNIQUE (uuid),
    CONSTRAINT uq_baglanti_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_baglanti_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT ck_baglanti_tur CHECK (veritabani_turu IN ('ORACLE', 'POSTGRESQL', 'MYSQL')),
    CONSTRAINT ck_baglanti_durum CHECK (durum_kodu IN ('TASLAK', 'AKTIF', 'PASIF'))
);

CREATE TABLE baglanti_surumu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    baglanti_id BIGINT NOT NULL,
    surum_no INTEGER NOT NULL,
    surucu_referansi TEXT NOT NULL,
    sunucu_adi TEXT NOT NULL,
    servis_adi TEXT,
    sid TEXT,
    veritabani_adi TEXT,
    tls_modu TEXT NOT NULL DEFAULT 'DISABLED',
    port INTEGER NOT NULL,
    politika_surumu INTEGER NOT NULL DEFAULT 1,
    politika JSONB NOT NULL DEFAULT '{}'::jsonb,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_baglanti_surumu PRIMARY KEY (id),
    CONSTRAINT uq_baglanti_surumu_uuid UNIQUE (uuid),
    CONSTRAINT uq_baglanti_surumu UNIQUE (baglanti_id, surum_no),
    CONSTRAINT uq_baglanti_surumu_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_baglanti_surumu_baglanti FOREIGN KEY (proje_id, baglanti_id)
        REFERENCES baglanti(proje_id, id),
    CONSTRAINT ck_baglanti_surumu_port CHECK (port BETWEEN 1 AND 65535),
    CONSTRAINT ck_baglanti_surumu_no CHECK (surum_no > 0),
    CONSTRAINT ck_baglanti_surumu_tls CHECK (tls_modu IN ('DISABLED', 'REQUIRED', 'VERIFY_CA', 'VERIFY_FULL'))
);

CREATE TABLE baglanti_secret_bagi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    baglanti_surumu_id BIGINT NOT NULL,
    secret_referansi_id BIGINT NOT NULL,
    rol_kodu TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_baglanti_secret_bagi PRIMARY KEY (id),
    CONSTRAINT uq_baglanti_secret_bagi_uuid UNIQUE (uuid),
    CONSTRAINT uq_baglanti_secret_bagi UNIQUE (baglanti_surumu_id, rol_kodu),
    CONSTRAINT fk_baglanti_secret_surum FOREIGN KEY (proje_id, baglanti_surumu_id)
        REFERENCES baglanti_surumu(proje_id, id),
    CONSTRAINT fk_baglanti_secret_ref FOREIGN KEY (proje_id, secret_referansi_id)
        REFERENCES secret_referansi(proje_id, id),
    CONSTRAINT ck_baglanti_secret_rol CHECK (rol_kodu IN ('KIMLIK', 'WALLET', 'CLIENT_SERTIFIKA'))
);

CREATE TABLE fiziksel_sema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    baglanti_id BIGINT NOT NULL,
    kod TEXT NOT NULL,
    sema_referansi TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_fiziksel_sema PRIMARY KEY (id),
    CONSTRAINT uq_fiziksel_sema_uuid UNIQUE (uuid),
    CONSTRAINT uq_fiziksel_sema_ref UNIQUE (baglanti_id, sema_referansi),
    CONSTRAINT uq_fiziksel_sema_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_fiziksel_sema_baglanti FOREIGN KEY (proje_id, baglanti_id)
        REFERENCES baglanti(proje_id, id),
    CONSTRAINT ck_fiziksel_sema_durum CHECK (durum_kodu IN ('AKTIF', 'PASIF'))
);

CREATE TABLE mantiksal_sema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kod TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    ad TEXT NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_mantiksal_sema PRIMARY KEY (id),
    CONSTRAINT uq_mantiksal_sema_uuid UNIQUE (uuid),
    CONSTRAINT uq_mantiksal_sema_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_mantiksal_sema_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT ck_mantiksal_sema_durum CHECK (durum_kodu IN ('AKTIF', 'PASIF'))
);

CREATE TABLE ortam (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kod TEXT NOT NULL,
    risk_kodu TEXT NOT NULL DEFAULT 'DUSUK',
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    politika_surumu INTEGER NOT NULL DEFAULT 1,
    politika JSONB NOT NULL DEFAULT '{}'::jsonb,
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_ortam PRIMARY KEY (id),
    CONSTRAINT uq_ortam_uuid UNIQUE (uuid),
    CONSTRAINT uq_ortam_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_ortam_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT ck_ortam_risk CHECK (risk_kodu IN ('DUSUK', 'ORTA', 'URETIM')),
    CONSTRAINT ck_ortam_durum CHECK (durum_kodu IN ('AKTIF', 'PASIF'))
);

CREATE TABLE ortam_sema_eslemesi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    mantiksal_sema_id BIGINT NOT NULL,
    ortam_id BIGINT NOT NULL,
    fiziksel_sema_id BIGINT NOT NULL,
    baglanti_surumu_id BIGINT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_ortam_sema_eslemesi PRIMARY KEY (id),
    CONSTRAINT uq_ortam_sema_eslemesi_uuid UNIQUE (uuid),
    CONSTRAINT uq_ortam_sema_eslemesi UNIQUE (mantiksal_sema_id, ortam_id),
    CONSTRAINT uq_ortam_sema_eslemesi_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_ortam_esleme_mantiksal FOREIGN KEY (proje_id, mantiksal_sema_id)
        REFERENCES mantiksal_sema(proje_id, id),
    CONSTRAINT fk_ortam_esleme_ortam FOREIGN KEY (proje_id, ortam_id)
        REFERENCES ortam(proje_id, id),
    CONSTRAINT fk_ortam_esleme_fiziksel FOREIGN KEY (proje_id, fiziksel_sema_id)
        REFERENCES fiziksel_sema(proje_id, id),
    CONSTRAINT fk_ortam_esleme_surum FOREIGN KEY (proje_id, baglanti_surumu_id)
        REFERENCES baglanti_surumu(proje_id, id),
    CONSTRAINT ck_ortam_esleme_durum CHECK (durum_kodu IN ('AKTIF', 'PASIF'))
);

CREATE TABLE model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    mantiksal_sema_id BIGINT NOT NULL,
    kod TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    ad TEXT NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_model PRIMARY KEY (id),
    CONSTRAINT uq_model_uuid UNIQUE (uuid),
    CONSTRAINT uq_model_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_model_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_model_mantiksal FOREIGN KEY (proje_id, mantiksal_sema_id)
        REFERENCES mantiksal_sema(proje_id, id),
    CONSTRAINT ck_model_durum CHECK (durum_kodu IN ('AKTIF', 'ARSIV'))
);

CREATE TABLE alt_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    model_id BIGINT NOT NULL,
    ust_alt_model_id BIGINT,
    kod TEXT NOT NULL,
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_alt_model PRIMARY KEY (id),
    CONSTRAINT uq_alt_model_uuid UNIQUE (uuid),
    CONSTRAINT uq_alt_model_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT uq_alt_model_kod UNIQUE NULLS NOT DISTINCT (model_id, ust_alt_model_id, kod),
    CONSTRAINT fk_alt_model_model FOREIGN KEY (proje_id, model_id) REFERENCES model(proje_id, id),
    CONSTRAINT fk_alt_model_parent FOREIGN KEY (proje_id, ust_alt_model_id) REFERENCES alt_model(proje_id, id)
);

CREATE TABLE veri_nesnesi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    model_id BIGINT NOT NULL,
    alt_model_id BIGINT,
    kod TEXT NOT NULL,
    nesne_referansi TEXT NOT NULL,
    tur_kodu TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    sorgu_tanim_surumu INTEGER,
    sorgu_tanimi JSONB,
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_veri_nesnesi PRIMARY KEY (id),
    CONSTRAINT uq_veri_nesnesi_uuid UNIQUE (uuid),
    CONSTRAINT uq_veri_nesnesi_kod UNIQUE (model_id, kod),
    CONSTRAINT uq_veri_nesnesi_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_veri_nesnesi_model FOREIGN KEY (proje_id, model_id) REFERENCES model(proje_id, id),
    CONSTRAINT fk_veri_nesnesi_alt_model FOREIGN KEY (proje_id, alt_model_id) REFERENCES alt_model(proje_id, id),
    CONSTRAINT ck_veri_nesnesi_tur CHECK (tur_kodu IN ('TABLO', 'VIEW', 'SORGU')),
    CONSTRAINT ck_veri_nesnesi_sorgu CHECK (
        (tur_kodu = 'SORGU' AND sorgu_tanim_surumu IS NOT NULL AND sorgu_tanimi IS NOT NULL) OR
        (tur_kodu <> 'SORGU' AND sorgu_tanim_surumu IS NULL AND sorgu_tanimi IS NULL)),
    CONSTRAINT ck_veri_nesnesi_durum CHECK (durum_kodu IN ('AKTIF', 'PASIF'))
);

CREATE TABLE sema_goruntusu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    veri_nesnesi_id BIGINT NOT NULL,
    fiziksel_sema_id BIGINT NOT NULL,
    baglanti_surumu_id BIGINT NOT NULL,
    parmak_izi TEXT NOT NULL,
    motor_surumu TEXT NOT NULL,
    kesif_zamani TIMESTAMPTZ NOT NULL,
    ozellik_surumu INTEGER NOT NULL DEFAULT 1,
    ozellik JSONB NOT NULL DEFAULT '{}'::jsonb,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_sema_goruntusu PRIMARY KEY (id),
    CONSTRAINT uq_sema_goruntusu_uuid UNIQUE (uuid),
    CONSTRAINT uq_sema_goruntusu UNIQUE (veri_nesnesi_id, fiziksel_sema_id, baglanti_surumu_id, parmak_izi),
    CONSTRAINT uq_sema_goruntusu_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_sema_goruntusu_nesne FOREIGN KEY (proje_id, veri_nesnesi_id) REFERENCES veri_nesnesi(proje_id, id),
    CONSTRAINT fk_sema_goruntusu_fiziksel FOREIGN KEY (proje_id, fiziksel_sema_id) REFERENCES fiziksel_sema(proje_id, id),
    CONSTRAINT fk_sema_goruntusu_surum FOREIGN KEY (proje_id, baglanti_surumu_id) REFERENCES baglanti_surumu(proje_id, id)
);

CREATE TABLE kolon_goruntusu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    sema_goruntusu_id BIGINT NOT NULL,
    kolon_referansi TEXT NOT NULL,
    uretici_tip_kodu TEXT NOT NULL,
    kanonik_tip_kodu TEXT NOT NULL,
    sira_no INTEGER NOT NULL,
    hassasiyet INTEGER,
    olcek INTEGER,
    uzunluk BIGINT,
    zaman_hassasiyeti INTEGER,
    null_olabilir BOOLEAN NOT NULL,
    varsayilan_ifade TEXT,
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_kolon_goruntusu PRIMARY KEY (id),
    CONSTRAINT uq_kolon_goruntusu_uuid UNIQUE (uuid),
    CONSTRAINT uq_kolon_goruntusu_ref UNIQUE (sema_goruntusu_id, kolon_referansi),
    CONSTRAINT uq_kolon_goruntusu_sira UNIQUE (sema_goruntusu_id, sira_no),
    CONSTRAINT uq_kolon_goruntusu_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_kolon_goruntusu_sema FOREIGN KEY (proje_id, sema_goruntusu_id) REFERENCES sema_goruntusu(proje_id, id),
    CONSTRAINT ck_kolon_goruntusu_sira CHECK (sira_no > 0),
    CONSTRAINT ck_kolon_goruntusu_uzunluk CHECK (uzunluk IS NULL OR uzunluk >= 0)
);

CREATE TABLE kisit_goruntusu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    sema_goruntusu_id BIGINT NOT NULL,
    dis_referans TEXT NOT NULL,
    tur_kodu TEXT NOT NULL,
    etkin BOOLEAN NOT NULL DEFAULT TRUE,
    ayrinti_surumu INTEGER NOT NULL DEFAULT 1,
    ayrinti JSONB NOT NULL DEFAULT '{}'::jsonb,
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_kisit_goruntusu PRIMARY KEY (id),
    CONSTRAINT uq_kisit_goruntusu_uuid UNIQUE (uuid),
    CONSTRAINT uq_kisit_goruntusu_ref UNIQUE (sema_goruntusu_id, dis_referans),
    CONSTRAINT uq_kisit_goruntusu_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_kisit_goruntusu_sema FOREIGN KEY (proje_id, sema_goruntusu_id) REFERENCES sema_goruntusu(proje_id, id),
    CONSTRAINT ck_kisit_goruntusu_tur CHECK (tur_kodu IN ('PK', 'UK', 'FK', 'CHECK'))
);

CREATE TABLE kisit_kolonu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kisit_goruntusu_id BIGINT NOT NULL,
    kolon_goruntusu_id BIGINT NOT NULL,
    sira_no INTEGER NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_kisit_kolonu PRIMARY KEY (id),
    CONSTRAINT uq_kisit_kolonu_uuid UNIQUE (uuid),
    CONSTRAINT uq_kisit_kolonu_sira UNIQUE (kisit_goruntusu_id, sira_no),
    CONSTRAINT uq_kisit_kolonu_kolon UNIQUE (kisit_goruntusu_id, kolon_goruntusu_id),
    CONSTRAINT fk_kisit_kolonu_kisit FOREIGN KEY (proje_id, kisit_goruntusu_id) REFERENCES kisit_goruntusu(proje_id, id),
    CONSTRAINT fk_kisit_kolonu_kolon FOREIGN KEY (proje_id, kolon_goruntusu_id) REFERENCES kolon_goruntusu(proje_id, id),
    CONSTRAINT ck_kisit_kolonu_sira CHECK (sira_no > 0)
);

CREATE TABLE klasor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    ust_klasor_id BIGINT,
    kod TEXT NOT NULL,
    tur_kodu TEXT NOT NULL DEFAULT 'GELISTIRME',
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    ad TEXT NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_klasor PRIMARY KEY (id),
    CONSTRAINT uq_klasor_uuid UNIQUE (uuid),
    CONSTRAINT uq_klasor_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT uq_klasor_kod UNIQUE NULLS NOT DISTINCT (proje_id, ust_klasor_id, kod),
    CONSTRAINT fk_klasor_parent FOREIGN KEY (proje_id, ust_klasor_id) REFERENCES klasor(proje_id, id),
    CONSTRAINT ck_klasor_tur CHECK (tur_kodu IN ('GELISTIRME', 'MODEL', 'YUKLEME_PLANI')),
    CONSTRAINT ck_klasor_durum CHECK (durum_kodu IN ('AKTIF', 'ARSIV')),
    CONSTRAINT ck_klasor_parent CHECK (ust_klasor_id IS NULL OR ust_klasor_id <> id)
);

CREATE TABLE tanim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT REFERENCES proje(id),
    klasor_id BIGINT,
    kapsam_kodu TEXT NOT NULL,
    tur_kodu TEXT NOT NULL,
    kod TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'TASLAK',
    ad TEXT NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_tanim PRIMARY KEY (id),
    CONSTRAINT uq_tanim_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_tanim_klasor FOREIGN KEY (proje_id, klasor_id) REFERENCES klasor(proje_id, id),
    CONSTRAINT ck_tanim_kapsam CHECK (kapsam_kodu IN ('GLOBAL', 'PROJE')),
    CONSTRAINT ck_tanim_tur CHECK (tur_kodu IN (
        'MAPPING', 'REUSABLE_MAPPING', 'PACKAGE', 'PROCEDURE', 'VARIABLE',
        'SEQUENCE', 'USER_FUNCTION', 'KNOWLEDGE_MODULE', 'LOAD_PLAN')),
    CONSTRAINT ck_tanim_durum CHECK (durum_kodu IN ('TASLAK', 'AKTIF', 'ARSIV')),
    CONSTRAINT ck_tanim_sahiplik CHECK (
        (kapsam_kodu = 'GLOBAL' AND proje_id IS NULL AND klasor_id IS NULL AND
            tur_kodu IN ('REUSABLE_MAPPING', 'VARIABLE', 'SEQUENCE', 'USER_FUNCTION', 'KNOWLEDGE_MODULE')) OR
        (kapsam_kodu = 'PROJE' AND proje_id IS NOT NULL AND
            ((tur_kodu IN ('MAPPING', 'REUSABLE_MAPPING', 'PACKAGE', 'PROCEDURE') AND klasor_id IS NOT NULL) OR
             (tur_kodu IN ('VARIABLE', 'SEQUENCE', 'USER_FUNCTION', 'KNOWLEDGE_MODULE', 'LOAD_PLAN')))))
);

CREATE UNIQUE INDEX uq_tanim_global_kod ON tanim(tur_kodu, kod) WHERE proje_id IS NULL;
CREATE UNIQUE INDEX uq_tanim_proje_kod ON tanim(proje_id, tur_kodu, kod) WHERE proje_id IS NOT NULL;

CREATE TABLE tanim_taslagi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tanim_id BIGINT NOT NULL REFERENCES tanim(id),
    sema_surumu INTEGER NOT NULL,
    icerik JSONB NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_tanim_taslagi PRIMARY KEY (id),
    CONSTRAINT uq_tanim_taslagi_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_taslagi_tanim UNIQUE (tanim_id),
    CONSTRAINT ck_tanim_taslagi_sema CHECK (sema_surumu > 0),
    CONSTRAINT ck_tanim_taslagi_json CHECK (jsonb_typeof(icerik) = 'object')
);

CREATE TABLE tanim_surumu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tanim_id BIGINT NOT NULL REFERENCES tanim(id),
    surum_no INTEGER NOT NULL,
    sema_surumu INTEGER NOT NULL,
    icerik_ozeti TEXT NOT NULL,
    icerik JSONB NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_tanim_surumu PRIMARY KEY (id),
    CONSTRAINT uq_tanim_surumu_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_surumu UNIQUE (tanim_id, surum_no),
    CONSTRAINT ck_tanim_surumu_no CHECK (surum_no > 0 AND sema_surumu > 0),
    CONSTRAINT ck_tanim_surumu_json CHECK (jsonb_typeof(icerik) = 'object')
);

CREATE TABLE tanim_gorunumu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tanim_id BIGINT NOT NULL REFERENCES tanim(id),
    kullanici_id BIGINT NOT NULL REFERENCES kullanici(id),
    gorunum_surumu INTEGER NOT NULL DEFAULT 1,
    gorunum JSONB NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_tanim_gorunumu PRIMARY KEY (id),
    CONSTRAINT uq_tanim_gorunumu_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_gorunumu UNIQUE (tanim_id, kullanici_id),
    CONSTRAINT ck_tanim_gorunumu_json CHECK (jsonb_typeof(gorunum) = 'object')
);

CREATE TABLE tanim_bagimliligi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kaynak_tanim_surumu_id BIGINT NOT NULL REFERENCES tanim_surumu(id),
    hedef_tanim_surumu_id BIGINT NOT NULL REFERENCES tanim_surumu(id),
    rol_kodu TEXT NOT NULL,
    dugum_kodu TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_tanim_bagimliligi PRIMARY KEY (id),
    CONSTRAINT uq_tanim_bagimliligi_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_bagimliligi UNIQUE (kaynak_tanim_surumu_id, hedef_tanim_surumu_id, rol_kodu, dugum_kodu),
    CONSTRAINT ck_tanim_bagimliligi_rol CHECK (rol_kodu IN (
        'CALLS', 'READS', 'WRITES', 'USES_VARIABLE', 'USES_SEQUENCE',
        'USES_FUNCTION', 'USES_KM', 'GENERATED_FROM')),
    CONSTRAINT ck_tanim_bagimliligi_self CHECK (kaynak_tanim_surumu_id <> hedef_tanim_surumu_id)
);

CREATE TABLE dogrulama (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tanim_surumu_id BIGINT NOT NULL REFERENCES tanim_surumu(id),
    ortam_id BIGINT REFERENCES ortam(id),
    icerik_ozeti TEXT NOT NULL,
    sonuc_kodu TEXT NOT NULL,
    hata_sayisi INTEGER NOT NULL DEFAULT 0,
    uyari_sayisi INTEGER NOT NULL DEFAULT 0,
    sonuc_surumu INTEGER NOT NULL DEFAULT 1,
    sonuc JSONB NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_dogrulama PRIMARY KEY (id),
    CONSTRAINT uq_dogrulama_uuid UNIQUE (uuid),
    CONSTRAINT ck_dogrulama_sonuc CHECK (sonuc_kodu IN ('GECTI', 'UYARI', 'BLOKE')),
    CONSTRAINT ck_dogrulama_sayilar CHECK (hata_sayisi >= 0 AND uyari_sayisi >= 0),
    CONSTRAINT ck_dogrulama_json CHECK (jsonb_typeof(sonuc) = 'object')
);

CREATE TABLE senaryo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tanim_surumu_id BIGINT NOT NULL REFERENCES tanim_surumu(id),
    dogrulama_id BIGINT NOT NULL REFERENCES dogrulama(id),
    surum_no INTEGER NOT NULL,
    plan_surumu INTEGER NOT NULL,
    plan_ozeti TEXT NOT NULL,
    plan JSONB NOT NULL,
    parametre_semasi JSONB NOT NULL DEFAULT '{}'::jsonb,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_senaryo PRIMARY KEY (id),
    CONSTRAINT uq_senaryo_uuid UNIQUE (uuid),
    CONSTRAINT uq_senaryo_surum UNIQUE (tanim_surumu_id, surum_no),
    CONSTRAINT ck_senaryo_no CHECK (surum_no > 0 AND plan_surumu > 0),
    CONSTRAINT ck_senaryo_json CHECK (jsonb_typeof(plan) = 'object' AND jsonb_typeof(parametre_semasi) = 'object')
);

CREATE TABLE yayin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    senaryo_id BIGINT NOT NULL REFERENCES senaryo(id),
    ortam_id BIGINT NOT NULL,
    yayin_no INTEGER NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'ONAY_BEKLIYOR',
    bagimlilik_ozeti TEXT NOT NULL,
    fiziksel_manifesto JSONB NOT NULL,
    yayin_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_yayin PRIMARY KEY (id),
    CONSTRAINT uq_yayin_uuid UNIQUE (uuid),
    CONSTRAINT uq_yayin UNIQUE (senaryo_id, ortam_id, yayin_no),
    CONSTRAINT uq_yayin_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_yayin_ortam FOREIGN KEY (proje_id, ortam_id) REFERENCES ortam(proje_id, id),
    CONSTRAINT ck_yayin_no CHECK (yayin_no > 0),
    CONSTRAINT ck_yayin_durum CHECK (durum_kodu IN ('ONAY_BEKLIYOR', 'AKTIF', 'ASKIDA', 'IPTAL')),
    CONSTRAINT ck_yayin_json CHECK (jsonb_typeof(fiziksel_manifesto) = 'object')
);

CREATE TABLE yayin_onayi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    yayin_id BIGINT NOT NULL,
    kullanici_id BIGINT NOT NULL REFERENCES kullanici(id),
    plan_ozeti TEXT NOT NULL,
    karar_kodu TEXT NOT NULL,
    karar_zamani TIMESTAMPTZ NOT NULL,
    gerekce TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_yayin_onayi PRIMARY KEY (id),
    CONSTRAINT uq_yayin_onayi_uuid UNIQUE (uuid),
    CONSTRAINT uq_yayin_onayi UNIQUE (yayin_id, kullanici_id, karar_zamani),
    CONSTRAINT fk_yayin_onayi_yayin FOREIGN KEY (proje_id, yayin_id) REFERENCES yayin(proje_id, id),
    CONSTRAINT ck_yayin_onayi_karar CHECK (karar_kodu IN ('ONAY', 'RED', 'GERI_CEK'))
);

CREATE TABLE zamanlama (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    yayin_id BIGINT NOT NULL,
    kod TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'ASKIDA',
    cakisma_politikasi TEXT NOT NULL DEFAULT 'SKIP',
    kacirma_politikasi TEXT NOT NULL DEFAULT 'SKIP',
    sonraki_tetikleme_zamani TIMESTAMPTZ,
    cron_ifadesi TEXT NOT NULL,
    zaman_dilimi TEXT NOT NULL,
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_zamanlama PRIMARY KEY (id),
    CONSTRAINT uq_zamanlama_uuid UNIQUE (uuid),
    CONSTRAINT uq_zamanlama_kod UNIQUE (proje_id, kod),
    CONSTRAINT fk_zamanlama_yayin FOREIGN KEY (proje_id, yayin_id) REFERENCES yayin(proje_id, id),
    CONSTRAINT ck_zamanlama_durum CHECK (durum_kodu IN ('AKTIF', 'ASKIDA')),
    CONSTRAINT ck_zamanlama_cakisma CHECK (cakisma_politikasi IN ('SKIP', 'QUEUE', 'PARALLEL')),
    CONSTRAINT ck_zamanlama_kacirma CHECK (kacirma_politikasi IN ('SKIP', 'RUN_ONCE'))
);

CREATE TABLE worker_profili (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kod TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'AKTIF',
    capability_surumu INTEGER NOT NULL DEFAULT 1,
    capability JSONB NOT NULL,
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_worker_profili PRIMARY KEY (id),
    CONSTRAINT uq_worker_profili_uuid UNIQUE (uuid),
    CONSTRAINT uq_worker_profili_kod UNIQUE (kod),
    CONSTRAINT ck_worker_profili_durum CHECK (durum_kodu IN ('AKTIF', 'PASIF')),
    CONSTRAINT ck_worker_profili_json CHECK (jsonb_typeof(capability) = 'object')
);

CREATE TABLE is_talebi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    yayin_id BIGINT,
    zamanlama_id BIGINT REFERENCES zamanlama(id),
    istek_ozeti TEXT NOT NULL,
    is_turu TEXT NOT NULL,
    oncelik INTEGER NOT NULL DEFAULT 50,
    planlanan_zamani TIMESTAMPTZ,
    parametre_surumu INTEGER NOT NULL DEFAULT 1,
    parametre JSONB NOT NULL DEFAULT '{}'::jsonb,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_is_talebi PRIMARY KEY (id),
    CONSTRAINT uq_is_talebi_uuid UNIQUE (uuid),
    CONSTRAINT uq_is_talebi_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_is_talebi_yayin FOREIGN KEY (proje_id, yayin_id) REFERENCES yayin(proje_id, id),
    CONSTRAINT ck_is_talebi_tur CHECK (is_turu IN ('RUN', 'TEST', 'KESIF', 'ONIZLEME')),
    CONSTRAINT ck_is_talebi_oncelik CHECK (oncelik BETWEEN 0 AND 100),
    CONSTRAINT ck_is_talebi_json CHECK (jsonb_typeof(parametre) = 'object'),
    CONSTRAINT ck_is_talebi_run CHECK (is_turu <> 'RUN' OR yayin_id IS NOT NULL),
    CONSTRAINT ck_is_talebi_zamanlama CHECK (zamanlama_id IS NULL OR planlanan_zamani IS NOT NULL)
);

CREATE UNIQUE INDEX uq_is_talebi_zamanlama ON is_talebi(zamanlama_id, planlanan_zamani)
    WHERE zamanlama_id IS NOT NULL;

CREATE TABLE calistirma (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    is_talebi_id BIGINT NOT NULL,
    deneme_no INTEGER NOT NULL,
    plan_ozeti TEXT NOT NULL,
    baslatma_turu TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_calistirma PRIMARY KEY (id),
    CONSTRAINT uq_calistirma_uuid UNIQUE (uuid),
    CONSTRAINT uq_calistirma UNIQUE (is_talebi_id, deneme_no),
    CONSTRAINT uq_calistirma_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_calistirma_is FOREIGN KEY (proje_id, is_talebi_id) REFERENCES is_talebi(proje_id, id),
    CONSTRAINT ck_calistirma_deneme CHECK (deneme_no > 0),
    CONSTRAINT ck_calistirma_baslatma CHECK (baslatma_turu IN ('ILK', 'RETRY', 'RESUME'))
);

CREATE TABLE hedef_kaynagi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    calistirma_id BIGINT REFERENCES calistirma(id),
    fiziksel_ozet TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'BOS',
    nesil_no BIGINT NOT NULL DEFAULT 0,
    kiralama_bitis_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_hedef_kaynagi PRIMARY KEY (id),
    CONSTRAINT uq_hedef_kaynagi_uuid UNIQUE (uuid),
    CONSTRAINT uq_hedef_kaynagi_ozet UNIQUE (fiziksel_ozet),
    CONSTRAINT ck_hedef_kaynagi_durum CHECK (durum_kodu IN ('BOS', 'SAHIPLENILDI', 'ASKIDA')),
    CONSTRAINT ck_hedef_kaynagi_nesil CHECK (nesil_no >= 0),
    CONSTRAINT ck_hedef_kaynagi_sahip CHECK (
        (durum_kodu = 'SAHIPLENILDI' AND calistirma_id IS NOT NULL AND kiralama_bitis_zamani IS NOT NULL) OR
        durum_kodu <> 'SAHIPLENILDI')
);

CREATE TABLE calistirma_durumu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_id BIGINT NOT NULL,
    hedef_kaynagi_id BIGINT REFERENCES hedef_kaynagi(id),
    worker_profili_id BIGINT REFERENCES worker_profili(id),
    isleyici_referansi TEXT,
    durum_kodu TEXT NOT NULL,
    nesil_no BIGINT NOT NULL DEFAULT 0,
    hedef_nesil_no BIGINT,
    son_olay_no BIGINT NOT NULL DEFAULT 0,
    kiralama_bitis_zamani TIMESTAMPTZ,
    yasam_sinyali_zamani TIMESTAMPTZ,
    baslama_zamani TIMESTAMPTZ,
    bitis_zamani TIMESTAMPTZ,
    iptal_isteme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_calistirma_durumu PRIMARY KEY (id),
    CONSTRAINT uq_calistirma_durumu_uuid UNIQUE (uuid),
    CONSTRAINT uq_calistirma_durumu_run UNIQUE (calistirma_id),
    CONSTRAINT fk_calistirma_durumu_run FOREIGN KEY (proje_id, calistirma_id) REFERENCES calistirma(proje_id, id),
    CONSTRAINT ck_calistirma_durumu_kod CHECK (durum_kodu IN (
        'BEKLIYOR', 'SAHIPLENILDI', 'CALISIYOR', 'IPTAL_ISTENDI', 'BASARILI',
        'BASARISIZ', 'IPTAL', 'SONUCU_BILINMIYOR')),
    CONSTRAINT ck_calistirma_durumu_nesil CHECK (nesil_no >= 0 AND son_olay_no >= 0),
    CONSTRAINT ck_calistirma_durumu_zaman CHECK (bitis_zamani IS NULL OR baslama_zamani IS NULL OR bitis_zamani >= baslama_zamani)
);

CREATE TABLE calistirma_adimi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_id BIGINT NOT NULL,
    adim_kodu TEXT NOT NULL,
    tur_kodu TEXT NOT NULL,
    sira_no INTEGER NOT NULL,
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_calistirma_adimi PRIMARY KEY (id),
    CONSTRAINT uq_calistirma_adimi_uuid UNIQUE (uuid),
    CONSTRAINT uq_calistirma_adimi UNIQUE (calistirma_id, adim_kodu),
    CONSTRAINT uq_calistirma_adimi_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_calistirma_adimi_run FOREIGN KEY (proje_id, calistirma_id) REFERENCES calistirma(proje_id, id),
    CONSTRAINT ck_calistirma_adimi_tur CHECK (tur_kodu IN (
        'PREFLIGHT', 'MAPPING', 'PROCEDURE', 'VARIABLE', 'PACKAGE', 'LOAD_PLAN',
        'EXTRACT', 'STAGE', 'VALIDATE', 'PUBLISH', 'RECONCILE')),
    CONSTRAINT ck_calistirma_adimi_sira CHECK (sira_no > 0)
);

CREATE TABLE calistirma_gorevi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_adimi_id BIGINT NOT NULL,
    gorev_kodu TEXT NOT NULL,
    tur_kodu TEXT NOT NULL,
    sira_no INTEGER NOT NULL,
    teknoloji_kodu TEXT,
    ad TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_calistirma_gorevi PRIMARY KEY (id),
    CONSTRAINT uq_calistirma_gorevi_uuid UNIQUE (uuid),
    CONSTRAINT uq_calistirma_gorevi UNIQUE (calistirma_adimi_id, gorev_kodu),
    CONSTRAINT uq_calistirma_gorevi_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_calistirma_gorevi_adim FOREIGN KEY (proje_id, calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id, id),
    CONSTRAINT ck_calistirma_gorevi_tur CHECK (tur_kodu IN ('SOURCE_COMMAND', 'TARGET_COMMAND', 'TRANSFER', 'CONTROL')),
    CONSTRAINT ck_calistirma_gorevi_sira CHECK (sira_no > 0)
);

CREATE TABLE calistirma_olayi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_id BIGINT NOT NULL,
    calistirma_adimi_id BIGINT,
    calistirma_gorevi_id BIGINT,
    olay_no BIGINT NOT NULL,
    tur_kodu TEXT NOT NULL,
    olay_zamani TIMESTAMPTZ NOT NULL,
    veri_surumu INTEGER NOT NULL DEFAULT 1,
    veri JSONB NOT NULL DEFAULT '{}'::jsonb,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_calistirma_olayi PRIMARY KEY (id),
    CONSTRAINT uq_calistirma_olayi_uuid UNIQUE (uuid),
    CONSTRAINT uq_calistirma_olayi UNIQUE (calistirma_id, olay_no),
    CONSTRAINT fk_calistirma_olayi_run FOREIGN KEY (proje_id, calistirma_id) REFERENCES calistirma(proje_id, id),
    CONSTRAINT fk_calistirma_olayi_adim FOREIGN KEY (proje_id, calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id, id),
    CONSTRAINT fk_calistirma_olayi_gorev FOREIGN KEY (proje_id, calistirma_gorevi_id) REFERENCES calistirma_gorevi(proje_id, id),
    CONSTRAINT ck_calistirma_olayi_no CHECK (olay_no > 0),
    CONSTRAINT ck_calistirma_olayi_json CHECK (jsonb_typeof(veri) = 'object')
);

CREATE TABLE degisken_deger_olayi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tanim_id BIGINT NOT NULL REFERENCES tanim(id),
    calistirma_id BIGINT REFERENCES calistirma(id),
    calistirma_adimi_id BIGINT REFERENCES calistirma_adimi(id),
    kaynak_kodu TEXT NOT NULL,
    deger_turu TEXT NOT NULL,
    deger JSONB,
    redakte BOOLEAN NOT NULL DEFAULT FALSE,
    olay_zamani TIMESTAMPTZ NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_degisken_deger_olayi PRIMARY KEY (id),
    CONSTRAINT uq_degisken_deger_olayi_uuid UNIQUE (uuid),
    CONSTRAINT ck_degisken_deger_kaynak CHECK (kaynak_kodu IN ('INPUT', 'DEFAULT', 'REFRESH_QUERY', 'EXPRESSION', 'STEP_OUTPUT')),
    CONSTRAINT ck_degisken_deger_tur CHECK (deger_turu IN ('STRING', 'INTEGER', 'DECIMAL', 'BOOLEAN', 'DATE', 'TIMESTAMP', 'JSON')),
    CONSTRAINT ck_degisken_deger_redakte CHECK (NOT redakte OR deger IS NULL)
);

CREATE TABLE sekans_durumu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tanim_id BIGINT NOT NULL REFERENCES tanim(id),
    guncel_deger NUMERIC NOT NULL,
    nesil_no BIGINT NOT NULL DEFAULT 0,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_sekans_durumu PRIMARY KEY (id),
    CONSTRAINT uq_sekans_durumu_uuid UNIQUE (uuid),
    CONSTRAINT uq_sekans_durumu_tanim UNIQUE (tanim_id),
    CONSTRAINT ck_sekans_durumu_nesil CHECK (nesil_no >= 0)
);

CREATE TABLE sekans_deger_olayi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tanim_id BIGINT NOT NULL REFERENCES tanim(id),
    calistirma_id BIGINT REFERENCES calistirma(id),
    uygulama_kodu TEXT NOT NULL,
    uretilen_deger NUMERIC NOT NULL,
    nesil_no BIGINT NOT NULL,
    olay_zamani TIMESTAMPTZ NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_sekans_deger_olayi PRIMARY KEY (id),
    CONSTRAINT uq_sekans_deger_olayi_uuid UNIQUE (uuid),
    CONSTRAINT ck_sekans_deger_uygulama CHECK (uygulama_kodu IN ('NATIVE', 'REPOSITORY', 'TABLE')),
    CONSTRAINT ck_sekans_deger_nesil CHECK (nesil_no >= 0)
);

CREATE TABLE kontrol_noktasi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_id BIGINT NOT NULL,
    calistirma_adimi_id BIGINT NOT NULL,
    kapsam_ozeti TEXT NOT NULL,
    bolum_kodu TEXT NOT NULL,
    sira_no BIGINT NOT NULL,
    paket_anahtari TEXT NOT NULL,
    hedef_defter_referansi TEXT NOT NULL,
    tur_kodu TEXT NOT NULL,
    dogrulama_zamani TIMESTAMPTZ NOT NULL,
    imlec_surumu INTEGER NOT NULL DEFAULT 1,
    imlec JSONB NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_kontrol_noktasi PRIMARY KEY (id),
    CONSTRAINT uq_kontrol_noktasi_uuid UNIQUE (uuid),
    CONSTRAINT uq_kontrol_noktasi UNIQUE (calistirma_id, calistirma_adimi_id, bolum_kodu, sira_no),
    CONSTRAINT fk_kontrol_noktasi_run FOREIGN KEY (proje_id, calistirma_id) REFERENCES calistirma(proje_id, id),
    CONSTRAINT fk_kontrol_noktasi_adim FOREIGN KEY (proje_id, calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id, id),
    CONSTRAINT ck_kontrol_noktasi_tur CHECK (tur_kodu IN ('BATCH', 'PUBLISH', 'WATERMARK')),
    CONSTRAINT ck_kontrol_noktasi_sira CHECK (sira_no > 0),
    CONSTRAINT ck_kontrol_noktasi_json CHECK (jsonb_typeof(imlec) = 'object')
);

CREATE TABLE metrik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_id BIGINT NOT NULL,
    calistirma_adimi_id BIGINT,
    kod TEXT NOT NULL,
    kalite_kodu TEXT NOT NULL,
    olcum_zamani TIMESTAMPTZ NOT NULL,
    deger NUMERIC,
    birim TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_metrik PRIMARY KEY (id),
    CONSTRAINT uq_metrik_uuid UNIQUE (uuid),
    CONSTRAINT fk_metrik_run FOREIGN KEY (proje_id, calistirma_id) REFERENCES calistirma(proje_id, id),
    CONSTRAINT fk_metrik_adim FOREIGN KEY (proje_id, calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id, id),
    CONSTRAINT ck_metrik_kalite CHECK (kalite_kodu IN ('KESIN', 'TAHMIN', 'BILINMIYOR')),
    CONSTRAINT ck_metrik_deger CHECK ((kalite_kodu = 'BILINMIYOR' AND deger IS NULL) OR kalite_kodu <> 'BILINMIYOR')
);

CREATE TABLE hata_ozeti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_id BIGINT NOT NULL,
    calistirma_adimi_id BIGINT,
    hata_kodu TEXT NOT NULL,
    sinif_kodu TEXT NOT NULL,
    kayit_turu TEXT NOT NULL,
    tekrar_denenebilir BOOLEAN NOT NULL,
    satir_sayisi BIGINT,
    hata_zamani TIMESTAMPTZ NOT NULL,
    ornek_surumu INTEGER,
    maskeli_ornek JSONB,
    mesaj TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_hata_ozeti PRIMARY KEY (id),
    CONSTRAINT uq_hata_ozeti_uuid UNIQUE (uuid),
    CONSTRAINT fk_hata_ozeti_run FOREIGN KEY (proje_id, calistirma_id) REFERENCES calistirma(proje_id, id),
    CONSTRAINT fk_hata_ozeti_adim FOREIGN KEY (proje_id, calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id, id),
    CONSTRAINT ck_hata_ozeti_tur CHECK (kayit_turu IN ('OZET', 'ORNEK')),
    CONSTRAINT ck_hata_ozeti_sayim CHECK (satir_sayisi IS NULL OR satir_sayisi >= 0)
);

CREATE TABLE denetim_olayi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT REFERENCES proje(id),
    kullanici_id BIGINT REFERENCES kullanici(id),
    dis_nesne_uuid UUID,
    korelasyon_kodu TEXT NOT NULL,
    aktor_turu TEXT NOT NULL,
    eylem_kodu TEXT NOT NULL,
    sonuc_kodu TEXT NOT NULL,
    olay_zamani TIMESTAMPTZ NOT NULL,
    ayrinti_surumu INTEGER NOT NULL DEFAULT 1,
    ayrinti JSONB NOT NULL DEFAULT '{}'::jsonb,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_denetim_olayi PRIMARY KEY (id),
    CONSTRAINT uq_denetim_olayi_uuid UNIQUE (uuid),
    CONSTRAINT ck_denetim_olayi_aktor CHECK (aktor_turu IN ('KULLANICI', 'SISTEM')),
    CONSTRAINT ck_denetim_olayi_sonuc CHECK (sonuc_kodu IN ('BASARILI', 'RED', 'BASARISIZ')),
    CONSTRAINT ck_denetim_olayi_json CHECK (jsonb_typeof(ayrinti) = 'object')
);

CREATE TABLE veri_soyu_olayi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_id BIGINT NOT NULL,
    olay_anahtari TEXT NOT NULL,
    standart_surumu TEXT NOT NULL,
    tur_kodu TEXT NOT NULL,
    olay_zamani TIMESTAMPTZ NOT NULL,
    veri JSONB NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_veri_soyu_olayi PRIMARY KEY (id),
    CONSTRAINT uq_veri_soyu_olayi_uuid UNIQUE (uuid),
    CONSTRAINT uq_veri_soyu_olayi_anahtar UNIQUE (olay_anahtari),
    CONSTRAINT fk_veri_soyu_olayi_run FOREIGN KEY (proje_id, calistirma_id) REFERENCES calistirma(proje_id, id),
    CONSTRAINT ck_veri_soyu_olayi_json CHECK (jsonb_typeof(veri) = 'object')
);

CREATE TABLE olay_kutusu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT REFERENCES proje(id),
    calistirma_olayi_id BIGINT REFERENCES calistirma_olayi(id),
    denetim_olayi_id BIGINT REFERENCES denetim_olayi(id),
    veri_soyu_olayi_id BIGINT REFERENCES veri_soyu_olayi(id),
    hedef_kodu TEXT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'BEKLIYOR',
    deneme_sayisi INTEGER NOT NULL DEFAULT 0,
    sonraki_deneme_zamani TIMESTAMPTZ,
    teslim_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_olay_kutusu PRIMARY KEY (id),
    CONSTRAINT uq_olay_kutusu_uuid UNIQUE (uuid),
    CONSTRAINT ck_olay_kutusu_durum CHECK (durum_kodu IN ('BEKLIYOR', 'GONDERILDI', 'BASARISIZ')),
    CONSTRAINT ck_olay_kutusu_deneme CHECK (deneme_sayisi >= 0),
    CONSTRAINT ck_olay_kutusu_kaynak CHECK (num_nonnulls(calistirma_olayi_id, denetim_olayi_id, veri_soyu_olayi_id) = 1)
);

CREATE UNIQUE INDEX uq_olay_kutusu_calistirma ON olay_kutusu(calistirma_olayi_id, hedef_kodu)
    WHERE calistirma_olayi_id IS NOT NULL;
CREATE UNIQUE INDEX uq_olay_kutusu_denetim ON olay_kutusu(denetim_olayi_id, hedef_kodu)
    WHERE denetim_olayi_id IS NOT NULL;
CREATE UNIQUE INDEX uq_olay_kutusu_soy ON olay_kutusu(veri_soyu_olayi_id, hedef_kodu)
    WHERE veri_soyu_olayi_id IS NOT NULL;

CREATE TABLE istek_anahtari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kullanici_id BIGINT NOT NULL REFERENCES kullanici(id),
    is_talebi_id BIGINT,
    kapsam_kodu TEXT NOT NULL,
    anahtar_ozeti TEXT NOT NULL,
    istek_ozeti TEXT NOT NULL,
    durum_kodu TEXT NOT NULL,
    sona_erme_zamani TIMESTAMPTZ NOT NULL,
    yanit_surumu INTEGER,
    yanit JSONB,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_istek_anahtari PRIMARY KEY (id),
    CONSTRAINT uq_istek_anahtari_uuid UNIQUE (uuid),
    CONSTRAINT uq_istek_anahtari UNIQUE (proje_id, kullanici_id, kapsam_kodu, anahtar_ozeti),
    CONSTRAINT fk_istek_anahtari_is FOREIGN KEY (proje_id, is_talebi_id) REFERENCES is_talebi(proje_id, id),
    CONSTRAINT ck_istek_anahtari_durum CHECK (durum_kodu IN ('ISLENIYOR', 'TAMAMLANDI', 'BASARISIZ')),
    CONSTRAINT ck_istek_anahtari_yanit CHECK ((yanit IS NULL AND yanit_surumu IS NULL) OR (yanit IS NOT NULL AND yanit_surumu IS NOT NULL))
);

CREATE TABLE sema_gocu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    surum_no BIGINT NOT NULL,
    dosya_referansi TEXT NOT NULL,
    icerik_ozeti TEXT NOT NULL,
    uygulama_surumu TEXT NOT NULL,
    uygulama_zamani TIMESTAMPTZ NOT NULL,
    sure_ms BIGINT NOT NULL,
    aciklama TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_sema_gocu PRIMARY KEY (id),
    CONSTRAINT uq_sema_gocu_uuid UNIQUE (uuid),
    CONSTRAINT uq_sema_gocu_surum UNIQUE (surum_no),
    CONSTRAINT uq_sema_gocu_dosya UNIQUE (dosya_referansi),
    CONSTRAINT ck_sema_gocu_deger CHECK (surum_no > 0 AND sure_ms >= 0)
);

CREATE INDEX ix_proje_uyeligi_kullanici ON proje_uyeligi(kullanici_id, durum_kodu);
CREATE INDEX ix_baglanti_proje_durum ON baglanti(proje_id, durum_kodu);
CREATE INDEX ix_ortam_proje_risk ON ortam(proje_id, risk_kodu);
CREATE INDEX ix_veri_nesnesi_model ON veri_nesnesi(proje_id, model_id);
CREATE INDEX ix_sema_goruntusu_nesne ON sema_goruntusu(proje_id, veri_nesnesi_id, kesif_zamani);
CREATE INDEX ix_tanim_proje_tur ON tanim(proje_id, tur_kodu, durum_kodu);
CREATE INDEX ix_tanim_bagimliligi_hedef ON tanim_bagimliligi(hedef_tanim_surumu_id);
CREATE INDEX ix_yayin_proje_ortam ON yayin(proje_id, ortam_id, durum_kodu);
CREATE INDEX ix_zamanlama_tetikleme ON zamanlama(durum_kodu, sonraki_tetikleme_zamani);
CREATE INDEX ix_calistirma_durumu_claim ON calistirma_durumu(durum_kodu, kiralama_bitis_zamani);
CREATE INDEX ix_calistirma_olayi_run ON calistirma_olayi(proje_id, calistirma_id, olay_no);
CREATE INDEX ix_kontrol_noktasi_run ON kontrol_noktasi(proje_id, calistirma_id, sira_no);
CREATE INDEX ix_hata_ozeti_run ON hata_ozeti(proje_id, calistirma_id);
CREATE INDEX ix_denetim_olayi_proje ON denetim_olayi(proje_id, olay_zamani);
CREATE INDEX ix_veri_soyu_olayi_run ON veri_soyu_olayi(proje_id, calistirma_id);
CREATE INDEX ix_olay_kutusu_teslim ON olay_kutusu(durum_kodu, sonraki_deneme_zamani);

CREATE FUNCTION immutable_update_engelle() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% tablosundaki immutable kayıt güncellenemez', TG_TABLE_NAME;
END;
$$;

CREATE TRIGGER tr_tanim_surumu_immutable BEFORE UPDATE ON tanim_surumu
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_dogrulama_immutable BEFORE UPDATE ON dogrulama
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_senaryo_immutable BEFORE UPDATE ON senaryo
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_calistirma_immutable BEFORE UPDATE ON calistirma
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_calistirma_adimi_immutable BEFORE UPDATE ON calistirma_adimi
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_calistirma_gorevi_immutable BEFORE UPDATE ON calistirma_gorevi
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_calistirma_olayi_immutable BEFORE UPDATE ON calistirma_olayi
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_degisken_deger_immutable BEFORE UPDATE ON degisken_deger_olayi
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_sekans_deger_immutable BEFORE UPDATE ON sekans_deger_olayi
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_kontrol_noktasi_immutable BEFORE UPDATE ON kontrol_noktasi
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_denetim_olayi_immutable BEFORE UPDATE ON denetim_olayi
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_veri_soyu_immutable BEFORE UPDATE ON veri_soyu_olayi
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();

COMMENT ON TABLE tanim IS 'Mapping, Package, Procedure, Variable, Sequence, User Function, KM ve Load Plan kimlik kataloğu';
COMMENT ON TABLE tanim_surumu IS 'Tasarım nesnesinin immutable ve şema sürümlü içeriği';
COMMENT ON TABLE senaryo IS 'Doğrulanmış tanım sürümünden deterministik üretilen immutable executable';
COMMENT ON TABLE degisken_deger_olayi IS 'Session/adım boyunca değişken değerinin append-only kanıtı';
COMMENT ON TABLE sekans_durumu IS 'Yalnız REPOSITORY uygulamalı Sequence için atomik sayaç durumu';
