SET search_path TO entegrasyon, public;

CREATE TABLE baglanti_yetkisi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    baglanti_id BIGINT NOT NULL,
    proje_rolu_id BIGINT NOT NULL,
    ortam_id BIGINT NOT NULL,
    yetki_id BIGINT NOT NULL REFERENCES yetki(id),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_baglanti_yetkisi PRIMARY KEY (id),
    CONSTRAINT uq_baglanti_yetkisi_uuid UNIQUE (uuid),
    CONSTRAINT uq_baglanti_yetkisi UNIQUE (baglanti_id, proje_rolu_id, ortam_id, yetki_id),
    CONSTRAINT fk_baglanti_yetkisi_baglanti FOREIGN KEY (proje_id, baglanti_id)
        REFERENCES baglanti(proje_id, id),
    CONSTRAINT fk_baglanti_yetkisi_rol FOREIGN KEY (proje_id, proje_rolu_id)
        REFERENCES proje_rolu(proje_id, id),
    CONSTRAINT fk_baglanti_yetkisi_ortam FOREIGN KEY (proje_id, ortam_id)
        REFERENCES ortam(proje_id, id),
    CONSTRAINT ck_baglanti_yetkisi_audit CHECK (versiyon_no > 0 AND
        (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani))
);

CREATE TABLE tanim_veri_nesnesi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    tanim_surumu_id BIGINT NOT NULL REFERENCES tanim_surumu(id),
    veri_nesnesi_id BIGINT NOT NULL,
    sema_goruntusu_id BIGINT NOT NULL,
    dugum_kodu TEXT NOT NULL,
    rol_kodu TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_tanim_veri_nesnesi PRIMARY KEY (id),
    CONSTRAINT uq_tanim_veri_nesnesi_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_veri_nesnesi_dugum UNIQUE (tanim_surumu_id, dugum_kodu),
    CONSTRAINT uq_tanim_veri_nesnesi_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_tanim_veri_nesnesi_nesne FOREIGN KEY (proje_id, veri_nesnesi_id)
        REFERENCES veri_nesnesi(proje_id, id),
    CONSTRAINT fk_tanim_veri_nesnesi_sema FOREIGN KEY (proje_id, sema_goruntusu_id)
        REFERENCES sema_goruntusu(proje_id, id),
    CONSTRAINT ck_tanim_veri_nesnesi_rol CHECK (rol_kodu IN ('KAYNAK', 'HEDEF'))
);

CREATE FUNCTION tanim_veri_nesnesi_proje_dogrula() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    tanim_proje_id BIGINT;
BEGIN
    SELECT t.proje_id
      INTO tanim_proje_id
      FROM tanim_surumu ts
      JOIN tanim t ON t.id = ts.tanim_id
     WHERE ts.id = NEW.tanim_surumu_id;

    IF tanim_proje_id IS NULL OR tanim_proje_id <> NEW.proje_id THEN
        RAISE EXCEPTION 'Tanım sürümü ile veri nesnesi aynı projede olmalıdır';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_tanim_veri_nesnesi_proje
    BEFORE INSERT OR UPDATE ON tanim_veri_nesnesi
    FOR EACH ROW EXECUTE FUNCTION tanim_veri_nesnesi_proje_dogrula();

CREATE TABLE yayin_veri_bagi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    yayin_id BIGINT NOT NULL,
    tanim_veri_nesnesi_id BIGINT NOT NULL,
    ortam_sema_eslemesi_id BIGINT NOT NULL,
    fiziksel_sema_id BIGINT NOT NULL,
    baglanti_surumu_id BIGINT NOT NULL,
    sema_goruntusu_id BIGINT NOT NULL,
    fiziksel_kimlik TEXT NOT NULL,
    bag_versiyon_no BIGINT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_yayin_veri_bagi PRIMARY KEY (id),
    CONSTRAINT uq_yayin_veri_bagi_uuid UNIQUE (uuid),
    CONSTRAINT uq_yayin_veri_bagi UNIQUE (yayin_id, tanim_veri_nesnesi_id),
    CONSTRAINT fk_yayin_veri_bagi_yayin FOREIGN KEY (proje_id, yayin_id)
        REFERENCES yayin(proje_id, id),
    CONSTRAINT fk_yayin_veri_bagi_tanim FOREIGN KEY (proje_id, tanim_veri_nesnesi_id)
        REFERENCES tanim_veri_nesnesi(proje_id, id),
    CONSTRAINT fk_yayin_veri_bagi_ortam FOREIGN KEY (proje_id, ortam_sema_eslemesi_id)
        REFERENCES ortam_sema_eslemesi(proje_id, id),
    CONSTRAINT fk_yayin_veri_bagi_fiziksel FOREIGN KEY (proje_id, fiziksel_sema_id)
        REFERENCES fiziksel_sema(proje_id, id),
    CONSTRAINT fk_yayin_veri_bagi_surum FOREIGN KEY (proje_id, baglanti_surumu_id)
        REFERENCES baglanti_surumu(proje_id, id),
    CONSTRAINT fk_yayin_veri_bagi_sema FOREIGN KEY (proje_id, sema_goruntusu_id)
        REFERENCES sema_goruntusu(proje_id, id),
    CONSTRAINT ck_yayin_veri_bagi_versiyon CHECK (bag_versiyon_no > 0)
);

CREATE INDEX ix_baglanti_yetkisi_rol ON baglanti_yetkisi(proje_id, proje_rolu_id);
CREATE INDEX ix_baglanti_yetkisi_ortam ON baglanti_yetkisi(proje_id, ortam_id);
CREATE INDEX ix_tanim_veri_nesnesi_nesne ON tanim_veri_nesnesi(proje_id, veri_nesnesi_id);
CREATE INDEX ix_tanim_veri_nesnesi_sema ON tanim_veri_nesnesi(proje_id, sema_goruntusu_id);
CREATE INDEX ix_yayin_veri_bagi_fiziksel ON yayin_veri_bagi(proje_id, fiziksel_sema_id);
CREATE INDEX ix_yayin_veri_bagi_surum ON yayin_veri_bagi(proje_id, baglanti_surumu_id);

CREATE TRIGGER tr_tanim_veri_nesnesi_immutable BEFORE UPDATE ON tanim_veri_nesnesi
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_yayin_veri_bagi_immutable BEFORE UPDATE ON yayin_veri_bagi
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();

COMMENT ON TABLE tanim_veri_nesnesi IS 'Mapping veya başka tanım sürümünün ilişkisel kaynak/hedef veri nesnesi bağı';
COMMENT ON TABLE yayin_veri_bagi IS 'Yayında context ile çözülüp sabitlenmiş fiziksel veri bağı';

