SET search_path TO entegrasyon, public;

-- The exact evidence needed to reconcile an ambiguous Oracle commit must be
-- durable before the run enters YAYINLANIYOR. It is immutable and scoped to one
-- run, lease generation, target generation and publish step.
CREATE TABLE pilot_yayin_niyeti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    is_talebi_id BIGINT NOT NULL REFERENCES is_talebi(id),
    calistirma_id BIGINT NOT NULL,
    calistirma_adimi_id BIGINT NOT NULL,
    calistirma_nesil_no BIGINT NOT NULL,
    isleyici_referansi TEXT NOT NULL,
    deneme_no INTEGER NOT NULL,
    hedef_kaynagi_id BIGINT NOT NULL REFERENCES hedef_kaynagi(id),
    hedef_nesil_no BIGINT NOT NULL,
    hedef_fiziksel_ozeti TEXT NOT NULL,
    hedef_kimlik_surumu INTEGER NOT NULL,
    yayin_ozeti TEXT NOT NULL,
    plan_ozeti TEXT NOT NULL,
    runtime_plan_ozeti TEXT NOT NULL,
    yayin_anahtari_ozeti TEXT NOT NULL,
    payload_ozeti TEXT NOT NULL,
    satir_sayisi BIGINT NOT NULL,
    bayt_sayisi BIGINT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_pilot_yayin_niyeti PRIMARY KEY (id),
    CONSTRAINT uq_pilot_yayin_niyeti_uuid UNIQUE (uuid),
    CONSTRAINT uq_pilot_yayin_niyeti_run UNIQUE (calistirma_id),
    CONSTRAINT uq_pilot_yayin_niyeti_publish
        UNIQUE (hedef_kaynagi_id, yayin_anahtari_ozeti),
    CONSTRAINT fk_pilot_yayin_niyeti_run
        FOREIGN KEY (proje_id, calistirma_id)
        REFERENCES calistirma(proje_id, id),
    CONSTRAINT fk_pilot_yayin_niyeti_step
        FOREIGN KEY (proje_id, calistirma_adimi_id)
        REFERENCES calistirma_adimi(proje_id, id),
    CONSTRAINT ck_pilot_yayin_niyeti_generation CHECK (
        calistirma_nesil_no > 0 AND hedef_nesil_no > 0
        AND hedef_kimlik_surumu > 0 AND deneme_no > 0),
    CONSTRAINT ck_pilot_yayin_niyeti_hashes CHECK (
        hedef_fiziksel_ozeti ~ '^[0-9a-f]{64}$'
        AND yayin_ozeti ~ '^[0-9a-f]{64}$'
        AND plan_ozeti ~ '^[0-9a-f]{64}$'
        AND runtime_plan_ozeti ~ '^[0-9a-f]{64}$'
        AND yayin_anahtari_ozeti ~ '^[0-9a-f]{64}$'
        AND payload_ozeti ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_pilot_yayin_niyeti_counts CHECK (
        satir_sayisi >= 0 AND bayt_sayisi >= 0),
    CONSTRAINT ck_pilot_yayin_niyeti_worker CHECK (
        btrim(isleyici_referansi) <> '')
);

CREATE TRIGGER tr_pilot_yayin_niyeti_immutable_update
    BEFORE UPDATE ON pilot_yayin_niyeti
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_pilot_yayin_niyeti_immutable_delete
    BEFORE DELETE ON pilot_yayin_niyeti
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();

CREATE FUNCTION pilot_yayin_niyeti_eklemeyi_dogrula() RETURNS trigger
LANGUAGE plpgsql
SET search_path = entegrasyon, public
AS $$
DECLARE
    v_calisma calistirma%ROWTYPE;
    v_durum calistirma_durumu%ROWTYPE;
    v_hedef hedef_kaynagi%ROWTYPE;
BEGIN
    SELECT c.* INTO v_calisma FROM calistirma c
     WHERE c.proje_id = NEW.proje_id AND c.id = NEW.calistirma_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Pilot publish intent run kanıtı geçersiz'; END IF;

    SELECT cd.* INTO v_durum FROM calistirma_durumu cd
     WHERE cd.proje_id = NEW.proje_id AND cd.calistirma_id = NEW.calistirma_id
     FOR UPDATE;
    IF NOT FOUND OR v_durum.durum_kodu <> 'CALISIYOR'
       OR v_durum.nesil_no <> NEW.calistirma_nesil_no
       OR v_durum.isleyici_referansi IS DISTINCT FROM NEW.isleyici_referansi
       OR v_durum.kiralama_bitis_zamani <= clock_timestamp()
       OR v_durum.hedef_kaynagi_id <> NEW.hedef_kaynagi_id
       OR v_durum.hedef_nesil_no <> NEW.hedef_nesil_no THEN
        RAISE EXCEPTION 'Pilot publish intent aktif lease ile eşleşmiyor';
    END IF;

    SELECT hk.* INTO v_hedef FROM hedef_kaynagi hk
     WHERE hk.id = NEW.hedef_kaynagi_id FOR UPDATE;
    IF NOT FOUND OR v_hedef.durum_kodu <> 'SAHIPLENILDI'
       OR v_hedef.calistirma_id <> NEW.calistirma_id
       OR v_hedef.nesil_no <> NEW.hedef_nesil_no
       OR v_hedef.kiralama_bitis_zamani <= clock_timestamp()
       OR v_hedef.fiziksel_ozet <> NEW.hedef_fiziksel_ozeti
       OR v_hedef.kimlik_surumu <> NEW.hedef_kimlik_surumu THEN
        RAISE EXCEPTION 'Pilot publish intent target fence ile eşleşmiyor';
    END IF;

    IF NEW.is_talebi_id <> v_calisma.is_talebi_id
       OR NEW.deneme_no <> v_calisma.deneme_no
       OR NEW.yayin_ozeti <> v_calisma.yayin_ozeti
       OR NEW.plan_ozeti <> v_calisma.plan_ozeti
       OR NOT EXISTS (
            SELECT 1 FROM calistirma_adimi ca
             WHERE ca.proje_id = NEW.proje_id
               AND ca.id = NEW.calistirma_adimi_id
               AND ca.calistirma_id = NEW.calistirma_id
               AND ca.adim_kodu = 'PILOT_PUBLISH')
       OR NOT EXISTS (
            SELECT 1 FROM is_talebi it
            JOIN yayin y ON y.proje_id = it.proje_id AND y.id = it.yayin_id
             WHERE it.proje_id = NEW.proje_id
               AND it.id = NEW.is_talebi_id
               AND y.release_hash = NEW.yayin_ozeti
               AND y.fiziksel_manifesto ->> 'runtimeCapability'
                    = 'ORACLE_TABLE_COPY_V1'
               AND y.fiziksel_manifesto ->> 'runtimePlanHash'
                    = NEW.runtime_plan_ozeti) THEN
        RAISE EXCEPTION 'Pilot publish intent pinned execution ile eşleşmiyor';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_pilot_yayin_niyeti_insert
    BEFORE INSERT ON pilot_yayin_niyeti
    FOR EACH ROW EXECUTE FUNCTION pilot_yayin_niyeti_eklemeyi_dogrula();

-- Even the migration owner cannot use the older generic transition to publish
-- unless a validated immutable intent is already present.
CREATE FUNCTION pilot_yayin_gecisini_dogrula() RETURNS trigger
LANGUAGE plpgsql
SET search_path = entegrasyon, public
AS $$
BEGIN
    IF OLD.durum_kodu = 'CALISIYOR' AND NEW.durum_kodu = 'YAYINLANIYOR'
       AND NOT EXISTS (
            SELECT 1 FROM pilot_yayin_niyeti pyn
             WHERE pyn.proje_id = NEW.proje_id
               AND pyn.calistirma_id = NEW.calistirma_id
               AND pyn.calistirma_nesil_no = NEW.nesil_no
               AND pyn.isleyici_referansi = NEW.isleyici_referansi
               AND pyn.hedef_kaynagi_id = NEW.hedef_kaynagi_id
               AND pyn.hedef_nesil_no = NEW.hedef_nesil_no) THEN
        RAISE EXCEPTION 'Yayın geçişi immutable pilot publish intent gerektirir';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_pilot_yayin_gecisi
    BEFORE UPDATE ON calistirma_durumu
    FOR EACH ROW EXECUTE FUNCTION pilot_yayin_gecisini_dogrula();

DROP FUNCTION calistirma_yayina_gec(UUID, TEXT, BIGINT, UUID, BIGINT);

CREATE FUNCTION calistirma_yayina_gec(
    p_calistirma_uuid UUID, p_isleyici_referansi TEXT,
    p_calistirma_nesil_no BIGINT, p_hedef_kaynagi_uuid UUID,
    p_hedef_nesil_no BIGINT, p_runtime_plan_ozeti TEXT,
    p_yayin_anahtari_ozeti TEXT, p_payload_ozeti TEXT,
    p_satir_sayisi BIGINT, p_bayt_sayisi BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SET search_path = entegrasyon, public
AS $$
DECLARE
    v_calisma calistirma%ROWTYPE;
    v_durum calistirma_durumu%ROWTYPE;
    v_hedef hedef_kaynagi%ROWTYPE;
    v_adim_id BIGINT;
    v_simdi TIMESTAMPTZ := clock_timestamp();
BEGIN
    IF p_runtime_plan_ozeti !~ '^[0-9a-f]{64}$'
       OR p_yayin_anahtari_ozeti !~ '^[0-9a-f]{64}$'
       OR p_payload_ozeti !~ '^[0-9a-f]{64}$'
       OR p_satir_sayisi < 0 OR p_bayt_sayisi < 0 THEN
        RAISE EXCEPTION 'Pilot publish intent kanıtı geçersiz';
    END IF;
    SELECT c.* INTO v_calisma FROM calistirma c
     WHERE c.uuid = p_calistirma_uuid;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    SELECT cd.* INTO v_durum FROM calistirma_durumu cd
     WHERE cd.proje_id = v_calisma.proje_id
       AND cd.calistirma_id = v_calisma.id FOR UPDATE;
    IF NOT FOUND THEN RETURN FALSE; END IF;

    IF v_durum.durum_kodu = 'YAYINLANIYOR' THEN
        RETURN EXISTS (
            SELECT 1 FROM pilot_yayin_niyeti pyn
             WHERE pyn.calistirma_id = v_calisma.id
               AND pyn.calistirma_nesil_no = p_calistirma_nesil_no
               AND pyn.isleyici_referansi = p_isleyici_referansi
               AND pyn.hedef_nesil_no = p_hedef_nesil_no
               AND pyn.runtime_plan_ozeti = p_runtime_plan_ozeti
               AND pyn.yayin_anahtari_ozeti = p_yayin_anahtari_ozeti
               AND pyn.payload_ozeti = p_payload_ozeti
               AND pyn.satir_sayisi = p_satir_sayisi
               AND pyn.bayt_sayisi = p_bayt_sayisi);
    END IF;
    IF v_durum.durum_kodu <> 'CALISIYOR'
       OR v_durum.isleyici_referansi IS DISTINCT FROM p_isleyici_referansi
       OR v_durum.nesil_no <> p_calistirma_nesil_no
       OR v_durum.kiralama_bitis_zamani <= v_simdi
       OR v_durum.hedef_nesil_no <> p_hedef_nesil_no THEN RETURN FALSE; END IF;
    SELECT hk.* INTO v_hedef FROM hedef_kaynagi hk
     WHERE hk.id = v_durum.hedef_kaynagi_id
       AND hk.uuid = p_hedef_kaynagi_uuid FOR UPDATE;
    IF NOT FOUND OR v_hedef.durum_kodu <> 'SAHIPLENILDI'
       OR v_hedef.calistirma_id <> v_calisma.id
       OR v_hedef.nesil_no <> p_hedef_nesil_no
       OR v_hedef.kiralama_bitis_zamani <= v_simdi THEN RETURN FALSE; END IF;
    SELECT ca.id INTO v_adim_id FROM calistirma_adimi ca
     WHERE ca.calistirma_id = v_calisma.id AND ca.adim_kodu = 'PILOT_PUBLISH';
    IF NOT FOUND THEN RETURN FALSE; END IF;

    INSERT INTO pilot_yayin_niyeti(
        proje_id, is_talebi_id, calistirma_id, calistirma_adimi_id,
        calistirma_nesil_no, isleyici_referansi, deneme_no,
        hedef_kaynagi_id, hedef_nesil_no, hedef_fiziksel_ozeti,
        hedef_kimlik_surumu, yayin_ozeti, plan_ozeti, runtime_plan_ozeti,
        yayin_anahtari_ozeti, payload_ozeti, satir_sayisi, bayt_sayisi)
    VALUES (
        v_calisma.proje_id, v_calisma.is_talebi_id, v_calisma.id, v_adim_id,
        p_calistirma_nesil_no, p_isleyici_referansi, v_calisma.deneme_no,
        v_hedef.id, p_hedef_nesil_no, v_hedef.fiziksel_ozet,
        v_hedef.kimlik_surumu, v_calisma.yayin_ozeti, v_calisma.plan_ozeti,
        p_runtime_plan_ozeti, p_yayin_anahtari_ozeti, p_payload_ozeti,
        p_satir_sayisi, p_bayt_sayisi);

    RETURN pilot_calistirma_asamasina_gec(
        p_calistirma_uuid, p_isleyici_referansi, p_calistirma_nesil_no,
        p_hedef_kaynagi_uuid, p_hedef_nesil_no,
        'CALISIYOR', 'YAYINLANIYOR', 'PUBLISH_STARTED');
END;
$$;

-- A publish checkpoint can only repeat the evidence frozen before Oracle DML.
CREATE FUNCTION kontrol_noktasi_yayin_niyetini_dogrula() RETURNS trigger
LANGUAGE plpgsql
SET search_path = entegrasyon, public
AS $$
BEGIN
    IF NEW.tur_kodu = 'PUBLISH'
       AND EXISTS (
            SELECT 1 FROM calistirma_adimi ca
             WHERE ca.id = NEW.calistirma_adimi_id
               AND ca.adim_kodu = 'PILOT_PUBLISH')
       AND NOT EXISTS (
            SELECT 1 FROM pilot_yayin_niyeti pyn
             WHERE pyn.proje_id = NEW.proje_id
               AND pyn.calistirma_id = NEW.calistirma_id
               AND pyn.calistirma_adimi_id = NEW.calistirma_adimi_id
               AND pyn.hedef_kaynagi_id = NEW.hedef_kaynagi_id
               AND pyn.hedef_nesil_no = NEW.hedef_nesil_no
               AND pyn.yayin_ozeti = NEW.yayin_ozeti
               AND pyn.plan_ozeti = NEW.plan_ozeti
               AND pyn.runtime_plan_ozeti = NEW.kapsam_ozeti
               AND pyn.yayin_anahtari_ozeti = NEW.hedef_defter_referansi
               AND pyn.payload_ozeti = NEW.payload_ozeti
               AND pyn.satir_sayisi = (NEW.imlec ->> 'rowCount')::BIGINT
               AND pyn.bayt_sayisi = (NEW.imlec ->> 'byteCount')::BIGINT) THEN
        RAISE EXCEPTION 'Checkpoint immutable pilot publish intent ile eşleşmiyor';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_kontrol_noktasi_yayin_niyeti
    BEFORE INSERT ON kontrol_noktasi
    FOR EACH ROW EXECUTE FUNCTION kontrol_noktasi_yayin_niyetini_dogrula();

REVOKE ALL ON TABLE pilot_yayin_niyeti FROM PUBLIC;
REVOKE ALL ON FUNCTION pilot_yayin_niyeti_eklemeyi_dogrula() FROM PUBLIC;
REVOKE ALL ON FUNCTION pilot_yayin_gecisini_dogrula() FROM PUBLIC;
REVOKE ALL ON FUNCTION calistirma_yayina_gec(
    UUID, TEXT, BIGINT, UUID, BIGINT, TEXT, TEXT, TEXT, BIGINT, BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION kontrol_noktasi_yayin_niyetini_dogrula() FROM PUBLIC;

COMMENT ON TABLE pilot_yayin_niyeti IS
    'Oracle DML öncesinde sabitlenen append-only publish ve crash reconciliation kanıtı';
COMMENT ON FUNCTION calistirma_yayina_gec(
    UUID, TEXT, BIGINT, UUID, BIGINT, TEXT, TEXT, TEXT, BIGINT, BIGINT) IS
    'Publish intent kanıtını sabitleyip runı aynı transactionda YAYINLANIYOR durumuna geçirir';
