SET search_path TO entegrasyon, public;

-- Procedure execution has a separate evidence model.  The existing pilot
-- checkpoint and publish-intent tables remain reserved for ORACLE_TABLE_COPY_V1.
CREATE TABLE prosedur_adim_kaniti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_id BIGINT NOT NULL,
    calistirma_adimi_id BIGINT NOT NULL,
    sira_no INTEGER NOT NULL,
    runtime_plan_ozeti TEXT NOT NULL,
    komut_ozeti TEXT NOT NULL,
    baglanti_rolu TEXT NOT NULL,
    risk_kodu TEXT NOT NULL,
    hata_politikasi TEXT NOT NULL,
    zaman_asimi_saniyesi INTEGER NOT NULL,
    tanim_veri_nesnesi_uuid UUID NOT NULL,
    baglanti_surumu_uuid UUID NOT NULL,
    sema_goruntusu_uuid UUID NOT NULL,
    sema_parmak_izi TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_prosedur_adim_kaniti PRIMARY KEY (id),
    CONSTRAINT uq_prosedur_adim_kaniti_uuid UNIQUE (uuid),
    CONSTRAINT uq_prosedur_adim_kaniti_adim UNIQUE (calistirma_adimi_id),
    CONSTRAINT uq_prosedur_adim_kaniti_sira UNIQUE (calistirma_id, sira_no),
    CONSTRAINT uq_prosedur_adim_kaniti_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_prosedur_adim_kaniti_run
        FOREIGN KEY (proje_id, calistirma_id)
        REFERENCES calistirma(proje_id, id),
    CONSTRAINT fk_prosedur_adim_kaniti_adim
        FOREIGN KEY (proje_id, calistirma_adimi_id)
        REFERENCES calistirma_adimi(proje_id, id),
    CONSTRAINT ck_prosedur_adim_kaniti_sira CHECK (sira_no > 0),
    CONSTRAINT ck_prosedur_adim_kaniti_hash CHECK (
        runtime_plan_ozeti ~ '^[0-9a-f]{64}$'
        AND komut_ozeti ~ '^[0-9a-f]{64}$'
        AND sema_parmak_izi ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_prosedur_adim_kaniti_rol CHECK (
        baglanti_rolu IN ('SOURCE', 'TARGET')),
    CONSTRAINT ck_prosedur_adim_kaniti_risk CHECK (
        risk_kodu IN ('READ_ONLY', 'DML', 'DDL', 'DESTRUCTIVE')),
    CONSTRAINT ck_prosedur_adim_kaniti_hata CHECK (
        hata_politikasi IN ('STOP', 'CONTINUE')),
    CONSTRAINT ck_prosedur_adim_kaniti_timeout CHECK (
        zaman_asimi_saniyesi BETWEEN 1 AND 300)
);

CREATE TABLE prosedur_adim_durumu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_id BIGINT NOT NULL,
    calistirma_adimi_id BIGINT NOT NULL,
    prosedur_adim_kaniti_id BIGINT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'BEKLIYOR',
    son_olay_no BIGINT,
    baslama_zamani TIMESTAMPTZ,
    bitis_zamani TIMESTAMPTZ,
    satir_sayisi BIGINT,
    bayt_sayisi BIGINT,
    hata_kodu TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_prosedur_adim_durumu PRIMARY KEY (id),
    CONSTRAINT uq_prosedur_adim_durumu_uuid UNIQUE (uuid),
    CONSTRAINT uq_prosedur_adim_durumu_adim UNIQUE (calistirma_adimi_id),
    CONSTRAINT uq_prosedur_adim_durumu_kanit UNIQUE (prosedur_adim_kaniti_id),
    CONSTRAINT uq_prosedur_adim_durumu_proje_id_id UNIQUE (proje_id, id),
    CONSTRAINT fk_prosedur_adim_durumu_run
        FOREIGN KEY (proje_id, calistirma_id)
        REFERENCES calistirma(proje_id, id),
    CONSTRAINT fk_prosedur_adim_durumu_adim
        FOREIGN KEY (proje_id, calistirma_adimi_id)
        REFERENCES calistirma_adimi(proje_id, id),
    CONSTRAINT fk_prosedur_adim_durumu_kanit
        FOREIGN KEY (proje_id, prosedur_adim_kaniti_id)
        REFERENCES prosedur_adim_kaniti(proje_id, id),
    CONSTRAINT ck_prosedur_adim_durumu_kod CHECK (durum_kodu IN (
        'BEKLIYOR', 'CALISIYOR', 'BASARILI', 'HATA_DEVAM',
        'BASARISIZ', 'SONUC_BELIRSIZ', 'ATLANDI')),
    CONSTRAINT ck_prosedur_adim_durumu_sayim CHECK (
        (satir_sayisi IS NULL OR satir_sayisi >= 0)
        AND (bayt_sayisi IS NULL OR bayt_sayisi >= 0)),
    CONSTRAINT ck_prosedur_adim_durumu_sekil CHECK (
        (durum_kodu = 'BEKLIYOR'
            AND son_olay_no IS NULL AND baslama_zamani IS NULL
            AND bitis_zamani IS NULL AND hata_kodu IS NULL)
        OR (durum_kodu = 'CALISIYOR'
            AND son_olay_no > 0 AND baslama_zamani IS NOT NULL
            AND bitis_zamani IS NULL AND hata_kodu IS NULL)
        OR (durum_kodu = 'BASARILI'
            AND son_olay_no > 0 AND baslama_zamani IS NOT NULL
            AND bitis_zamani IS NOT NULL AND hata_kodu IS NULL)
        OR (durum_kodu IN ('HATA_DEVAM', 'BASARISIZ')
            AND son_olay_no > 0 AND baslama_zamani IS NOT NULL
            AND bitis_zamani IS NOT NULL AND hata_kodu IS NOT NULL)
        OR (durum_kodu = 'SONUC_BELIRSIZ'
            AND son_olay_no > 0 AND baslama_zamani IS NOT NULL
            AND bitis_zamani IS NOT NULL)
        OR (durum_kodu = 'ATLANDI'
            AND son_olay_no > 0 AND baslama_zamani IS NULL
            AND bitis_zamani IS NOT NULL))
);

CREATE TABLE prosedur_adim_niyeti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    calistirma_id BIGINT NOT NULL,
    calistirma_adimi_id BIGINT NOT NULL,
    prosedur_adim_kaniti_id BIGINT NOT NULL,
    calistirma_nesil_no BIGINT NOT NULL,
    isleyici_referansi TEXT NOT NULL,
    hedef_kaynagi_id BIGINT NOT NULL REFERENCES hedef_kaynagi(id),
    hedef_nesil_no BIGINT NOT NULL,
    hedef_fiziksel_ozeti TEXT NOT NULL,
    yayin_ozeti TEXT NOT NULL,
    plan_ozeti TEXT NOT NULL,
    runtime_plan_ozeti TEXT NOT NULL,
    komut_ozeti TEXT NOT NULL,
    operasyon_anahtari_ozeti TEXT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_prosedur_adim_niyeti PRIMARY KEY (id),
    CONSTRAINT uq_prosedur_adim_niyeti_uuid UNIQUE (uuid),
    CONSTRAINT uq_prosedur_adim_niyeti_adim UNIQUE (calistirma_adimi_id),
    CONSTRAINT uq_prosedur_adim_niyeti_operasyon
        UNIQUE (hedef_kaynagi_id, operasyon_anahtari_ozeti),
    CONSTRAINT fk_prosedur_adim_niyeti_run
        FOREIGN KEY (proje_id, calistirma_id)
        REFERENCES calistirma(proje_id, id),
    CONSTRAINT fk_prosedur_adim_niyeti_adim
        FOREIGN KEY (proje_id, calistirma_adimi_id)
        REFERENCES calistirma_adimi(proje_id, id),
    CONSTRAINT fk_prosedur_adim_niyeti_kanit
        FOREIGN KEY (proje_id, prosedur_adim_kaniti_id)
        REFERENCES prosedur_adim_kaniti(proje_id, id),
    CONSTRAINT ck_prosedur_adim_niyeti_nesil CHECK (
        calistirma_nesil_no > 0 AND hedef_nesil_no > 0),
    CONSTRAINT ck_prosedur_adim_niyeti_worker CHECK (
        length(btrim(isleyici_referansi)) BETWEEN 1 AND 200),
    CONSTRAINT ck_prosedur_adim_niyeti_hash CHECK (
        hedef_fiziksel_ozeti ~ '^[0-9a-f]{64}$'
        AND yayin_ozeti ~ '^[0-9a-f]{64}$'
        AND plan_ozeti ~ '^[0-9a-f]{64}$'
        AND runtime_plan_ozeti ~ '^[0-9a-f]{64}$'
        AND komut_ozeti ~ '^[0-9a-f]{64}$'
        AND operasyon_anahtari_ozeti ~ '^[0-9a-f]{64}$')
);

CREATE INDEX ix_prosedur_adim_durumu_run
    ON prosedur_adim_durumu(proje_id, calistirma_id, durum_kodu);
CREATE INDEX ix_prosedur_adim_niyeti_run
    ON prosedur_adim_niyeti(proje_id, calistirma_id);

CREATE TRIGGER tr_prosedur_adim_kaniti_immutable
    BEFORE UPDATE OR DELETE ON prosedur_adim_kaniti
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();
CREATE TRIGGER tr_prosedur_adim_niyeti_immutable
    BEFORE UPDATE OR DELETE ON prosedur_adim_niyeti
    FOR EACH ROW EXECUTE FUNCTION immutable_update_engelle();

CREATE FUNCTION prosedur_adim_durumunu_dogrula() RETURNS trigger
LANGUAGE plpgsql
SET search_path = entegrasyon, public
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Prosedür adım durumu silinemez';
    END IF;
    IF NEW.proje_id IS DISTINCT FROM OLD.proje_id
       OR NEW.calistirma_id IS DISTINCT FROM OLD.calistirma_id
       OR NEW.calistirma_adimi_id IS DISTINCT FROM OLD.calistirma_adimi_id
       OR NEW.prosedur_adim_kaniti_id IS DISTINCT FROM OLD.prosedur_adim_kaniti_id
       OR NEW.uuid IS DISTINCT FROM OLD.uuid
       OR NEW.olusturulma_zamani IS DISTINCT FROM OLD.olusturulma_zamani THEN
        RAISE EXCEPTION 'Prosedür adım durumu kimlik alanları güncellenemez';
    END IF;
    IF NEW.versiyon_no <> OLD.versiyon_no + 1 THEN
        RAISE EXCEPTION 'Prosedür adım durumu versiyonu tam bir artırılmalıdır';
    END IF;
    IF OLD.durum_kodu = 'BEKLIYOR' AND NEW.durum_kodu = 'CALISIYOR'
       OR OLD.durum_kodu = 'CALISIYOR'
          AND NEW.durum_kodu IN (
              'BASARILI', 'HATA_DEVAM', 'BASARISIZ', 'SONUC_BELIRSIZ')
       OR OLD.durum_kodu = 'BEKLIYOR' AND NEW.durum_kodu = 'ATLANDI' THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'Geçersiz prosedür adım durumu geçişi: % -> %',
        OLD.durum_kodu, NEW.durum_kodu;
END;
$$;

CREATE TRIGGER tr_prosedur_adim_durumu_guard
    BEFORE UPDATE OR DELETE ON prosedur_adim_durumu
    FOR EACH ROW EXECUTE FUNCTION prosedur_adim_durumunu_dogrula();

-- Materializes the immutable task list only after the generic run lease and
-- the single Procedure V1 target fence have both been acquired.
CREATE FUNCTION prosedur_calistirmayi_baslat(
    p_calistirma_uuid UUID, p_isleyici_referansi TEXT,
    p_calistirma_nesil_no BIGINT, p_hedef_kaynagi_uuid UUID,
    p_hedef_nesil_no BIGINT, p_runtime_plan_ozeti TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SET search_path = entegrasyon, public
AS $$
DECLARE
    v_calisma calistirma%ROWTYPE;
    v_durum calistirma_durumu%ROWTYPE;
    v_hedef hedef_kaynagi%ROWTYPE;
    v_yayin yayin%ROWTYPE;
    v_senaryo senaryo%ROWTYPE;
    v_simdi TIMESTAMPTZ := clock_timestamp();
    v_gorev_sayisi INTEGER;
    v_eslesme_sayisi INTEGER;
BEGIN
    IF p_runtime_plan_ozeti !~ '^[0-9a-f]{64}$'
       OR p_isleyici_referansi IS NULL
       OR length(btrim(p_isleyici_referansi)) NOT BETWEEN 1 AND 200 THEN
        RAISE EXCEPTION 'Prosedür çalışma başlangıç kanıtı geçersiz';
    END IF;

    SELECT * INTO v_calisma FROM calistirma
     WHERE uuid = p_calistirma_uuid;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    SELECT * INTO v_durum FROM calistirma_durumu
     WHERE proje_id = v_calisma.proje_id AND calistirma_id = v_calisma.id
     FOR UPDATE;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    SELECT y.* INTO v_yayin
      FROM is_talebi it JOIN yayin y
        ON y.proje_id = it.proje_id AND y.id = it.yayin_id
     WHERE it.proje_id = v_calisma.proje_id
       AND it.id = v_calisma.is_talebi_id;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    SELECT * INTO v_senaryo FROM senaryo WHERE id = v_yayin.senaryo_id;

    IF v_yayin.fiziksel_manifesto ->> 'runtimeCapability'
            IS DISTINCT FROM 'ORACLE_PROCEDURE_V1'
       OR v_yayin.durum_kodu <> 'AKTIF'
       OR v_yayin.fiziksel_manifesto ->> 'runtimePlanHash'
            IS DISTINCT FROM p_runtime_plan_ozeti
       OR v_calisma.yayin_ozeti IS DISTINCT FROM v_yayin.release_hash
       OR v_calisma.plan_ozeti IS DISTINCT FROM v_senaryo.plan_ozeti
       OR v_senaryo.plan #>> '{executable,kind}' IS DISTINCT FROM 'PROCEDURE' THEN
        RETURN FALSE;
    END IF;

    SELECT * INTO v_hedef FROM hedef_kaynagi
     WHERE id = v_durum.hedef_kaynagi_id AND uuid = p_hedef_kaynagi_uuid
     FOR UPDATE;
    IF NOT FOUND
       OR v_durum.durum_kodu NOT IN ('HAZIRLANIYOR', 'CALISIYOR')
       OR v_durum.isleyici_referansi IS DISTINCT FROM p_isleyici_referansi
       OR v_durum.nesil_no <> p_calistirma_nesil_no
       OR v_durum.hedef_nesil_no <> p_hedef_nesil_no
       OR v_durum.kiralama_bitis_zamani <= v_simdi
       OR v_hedef.durum_kodu <> 'SAHIPLENILDI'
       OR v_hedef.calistirma_id <> v_calisma.id
       OR v_hedef.nesil_no <> p_hedef_nesil_no
       OR v_hedef.kiralama_bitis_zamani <= v_simdi THEN
        RETURN FALSE;
    END IF;

    SELECT count(*) INTO v_gorev_sayisi
      FROM jsonb_array_elements(
          v_senaryo.plan #> '{executable,definition,tasks}');
    SELECT count(*) INTO v_eslesme_sayisi
      FROM jsonb_array_elements(
               v_senaryo.plan #> '{executable,definition,tasks}') task
      JOIN jsonb_array_elements(v_yayin.fiziksel_manifesto -> 'bindings') binding
        ON binding ->> 'nodeCode' = task ->> 'id';
    IF v_gorev_sayisi < 1 OR v_gorev_sayisi > 1000
       OR v_eslesme_sayisi <> v_gorev_sayisi
       OR jsonb_array_length(v_yayin.fiziksel_manifesto -> 'bindings')
            <> v_gorev_sayisi THEN
        RETURN FALSE;
    END IF;

    INSERT INTO calistirma_adimi(
        proje_id, calistirma_id, adim_kodu, tur_kodu, sira_no, ad)
    SELECT v_calisma.proje_id, v_calisma.id,
           task ->> 'id', 'PROCEDURE', ordinality::INTEGER,
           COALESCE(NULLIF(task ->> 'name', ''), task ->> 'id')
      FROM jsonb_array_elements(
               v_senaryo.plan #> '{executable,definition,tasks}')
           WITH ORDINALITY AS tasks(task, ordinality)
    ON CONFLICT (calistirma_id, adim_kodu) DO NOTHING;

    INSERT INTO prosedur_adim_kaniti(
        proje_id, calistirma_id, calistirma_adimi_id, sira_no,
        runtime_plan_ozeti, komut_ozeti, baglanti_rolu, risk_kodu,
        hata_politikasi, zaman_asimi_saniyesi, tanim_veri_nesnesi_uuid,
        baglanti_surumu_uuid, sema_goruntusu_uuid, sema_parmak_izi)
    SELECT v_calisma.proje_id, v_calisma.id, ca.id, ordinality::INTEGER,
           p_runtime_plan_ozeti,
           encode(sha256(convert_to(task ->> 'command', 'UTF8')), 'hex'),
           task ->> 'connectionRole', task ->> 'riskClass',
           COALESCE(task ->> 'onError', 'STOP'),
           COALESCE((task ->> 'timeoutSeconds')::INTEGER, 300),
           (binding ->> 'definitionDataObjectUuid')::UUID,
           (binding ->> 'connectionVersionUuid')::UUID,
           (binding ->> 'schemaSnapshotUuid')::UUID,
           binding ->> 'schemaSnapshotFingerprint'
      FROM jsonb_array_elements(
               v_senaryo.plan #> '{executable,definition,tasks}')
           WITH ORDINALITY AS tasks(task, ordinality)
      JOIN calistirma_adimi ca
        ON ca.calistirma_id = v_calisma.id
       AND ca.adim_kodu = task ->> 'id'
      JOIN jsonb_array_elements(v_yayin.fiziksel_manifesto -> 'bindings') binding
        ON binding ->> 'nodeCode' = task ->> 'id'
    ON CONFLICT (calistirma_adimi_id) DO NOTHING;

    INSERT INTO prosedur_adim_durumu(
        proje_id, calistirma_id, calistirma_adimi_id,
        prosedur_adim_kaniti_id)
    SELECT pak.proje_id, pak.calistirma_id, pak.calistirma_adimi_id, pak.id
      FROM prosedur_adim_kaniti pak
     WHERE pak.proje_id = v_calisma.proje_id
       AND pak.calistirma_id = v_calisma.id
    ON CONFLICT (calistirma_adimi_id) DO NOTHING;

    IF (SELECT count(*) FROM prosedur_adim_kaniti
         WHERE calistirma_id = v_calisma.id) <> v_gorev_sayisi
       OR EXISTS (
            SELECT 1
              FROM jsonb_array_elements(
                       v_senaryo.plan #> '{executable,definition,tasks}')
                   WITH ORDINALITY AS tasks(task, ordinality)
              JOIN jsonb_array_elements(
                       v_yayin.fiziksel_manifesto -> 'bindings') binding
                ON binding ->> 'nodeCode' = task ->> 'id'
              LEFT JOIN calistirma_adimi ca
                ON ca.calistirma_id = v_calisma.id
               AND ca.adim_kodu = task ->> 'id'
              LEFT JOIN prosedur_adim_kaniti pak
                ON pak.calistirma_adimi_id = ca.id
             WHERE pak.id IS NULL
                OR ca.sira_no <> ordinality
                OR ca.tur_kodu <> 'PROCEDURE'
                OR pak.sira_no <> ordinality
                OR pak.runtime_plan_ozeti <> p_runtime_plan_ozeti
                OR pak.komut_ozeti <> encode(
                       sha256(convert_to(task ->> 'command', 'UTF8')), 'hex')
                OR pak.baglanti_rolu <> task ->> 'connectionRole'
                OR pak.risk_kodu <> task ->> 'riskClass'
                OR pak.hata_politikasi <> COALESCE(task ->> 'onError', 'STOP')
                OR pak.zaman_asimi_saniyesi <>
                       COALESCE((task ->> 'timeoutSeconds')::INTEGER, 300)
                OR pak.tanim_veri_nesnesi_uuid <>
                       (binding ->> 'definitionDataObjectUuid')::UUID
                OR pak.baglanti_surumu_uuid <>
                       (binding ->> 'connectionVersionUuid')::UUID
                OR pak.sema_goruntusu_uuid <>
                       (binding ->> 'schemaSnapshotUuid')::UUID
                OR pak.sema_parmak_izi <>
                       binding ->> 'schemaSnapshotFingerprint') THEN
        RAISE EXCEPTION 'Prosedür adım kanıtı sabitlenmiş planla eşleşmiyor';
    END IF;

    IF v_durum.durum_kodu = 'CALISIYOR' THEN
        RETURN EXISTS (
            SELECT 1 FROM calistirma_olayi co
             WHERE co.proje_id = v_calisma.proje_id
               AND co.calistirma_id = v_calisma.id
               AND co.tur_kodu = 'PROCEDURE_PREPARED'
               AND co.veri ->> 'generation' = p_calistirma_nesil_no::TEXT
               AND co.veri ->> 'workerReference' = p_isleyici_referansi
               AND co.veri ->> 'targetResourceUuid' = p_hedef_kaynagi_uuid::TEXT
               AND co.veri ->> 'targetGeneration' = p_hedef_nesil_no::TEXT
               AND co.veri ->> 'runtimePlanHash' = p_runtime_plan_ozeti);
    END IF;

    UPDATE calistirma_durumu
       SET durum_kodu = 'CALISIYOR',
           son_olay_no = v_durum.son_olay_no + 1,
           guncellenme_zamani = v_simdi,
           versiyon_no = v_durum.versiyon_no + 1
     WHERE id = v_durum.id;
    INSERT INTO calistirma_olayi(
        proje_id, calistirma_id, olay_no, tur_kodu, olay_zamani, veri)
    VALUES (v_calisma.proje_id, v_calisma.id,
            v_durum.son_olay_no + 1, 'PROCEDURE_PREPARED', v_simdi,
            jsonb_build_object(
                'generation', p_calistirma_nesil_no,
                'workerReference', p_isleyici_referansi,
                'targetResourceUuid', p_hedef_kaynagi_uuid,
                'targetGeneration', p_hedef_nesil_no,
                'runtimePlanHash', p_runtime_plan_ozeti,
                'taskCount', v_gorev_sayisi));
    RETURN TRUE;
END;
$$;

CREATE FUNCTION prosedur_adimini_baslat(
    p_calistirma_uuid UUID, p_isleyici_referansi TEXT,
    p_calistirma_nesil_no BIGINT, p_hedef_kaynagi_uuid UUID,
    p_hedef_nesil_no BIGINT, p_adim_kodu TEXT,
    p_operasyon_anahtari_ozeti TEXT DEFAULT NULL)
RETURNS BOOLEAN
LANGUAGE plpgsql
SET search_path = entegrasyon, public
AS $$
DECLARE
    v_calisma calistirma%ROWTYPE;
    v_durum calistirma_durumu%ROWTYPE;
    v_hedef hedef_kaynagi%ROWTYPE;
    v_kanit prosedur_adim_kaniti%ROWTYPE;
    v_adim_durumu prosedur_adim_durumu%ROWTYPE;
    v_simdi TIMESTAMPTZ := clock_timestamp();
BEGIN
    SELECT * INTO v_calisma FROM calistirma WHERE uuid = p_calistirma_uuid;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    SELECT * INTO v_durum FROM calistirma_durumu
     WHERE proje_id = v_calisma.proje_id AND calistirma_id = v_calisma.id
     FOR UPDATE;
    SELECT * INTO v_hedef FROM hedef_kaynagi
     WHERE id = v_durum.hedef_kaynagi_id AND uuid = p_hedef_kaynagi_uuid
     FOR UPDATE;
    SELECT pak.* INTO v_kanit FROM prosedur_adim_kaniti pak
      JOIN calistirma_adimi ca ON ca.id = pak.calistirma_adimi_id
     WHERE pak.proje_id = v_calisma.proje_id
       AND pak.calistirma_id = v_calisma.id
       AND ca.adim_kodu = p_adim_kodu;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    SELECT * INTO v_adim_durumu FROM prosedur_adim_durumu
     WHERE prosedur_adim_kaniti_id = v_kanit.id FOR UPDATE;

    IF v_adim_durumu.durum_kodu = 'CALISIYOR' THEN
        RETURN COALESCE((
            v_durum.durum_kodu = 'CALISIYOR'
            AND v_durum.isleyici_referansi = p_isleyici_referansi
            AND v_durum.nesil_no = p_calistirma_nesil_no
            AND v_durum.hedef_nesil_no = p_hedef_nesil_no
            AND v_durum.kiralama_bitis_zamani > v_simdi
            AND v_hedef.id IS NOT NULL
            AND v_hedef.durum_kodu = 'SAHIPLENILDI'
            AND v_hedef.calistirma_id = v_calisma.id
            AND v_hedef.nesil_no = p_hedef_nesil_no
            AND v_hedef.kiralama_bitis_zamani > v_simdi
            AND EXISTS (
            SELECT 1 FROM calistirma_olayi co
             WHERE co.proje_id = v_calisma.proje_id
               AND co.calistirma_id = v_calisma.id
               AND co.calistirma_adimi_id = v_kanit.calistirma_adimi_id
               AND co.olay_no = v_adim_durumu.son_olay_no
               AND co.tur_kodu = 'PROCEDURE_STEP_STARTED'
               AND co.veri ->> 'generation' = p_calistirma_nesil_no::TEXT
               AND co.veri ->> 'workerReference' = p_isleyici_referansi
               AND co.veri ->> 'targetGeneration' = p_hedef_nesil_no::TEXT
               AND co.veri ->> 'commandHash' = v_kanit.komut_ozeti
               AND (co.veri ->> 'operationKeyHash') IS NOT DISTINCT FROM
                   p_operasyon_anahtari_ozeti)), FALSE);
    END IF;

    IF v_durum.durum_kodu <> 'CALISIYOR'
       OR v_durum.isleyici_referansi IS DISTINCT FROM p_isleyici_referansi
       OR v_durum.nesil_no <> p_calistirma_nesil_no
       OR v_durum.hedef_nesil_no <> p_hedef_nesil_no
       OR v_durum.kiralama_bitis_zamani <= v_simdi
       OR v_hedef.id IS NULL OR v_hedef.durum_kodu <> 'SAHIPLENILDI'
       OR v_hedef.calistirma_id <> v_calisma.id
       OR v_hedef.nesil_no <> p_hedef_nesil_no
       OR v_hedef.kiralama_bitis_zamani <= v_simdi
       OR v_adim_durumu.durum_kodu <> 'BEKLIYOR'
       OR EXISTS (
            SELECT 1 FROM prosedur_adim_kaniti onceki
              JOIN prosedur_adim_durumu onceki_durum
                ON onceki_durum.prosedur_adim_kaniti_id = onceki.id
             WHERE onceki.calistirma_id = v_calisma.id
               AND onceki.sira_no < v_kanit.sira_no
               AND onceki_durum.durum_kodu NOT IN ('BASARILI', 'HATA_DEVAM')) THEN
        RETURN FALSE;
    END IF;

    IF v_kanit.risk_kodu = 'READ_ONLY' THEN
        IF p_operasyon_anahtari_ozeti IS NOT NULL THEN RETURN FALSE; END IF;
    ELSE
        IF p_operasyon_anahtari_ozeti !~ '^[0-9a-f]{64}$' THEN RETURN FALSE; END IF;
        INSERT INTO prosedur_adim_niyeti(
            proje_id, calistirma_id, calistirma_adimi_id,
            prosedur_adim_kaniti_id, calistirma_nesil_no,
            isleyici_referansi, hedef_kaynagi_id, hedef_nesil_no,
            hedef_fiziksel_ozeti, yayin_ozeti, plan_ozeti,
            runtime_plan_ozeti, komut_ozeti, operasyon_anahtari_ozeti)
        VALUES (v_calisma.proje_id, v_calisma.id,
                v_kanit.calistirma_adimi_id, v_kanit.id,
                p_calistirma_nesil_no, p_isleyici_referansi,
                v_hedef.id, p_hedef_nesil_no, v_hedef.fiziksel_ozet,
                v_calisma.yayin_ozeti, v_calisma.plan_ozeti,
                v_kanit.runtime_plan_ozeti, v_kanit.komut_ozeti,
                p_operasyon_anahtari_ozeti)
        ON CONFLICT (calistirma_adimi_id) DO NOTHING;
        IF NOT EXISTS (
            SELECT 1 FROM prosedur_adim_niyeti pan
             WHERE pan.calistirma_adimi_id = v_kanit.calistirma_adimi_id
               AND pan.calistirma_nesil_no = p_calistirma_nesil_no
               AND pan.isleyici_referansi = p_isleyici_referansi
               AND pan.hedef_kaynagi_id = v_hedef.id
               AND pan.hedef_nesil_no = p_hedef_nesil_no
               AND pan.runtime_plan_ozeti = v_kanit.runtime_plan_ozeti
               AND pan.komut_ozeti = v_kanit.komut_ozeti
               AND pan.operasyon_anahtari_ozeti = p_operasyon_anahtari_ozeti) THEN
            RETURN FALSE;
        END IF;
    END IF;

    UPDATE prosedur_adim_durumu
       SET durum_kodu = 'CALISIYOR', son_olay_no = v_durum.son_olay_no + 1,
           baslama_zamani = v_simdi, guncellenme_zamani = v_simdi,
           versiyon_no = v_adim_durumu.versiyon_no + 1
     WHERE id = v_adim_durumu.id;
    UPDATE calistirma_durumu
       SET son_olay_no = v_durum.son_olay_no + 1,
           guncellenme_zamani = v_simdi,
           versiyon_no = v_durum.versiyon_no + 1
     WHERE id = v_durum.id;
    INSERT INTO calistirma_olayi(
        proje_id, calistirma_id, calistirma_adimi_id, olay_no,
        tur_kodu, olay_zamani, veri)
    VALUES (v_calisma.proje_id, v_calisma.id,
            v_kanit.calistirma_adimi_id, v_durum.son_olay_no + 1,
            'PROCEDURE_STEP_STARTED', v_simdi,
            jsonb_build_object(
                'generation', p_calistirma_nesil_no,
                'workerReference', p_isleyici_referansi,
                'targetResourceUuid', p_hedef_kaynagi_uuid,
                'targetGeneration', p_hedef_nesil_no,
                'runtimePlanHash', v_kanit.runtime_plan_ozeti,
                'commandHash', v_kanit.komut_ozeti,
                'operationKeyHash', p_operasyon_anahtari_ozeti));
    RETURN TRUE;
END;
$$;

CREATE FUNCTION prosedur_adimini_basarili_tamamla(
    p_calistirma_uuid UUID, p_isleyici_referansi TEXT,
    p_calistirma_nesil_no BIGINT, p_hedef_kaynagi_uuid UUID,
    p_hedef_nesil_no BIGINT, p_adim_kodu TEXT,
    p_satir_sayisi BIGINT, p_bayt_sayisi BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SET search_path = entegrasyon, public
AS $$
DECLARE
    v_calisma calistirma%ROWTYPE;
    v_durum calistirma_durumu%ROWTYPE;
    v_hedef hedef_kaynagi%ROWTYPE;
    v_kanit prosedur_adim_kaniti%ROWTYPE;
    v_adim_durumu prosedur_adim_durumu%ROWTYPE;
    v_simdi TIMESTAMPTZ := clock_timestamp();
BEGIN
    IF p_satir_sayisi < 0 OR p_bayt_sayisi < 0 THEN
        RAISE EXCEPTION 'Prosedür adım sayımları geçersiz';
    END IF;
    SELECT * INTO v_calisma FROM calistirma WHERE uuid = p_calistirma_uuid;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    SELECT * INTO v_durum FROM calistirma_durumu
     WHERE proje_id = v_calisma.proje_id AND calistirma_id = v_calisma.id
     FOR UPDATE;
    SELECT * INTO v_hedef FROM hedef_kaynagi
     WHERE id = v_durum.hedef_kaynagi_id AND uuid = p_hedef_kaynagi_uuid
     FOR UPDATE;
    SELECT pak.* INTO v_kanit FROM prosedur_adim_kaniti pak
      JOIN calistirma_adimi ca ON ca.id = pak.calistirma_adimi_id
     WHERE pak.calistirma_id = v_calisma.id AND ca.adim_kodu = p_adim_kodu;
    IF NOT FOUND THEN RETURN FALSE; END IF;
    SELECT * INTO v_adim_durumu FROM prosedur_adim_durumu
     WHERE prosedur_adim_kaniti_id = v_kanit.id FOR UPDATE;

    IF v_adim_durumu.durum_kodu = 'BASARILI' THEN
        RETURN COALESCE((
           v_durum.durum_kodu = 'CALISIYOR'
           AND v_durum.isleyici_referansi = p_isleyici_referansi
           AND v_durum.nesil_no = p_calistirma_nesil_no
           AND v_durum.hedef_nesil_no = p_hedef_nesil_no
           AND v_durum.kiralama_bitis_zamani > v_simdi
           AND v_hedef.id IS NOT NULL
           AND v_hedef.durum_kodu = 'SAHIPLENILDI'
           AND v_hedef.calistirma_id = v_calisma.id
           AND v_hedef.nesil_no = p_hedef_nesil_no
           AND v_hedef.kiralama_bitis_zamani > v_simdi
           AND v_adim_durumu.satir_sayisi = p_satir_sayisi
           AND v_adim_durumu.bayt_sayisi = p_bayt_sayisi
           AND EXISTS (
                SELECT 1 FROM calistirma_olayi co
                 WHERE co.calistirma_id = v_calisma.id
                   AND co.calistirma_adimi_id = v_kanit.calistirma_adimi_id
                   AND co.olay_no = v_adim_durumu.son_olay_no
                   AND co.tur_kodu = 'PROCEDURE_STEP_SUCCEEDED'
                   AND co.veri ->> 'generation' = p_calistirma_nesil_no::TEXT
                   AND co.veri ->> 'workerReference' = p_isleyici_referansi
                   AND co.veri ->> 'targetGeneration' = p_hedef_nesil_no::TEXT
                   AND co.veri ->> 'rowCount' = p_satir_sayisi::TEXT
                   AND co.veri ->> 'byteCount' = p_bayt_sayisi::TEXT)), FALSE);
    END IF;

    IF v_durum.durum_kodu <> 'CALISIYOR'
       OR v_durum.isleyici_referansi IS DISTINCT FROM p_isleyici_referansi
       OR v_durum.nesil_no <> p_calistirma_nesil_no
       OR v_durum.hedef_nesil_no <> p_hedef_nesil_no
       OR v_durum.kiralama_bitis_zamani <= v_simdi
       OR v_hedef.id IS NULL OR v_hedef.durum_kodu <> 'SAHIPLENILDI'
       OR v_hedef.calistirma_id <> v_calisma.id
       OR v_hedef.nesil_no <> p_hedef_nesil_no
       OR v_hedef.kiralama_bitis_zamani <= v_simdi
       OR v_adim_durumu.durum_kodu <> 'CALISIYOR' THEN
        RETURN FALSE;
    END IF;

    UPDATE prosedur_adim_durumu
       SET durum_kodu = 'BASARILI', son_olay_no = v_durum.son_olay_no + 1,
           bitis_zamani = v_simdi, satir_sayisi = p_satir_sayisi,
           bayt_sayisi = p_bayt_sayisi, guncellenme_zamani = v_simdi,
           versiyon_no = v_adim_durumu.versiyon_no + 1
     WHERE id = v_adim_durumu.id;
    UPDATE calistirma_durumu
       SET son_olay_no = v_durum.son_olay_no + 1,
           guncellenme_zamani = v_simdi,
           versiyon_no = v_durum.versiyon_no + 1
     WHERE id = v_durum.id;
    INSERT INTO calistirma_olayi(
        proje_id, calistirma_id, calistirma_adimi_id, olay_no,
        tur_kodu, olay_zamani, veri)
    VALUES (v_calisma.proje_id, v_calisma.id,
            v_kanit.calistirma_adimi_id, v_durum.son_olay_no + 1,
            'PROCEDURE_STEP_SUCCEEDED', v_simdi,
            jsonb_build_object(
                'generation', p_calistirma_nesil_no,
                'workerReference', p_isleyici_referansi,
                'targetResourceUuid', p_hedef_kaynagi_uuid,
                'targetGeneration', p_hedef_nesil_no,
                'runtimePlanHash', v_kanit.runtime_plan_ozeti,
                'commandHash', v_kanit.komut_ozeti,
                'rowCount', p_satir_sayisi,
                'byteCount', p_bayt_sayisi));
    RETURN TRUE;
END;
$$;

REVOKE ALL ON FUNCTION prosedur_adim_durumunu_dogrula() FROM PUBLIC;
REVOKE ALL ON FUNCTION prosedur_calistirmayi_baslat(
    UUID, TEXT, BIGINT, UUID, BIGINT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION prosedur_adimini_baslat(
    UUID, TEXT, BIGINT, UUID, BIGINT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION prosedur_adimini_basarili_tamamla(
    UUID, TEXT, BIGINT, UUID, BIGINT, TEXT, BIGINT, BIGINT) FROM PUBLIC;

COMMENT ON TABLE prosedur_adim_kaniti IS
    'ORACLE_PROCEDURE_V1 run adımlarının immutable, secret-free plan kanıtı';
COMMENT ON TABLE prosedur_adim_durumu IS
    'Prosedür adımlarının kontrollü mutable durum projeksiyonu';
COMMENT ON TABLE prosedur_adim_niyeti IS
    'Oracle mutating prosedür adımı başlamadan önce yazılan immutable niyet';
COMMENT ON FUNCTION prosedur_calistirmayi_baslat(
    UUID, TEXT, BIGINT, UUID, BIGINT, TEXT) IS
    'Pinned Procedure planını materialize eder ve exact-ACK ile CALISIYOR durumuna geçirir';
