SET search_path TO entegrasyon, public;

CREATE TABLE baglanti_surumu_yasam_dongusu (
    proje_id BIGINT NOT NULL,
    baglanti_id BIGINT NOT NULL,
    baglanti_surumu_id BIGINT NOT NULL,
    durum_kodu TEXT NOT NULL DEFAULT 'DRAFT',
    durum_surumu BIGINT NOT NULL DEFAULT 1,
    hedef_kimlik_surumu INTEGER,
    hedef_parmak_izi TEXT,
    son_basarili_test_uuid UUID,
    test_edilme_zamani TIMESTAMPTZ,
    aktiflestirilme_zamani TIMESTAMPTZ,
    guncellenme_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_baglanti_surumu_yasam_dongusu PRIMARY KEY (baglanti_surumu_id),
    CONSTRAINT uq_baglanti_surumu_yasam_dongusu_bag
        UNIQUE (proje_id, baglanti_id, baglanti_surumu_id),
    CONSTRAINT fk_baglanti_surumu_yasam_dongusu_proje
        FOREIGN KEY (proje_id) REFERENCES proje(id),
    CONSTRAINT fk_baglanti_surumu_yasam_dongusu_baglanti
        FOREIGN KEY (proje_id, baglanti_id) REFERENCES baglanti(proje_id, id),
    CONSTRAINT fk_baglanti_surumu_yasam_dongusu_surum
        FOREIGN KEY (proje_id, baglanti_surumu_id)
        REFERENCES baglanti_surumu(proje_id, id),
    CONSTRAINT ck_baglanti_surumu_yasam_dongusu_durum
        CHECK (durum_kodu IN ('DRAFT', 'TESTED', 'ACTIVE')),
    CONSTRAINT ck_baglanti_surumu_yasam_dongusu_surum_no
        CHECK (durum_surumu > 0),
    CONSTRAINT ck_baglanti_surumu_yasam_dongusu_hedef
        CHECK (
            (durum_kodu = 'DRAFT'
                AND hedef_kimlik_surumu IS NULL
                AND hedef_parmak_izi IS NULL
                AND son_basarili_test_uuid IS NULL
                AND test_edilme_zamani IS NULL
                AND aktiflestirilme_zamani IS NULL)
            OR
            (durum_kodu = 'TESTED'
                AND hedef_kimlik_surumu > 0
                AND hedef_parmak_izi ~ '^[0-9a-f]{64}$'
                AND son_basarili_test_uuid IS NOT NULL
                AND test_edilme_zamani IS NOT NULL
                AND aktiflestirilme_zamani IS NULL)
            OR
            (durum_kodu = 'ACTIVE'
                AND hedef_kimlik_surumu > 0
                AND hedef_parmak_izi ~ '^[0-9a-f]{64}$'
                AND son_basarili_test_uuid IS NOT NULL
                AND test_edilme_zamani IS NOT NULL
                AND aktiflestirilme_zamani IS NOT NULL)
        )
);

CREATE TABLE baglanti_surumu_testi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL,
    baglanti_id BIGINT NOT NULL,
    baglanti_surumu_id BIGINT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    deneme_no INTEGER NOT NULL,
    sonuc_kodu TEXT NOT NULL,
    hata_kodu TEXT,
    database_product TEXT,
    database_version TEXT,
    database_major INTEGER,
    database_minor INTEGER,
    driver_name TEXT,
    driver_version TEXT,
    hedef_kimlik_surumu INTEGER,
    hedef_parmak_izi TEXT,
    baslama_zamani TIMESTAMPTZ NOT NULL,
    tamamlanma_zamani TIMESTAMPTZ NOT NULL,
    sure_ms BIGINT NOT NULL,
    CONSTRAINT pk_baglanti_surumu_testi PRIMARY KEY (id),
    CONSTRAINT uq_baglanti_surumu_testi_uuid UNIQUE (uuid),
    CONSTRAINT uq_baglanti_surumu_testi_deneme
        UNIQUE (baglanti_surumu_id, deneme_no),
    CONSTRAINT uq_baglanti_surumu_testi_bag
        UNIQUE (proje_id, baglanti_id, baglanti_surumu_id, uuid),
    CONSTRAINT fk_baglanti_surumu_testi_proje
        FOREIGN KEY (proje_id) REFERENCES proje(id),
    CONSTRAINT fk_baglanti_surumu_testi_baglanti
        FOREIGN KEY (proje_id, baglanti_id) REFERENCES baglanti(proje_id, id),
    CONSTRAINT fk_baglanti_surumu_testi_yasam_dongusu
        FOREIGN KEY (proje_id, baglanti_id, baglanti_surumu_id)
        REFERENCES baglanti_surumu_yasam_dongusu(proje_id, baglanti_id, baglanti_surumu_id),
    CONSTRAINT ck_baglanti_surumu_testi_deneme_no CHECK (deneme_no > 0),
    CONSTRAINT ck_baglanti_surumu_testi_sonuc
        CHECK (sonuc_kodu IN ('PASSED', 'FAILED', 'TARGET_MISMATCH')),
    CONSTRAINT ck_baglanti_surumu_testi_sure
        CHECK (sure_ms >= 0 AND tamamlanma_zamani >= baslama_zamani),
    CONSTRAINT ck_baglanti_surumu_testi_parmak_izi
        CHECK (hedef_parmak_izi IS NULL OR hedef_parmak_izi ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_baglanti_surumu_testi_sonuc_yapisi
        CHECK (
            (sonuc_kodu = 'PASSED'
                AND hata_kodu IS NULL
                AND database_product IS NOT NULL
                AND database_version IS NOT NULL
                AND database_major >= 0
                AND database_minor >= 0
                AND driver_name IS NOT NULL
                AND driver_version IS NOT NULL
                AND hedef_kimlik_surumu > 0
                AND hedef_parmak_izi ~ '^[0-9a-f]{64}$')
            OR
            (sonuc_kodu = 'FAILED'
                AND hata_kodu IS NOT NULL)
            OR
            (sonuc_kodu = 'TARGET_MISMATCH'
                AND hata_kodu IS NOT NULL
                AND hedef_kimlik_surumu > 0
                AND hedef_parmak_izi ~ '^[0-9a-f]{64}$')
        )
);

ALTER TABLE baglanti_surumu_yasam_dongusu
    ADD CONSTRAINT fk_baglanti_surumu_yasam_dongusu_son_test
    FOREIGN KEY (proje_id, baglanti_id, baglanti_surumu_id, son_basarili_test_uuid)
    REFERENCES baglanti_surumu_testi(proje_id, baglanti_id, baglanti_surumu_id, uuid);

CREATE INDEX ix_baglanti_surumu_testi_surum_zaman
    ON baglanti_surumu_testi(proje_id, baglanti_surumu_id, tamamlanma_zamani DESC, id DESC);

INSERT INTO baglanti_surumu_yasam_dongusu(
    proje_id, baglanti_id, baglanti_surumu_id, durum_kodu)
SELECT proje_id, baglanti_id, id, 'DRAFT'
  FROM baglanti_surumu;

CREATE OR REPLACE FUNCTION fn_baglanti_surumu_yasam_dongusu_olustur()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO entegrasyon.baglanti_surumu_yasam_dongusu(
        proje_id, baglanti_id, baglanti_surumu_id, durum_kodu)
    VALUES (NEW.proje_id, NEW.baglanti_id, NEW.id, 'DRAFT');
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_baglanti_surumu_yasam_dongusu_olustur
AFTER INSERT ON baglanti_surumu
FOR EACH ROW EXECUTE FUNCTION fn_baglanti_surumu_yasam_dongusu_olustur();

CREATE OR REPLACE FUNCTION fn_baglanti_surumu_testi_degistirilemez()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Connection version test journal is append-only.';
END;
$$;

CREATE TRIGGER tr_baglanti_surumu_testi_degistirilemez
BEFORE UPDATE OR DELETE ON baglanti_surumu_testi
FOR EACH ROW EXECUTE FUNCTION fn_baglanti_surumu_testi_degistirilemez();

CREATE OR REPLACE FUNCTION fn_baglanti_surumu_yasam_dongusu_dogrula()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_surum_baglanti_id BIGINT;
    v_test entegrasyon.baglanti_surumu_testi%ROWTYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Connection version lifecycle rows cannot be deleted.';
    END IF;

    SELECT baglanti_id
      INTO v_surum_baglanti_id
      FROM entegrasyon.baglanti_surumu
     WHERE proje_id = NEW.proje_id
       AND id = NEW.baglanti_surumu_id;
    IF v_surum_baglanti_id IS NULL OR v_surum_baglanti_id <> NEW.baglanti_id THEN
        RAISE EXCEPTION 'Connection version lifecycle relationship is invalid.';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF NEW.durum_kodu <> 'DRAFT'
                OR NEW.durum_surumu <> 1
                OR NEW.hedef_kimlik_surumu IS NOT NULL
                OR NEW.hedef_parmak_izi IS NOT NULL
                OR NEW.son_basarili_test_uuid IS NOT NULL
                OR NEW.test_edilme_zamani IS NOT NULL
                OR NEW.aktiflestirilme_zamani IS NOT NULL THEN
            RAISE EXCEPTION 'Connection version lifecycle must start in DRAFT.';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.proje_id <> OLD.proje_id
            OR NEW.baglanti_id <> OLD.baglanti_id
            OR NEW.baglanti_surumu_id <> OLD.baglanti_surumu_id THEN
        RAISE EXCEPTION 'Connection version lifecycle identity is immutable.';
    END IF;
    IF NEW.durum_surumu <> OLD.durum_surumu + 1 THEN
        RAISE EXCEPTION 'Connection version lifecycle state version is stale.';
    END IF;
    IF OLD.hedef_parmak_izi IS NOT NULL
            AND (NEW.hedef_parmak_izi IS DISTINCT FROM OLD.hedef_parmak_izi
                 OR NEW.hedef_kimlik_surumu IS DISTINCT FROM OLD.hedef_kimlik_surumu) THEN
        RAISE EXCEPTION 'Pinned Oracle target identity is immutable.';
    END IF;

    IF NOT ((OLD.durum_kodu = 'DRAFT' AND NEW.durum_kodu = 'TESTED')
            OR (OLD.durum_kodu = 'TESTED' AND NEW.durum_kodu = 'TESTED')
            OR (OLD.durum_kodu = 'TESTED' AND NEW.durum_kodu = 'ACTIVE')
            OR (OLD.durum_kodu = 'ACTIVE' AND NEW.durum_kodu = 'ACTIVE')) THEN
        RAISE EXCEPTION 'Invalid connection version lifecycle transition.';
    END IF;

    IF OLD.durum_kodu = 'TESTED' AND NEW.durum_kodu = 'ACTIVE' THEN
        IF NEW.hedef_kimlik_surumu IS DISTINCT FROM OLD.hedef_kimlik_surumu
                OR NEW.hedef_parmak_izi IS DISTINCT FROM OLD.hedef_parmak_izi
                OR NEW.son_basarili_test_uuid IS DISTINCT FROM OLD.son_basarili_test_uuid
                OR NEW.test_edilme_zamani IS DISTINCT FROM OLD.test_edilme_zamani
                OR NEW.aktiflestirilme_zamani IS NULL THEN
            RAISE EXCEPTION 'Activation may only add its activation timestamp.';
        END IF;
    ELSE
        IF NEW.aktiflestirilme_zamani IS DISTINCT FROM OLD.aktiflestirilme_zamani THEN
            RAISE EXCEPTION 'Activation timestamp may change only during activation.';
        END IF;
        SELECT *
          INTO v_test
          FROM entegrasyon.baglanti_surumu_testi
         WHERE proje_id = NEW.proje_id
           AND baglanti_id = NEW.baglanti_id
           AND baglanti_surumu_id = NEW.baglanti_surumu_id
           AND uuid = NEW.son_basarili_test_uuid;
        IF NOT FOUND
                OR v_test.sonuc_kodu <> 'PASSED'
                OR v_test.hedef_kimlik_surumu IS DISTINCT FROM NEW.hedef_kimlik_surumu
                OR v_test.hedef_parmak_izi IS DISTINCT FROM NEW.hedef_parmak_izi
                OR v_test.tamamlanma_zamani IS DISTINCT FROM NEW.test_edilme_zamani THEN
            RAISE EXCEPTION 'Lifecycle test evidence is invalid.';
        END IF;
    END IF;

    NEW.guncellenme_zamani := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_baglanti_surumu_yasam_dongusu_dogrula
BEFORE INSERT OR UPDATE OR DELETE ON baglanti_surumu_yasam_dongusu
FOR EACH ROW EXECUTE FUNCTION fn_baglanti_surumu_yasam_dongusu_dogrula();
