import { Database, GitBranch, Plus, Workflow } from 'lucide-react'
import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { useCurrentProjectUuid } from '../projects/CurrentProjectContext'
import { AsyncState, Button, Dialog, PageHeader, SummaryStrip } from '../../core/ui'
import { useProjectAccess } from '../../core/auth/ProjectAccessContext'
import { topologyApi, type Environment, type LogicalSchema, type SchemaBinding } from '../topology/api'
import { FeedbackToast } from '../../core/ui/FeedbackToast'
import { QueryFilter } from '../../core/ui/QueryFilter'
import '../schemas/schemas.css'

export function EnvironmentsPage() {
  const [notice, setNotice] = useState('')
  const closeNotice = useCallback(() => setNotice(''), [])
  const projectUuid = useCurrentProjectUuid(); const { t } = useTranslation(); const { can } = useProjectAccess(); const canManage = can('BAGLANTI_YONET')
  const [items, setItems] = useState<Environment[]>([]); const [logicalSchemas, setLogicalSchemas] = useState<LogicalSchema[]>([]); const [bindings, setBindings] = useState<SchemaBinding[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [nextItems, nextLogical, nextBindings] = await Promise.all([topologyApi.listEnvironments(projectUuid), topologyApi.listLogicalSchemas(projectUuid), topologyApi.listBindings(projectUuid)]); setItems(nextItems); setLogicalSchemas(nextLogical); setBindings(nextBindings) } catch { setError(t('common.loadError')) } finally { setLoading(false) } }, [projectUuid, t])
  useEffect(() => { void load() }, [load])
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { await topologyApi.createEnvironment(projectUuid, { code: String(data.get('code')).trim().toUpperCase(), name: String(data.get('name')).trim() }); setOpen(false); setNotice(t('common.savedSuccessfully')); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : t('common.saveError')) } finally { setBusy(false) } }
  const filteredItems = items.filter((item) => `${item.name} ${item.code}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))
  return <section className="page-stack schema-page"><FeedbackToast message={notice} onClose={closeNotice} /><PageHeader eyebrow={t('schemas.eyebrow')} title={t('schemas.environmentsTitle')} description={t('schemas.environmentsDescription')} actions={canManage ? <Button tone="primary" icon={<Plus size={16} />} onClick={() => setOpen(true)}>{t('schemas.addEnvironment')}</Button> : undefined} />{error ? <div className="error-banner" role="alert">{error}</div> : null}<QueryFilter onApply={setQuery} placeholder={`${t('schemas.name')} · ${t('schemas.code')}`} /><SummaryStrip ariaLabel={t('schemas.environmentsTitle')} items={[{ label: t('schemas.environmentsTitle'), value: items.length, icon: <Workflow />, tone: 'info' }, { label: t('schemas.logicalTitle'), value: logicalSchemas.length, icon: <GitBranch />, tone: 'neutral' }, { label: t('schemas.initialMapping'), value: bindings.length, icon: <Database />, tone: 'success' }]} />{loading ? <AsyncState state="loading" title={t('common.loading')} /> : filteredItems.length === 0 ? <AsyncState state="empty" title={t('schemas.noEnvironments')} /> : <div className="schema-list-table"><table><thead><tr><th>{t('schemas.name')}</th><th>{t('schemas.code')}</th></tr></thead><tbody>{filteredItems.map((item) => <tr key={item.uuid}><td><Link className="schema-name-link" to={`/project/environments/${item.uuid}`}>{item.name}</Link></td><td><code>{item.code}</code></td></tr>)}</tbody></table></div>}<Dialog open={canManage && open} title={t('schemas.addEnvironment')} closeLabel={t('common.close')} busy={busy} onClose={() => setOpen(false)}><form onSubmit={(event) => void create(event)}><label>{t('schemas.name')}<input name="name" required /></label><label>{t('schemas.code')}<input name="code" pattern="[A-Za-z][A-Za-z0-9_]{0,99}" required /></label><p className="form-note">{t('schemas.environmentSimpleHint')}</p><footer><Button type="button" onClick={() => setOpen(false)}>{t('common.cancel')}</Button><Button type="submit" tone="primary" busy={busy}>{t('schemas.create')}</Button></footer></form></Dialog></section>
}
