import { Link2 } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { useParams } from 'react-router-dom'
import { AsyncState, Button, Dialog, PageHeader } from '../../core/ui'
import { useProjectAccess } from '../../core/auth/ProjectAccessContext'
import { topologyApi, type Connection, type ConnectionVersion, type Environment, type LogicalSchema, type PhysicalSchema, type SchemaBinding } from '../topology/api'
import './schemas.css'
import { bindingForContext, compatibleVersions } from './bindingModel'
import { lifecycleLabel } from '../topology/ConnectionVersionLifecyclePanel'
import { getTopologyCopy } from '../topology/copy'

export function SchemaBindingsPage() {
  const { projectUuid = '' } = useParams(); const { t, i18n } = useTranslation(); const topologyCopy = getTopologyCopy(i18n.language); const { can } = useProjectAccess(); const canManage = can('BAGLANTI_YONET')
  const [logical, setLogical] = useState<LogicalSchema[]>([]); const [environments, setEnvironments] = useState<Environment[]>([]); const [physical, setPhysical] = useState<PhysicalSchema[]>([]); const [connections, setConnections] = useState<Connection[]>([]); const [bindings, setBindings] = useState<SchemaBinding[]>([]); const [versions, setVersions] = useState<Record<string, ConnectionVersion[]>>({}); const [selection, setSelection] = useState<{ logicalUuid: string; environmentUuid: string } | null>(null); const [physicalUuid, setPhysicalUuid] = useState(''); const [versionUuid, setVersionUuid] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [nextLogical, nextEnvironments, nextPhysical, nextConnections, nextBindings] = await Promise.all([topologyApi.listLogicalSchemas(projectUuid), topologyApi.listEnvironments(projectUuid), topologyApi.listPhysicalSchemas(projectUuid), topologyApi.listConnections(projectUuid), topologyApi.listBindings(projectUuid)]); const versionEntries = await Promise.all(nextConnections.map(async (connection) => [connection.uuid, await topologyApi.listVersions(projectUuid, connection.uuid)] as const)); setLogical(nextLogical); setEnvironments(nextEnvironments); setPhysical(nextPhysical); setConnections(nextConnections); setBindings(nextBindings); setVersions(Object.fromEntries(versionEntries)) } catch { setError(t('common.loadError')) } finally { setLoading(false) } }, [projectUuid, t])
  useEffect(() => { void load() }, [load])
  const availableVersions = useMemo(() => compatibleVersions(physicalUuid, physical, versions), [physical, physicalUuid, versions])
  const bindingFor = (logicalUuid: string, environmentUuid: string) => bindingForContext(bindings, logicalUuid, environmentUuid)
  const openEditor = (logicalUuid: string, environmentUuid: string) => { const existing = bindingFor(logicalUuid, environmentUuid); setSelection({ logicalUuid, environmentUuid }); setPhysicalUuid(existing?.physicalSchemaUuid ?? ''); setVersionUuid(existing?.connectionVersionUuid ?? '') }
  const labelForBinding = (binding?: SchemaBinding) => { if (!binding) return t('schemas.notMapped'); const schema = physical.find((item) => item.uuid === binding.physicalSchemaUuid); const connection = connections.find((item) => item.uuid === schema?.connectionUuid); const version = Object.values(versions).flat().find((item) => item.uuid === binding.connectionVersionUuid); return `${connection?.name ?? '—'} / ${schema?.name ?? '—'} / r${version?.versionNumber ?? '—'}` }
  async function save(event: FormEvent) { event.preventDefault(); if (!selection) return; const existing = bindingFor(selection.logicalUuid, selection.environmentUuid); setBusy(true); setError(''); const body = { logicalSchemaUuid: selection.logicalUuid, environmentUuid: selection.environmentUuid, physicalSchemaUuid: physicalUuid, connectionVersionUuid: versionUuid, ...(existing ? { expectedVersion: existing.version } : {}) }; try { if (existing) await topologyApi.updateBinding(projectUuid, existing.uuid, body); else await topologyApi.createBinding(projectUuid, body); setSelection(null); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : t('common.saveError')) } finally { setBusy(false) } }
  useEffect(() => { if (availableVersions.some((item) => item.uuid === versionUuid)) return; setVersionUuid(availableVersions.find((item) => item.lifecycleStatus === 'ACTIVE')?.uuid ?? availableVersions[0]?.uuid ?? '') }, [availableVersions, versionUuid])
  if (loading) return <AsyncState state="loading" title={t('common.loading')} />
  return <section className="page-stack schema-page"><PageHeader eyebrow={t('schemas.eyebrow')} title={t('schemas.bindingsTitle')} description={t('schemas.bindingsDescription')} />{error ? <div className="error-banner" role="alert">{error}</div> : null}{logical.length === 0 || environments.length === 0 ? <AsyncState state="empty" title={t('schemas.bindingPrerequisite')} description={t('schemas.bindingPrerequisiteHint')} /> : <div className="binding-matrix-wrap"><table className="binding-matrix"><thead><tr><th>{t('schemas.logicalSchema')}</th>{environments.map((environment) => <th key={environment.uuid}>{environment.name}<small>{environment.code}</small></th>)}</tr></thead><tbody>{logical.map((schema) => <tr key={schema.uuid}><th><strong>{schema.name}</strong><small>{schema.code}</small></th>{environments.map((environment) => { const binding = bindingFor(schema.uuid, environment.uuid); return <td key={environment.uuid}><button type="button" className={binding ? 'is-mapped' : ''} disabled={!canManage} onClick={() => openEditor(schema.uuid, environment.uuid)}><Link2 /><span>{labelForBinding(binding)}</span></button></td> })}</tr>)}</tbody></table></div>}<Dialog open={canManage && selection !== null} title={t('schemas.editBinding')} closeLabel={t('common.close')} busy={busy} onClose={() => setSelection(null)}><form onSubmit={(event) => void save(event)}><label>{t('schemas.physicalSchema')}<select required value={physicalUuid} onChange={(event) => setPhysicalUuid(event.target.value)}><option value="">—</option>{physical.map((item) => <option key={item.uuid} value={item.uuid}>{connections.find((connection) => connection.uuid === item.connectionUuid)?.name} / {item.name}</option>)}</select></label><label>{t('schemas.connectionRevision')}<select required value={versionUuid} onChange={(event) => setVersionUuid(event.target.value)} disabled={!physicalUuid}><option value="">—</option>{availableVersions.map((item) => <option key={item.uuid} value={item.uuid}>r{item.versionNumber} · {lifecycleLabel(item.lifecycleStatus, topologyCopy)}</option>)}</select></label><p className="form-note">{t('schemas.bindingPinHint')}</p><footer><Button type="button" onClick={() => setSelection(null)}>{t('common.cancel')}</Button><Button type="submit" tone="primary" busy={busy} disabled={!physicalUuid || !versionUuid}>{t('schemas.saveBinding')}</Button></footer></form></Dialog></section>
}
