const copy = {
  en: {
    eyebrow: 'CONNECTION DEFINITIONS', title: 'Connections', subtitle: 'Manage providers, versioned endpoints, physical schemas, and logical environment mappings for this project.',
    connections: 'Connections', schemas: 'Schemas', bindings: 'Schema mappings', catalog: 'Catalog',
    secretRefs: 'Secret references', versions: 'Connection versions', physical: 'Physical schemas', logical: 'Logical schemas', environments: 'Environments',
    models: 'Models', submodels: 'Submodels', dataObjects: 'Data objects', create: 'Create', creating: 'Creating…', refresh: 'Refresh',
    name: 'Name', code: 'Code', status: 'Status', description: 'Description', actions: 'Actions', select: 'Select', selected: 'Selected', unavailable: 'Unavailable',
    provider: 'Provider', referencePath: 'Reference path', versionReference: 'Version reference', databaseType: 'Database type',
    addSecret: 'Add Secret Reference', addConnection: 'Add Connection', addVersion: 'Add Version', addPhysical: 'Add Physical Schema', addLogical: 'Add Logical Schema', addEnvironment: 'Add Environment', addBinding: 'Add Schema Mapping', addModel: 'Add Model', addSubmodel: 'Add Submodel', addDataObject: 'Add Data Object',
    driver: 'Driver reference', host: 'Host', port: 'Port', serviceName: 'Service name', sid: 'SID', tlsMode: 'TLS mode', secret: 'Secret reference', secretRole: 'Secret role',
    connection: 'Connection', version: 'Version', schemaReference: 'Schema reference', logicalSchema: 'Logical schema', physicalSchema: 'Physical schema', environment: 'Environment', risk: 'Risk', riskLow: 'Low', riskMedium: 'Medium', riskProduction: 'Production',
    model: 'Model', parent: 'Parent submodel', submodel: 'Submodel', objectReference: 'Object reference', type: 'Type', tableType: 'Table', viewType: 'View',
    test: 'Test Oracle Connection', testing: 'Testing…', discover: 'Discover Oracle Schema', discovering: 'Discovering…', tableFilter: 'Table name (optional)', limit: 'Table limit',
    noItems: 'No records yet.', loading: 'Loading…', loadFailed: 'Could not load data.', tryAgain: 'Try Again', saveFailed: 'Could not save the record.',
    chooseConnection: 'Select a connection to manage versions.', chooseModel: 'Select a model to manage its catalog.', chooseVersion: 'Select a version first.',
    chooseDiscovery: 'Choose a connection version and a physical schema for that connection.', testSuccess: 'Connection successful', compatible: 'Oracle 19c compatible', incompatible: 'Not Oracle 19c compatible',
    discoveryResults: 'Discovery results', tables: 'tables', truncated: 'Result limited', emptyDiscovery: 'No tables found.', required: 'Required', optional: 'Optional',
    activeSelection: 'Active selection', details: 'Details', close: 'Close', policyVersion: 'Policy version', all: 'All', noSecretValues: 'Only secret references are stored here. Secret values are never requested or displayed.',
    endpointStep: 'Endpoint', credentialsStep: 'Credentials', reviewStep: 'Review', connectionMode: 'Connection mode',
    jdbcModeHint: 'Direct, platform-managed Oracle JDBC connection', jndiModeHint: 'Application-server managed local DataSource',
    transport: 'Transport', connectIdentifier: 'Connect identifier', driverManaged: 'The Oracle JDBC driver and policy version are managed by the platform.',
    executionPolicy: 'Connection timeouts', connectTimeout: 'Connect timeout (ms)', readTimeout: 'Read timeout (ms)', networkTimeout: 'Network timeout (ms)', queryTimeout: 'Query timeout (seconds)',
    jndiName: 'JNDI name', localJndiOnly: 'Only local java:comp/env/jdbc/ resources are accepted. Remote providers are blocked.',
    credentialSecret: 'Credential profile', secretRequiredHint: 'No managed credential profile is available for a JDBC version.',
    containerManaged: 'Container-managed credentials', containerManagedHint: 'The application server owns the DataSource and its credentials; Akis stores only the local JNDI name.',
    endpoint: 'Endpoint', systemManaged: 'system managed', back: 'Back', continue: 'Continue', createVersion: 'Create Version',
    versionCreated: 'Connection version created', done: 'Done', invalidConnectionFields: 'Complete the required connection fields with valid values.',
    jndiRuntimeHint: 'Testing requires this JNDI DataSource to be registered in the running application environment.',
    jndiExecutionBlocked: 'This mode is metadata/test only; package and procedure execution is blocked until target identity pinning is available.',
    tcpsPlanned: 'TCPS · verified TLS coming later',
    lifecycleDraft: 'Draft', lifecycleTested: 'Tested', lifecycleActive: 'Active', notTested: 'Not tested yet',
    testedAt: 'Tested', activatedAt: 'Activated', latestTestEvidence: 'Latest test evidence', noTestEvidence: 'No test evidence recorded yet.',
    testVersion: 'Test Version', testAgain: 'Test Again', activateVersion: 'Activate Version', activating: 'Activating…',
    activationPrompt: 'Approve this version for runtime use?', activationEvidence: 'Activation uses the latest successful test evidence.',
    confirmActivation: 'Confirm Activation', cancel: 'Cancel', versionActivated: 'Connection version activated.',
    activationRequiresTest: 'A successful test is required before activation.', runtimeLimited: 'Runtime limited',
    targetFingerprint: 'Target fingerprint', revealFingerprint: 'Reveal full fingerprint', hideFingerprint: 'Hide full fingerprint',
    copyFingerprint: 'Copy fingerprint', fingerprintCopied: 'Fingerprint copied', targetIdentity: 'Target identity v{{version}}',
    testPassed: 'Passed', testFailed: 'Failed', targetMismatch: 'Target mismatch', attempt: 'Attempt {{number}}', duration: '{{duration}} ms',
    evidenceLoadFailed: 'Test evidence could not be loaded.', activationFailed: 'The connection version could not be activated.',
    activationConflict: 'The version changed. Refresh and activate it using the current successful test.', connectionTestFailed: 'The connection test failed.',
    saveSchemaSnapshot: 'Save Schema Snapshot', schemaSnapshot: 'Schema snapshot', dataObject: 'Data object',
    discoveredAt: 'Discovered at', columns: 'Columns', constraints: 'Constraints', nullable: 'Nullable', position: 'Position', yes: 'Yes', no: 'No', recommended: 'Recommended',
    immutableSnapshotHint: 'This creates immutable, server-produced schema evidence. It cannot be edited after saving.',
    confirmSnapshot: 'Confirm and Save', savingSnapshot: 'Saving snapshot…', snapshotSaved: 'Schema snapshot saved',
    snapshotId: 'Snapshot ID', createdAt: 'Created at', databaseEngine: 'Database engine', loadingDataObjects: 'Loading data objects…',
    snapshotReferenceMismatch: 'The selected catalog reference differs from this result. The server will capture the selected data object reference.',
    noCompatibleModels: 'No active model is linked to this physical schema context.',
    noCompatibleDataObjects: 'No active table data object is available in this model.', missingProject: 'Select a project before opening connections.',
    snapshotObjectsLoadFailed: 'Data objects could not be loaded.', snapshotSaveFailed: 'The schema snapshot could not be saved.',
  },
  tr: {
    eyebrow: 'BAĞLANTI TANIMLARI', title: 'Bağlantılar', subtitle: 'Bu projenin sağlayıcı, sürümlü uç nokta, fiziksel şema ve mantıksal ortam eşlemelerini yönetin.',
    connections: 'Bağlantılar', schemas: 'Şemalar', bindings: 'Şema Eşlemeleri', catalog: 'Katalog',
    secretRefs: 'Gizli bilgi referansları', versions: 'Bağlantı sürümleri', physical: 'Fiziksel şemalar', logical: 'Mantıksal şemalar', environments: 'Ortamlar',
    models: 'Modeller', submodels: 'Alt modeller', dataObjects: 'Veri nesneleri', create: 'Oluştur', creating: 'Oluşturuluyor…', refresh: 'Yenile',
    name: 'Ad', code: 'Kod', status: 'Durum', description: 'Açıklama', actions: 'İşlemler', select: 'Seç', selected: 'Seçili', unavailable: 'Kullanılamıyor',
    provider: 'Sağlayıcı', referencePath: 'Referans yolu', versionReference: 'Sürüm referansı', databaseType: 'Veritabanı türü',
    addSecret: 'Gizli Bilgi Referansı Ekle', addConnection: 'Bağlantı Ekle', addVersion: 'Sürüm Ekle', addPhysical: 'Fiziksel Şema Ekle', addLogical: 'Mantıksal Şema Ekle', addEnvironment: 'Ortam Ekle', addBinding: 'Şema Eşlemesi Ekle', addModel: 'Model Ekle', addSubmodel: 'Alt Model Ekle', addDataObject: 'Veri Nesnesi Ekle',
    driver: 'Sürücü referansı', host: 'Sunucu', port: 'Port', serviceName: 'Servis adı', sid: 'SID', tlsMode: 'TLS modu', secret: 'Gizli bilgi referansı', secretRole: 'Gizli bilgi rolü',
    connection: 'Bağlantı', version: 'Sürüm', schemaReference: 'Şema referansı', logicalSchema: 'Mantıksal şema', physicalSchema: 'Fiziksel şema', environment: 'Ortam', risk: 'Risk', riskLow: 'Düşük', riskMedium: 'Orta', riskProduction: 'Üretim',
    model: 'Model', parent: 'Üst alt model', submodel: 'Alt model', objectReference: 'Nesne referansı', type: 'Tür', tableType: 'Tablo', viewType: 'Görünüm',
    test: 'Oracle Bağlantısını Test Et', testing: 'Test ediliyor…', discover: 'Oracle Şemasını Keşfet', discovering: 'Keşfediliyor…', tableFilter: 'Tablo adı (isteğe bağlı)', limit: 'Tablo sınırı',
    noItems: 'Henüz kayıt yok.', loading: 'Yükleniyor…', loadFailed: 'Veriler yüklenemedi.', tryAgain: 'Yeniden Dene', saveFailed: 'Kayıt oluşturulamadı.',
    chooseConnection: 'Sürümlerini yönetmek için bir bağlantı seçin.', chooseModel: 'Kataloğunu yönetmek için bir model seçin.', chooseVersion: 'Önce bir sürüm seçin.',
    chooseDiscovery: 'Bir bağlantı sürümü ve o bağlantıya ait fiziksel şema seçin.', testSuccess: 'Bağlantı başarılı', compatible: 'Oracle 19c uyumlu', incompatible: 'Oracle 19c uyumlu değil',
    discoveryResults: 'Keşif sonuçları', tables: 'tablo', truncated: 'Sonuç sınırlandı', emptyDiscovery: 'Tablo bulunamadı.', required: 'Zorunlu', optional: 'İsteğe bağlı',
    activeSelection: 'Etkin seçim', details: 'Ayrıntılar', close: 'Kapat', policyVersion: 'Politika sürümü', all: 'Tümü', noSecretValues: 'Burada yalnızca gizli bilgi referansları tutulur. Gizli değerler hiçbir zaman istenmez veya gösterilmez.',
    endpointStep: 'Uç nokta', credentialsStep: 'Kimlik bilgisi', reviewStep: 'Gözden geçir', connectionMode: 'Bağlantı modu',
    jdbcModeHint: 'Platform tarafından yönetilen doğrudan Oracle JDBC bağlantısı', jndiModeHint: 'Uygulama sunucusunun yönettiği yerel DataSource',
    transport: 'Aktarım', connectIdentifier: 'Bağlantı tanımlayıcısı', driverManaged: 'Oracle JDBC sürücüsü ve politika sürümü platform tarafından yönetilir.',
    executionPolicy: 'Bağlantı zaman aşımları', connectTimeout: 'Bağlantı kurma zaman aşımı (ms)', readTimeout: 'Okuma zaman aşımı (ms)', networkTimeout: 'Ağ zaman aşımı (ms)', queryTimeout: 'Sorgu zaman aşımı (saniye)',
    jndiName: 'JNDI adı', localJndiOnly: 'Yalnız yerel java:comp/env/jdbc/ kaynakları kabul edilir. Uzak sağlayıcılar engellenir.',
    credentialSecret: 'Kimlik bilgisi profili', secretRequiredHint: 'JDBC sürümü için yönetilen kimlik bilgisi profili bulunmuyor.',
    containerManaged: 'Container tarafından yönetilen kimlik', containerManagedHint: 'DataSource ve kimlik bilgileri uygulama sunucusuna aittir; Akis yalnızca yerel JNDI adını saklar.',
    endpoint: 'Uç nokta', systemManaged: 'sistem yönetimli', back: 'Geri', continue: 'Devam', createVersion: 'Sürümü Oluştur',
    versionCreated: 'Bağlantı sürümü oluşturuldu', done: 'Tamam', invalidConnectionFields: 'Zorunlu bağlantı alanlarını geçerli değerlerle tamamlayın.',
    jndiRuntimeHint: 'Test için bu JNDI DataSource çalışan uygulama ortamında kayıtlı olmalıdır.',
    jndiExecutionBlocked: 'Bu mod yalnız metadata/test içindir; hedef kimliği sabitleme tamamlanana kadar paket ve prosedür çalıştırması engellidir.',
    tcpsPlanned: 'TCPS · doğrulanmış TLS daha sonra',
    lifecycleDraft: 'Taslak', lifecycleTested: 'Test edildi', lifecycleActive: 'Etkin', notTested: 'Henüz test edilmedi',
    testedAt: 'Test zamanı', activatedAt: 'Etkinleştirme zamanı', latestTestEvidence: 'Son test kanıtı', noTestEvidence: 'Henüz test kanıtı kaydedilmedi.',
    testVersion: 'Sürümü Test Et', testAgain: 'Yeniden Test Et', activateVersion: 'Sürümü Etkinleştir', activating: 'Etkinleştiriliyor…',
    activationPrompt: 'Bu sürümün çalışma zamanında kullanımı onaylansın mı?', activationEvidence: 'Etkinleştirme, son başarılı test kanıtını kullanır.',
    confirmActivation: 'Etkinleştirmeyi Onayla', cancel: 'İptal', versionActivated: 'Bağlantı sürümü etkinleştirildi.',
    activationRequiresTest: 'Etkinleştirmeden önce başarılı bir test gereklidir.', runtimeLimited: 'Çalışma zamanı sınırlı',
    targetFingerprint: 'Hedef parmak izi', revealFingerprint: 'Tam parmak izini göster', hideFingerprint: 'Tam parmak izini gizle',
    copyFingerprint: 'Parmak izini kopyala', fingerprintCopied: 'Parmak izi kopyalandı', targetIdentity: 'Hedef kimliği v{{version}}',
    testPassed: 'Başarılı', testFailed: 'Başarısız', targetMismatch: 'Hedef eşleşmedi', attempt: 'Deneme {{number}}', duration: '{{duration}} ms',
    evidenceLoadFailed: 'Test kanıtı yüklenemedi.', activationFailed: 'Bağlantı sürümü etkinleştirilemedi.',
    activationConflict: 'Sürüm değişti. Yenileyip güncel başarılı test ile yeniden etkinleştirin.', connectionTestFailed: 'Bağlantı testi başarısız oldu.',
    saveSchemaSnapshot: 'Şema Görüntüsünü Kaydet', schemaSnapshot: 'Şema görüntüsü', dataObject: 'Veri nesnesi',
    discoveredAt: 'Keşif zamanı', columns: 'Kolonlar', constraints: 'Kısıtlar', nullable: 'Null olabilir', position: 'Sıra', yes: 'Evet', no: 'Hayır', recommended: 'Önerilen',
    immutableSnapshotHint: 'Bu işlem sunucu tarafından üretilen, değiştirilemez şema kanıtı oluşturur. Kaydedildikten sonra düzenlenemez.',
    confirmSnapshot: 'Onayla ve Kaydet', savingSnapshot: 'Şema görüntüsü kaydediliyor…', snapshotSaved: 'Şema görüntüsü kaydedildi',
    snapshotId: 'Görüntü kimliği', createdAt: 'Oluşturulma zamanı', databaseEngine: 'Veritabanı motoru', loadingDataObjects: 'Veri nesneleri yükleniyor…',
    snapshotReferenceMismatch: 'Seçilen katalog referansı bu sonuçtan farklı. Sunucu, seçilen veri nesnesinin referansını keşfedecek.',
    noCompatibleModels: 'Bu fiziksel şema bağlamına bağlı etkin model bulunamadı.',
    noCompatibleDataObjects: 'Bu modelde kullanılabilir etkin tablo veri nesnesi bulunamadı.', missingProject: 'Bağlantıları açmadan önce bir proje seçin.',
    snapshotObjectsLoadFailed: 'Veri nesneleri yüklenemedi.', snapshotSaveFailed: 'Şema görüntüsü kaydedilemedi.',
  },
} as const

export type CopyKey = keyof typeof copy.en

export function getTopologyCopy(language: string) {
  return language.startsWith('tr') ? copy.tr : copy.en
}
