const copy = {
  en: {
    title: 'Data topology', subtitle: 'Configure database access, schema mappings, and the catalog for this project.',
    connections: 'Connections', schemas: 'Schemas', bindings: 'Bindings', catalog: 'Catalog',
    secretRefs: 'Secret references', versions: 'Connection versions', physical: 'Physical schemas', logical: 'Logical schemas', environments: 'Environments',
    models: 'Models', submodels: 'Submodels', dataObjects: 'Data objects', create: 'Create', creating: 'Creating…', refresh: 'Refresh',
    name: 'Name', code: 'Code', status: 'Status', description: 'Description', actions: 'Actions', select: 'Select', selected: 'Selected',
    provider: 'Provider', referencePath: 'Reference path', versionReference: 'Version reference', databaseType: 'Database type',
    addSecret: 'Add secret reference', addConnection: 'Add connection', addVersion: 'Add version', addPhysical: 'Add physical schema', addLogical: 'Add logical schema', addEnvironment: 'Add environment', addBinding: 'Add binding', addModel: 'Add model', addSubmodel: 'Add submodel', addDataObject: 'Add data object',
    driver: 'Driver reference', host: 'Host', port: 'Port', serviceName: 'Service name', sid: 'SID', tlsMode: 'TLS mode', secret: 'Secret reference', secretRole: 'Secret role',
    connection: 'Connection', version: 'Version', schemaReference: 'Schema reference', logicalSchema: 'Logical schema', physicalSchema: 'Physical schema', environment: 'Environment', risk: 'Risk', riskLow: 'Low', riskMedium: 'Medium', riskProduction: 'Production',
    model: 'Model', parent: 'Parent submodel', submodel: 'Submodel', objectReference: 'Object reference', type: 'Type', tableType: 'Table', viewType: 'View',
    test: 'Test Oracle connection', testing: 'Testing…', discover: 'Discover Oracle schema', discovering: 'Discovering…', tableFilter: 'Table name (optional)', limit: 'Table limit',
    noItems: 'No records yet.', loading: 'Loading…', loadFailed: 'Could not load data.', tryAgain: 'Try again', saveFailed: 'Could not save the record.',
    chooseConnection: 'Select a connection to manage versions.', chooseModel: 'Select a model to manage its catalog.', chooseVersion: 'Select a version first.',
    chooseDiscovery: 'Choose a connection version and a physical schema for that connection.', testSuccess: 'Connection successful', compatible: 'Oracle 19c compatible', incompatible: 'Not Oracle 19c compatible',
    discoveryResults: 'Discovery results', tables: 'tables', truncated: 'Result limited', emptyDiscovery: 'No tables found.', required: 'Required', optional: 'Optional',
    activeSelection: 'Active selection', details: 'Details', close: 'Close', policyVersion: 'Policy version', all: 'All', noSecretValues: 'Only secret references are stored here. Secret values are never requested or displayed.',
    endpointStep: 'Endpoint', credentialsStep: 'Credentials', reviewStep: 'Review', connectionMode: 'Connection mode',
    jdbcModeHint: 'Direct, platform-managed Oracle JDBC connection', jndiModeHint: 'Application-server managed local DataSource',
    transport: 'Transport', connectIdentifier: 'Connect identifier', driverManaged: 'The Oracle JDBC driver and policy version are managed by the platform.',
    jndiName: 'JNDI name', localJndiOnly: 'Only local java:comp/env/jdbc/ resources are accepted. Remote providers are blocked.',
    credentialSecret: 'Credential secret reference', secretRequiredHint: 'Create a credential secret reference before adding a JDBC version.',
    containerManaged: 'Container-managed credentials', containerManagedHint: 'The application server owns the DataSource and its credentials; Akis stores only the local JNDI name.',
    endpoint: 'Endpoint', systemManaged: 'system managed', back: 'Back', continue: 'Continue', createVersion: 'Create version',
    versionCreated: 'Connection version created', done: 'Done', invalidConnectionFields: 'Complete the required connection fields with valid values.',
    jndiRuntimeHint: 'Testing requires this JNDI DataSource to be registered in the running application environment.',
    jndiExecutionBlocked: 'This mode is metadata/test only; package and procedure execution is blocked until target identity pinning is available.',
    tcpsPlanned: 'TCPS · verified TLS coming later',
  },
  tr: {
    title: 'Veri topolojisi', subtitle: 'Bu proje için veritabanı erişimini, şema eşlemelerini ve kataloğu yapılandırın.',
    connections: 'Bağlantılar', schemas: 'Şemalar', bindings: 'Bağlamalar', catalog: 'Katalog',
    secretRefs: 'Gizli bilgi referansları', versions: 'Bağlantı sürümleri', physical: 'Fiziksel şemalar', logical: 'Mantıksal şemalar', environments: 'Ortamlar',
    models: 'Modeller', submodels: 'Alt modeller', dataObjects: 'Veri nesneleri', create: 'Oluştur', creating: 'Oluşturuluyor…', refresh: 'Yenile',
    name: 'Ad', code: 'Kod', status: 'Durum', description: 'Açıklama', actions: 'İşlemler', select: 'Seç', selected: 'Seçili',
    provider: 'Sağlayıcı', referencePath: 'Referans yolu', versionReference: 'Sürüm referansı', databaseType: 'Veritabanı türü',
    addSecret: 'Gizli bilgi referansı ekle', addConnection: 'Bağlantı ekle', addVersion: 'Sürüm ekle', addPhysical: 'Fiziksel şema ekle', addLogical: 'Mantıksal şema ekle', addEnvironment: 'Ortam ekle', addBinding: 'Bağlama ekle', addModel: 'Model ekle', addSubmodel: 'Alt model ekle', addDataObject: 'Veri nesnesi ekle',
    driver: 'Sürücü referansı', host: 'Sunucu', port: 'Port', serviceName: 'Servis adı', sid: 'SID', tlsMode: 'TLS modu', secret: 'Gizli bilgi referansı', secretRole: 'Gizli bilgi rolü',
    connection: 'Bağlantı', version: 'Sürüm', schemaReference: 'Şema referansı', logicalSchema: 'Mantıksal şema', physicalSchema: 'Fiziksel şema', environment: 'Ortam', risk: 'Risk', riskLow: 'Düşük', riskMedium: 'Orta', riskProduction: 'Üretim',
    model: 'Model', parent: 'Üst alt model', submodel: 'Alt model', objectReference: 'Nesne referansı', type: 'Tür', tableType: 'Tablo', viewType: 'Görünüm',
    test: 'Oracle bağlantısını test et', testing: 'Test ediliyor…', discover: 'Oracle şemasını keşfet', discovering: 'Keşfediliyor…', tableFilter: 'Tablo adı (isteğe bağlı)', limit: 'Tablo sınırı',
    noItems: 'Henüz kayıt yok.', loading: 'Yükleniyor…', loadFailed: 'Veriler yüklenemedi.', tryAgain: 'Yeniden dene', saveFailed: 'Kayıt oluşturulamadı.',
    chooseConnection: 'Sürümlerini yönetmek için bir bağlantı seçin.', chooseModel: 'Kataloğunu yönetmek için bir model seçin.', chooseVersion: 'Önce bir sürüm seçin.',
    chooseDiscovery: 'Bir bağlantı sürümü ve o bağlantıya ait fiziksel şema seçin.', testSuccess: 'Bağlantı başarılı', compatible: 'Oracle 19c uyumlu', incompatible: 'Oracle 19c uyumlu değil',
    discoveryResults: 'Keşif sonuçları', tables: 'tablo', truncated: 'Sonuç sınırlandı', emptyDiscovery: 'Tablo bulunamadı.', required: 'Zorunlu', optional: 'İsteğe bağlı',
    activeSelection: 'Etkin seçim', details: 'Ayrıntılar', close: 'Kapat', policyVersion: 'Politika sürümü', all: 'Tümü', noSecretValues: 'Burada yalnızca gizli bilgi referansları tutulur. Gizli değerler hiçbir zaman istenmez veya gösterilmez.',
    endpointStep: 'Uç nokta', credentialsStep: 'Kimlik bilgisi', reviewStep: 'Gözden geçir', connectionMode: 'Bağlantı modu',
    jdbcModeHint: 'Platform tarafından yönetilen doğrudan Oracle JDBC bağlantısı', jndiModeHint: 'Uygulama sunucusunun yönettiği yerel DataSource',
    transport: 'Aktarım', connectIdentifier: 'Bağlantı tanımlayıcısı', driverManaged: 'Oracle JDBC sürücüsü ve politika sürümü platform tarafından yönetilir.',
    jndiName: 'JNDI adı', localJndiOnly: 'Yalnız yerel java:comp/env/jdbc/ kaynakları kabul edilir. Uzak sağlayıcılar engellenir.',
    credentialSecret: 'Kimlik bilgisi secret referansı', secretRequiredHint: 'JDBC sürümü eklemeden önce bir kimlik bilgisi secret referansı oluşturun.',
    containerManaged: 'Container tarafından yönetilen kimlik', containerManagedHint: 'DataSource ve kimlik bilgileri uygulama sunucusuna aittir; Akis yalnızca yerel JNDI adını saklar.',
    endpoint: 'Uç nokta', systemManaged: 'sistem yönetimli', back: 'Geri', continue: 'Devam', createVersion: 'Sürümü oluştur',
    versionCreated: 'Bağlantı sürümü oluşturuldu', done: 'Tamam', invalidConnectionFields: 'Zorunlu bağlantı alanlarını geçerli değerlerle tamamlayın.',
    jndiRuntimeHint: 'Test için bu JNDI DataSource çalışan uygulama ortamında kayıtlı olmalıdır.',
    jndiExecutionBlocked: 'Bu mod yalnız metadata/test içindir; hedef kimliği sabitleme tamamlanana kadar paket ve prosedür çalıştırması engellidir.',
    tcpsPlanned: 'TCPS · doğrulanmış TLS daha sonra',
  },
} as const

export type CopyKey = keyof typeof copy.en

export function getTopologyCopy(language: string) {
  return language.startsWith('tr') ? copy.tr : copy.en
}
