export type PackageStepType = 'MAPPING' | 'PROCEDURE' | 'PACKAGE' | 'VARIABLE_EVALUATE'
export type TransitionOutcome = 'SUCCESS' | 'FAILURE' | 'TRUE' | 'FALSE' | 'ALWAYS'
export interface PackageStep { id: string; type: PackageStepType; name?: string; definitionUuid?: string; x?: number; y?: number }
export interface PackageTransition { fromStepId: string; toStepId: string; outcome?: TransitionOutcome }
export interface PackageContent { firstStepId: string; steps: PackageStep[]; transitions: PackageTransition[]; [key: string]: unknown }

export function isPackageContent(value: unknown): value is PackageContent { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const item = value as Partial<PackageContent>; return typeof item.firstStepId === 'string' && Array.isArray(item.steps) && Array.isArray(item.transitions) }
export function nextPackageStepId(steps: PackageStep[]) { let number = steps.length + 1; while (steps.some((step) => step.id === `STEP_${number}`)) number += 1; return `STEP_${number}` }
export function removePackageStep(content: PackageContent, id: string): PackageContent { return { ...content, firstStepId: content.firstStepId === id ? '' : content.firstStepId, steps: content.steps.filter((step) => step.id !== id), transitions: content.transitions.filter((edge) => edge.fromStepId !== id && edge.toStepId !== id) } }
function semanticStep(step: PackageStep): PackageStep { const semantic = structuredClone(step); delete semantic.x; delete semantic.y; return semantic }
export function duplicatePackageStep(content: PackageContent, id: string): PackageContent { const source = content.steps.find((step) => step.id === id); if (!source) return content; const copy = { ...semanticStep(source), id: nextPackageStepId(content.steps), name: `${source.name ?? source.id} copy` }; return { ...content, steps: [...content.steps, copy] } }
export function withoutPackageLayout(content: PackageContent): PackageContent { return { ...content, steps: content.steps.map(semanticStep) } }
function hasDirectedCycle(steps: PackageStep[], transitions: PackageTransition[]) { const adjacency = new Map<string, string[]>(); for (const step of steps) adjacency.set(step.id, []); for (const edge of transitions) adjacency.get(edge.fromStepId)?.push(edge.toStepId); const visiting = new Set<string>(); const visited = new Set<string>(); const walk = (id: string): boolean => { if (visiting.has(id)) return true; if (visited.has(id)) return false; visiting.add(id); if ((adjacency.get(id) ?? []).some(walk)) return true; visiting.delete(id); visited.add(id); return false }; return steps.some((step) => walk(step.id)) }
export function createsCycle(content: PackageContent, from: string, to: string) { return hasDirectedCycle(content.steps, [...content.transitions, { fromStepId: from, toStepId: to }]) }
export function addPackageTransition(content: PackageContent, transition: PackageTransition) { if (transition.fromStepId === transition.toStepId || createsCycle(content, transition.fromStepId, transition.toStepId)) return null; if (content.transitions.some((edge) => edge.fromStepId === transition.fromStepId && (edge.outcome ?? 'ALWAYS') === (transition.outcome ?? 'ALWAYS'))) return null; return { ...content, transitions: [...content.transitions, transition] } }
export function packageValidation(content: PackageContent) { const errors: string[] = []; if (!content.firstStepId || !content.steps.some((step) => step.id === content.firstStepId)) errors.push('START_REQUIRED'); const ids = new Set<string>(); const stepTypes = new Map<string, PackageStepType>(); for (const step of content.steps) { if (ids.has(step.id)) errors.push('DUPLICATE_ID'); ids.add(step.id); stepTypes.set(step.id, step.type) } const ports = new Set<string>(); for (const edge of content.transitions) { if (!ids.has(edge.fromStepId) || !ids.has(edge.toStepId)) errors.push('MISSING_REFERENCE'); const outcome = edge.outcome ?? 'ALWAYS'; const port = `${edge.fromStepId}:${outcome}`; if (ports.has(port)) errors.push('DUPLICATE_OUTCOME'); ports.add(port); const allowed = stepTypes.get(edge.fromStepId) === 'VARIABLE_EVALUATE' ? new Set<TransitionOutcome>(['TRUE', 'FALSE', 'FAILURE', 'ALWAYS']) : new Set<TransitionOutcome>(['SUCCESS', 'FAILURE', 'ALWAYS']); if (!allowed.has(outcome)) errors.push('INVALID_OUTCOME') } if (hasDirectedCycle(content.steps, content.transitions)) errors.push('CYCLE'); if (content.firstStepId && ids.has(content.firstStepId)) { const adjacency = new Map<string, string[]>(); for (const step of content.steps) adjacency.set(step.id, []); for (const edge of content.transitions) adjacency.get(edge.fromStepId)?.push(edge.toStepId); const reachable = new Set<string>(); const pending = [content.firstStepId]; while (pending.length) { const id = pending.pop()!; if (reachable.has(id)) continue; reachable.add(id); pending.push(...(adjacency.get(id) ?? [])) } if (content.steps.some((step) => !reachable.has(step.id))) errors.push('UNREACHABLE_STEP') } return [...new Set(errors)] }
