import { expect, test, type Locator, type Page } from '@playwright/test'

// Real components/layout, synthetic metadata only. No source/target SQL or persisted edits.
async function mockCatalog(page: Page, newerSourceMetadata = false) {
  await page.route(/\/api\/v\d+\//, async route => {
    const path = new URL(route.request().url()).pathname
    if (path.endsWith('/mapping-expressions/compile')) {
      expect(route.request().method()).toBe('POST')
      const body = route.request().postDataJSON()
      expect(body.sources[0].alias).toBe('SRC_1')
      if (body.predicate === true && body.sql === 'SRC_1.ID > 10') {
        await route.fulfill({ json: { expression: { kind: 'BINARY', operator: '>', left: { kind: 'COLUMN', dataset: 'SOURCE_1', column: 'ID' }, right: { kind: 'LITERAL', value: 10 } }, references: [{ object: 'SOURCE_1', column: 'ID' }] } })
      } else if (body.sql === 'UPPER(SRC_1.NAME)') {
        await route.fulfill({ json: { expression: { kind: 'CALL', function: 'UPPER', args: [{ kind: 'COLUMN', dataset: 'SOURCE_1', column: 'NAME' }] }, references: [{ object: 'SOURCE_1', column: 'NAME' }] } })
      } else await route.fulfill({ status: 422, json: { code: 'MAPPING_EXPRESSION_INVALID', detail: 'Unsupported SQL function' } })
      return
    }
    expect(route.request().method()).toBe('GET')
    let json: unknown = []
    if (path.endsWith('/models')) json = [{ uuid: 'model', code: 'MODEL', name: 'Fixture Model', logicalSchemaUuid: 'logical', status: 'AKTIF', version: 1 }]
    if (path.endsWith('/submodels')) json = [{ uuid: 'folder', parentUuid: null, code: 'REPORTS', name: 'Reports', status: 'ACTIVE', version: 1 }]
    if (path.endsWith('/logical-schemas')) json = [{ uuid: 'logical', name: 'Fixture Schema', code: 'FIXTURE', status: 'AKTIF' }]
    if (path.endsWith('/data-objects')) json = [...['source', 'target'].map(role => ({ uuid: `${role}-object`, modelUuid: 'model', code: role.toUpperCase(), name: `${role} table`, objectReference: `APP.${role.toUpperCase()}`, type: 'TABLE', status: 'AKTIF', version: 1 })),
      { uuid: 'view-object', modelUuid: 'model', submodelUuid: 'folder', code: 'VIEW', name: 'Customer View', objectReference: 'APP.CUSTOMER_VIEW', type: 'VIEW', status: 'AKTIF', version: 1 }]
    if (path.endsWith('/schema-snapshots')) json = [{ uuid: 'snapshot', columns: [
      { reference: 'ID', producerType: 'NUMBER(10,0)', canonicalType: 'INTEGER', ordinal: 1, precision: 10, scale: 0, nullable: false },
      { reference: 'NAME', producerType: 'VARCHAR2(255)', canonicalType: 'STRING', ordinal: 2, length: 255, nullable: true },
    ], constraints: [] }]
    if (newerSourceMetadata && path.endsWith('/source-object/schema-snapshots')) json = [
      { uuid: 'new-snapshot', columns: [
        { reference: 'ID', producerType: 'NUMBER(10,0)', canonicalType: 'INTEGER', ordinal: 1, precision: 10, scale: 0, nullable: false },
        { reference: 'NEW_LABEL', producerType: 'VARCHAR2(500)', canonicalType: 'STRING', ordinal: 2, length: 500, nullable: true },
      ], constraints: [] }, ...(json as unknown[]),
    ]
    await route.fulfill({ json })
  })
}

for (const theme of ['light', 'dark'] as const) test(`mapping suggestions are explicit, invalidated by edits and undoable in ${theme}`, async ({ page }) => {
  await mockCatalog(page)
  await page.addInitScript(mode => localStorage.setItem('akis.theme', mode), theme)
  await page.setViewportSize({ width: 1366, height: 900 })
  await page.goto('/e2e/fixtures/authoring-workbench.html')
  const target = page.locator('.mapping-diagram-card--target')
  await expect(target.getByText('NAME', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Column Mappings', exact: true }).click()
  await page.getByRole('button', { name: 'Suggest Matches', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Apply Suggestions', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Diagram', exact: true }).click()
  await page.getByRole('button', { name: 'Add Source', exact: true }).click()
  await page.getByRole('tab', { name: 'Column Mappings', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Apply Suggestions', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Suggest Matches', exact: true }).click()
  await page.getByRole('button', { name: 'Apply Suggestions', exact: true }).click()
  await page.getByRole('tab', { name: 'Diagram', exact: true }).click()
  await expect(target.getByLabel('Mapped', { exact: true })).toHaveCount(2)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(target.getByLabel('Not mapped', { exact: true })).toHaveCount(1)
  await expect(target.getByLabel('Mapped', { exact: true })).toHaveCount(1)
})

for (const theme of ['light', 'dark'] as const) test(`pinned metadata changes only after an explicit model drop in ${theme}`, async ({ page }) => {
  await mockCatalog(page, true)
  await page.addInitScript(mode => localStorage.setItem('akis.theme', mode), theme)
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/e2e/fixtures/authoring-workbench.html?editor=explorer')
  const source = page.locator('.mapping-diagram-card--source')
  const targetName = page.locator('.mapping-diagram-card--target .mapping-diagram-column[title="NAME · VARCHAR2(255)"]')
  await expect(source.getByText('NAME', { exact: true })).toBeVisible()
  await expect(source.getByText('NEW_LABEL', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('status').filter({ hasText: 'Newer metadata' })).toBeVisible()
  await targetName.click()
  const inspector = page.getByRole('region', { name: 'Column Properties', exact: true })
  await inspector.locator('.mapping-expression-input .cm-content').fill('SRC_1.NAME')
  await inspector.getByRole('button', { name: 'Apply Mapping', exact: true }).click()
  await inspector.getByRole('button', { name: 'Collapse properties' }).click()
  await expect(targetName.getByLabel('Mapped', { exact: true })).toBeVisible()
  const tree = page.locator('.sidebar-model-link')
  await tree.getByRole('treeitem').filter({ has: page.locator('.akis-tree-static-label[title="Models"]') }).locator('.ant-tree-switcher').click()
  await tree.getByRole('treeitem', { name: /Fixture Model/ }).locator('.ant-tree-switcher').click()
  await tree.locator('.akis-tree-static-label[title="source table"]').dragTo(source, { timeout: 8000 })
  await expect(source.getByText('NEW_LABEL', { exact: true })).toBeVisible()
  await expect(source.getByText('NAME', { exact: true })).toHaveCount(0)
  await expect(targetName.getByLabel('Not mapped', { exact: true })).toBeVisible()
  await expect(page.getByRole('status').filter({ hasText: 'Newer metadata' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(source.getByText('NAME', { exact: true })).toBeVisible()
  await expect(targetName.getByLabel('Mapped', { exact: true })).toBeVisible()
  await expect(page.getByRole('status').filter({ hasText: 'Newer metadata' })).toBeVisible()
  await page.screenshot({ path: `test-results/mapping-pinned-metadata-${theme}.png` })
})

test('project and model explorers open only on double click or Enter', async ({ page }) => {
  await mockCatalog(page)
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/e2e/fixtures/authoring-workbench.html?editor=explorer')
  const opened = page.getByLabel('Opened route')
  const object = page.locator('.akis-tree-static-label[aria-label="Customer Load"]')
  await expect(object).toBeVisible()
  await object.click()
  await expect(opened).toBeEmpty()
  await object.dblclick()
  await expect(opened).toHaveText('/project/objects/definitions/mapping')
  await expect(page.getByRole('button', { name: /^Edit:/ })).toHaveCount(0)
  const tree = page.locator('.sidebar-model-link')
  const models = tree.getByRole('treeitem').filter({ has: page.locator('.akis-tree-static-label[title="Models"]') })
  await models.locator('.ant-tree-switcher').click()
  const model = tree.getByRole('treeitem', { name: /Fixture Model/ })
  await model.locator('.akis-tree-static-label').dblclick()
  await expect(opened).toHaveText('/project/models/model')
  await model.locator('.ant-tree-switcher').click()
  const folder = tree.getByRole('treeitem', { name: /Reports/ })
  await folder.locator('.akis-tree-static-label').dblclick()
  await expect(opened).toHaveText('/project/models/model?folder=folder')
  await folder.locator('.ant-tree-switcher').click()
  const view = tree.locator('.akis-tree-static-label').filter({ hasText: 'Customer View' })
  await view.click()
  await expect(opened).toHaveText('/project/models/model?folder=folder')
  await view.press('Enter')
  await expect(opened).toHaveText('/project/models/model?object=view-object')
  await tree.getByRole('button', { name: 'Actions: Customer View' }).click()
  await page.getByRole('menuitem', { name: 'Reverse Engineer' }).click()
  await expect(opened).toHaveText('/project/models/model/import?object=view-object')
  await models.locator('.akis-tree-static-label').dblclick()
  await expect(opened).toHaveText('/project/models/model/import?object=view-object')
  const target = page.locator('.mapping-diagram-card--target')
  await tree.locator('.akis-tree-static-label[title="source table"]').dragTo(target, { timeout: 8000 })
  await page.locator('.mapping-diagram-card--target .mapping-node-title').click()
  const properties = page.getByRole('region', { name: 'Object Properties', exact: true })
  await expect(properties.locator('header strong')).toHaveText('source table')
  await expect(properties.getByText('Fixture Schema', { exact: true })).toBeVisible()
  await properties.getByRole('button', { name: 'Collapse properties' }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('searchbox', { name: 'Search project objects' }).fill('Customer')
  await expect(object).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/explorer-workbench.png' })
})

test('mouse-driven filter palette drop opens column-scoped SQL editor', async ({ page }) => {
  test.setTimeout(25_000)
  await mockCatalog(page)
  await page.setViewportSize({ width: 1366, height: 900 })
  await page.goto('/e2e/fixtures/authoring-workbench.html')
  const source = page.locator('.mapping-diagram-card--source .mapping-diagram-column[title="ID · NUMBER(10,0)"]')
  await page.getByRole('button', { name: 'Filter', exact: true }).dragTo(source, { timeout: 8000 })
  await expect(page.getByRole('dialog', { name: 'Filter Properties' }).locator('.cm-content')).toContainText('SRC_1.ID IS NOT NULL')
  await expect(page.locator('.mapping-operation-node')).toHaveCount(0)
})

// Exercise the browser HTML5 payload/handlers without Windows native drag UI.
// Physical mouse dragging remains a separate manual acceptance check.
async function dispatchColumnDrop(page: Page, source: Locator, target: Locator) {
  const dataTransfer = await page.evaluateHandle(() => new DataTransfer())
  try {
    await source.dispatchEvent('dragstart', { dataTransfer })
    await target.dispatchEvent('dragover', { dataTransfer })
    await target.dispatchEvent('drop', { dataTransfer })
    await source.dispatchEvent('dragend', { dataTransfer })
  } finally { await dataTransfer.dispose() }
}

test('diagram properties replace the redundant object form and restore after resizing', async ({ page }) => {
  await mockCatalog(page)
  await page.setViewportSize({ width: 1366, height: 900 })
  await page.goto('/e2e/fixtures/authoring-workbench.html')
  await expect(page.getByText('Sources and Target', { exact: true })).toHaveCount(0)
  const source = page.getByRole('button', { name: 'Object Properties: SRC_1', exact: true })
  await expect(source).toBeVisible()
  await source.click()
  const panel = page.getByRole('region', { name: 'Object Properties', exact: true })
  await expect(panel.getByText('Fixture Schema')).toBeVisible()
  await panel.getByLabel('Alias', { exact: true }).fill('CUSTOMER')
  await expect(page.getByRole('button', { name: 'Object Properties: CUSTOMER' })).toBeVisible()
  const split = page.locator('.mapping-design-split')
  await panel.getByRole('button', { name: 'Maximize panel' }).click()
  await expect(split).toHaveClass(/inspector-maximized/)
  await panel.getByRole('button', { name: 'Restore panel' }).click()
  await expect(split).not.toHaveClass(/inspector-maximized/)
  const resize = page.getByRole('separator', { name: 'Resize properties panel' })
  const height = Number(await resize.getAttribute('aria-valuenow'))
  await resize.focus()
  await page.keyboard.press('ArrowUp')
  expect(Number(await resize.getAttribute('aria-valuenow'))).toBe(height + 24)
  await panel.getByRole('button', { name: 'Collapse properties' }).click()
  await expect(panel).toHaveCount(0)
  await page.getByRole('button', { name: 'Open Properties' }).click()
  await expect(panel.getByLabel('Alias', { exact: true })).toHaveValue('CUSTOMER')
  await panel.getByRole('button', { name: 'Remove Object' }).click()
  await page.getByRole('button', { name: 'Remove and clear references' }).click()
  await expect(page.getByRole('button', { name: 'Object Properties: CUSTOMER' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Object Properties: CUSTOMER' })).toBeVisible()
  await page.screenshot({ path: 'test-results/interface-object-properties.png' })
})

for (const theme of ['light', 'dark']) test(`mouse-driven column drag maps without panning the canvas in ${theme}`, async ({ page }) => {
  test.setTimeout(25_000)
  await mockCatalog(page)
  await page.addInitScript(mode => localStorage.setItem('akis.theme', mode), theme)
  await page.setViewportSize({ width: 1366, height: 900 })
  await page.goto('/e2e/fixtures/authoring-workbench.html')
  const source = page.locator('.mapping-diagram-card--source .mapping-diagram-column[title="NAME · VARCHAR2(255)"]')
  const target = page.locator('.mapping-diagram-card--target .mapping-diagram-column[title="NAME · VARCHAR2(255)"]')
  await expect(source).toBeInViewport({ ratio: 1 })
  await expect(target).toBeInViewport({ ratio: 1 })
  await source.hover()
  const canvas = page.locator('.react-flow__viewport')
  const transform = await canvas.evaluate(element => getComputedStyle(element).transform)
  const moveTo = async (locator: Locator) => {
    const box = (await locator.boundingBox())!
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2, { steps: 6 })
  }
  // Incompatible targets must be visibly rejected, not silently mapped.
  const sourceId = page.locator('.mapping-diagram-card--source .mapping-diagram-column[title="ID · NUMBER(10,0)"]')
  await moveTo(sourceId)
  await page.mouse.down()
  await moveTo(target)
  await expect(target).toHaveClass(/is-incompatible-target/)
  await page.mouse.up()
  await expect(target.getByLabel('Not mapped', { exact: true })).toBeVisible()
  await expect(target).not.toHaveClass(/is-incompatible-target/)
  // Escape cancels even after a valid target has been highlighted.
  await moveTo(source)
  await page.mouse.down()
  await moveTo(target)
  await expect(target).toHaveClass(/is-drop-target/)
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await expect(target.getByLabel('Not mapped', { exact: true })).toBeVisible()
  await expect(target).not.toHaveClass(/is-drop-target/)
  await source.dragTo(target, { timeout: 8000 })
  await expect(target.getByLabel('Mapped', { exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Column Properties', exact: true })).toHaveCount(0)
  expect(await canvas.evaluate(element => getComputedStyle(element).transform)).toBe(transform)
  expect(await page.evaluate(() => scrollY)).toBe(0)
  await target.click()
  await expect(page.getByRole('region', { name: 'Column Properties', exact: true }).locator('.cm-content')).toContainText('SRC_1.NAME')
})

for (const theme of ['light', 'dark']) {
  test(`filter component drop creates a validated flow node in ${theme} theme`, async ({ page }) => {
    await mockCatalog(page)
    await page.addInitScript(mode => localStorage.setItem('akis.theme', mode), theme)
    await page.setViewportSize({ width: 1366, height: 900 })
    await page.goto('/e2e/fixtures/authoring-workbench.html')
    const sourceId = page.locator('.mapping-diagram-card--source .mapping-diagram-column[title="ID · NUMBER(10,0)"]')
    await expect(sourceId).toBeVisible()
    await expect(page.locator('.react-flow__edge')).toHaveCount(1)
    await expect(page.locator('.mapping-diagram-column .react-flow__handle')).toHaveCount(0)
    await dispatchColumnDrop(page, page.getByRole('button', { name: 'Filter', exact: true }), sourceId)
    const panel = page.getByRole('dialog', { name: 'Filter Properties' })
    const editor = panel.locator('.mapping-expression-input .cm-content')
    await expect(editor).toContainText('SRC_1.ID IS NOT NULL')
    await expect(page.locator('.mapping-operation-node')).toHaveCount(0)
    await editor.fill('SRC_1.ID > 10')
    await panel.getByRole('button', { name: 'Apply Filter' }).click()
    await expect(panel).toHaveCount(0)
    const node = page.getByRole('button', { name: 'Filter · Source', exact: true })
    await expect(node).toContainText('(SRC_1.ID > 10)')
    await expect(page.locator('.react-flow__edge')).toHaveCount(2)
    await expect(sourceId.getByLabel('Mapped', { exact: true })).toBeVisible()
    await page.screenshot({ path: `test-results/filter-flow-${theme}.png` })
    await node.click()
    await expect(editor).toContainText('(SRC_1.ID > 10)')
    await expect(panel.getByRole('button', { name: 'Apply Filter' })).toBeInViewport({ ratio: 1 })
    await panel.getByRole('button', { name: 'Remove Filter', exact: true }).click()
    await expect(page.locator('.mapping-operation-node')).toHaveCount(0)
    await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  })
  test(`free mapping expression offers columns and survives inspector reopen in ${theme} theme`, async ({ page }) => {
    await mockCatalog(page)
    await page.addInitScript(mode => localStorage.setItem('akis.theme', mode), theme)
    await page.setViewportSize({ width: 1366, height: 900 })
    await page.goto('/e2e/fixtures/authoring-workbench.html')
    const targetName = page.locator('.mapping-diagram-card--target .mapping-diagram-column[title="NAME · VARCHAR2(255)"]')
    await targetName.click()
    const inspector = page.getByRole('region', { name: 'Column Properties', exact: true })
    const editor = inspector.locator('.mapping-expression-input .cm-content')
    await editor.fill('SRC_1.ID')
    await inspector.getByRole('button', { name: 'Apply Mapping', exact: true }).click()
    await expect(inspector.getByRole('alert')).toContainText('incompatible for direct mapping')
    await expect(targetName.getByLabel('Not mapped', { exact: true })).toBeVisible()
    await editor.fill('UPPER(SRC_1.')
    await editor.press('Control+Space')
    await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('NAME')
    await editor.press('Escape')
    await editor.fill('UPPER(SRC_1.NAME)')
    await inspector.getByRole('button', { name: 'Apply Mapping', exact: true }).click()
    await expect(targetName.getByLabel('Mapped', { exact: true })).toBeVisible()
    await inspector.getByRole('button', { name: 'Collapse properties' }).click()
    await targetName.click()
    await expect(editor).toContainText('UPPER(SRC_1.NAME)')
    await expect(inspector.getByRole('button', { name: 'Apply Mapping', exact: true })).toBeInViewport({ ratio: 1 })
    await page.screenshot({ path: `test-results/mapping-expression-${theme}.png` })
  })
  test(`HTML5 column drops preserve the canvas and native types in ${theme} theme`, async ({ page }) => {
    await mockCatalog(page)
    await page.addInitScript(mode => localStorage.setItem('akis.theme', mode), theme)
    await page.setViewportSize({ width: 1366, height: 900 })
    await page.goto('/e2e/fixtures/authoring-workbench.html')
    const sourceName = page.locator('.mapping-diagram-card--source .mapping-diagram-column[title="NAME · VARCHAR2(255)"]')
    const targetName = page.locator('.mapping-diagram-card--target .mapping-diagram-column[title="NAME · VARCHAR2(255)"]')
    await expect(sourceName).toBeVisible()
    await sourceName.hover()
    const canvas = page.locator('.react-flow__viewport')
    const transform = await canvas.evaluate(element => getComputedStyle(element).transform)
    await expect(targetName.getByLabel('Not mapped', { exact: true })).toBeVisible()
    await dispatchColumnDrop(page, page.locator('.mapping-diagram-card--source .mapping-diagram-column[title="ID · NUMBER(10,0)"]'), targetName)
    await expect(targetName.getByLabel('Not mapped', { exact: true })).toBeVisible()
    await dispatchColumnDrop(page, sourceName, targetName)
    await expect(targetName.getByLabel('Mapped', { exact: true })).toBeVisible()
    expect(await canvas.evaluate(element => getComputedStyle(element).transform)).toBe(transform)
    expect(await page.evaluate(() => scrollY)).toBe(0)
    await targetName.click()
    const inspector = page.getByRole('region', { name: 'Column Properties', exact: true })
    await expect(inspector.getByText('VARCHAR2(255)', { exact: true })).toBeVisible()
    await expect(inspector.locator('.mapping-expression-input .cm-content')).toContainText('SRC_1.NAME')
    await inspector.getByRole('button', { name: 'Maximize panel' }).click()
    await inspector.getByRole('button', { name: 'Restore panel' }).click()
    await expect(page.locator('.mapping-design-split')).not.toHaveClass(/inspector-maximized/)
    await expect(targetName).toBeInViewport({ ratio: 1 })
    await expect(sourceName).toBeInViewport({ ratio: 1 })
    await page.screenshot({ path: `test-results/mapping-column-properties-${theme}.png` })
  })

  test(`procedure steps and details fit independently in ${theme} theme`, async ({ page }) => {
    await mockCatalog(page)
    await page.addInitScript(mode => localStorage.setItem('akis.theme', mode), theme)
    await page.setViewportSize({ width: 1366, height: 900 })
    await page.goto('/e2e/fixtures/authoring-workbench.html?editor=procedure')
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
    const steps = page.getByRole('region', { name: 'Procedure steps', exact: true })
    const details = page.locator('.procedure-task-editor')
    await expect(steps).toBeVisible()
    await page.getByRole('tab', { name: 'Target Command', exact: true }).click()
    await page.getByRole('button', { name: 'Second step', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Target Command', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(details.locator(':scope > header')).toContainText('Second step')
    for (const height of [900, 768]) {
      await page.setViewportSize({ width: 1366, height })
      await expect.poll(async () => (await steps.boundingBox())!.height).toBeLessThan(300)
      const top = (await steps.boundingBox())!
      const bottom = (await details.boundingBox())!
      expect(bottom.y - top.y - top.height).toBeGreaterThanOrEqual(10)
      expect(bottom.y + bottom.height).toBeLessThanOrEqual(height)
      await expect(page.getByRole('button', { name: 'Second step', exact: true })).toBeInViewport({ ratio: 1 })
      const sql = details.locator('.cm-editor')
      await expect(sql).toBeVisible()
      const editor = (await sql.boundingBox())!
      expect(Math.min(editor.y + editor.height, bottom.y + bottom.height) - Math.max(editor.y, bottom.y)).toBeGreaterThan(80)
      await expect(details.getByRole('button', { name: 'Apply', exact: true })).toBeInViewport({ ratio: 1 })
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    }
    await page.screenshot({ path: `test-results/procedure-workbench-${theme}.png` })
  })
}
