import { test, expect, type Page } from '@playwright/test'
import { login, expectNoHorizontalOverflow } from './fixtures'

async function expandModels(page: Page) {
  const tree = page.locator('.sidebar-model-link')
  const root = tree.getByRole('treeitem').filter({ has: page.locator('.akis-tree-static-label[title="Models"]') })
  if (await root.getAttribute('aria-expanded') !== 'true') await root.locator('.ant-tree-switcher').click()
  const model = tree.getByRole('treeitem').filter({ has: page.locator('.model-tree-model-icon') }).nth(1)
  await expect(model).toBeVisible()
  return model
}

test('connection catalog shares data across card, list and table views and remembers the selection', async ({ page }) => {
  await login(page)
  await page.getByRole('menuitem', { name: 'Connections', exact: true }).click()
  await expect(page).toHaveURL(/\/project\/connections$/)
  await expect(page.locator('.ui-grid-records--card')).toBeVisible()
  const count = await page.locator('.ui-grid-record').count()
  expect(count).toBeGreaterThan(0)
  const cardBox = await page.locator('.ui-grid-record').first().boundingBox()
  expect(cardBox!.height).toBeLessThan(650)
  const connection = page.locator('.ui-grid-record').first()
  await connection.getByRole('button', { name: /^View:/ }).click()
  const detail = page.getByRole('dialog')
  await expect(detail).toBeVisible()
  await expect(page).toHaveURL(/\/project\/connections$/)
  await expect(detail.getByText(/Physical schemas|Fiziksel şemalar/i).first()).toBeVisible()
  await expect(detail.getByText(/Logical schemas|Mantıksal şemalar/i).first()).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(detail).toHaveCount(0)
  await expect(connection.getByRole('button', { name: /^View:/ })).toBeFocused()
  // Focus restoration may scroll to the record; capture sticky headers at the page origin.
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'test-results/connection-cards.png', fullPage: true })
  await page.getByRole('radio', { name: 'List', exact: true }).locator('..').click()
  await expect(page.locator('.ui-grid-records--list')).toBeVisible()
  await expect(page.locator('.connection-inline-test').first()).toBeVisible()
  await expect(page.locator('.ui-grid-record')).toHaveCount(count)
  await page.getByRole('radio', { name: 'Table', exact: true }).locator('..').click()
  await expect(page.locator('.ui-data-grid')).toBeVisible()
  await expect(page.locator('.connection-record-identity')).toHaveCount(count)
  await page.reload()
  await expect(page.getByRole('radio', { name: 'Table', exact: true })).toBeChecked()
  await page.getByRole('radio', { name: 'Cards', exact: true }).locator('..').click()
  await page.setViewportSize({ width: 390, height: 844 })
  await expectNoHorizontalOverflow(page)
  await page.locator('.ui-grid-record').first().getByRole('button', { name: /^View:/ }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  const dialog = page.getByRole('dialog')
  await expect.poll(async () => {
    const settledBox = await dialog.boundingBox()
    return settledBox ? Math.abs(settledBox.x + settledBox.width / 2 - 390 / 2) : Infinity
  }).toBeLessThanOrEqual(3)
  const box = await dialog.boundingBox()
  expect(box!.width).toBeLessThanOrEqual(390)
  await page.keyboard.press('Escape')
})

test('keeps the explorer mounted while opening a datastore and displays its logical schema', async ({ page }) => {
  await login(page)
  await page.getByRole('menuitem', { name: 'Project Objects', exact: true }).click()
  const model = await expandModels(page)
  await model.locator('.ant-tree-switcher').click()
  const object = page.locator('.sidebar-model-link .ant-tree-treenode').filter({ has: page.locator('svg.lucide-table-2') }).first().locator('.ant-tree-node-content-wrapper')
  await expect(object).toBeVisible()
  const explorer = page.locator('.shell-project-explorer')
  await explorer.evaluate((element) => element.setAttribute('data-test-persistent', 'yes'))
  await expect(object.getByRole('button', { name: /^(Edit|Düzenle|View|Görüntüle):/ })).toHaveCount(0)
  await object.locator('.akis-tree-static-label').dblclick()
  await expect(page).toHaveURL(/\/project\/models\/.+\?object=/)
  await expect(explorer).toHaveAttribute('data-test-persistent', 'yes')
  await expect(page.locator('.model-schema-context')).toContainText('Logical Schema')
  await expect(page.locator('.model-object-tree')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Add Folder' })).toBeVisible()
  await expectNoHorizontalOverflow(page)
  await page.screenshot({ path: 'test-results/model-workspace.png', fullPage: true })
})

test('opens reverse engineer from the model tree with resolved source context', async ({ page }) => {
  await login(page)
  await page.getByRole('menuitem', { name: 'Project Objects', exact: true }).click()
  const model = await expandModels(page)
  await model.getByRole('button', { name: /^Actions:/ }).click()
  await page.getByRole('menuitem', { name: 'Reverse Engineer' }).click()
  await expect(page).toHaveURL(/\/project\/models\/.+\/import$/)
  await expect(page.getByRole('heading', { name: 'Reverse Engineer', exact: true })).toBeVisible()
  await expect(page.getByText(/Resolved connection|Çözümlenen bağlantı/)).toBeVisible()
  await expect(page.getByRole('button', { name: /Fetch Objects From Source|Kaynaktan Nesneleri Getir/ })).toBeVisible()
  await expectNoHorizontalOverflow(page)
  await page.screenshot({ path: 'test-results/model-reverse-engineer.png', fullPage: true })
})

test('shared UI catalog uses centered responsive dialogs', async ({ page }) => {
  await login(page)
  await page.goto('/project/ui-kit')
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 900 })
    await page.getByRole('button', { name: 'Open Dialog' }).click()
    const dialog = page.getByRole('dialog')
    // Ant Modal animates from the trigger; validate its settled geometry.
    await expect.poll(async () => {
      const box = await dialog.boundingBox()
      return box ? Math.abs(box.x + box.width / 2 - width / 2) : Infinity
    }).toBeLessThan(3)
    const box = await dialog.boundingBox()
    expect(box!.width).toBeLessThanOrEqual(width)
    await page.screenshot({ path: `test-results/ant-dialog-${width}.png` })
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expectNoHorizontalOverflow(page)
  }
})

test('new modules start with executable language and editable runtime options', async ({ page }) => {
  await login(page)
  await page.goto('/project/objects?createType=KNOWLEDGE_MODULE')
  await expect(page).toHaveURL(/\/project\/objects(?:\?createType=KNOWLEDGE_MODULE)?$/)
  await expect(page.locator('.km-language-editor')).toBeVisible()
  const source = page.getByRole('textbox', { name: 'KM Language Source' })
  await expect(source).toHaveValue(/AKIS_KM\/2\nMODUL IKM/)
  await expect(source).toHaveValue(/TARGET ATOMIC_REPLACE/)
  const firstOption = page.getByRole('group', { name: 'Option 1', exact: true })
  await firstOption.getByLabel('Display Name', { exact: true }).fill('Write Strategy')
  await expect(firstOption.getByLabel('Key', { exact: true })).toHaveValue('WRITE_MODE')
  await page.getByRole('button', { name: 'Add Option', exact: true }).click()
  await expect(page.locator('.km-option-schema fieldset')).toHaveCount(5)
  await page.getByRole('group', { name: 'Option 5', exact: true }).getByLabel('Default', { exact: true }).fill('Example value')
  await expect(source).toHaveValue(/"Example value"/)
  await expectNoHorizontalOverflow(page)
  await page.screenshot({ path: 'test-results/module-editor.png', fullPage: true })
})

test('mapping shows model-backed diagram without horizontal page overflow', async ({ page }) => {
  await login(page)
  await page.goto('/project/objects?createType=MAPPING')
  await expect(page).toHaveURL(/\/project\/objects(?:\?createType=MAPPING)?$/)
  await expect(page.locator('.mapping-diagram')).toBeVisible()
  await expect(page.locator('.mapping-diagram-card')).toHaveCount(2)
  const model = await expandModels(page)
  await model.locator('.ant-tree-switcher').click()
  const object = page.locator('.sidebar-model-link .akis-tree-static-label[draggable="true"]').first()
  await expect(object).toBeVisible()
  await object.dragTo(page.locator('.mapping-diagram-card--source'))
  await object.dragTo(page.locator('.mapping-diagram-card--target'))
  await expect(page.locator('.mapping-diagram-card--source .mapping-diagram-column').first()).toBeVisible()
  await page.locator('.mapping-diagram-card--target .mapping-diagram-column').first().click()
  const inspector = page.locator('.mapping-column-inspector')
  await expect(inspector).toBeVisible()
  await expect(inspector).toContainText(/Logical Schema|Mantıksal Şema/)
  await expect(inspector).toContainText('Data Store')
  await expect(inspector.getByLabel('Data Store Alias')).toBeVisible()
  await expect(page.locator('.mapping-dataset select')).toHaveCount(0)
  await expectNoHorizontalOverflow(page)
  await inspector.scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/mapping-editor.png', fullPage: true })
  await page.getByRole('tab', { name: /Column Mappings|Kolon Eşleşmeleri/ }).click()
  await expect(page.locator('.mapping-grid select')).toHaveCount(0)
})
