import { test, expect } from '@playwright/test'
import { login, navigateInApp, expectNoHorizontalOverflow } from './fixtures'

test('connection catalog shares data across card, list and table views and remembers the selection', async ({ page }) => {
  await login(page)
  await page.getByRole('tab', { name: 'Connections', exact: true }).click()
  await expect(page).toHaveURL(/\/project\/connections$/)
  await expect(page.locator('.ui-collection--card')).toBeVisible()
  const count = await page.locator('.connection-record-card').count()
  expect(count).toBeGreaterThan(0)
  const cardBox = await page.locator('.connection-record-card').first().boundingBox()
  expect(cardBox!.height).toBeLessThan(400)
  const connection = page.locator('.connection-record-card').first()
  await connection.click()
  const detail = page.getByRole('dialog')
  await expect(detail).toBeVisible()
  await expect(page).toHaveURL(/\/project\/connections$/)
  await expect(detail.getByText(/Physical schemas|Fiziksel şemalar/i).first()).toBeVisible()
  await expect(detail.getByText(/Logical schemas|Mantıksal şemalar/i).first()).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(detail).toHaveCount(0)
  await expect(connection).toBeFocused()
  await page.screenshot({ path: 'test-results/connection-cards.png', fullPage: true })
  await page.getByRole('button', { name: 'List', exact: true }).click()
  await expect(page.locator('.ui-collection--list')).toBeVisible()
  await expect(page.locator('.connection-inline-test').first()).toBeVisible()
  await expect(page.locator('.connection-record-card')).toHaveCount(count)
  await page.getByRole('button', { name: 'Table', exact: true }).click()
  await expect(page.locator('.connections-table')).toBeVisible()
  await expect(page.locator('.connection-name-link')).toHaveCount(count)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Table', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Cards', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await expectNoHorizontalOverflow(page)
  await page.locator('.connection-record-card').first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  const box = await page.getByRole('dialog').boundingBox()
  expect(box!.width).toBeLessThanOrEqual(390)
  expect(Math.abs(box!.x + box!.width / 2 - 195)).toBeLessThanOrEqual(5)
  await page.keyboard.press('Escape')
})

test('keeps the explorer mounted while opening a datastore and displays its logical schema', async ({ page }) => {
  await login(page)
  await navigateInApp(page, '/project/objects')
  await page.locator('.sidebar-model-link > .sidebar-folder-action-row > .sidebar-folder-row').click()
  const model = page.locator('.sidebar-model-link .sidebar-folder .sidebar-folder-row').first()
  await expect(model).toBeVisible()
  await model.click()
  const object = page.locator('.model-catalog-tree button').first()
  await expect(object).toBeVisible()
  const explorer = page.locator('.design-explorer')
  await explorer.evaluate((element) => element.setAttribute('data-test-persistent', 'yes'))
  await object.click()
  await expect(page).toHaveURL(/\/project\/models\/.+\?object=/)
  await expect(explorer).toHaveAttribute('data-test-persistent', 'yes')
  await expect(page.locator('.model-schema-context')).toContainText('Logical Schema')
  await expect(page.locator('.model-object-tree')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Add Folder' })).toBeVisible()
  await expectNoHorizontalOverflow(page)
  await page.screenshot({ path: 'test-results/model-workspace.png', fullPage: true })
})

test('shared UI catalog uses centered responsive dialogs', async ({ page }) => {
  await login(page)
  await navigateInApp(page, '/project/ui-kit')
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 900 })
    await page.getByRole('button', { name: 'Open Dialog' }).click()
    const dialog = page.getByRole('dialog')
    const box = await dialog.boundingBox()
    expect(box).not.toBeNull()
    expect(Math.abs(box!.x + box!.width / 2 - width / 2)).toBeLessThan(3)
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expectNoHorizontalOverflow(page)
  }
})

test('module tasks use master/detail and model objects can be expanded without leaving design', async ({ page }) => {
  await login(page)
  await page.goto('/project/objects?createType=KNOWLEDGE_MODULE')
  await expect(page).toHaveURL(/\/project\/objects(?:\?createType=KNOWLEDGE_MODULE)?$/)
  await expect(page.locator('.km-editor')).toBeVisible()
  await page.getByRole('button', { name: 'Add Task', exact: true }).click()
  await page.getByRole('button', { name: 'Add Task', exact: true }).click()
  const rows = page.locator('.km-task-list tbody tr')
  await expect(rows).toHaveCount(2)
  const first = await rows.nth(0).boundingBox()
  const second = await rows.nth(1).boundingBox()
  expect(second!.y).toBeGreaterThanOrEqual(first!.y + first!.height)
  await page.locator('.km-task-detail textarea').fill('SELECT 1 FROM DUAL')
  await page.getByRole('button', { name: 'Move Up', exact: true }).click()
  await expect(page.locator('.km-task-detail textarea')).toHaveValue('SELECT 1 FROM DUAL')
  await page.getByRole('tab', { name: 'Options', exact: true }).click()
  await page.getByRole('button', { name: 'Add Option', exact: true }).click()
  await expect(page.locator('.km-options fieldset')).toHaveCount(1)
  await expectNoHorizontalOverflow(page)
  await page.screenshot({ path: 'test-results/module-editor.png', fullPage: true })
})

test('mapping shows model-backed diagram without horizontal page overflow', async ({ page }) => {
  await login(page)
  await page.goto('/project/objects?createType=MAPPING')
  await expect(page).toHaveURL(/\/project\/objects(?:\?createType=MAPPING)?$/)
  await expect(page.locator('.mapping-diagram')).toBeVisible()
  await expect(page.locator('.mapping-diagram-card')).toHaveCount(2)
  await expectNoHorizontalOverflow(page)
  await page.screenshot({ path: 'test-results/mapping-editor.png', fullPage: true })
})
