SET search_path TO akis, public;

CREATE TABLE baglanti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    saglayici_turu VARCHAR(30) NOT NULL,
    aciklama VARCHAR(2000),
    arsivlenme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_baglanti PRIMARY KEY (id),
    CONSTRAINT uq_baglanti_uuid UNIQUE (uuid),
    CONSTRAINT uq_baglanti_proje_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_baglanti_proje_id UNIQUE (proje_id, id),
    CONSTRAINT ck_baglanti_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_baglanti_ad CHECK (btrim(ad) <> ''),
    CONSTRAINT ck_baglanti_saglayici CHECK (
        saglayici_turu IN ('ORACLE', 'POSTGRESQL', 'MYSQL')
    ),
    CONSTRAINT ck_baglanti_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

CREATE TABLE baglanti_surumu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    baglanti_id BIGINT NOT NULL,
    surum_no INTEGER NOT NULL,
    baglanti_modu VARCHAR(20) NOT NULL,
    surucu_sinifi VARCHAR(500),
    sunucu_adi VARCHAR(500),
    port INTEGER,
    servis_adi VARCHAR(500),
    sid VARCHAR(500),
    veritabani_adi VARCHAR(500),
    jndi_adi VARCHAR(500),
    tls_modu VARCHAR(20) NOT NULL DEFAULT 'DEVRE_DISI',
    baglanti_zaman_asimi_ms INTEGER NOT NULL DEFAULT 10000,
    okuma_zaman_asimi_ms INTEGER NOT NULL DEFAULT 60000,
    ag_zaman_asimi_ms INTEGER NOT NULL DEFAULT 60000,
    sorgu_zaman_asimi_saniye INTEGER NOT NULL DEFAULT 60,
    kullanim_amaci VARCHAR(64),
    durum VARCHAR(20) NOT NULL DEFAULT 'TASLAK',
    hedef_kimlik_surumu INTEGER,
    hedef_parmak_izi VARCHAR(128),
    son_basarili_test_uuid UUID,
    test_edilme_zamani TIMESTAMPTZ,
    etkinlestirilme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_baglanti_surumu PRIMARY KEY (id),
    CONSTRAINT uq_baglanti_surumu_uuid UNIQUE (uuid),
    CONSTRAINT uq_baglanti_surumu_no UNIQUE (baglanti_id, surum_no),
    CONSTRAINT uq_baglanti_surumu_proje_id UNIQUE (proje_id, id),
    CONSTRAINT uq_baglanti_surumu_proje_id_baglanti UNIQUE (proje_id, id, baglanti_id),
    CONSTRAINT fk_baglanti_surumu_baglanti
        FOREIGN KEY (proje_id, baglanti_id) REFERENCES baglanti(proje_id, id),
    CONSTRAINT ck_baglanti_surumu_no CHECK (surum_no > 0),
    CONSTRAINT ck_baglanti_surumu_mod CHECK (baglanti_modu IN ('JDBC', 'JNDI')),
    CONSTRAINT ck_baglanti_surumu_tls CHECK (
        tls_modu IN ('DEVRE_DISI', 'ZORUNLU', 'SERTIFIKA_DOGRULA', 'TAM_DOGRULA')
    ),
    CONSTRAINT ck_baglanti_surumu_zaman_asimlari CHECK (
        baglanti_zaman_asimi_ms BETWEEN 1000 AND 120000
        AND okuma_zaman_asimi_ms BETWEEN 1000 AND 300000
        AND ag_zaman_asimi_ms BETWEEN 1000 AND 300000
        AND sorgu_zaman_asimi_saniye BETWEEN 1 AND 300
    ),
    CONSTRAINT ck_baglanti_surumu_kullanim_amaci CHECK (
        kullanim_amaci IS NULL OR kullanim_amaci ~ '^[A-Z][A-Z0-9_]{0,63}$'
    ),
    CONSTRAINT ck_baglanti_surumu_durum CHECK (
        durum IN ('TASLAK', 'TEST_EDILDI', 'ETKIN', 'KULLANIM_DISI')
    ),
    CONSTRAINT ck_baglanti_surumu_konum CHECK (
        (baglanti_modu = 'JNDI'
            AND jndi_adi IS NOT NULL AND btrim(jndi_adi) <> ''
            AND sunucu_adi IS NULL AND port IS NULL
            AND servis_adi IS NULL AND sid IS NULL AND veritabani_adi IS NULL)
        OR
        (baglanti_modu = 'JDBC'
            AND surucu_sinifi IS NOT NULL AND btrim(surucu_sinifi) <> ''
            AND sunucu_adi IS NOT NULL AND btrim(sunucu_adi) <> ''
            AND port BETWEEN 1 AND 65535
            AND jndi_adi IS NULL
            AND num_nonnulls(servis_adi, sid, veritabani_adi) >= 1)
    ),
    CONSTRAINT ck_baglanti_surumu_yasam CHECK (
        (durum = 'TASLAK' AND son_basarili_test_uuid IS NULL
            AND hedef_kimlik_surumu IS NULL AND hedef_parmak_izi IS NULL
            AND test_edilme_zamani IS NULL AND etkinlestirilme_zamani IS NULL)
        OR (durum = 'TEST_EDILDI' AND son_basarili_test_uuid IS NOT NULL
            AND hedef_kimlik_surumu IS NOT NULL AND hedef_parmak_izi IS NOT NULL
            AND test_edilme_zamani IS NOT NULL AND etkinlestirilme_zamani IS NULL)
        OR (durum = 'ETKIN' AND son_basarili_test_uuid IS NOT NULL
            AND hedef_kimlik_surumu IS NOT NULL AND hedef_parmak_izi IS NOT NULL
            AND test_edilme_zamani IS NOT NULL AND etkinlestirilme_zamani IS NOT NULL)
        OR durum = 'KULLANIM_DISI'
    ),
    CONSTRAINT ck_baglanti_surumu_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

CREATE TABLE baglanti_kimligi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    baglanti_surumu_id BIGINT NOT NULL,
    kullanim_amaci VARCHAR(30) NOT NULL DEFAULT 'VERITABANI',
    kullanici_adi VARCHAR(500),
    gizli_deger_saglayicisi VARCHAR(20) NOT NULL,
    gizli_deger_konumu VARCHAR(1000) NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_baglanti_kimligi PRIMARY KEY (id),
    CONSTRAINT uq_baglanti_kimligi_uuid UNIQUE (uuid),
    CONSTRAINT uq_baglanti_kimligi_amac UNIQUE (baglanti_surumu_id, kullanim_amaci),
    CONSTRAINT fk_baglanti_kimligi_surumu
        FOREIGN KEY (proje_id, baglanti_surumu_id)
        REFERENCES baglanti_surumu(proje_id, id),
    CONSTRAINT ck_baglanti_kimligi_amac CHECK (
        kullanim_amaci IN ('VERITABANI', 'WALLET', 'ISTEMCI_SERTIFIKASI')
    ),
    CONSTRAINT ck_baglanti_kimligi_saglayici CHECK (
        gizli_deger_saglayicisi IN ('ENV', 'VAULT')
    ),
    CONSTRAINT ck_baglanti_kimligi_konum CHECK (btrim(gizli_deger_konumu) <> ''),
    CONSTRAINT ck_baglanti_kimligi_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

CREATE TABLE baglanti_testi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    baglanti_surumu_id BIGINT NOT NULL,
    deneme_no INTEGER NOT NULL,
    sonuc VARCHAR(20) NOT NULL,
    hata_kodu VARCHAR(100),
    urun_adi VARCHAR(500),
    urun_surumu VARCHAR(500),
    surucu_adi VARCHAR(500),
    surucu_surumu VARCHAR(500),
    veritabani_ana_surumu INTEGER,
    veritabani_alt_surumu INTEGER,
    hedef_kimlik_surumu INTEGER,
    hedef_parmak_izi VARCHAR(128),
    baslama_zamani TIMESTAMPTZ NOT NULL,
    tamamlanma_zamani TIMESTAMPTZ NOT NULL,
    sure_milisaniye BIGINT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_baglanti_testi PRIMARY KEY (id),
    CONSTRAINT uq_baglanti_testi_uuid UNIQUE (uuid),
    CONSTRAINT uq_baglanti_testi_deneme UNIQUE (baglanti_surumu_id, deneme_no),
    CONSTRAINT uq_baglanti_testi_surum_uuid UNIQUE (baglanti_surumu_id, uuid),
    CONSTRAINT fk_baglanti_testi_surumu
        FOREIGN KEY (proje_id, baglanti_surumu_id)
        REFERENCES baglanti_surumu(proje_id, id),
    CONSTRAINT ck_baglanti_testi_deneme CHECK (deneme_no > 0),
    CONSTRAINT ck_baglanti_testi_sonuc CHECK (sonuc IN ('BASARILI', 'BASARISIZ')),
    CONSTRAINT ck_baglanti_testi_sure CHECK (
        sure_milisaniye >= 0 AND tamamlanma_zamani >= baslama_zamani
    ),
    CONSTRAINT ck_baglanti_testi_icerik CHECK (
        (sonuc = 'BASARILI' AND hata_kodu IS NULL
            AND urun_adi IS NOT NULL AND urun_surumu IS NOT NULL)
        OR (sonuc = 'BASARISIZ' AND hata_kodu IS NOT NULL)
    ),
    CONSTRAINT ck_baglanti_testi_hedef CHECK (
        (sonuc = 'BASARILI' AND hedef_kimlik_surumu IS NOT NULL
            AND hedef_parmak_izi IS NOT NULL)
        OR sonuc = 'BASARISIZ'
    ),
    CONSTRAINT ck_baglanti_testi_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

ALTER TABLE baglanti_surumu
    ADD CONSTRAINT fk_baglanti_surumu_son_test
    FOREIGN KEY (id, son_basarili_test_uuid)
    REFERENCES baglanti_testi(baglanti_surumu_id, uuid);

CREATE TABLE fiziksel_sema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    baglanti_id BIGINT NOT NULL,
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    sema_adi VARCHAR(500) NOT NULL,
    arsivlenme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_fiziksel_sema PRIMARY KEY (id),
    CONSTRAINT uq_fiziksel_sema_uuid UNIQUE (uuid),
    CONSTRAINT uq_fiziksel_sema_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_fiziksel_sema_ad UNIQUE (baglanti_id, sema_adi),
    CONSTRAINT uq_fiziksel_sema_proje_id_baglanti UNIQUE (proje_id, id, baglanti_id),
    CONSTRAINT fk_fiziksel_sema_baglanti
        FOREIGN KEY (proje_id, baglanti_id) REFERENCES baglanti(proje_id, id),
    CONSTRAINT ck_fiziksel_sema_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_fiziksel_sema_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

CREATE TABLE mantiksal_sema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    arsivlenme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_mantiksal_sema PRIMARY KEY (id),
    CONSTRAINT uq_mantiksal_sema_uuid UNIQUE (uuid),
    CONSTRAINT uq_mantiksal_sema_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_mantiksal_sema_proje_id UNIQUE (proje_id, id),
    CONSTRAINT ck_mantiksal_sema_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_mantiksal_sema_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

CREATE TABLE ortam (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    uretim_mi BOOLEAN NOT NULL DEFAULT FALSE,
    arsivlenme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_ortam PRIMARY KEY (id),
    CONSTRAINT uq_ortam_uuid UNIQUE (uuid),
    CONSTRAINT uq_ortam_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_ortam_proje_id UNIQUE (proje_id, id),
    CONSTRAINT ck_ortam_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_ortam_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

CREATE TABLE sema_eslemesi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    ortam_id BIGINT NOT NULL,
    mantiksal_sema_id BIGINT NOT NULL,
    baglanti_id BIGINT NOT NULL,
    fiziksel_sema_id BIGINT NOT NULL,
    baglanti_surumu_id BIGINT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_sema_eslemesi PRIMARY KEY (id),
    CONSTRAINT uq_sema_eslemesi_uuid UNIQUE (uuid),
    CONSTRAINT uq_sema_eslemesi UNIQUE (ortam_id, mantiksal_sema_id),
    CONSTRAINT fk_sema_eslemesi_ortam
        FOREIGN KEY (proje_id, ortam_id) REFERENCES ortam(proje_id, id),
    CONSTRAINT fk_sema_eslemesi_mantiksal
        FOREIGN KEY (proje_id, mantiksal_sema_id) REFERENCES mantiksal_sema(proje_id, id),
    CONSTRAINT fk_sema_eslemesi_fiziksel
        FOREIGN KEY (proje_id, fiziksel_sema_id, baglanti_id)
        REFERENCES fiziksel_sema(proje_id, id, baglanti_id),
    CONSTRAINT fk_sema_eslemesi_surum
        FOREIGN KEY (proje_id, baglanti_surumu_id, baglanti_id)
        REFERENCES baglanti_surumu(proje_id, id, baglanti_id),
    CONSTRAINT ck_sema_eslemesi_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

CREATE INDEX ix_baglanti_proje ON baglanti(proje_id) WHERE arsivlenme_zamani IS NULL;
CREATE INDEX ix_baglanti_surumu_baglanti ON baglanti_surumu(baglanti_id, surum_no DESC);
CREATE UNIQUE INDEX uq_baglanti_surumu_etkin
    ON baglanti_surumu(baglanti_id)
    WHERE durum = 'ETKIN';
CREATE INDEX ix_baglanti_testi_surum ON baglanti_testi(baglanti_surumu_id, deneme_no DESC);
CREATE INDEX ix_fiziksel_sema_baglanti ON fiziksel_sema(baglanti_id) WHERE arsivlenme_zamani IS NULL;
CREATE INDEX ix_sema_eslemesi_fiziksel ON sema_eslemesi(fiziksel_sema_id);
