SET search_path TO akis, public;

CREATE TABLE klasor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    ust_klasor_id BIGINT,
    amac VARCHAR(30) NOT NULL DEFAULT 'GELISTIRME',
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    arsivlenme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_klasor PRIMARY KEY (id),
    CONSTRAINT uq_klasor_uuid UNIQUE (uuid),
    CONSTRAINT uq_klasor_proje_id UNIQUE (proje_id, id),
    CONSTRAINT uq_klasor_proje_kod UNIQUE (proje_id, kod),
    CONSTRAINT fk_klasor_ust
        FOREIGN KEY (proje_id, ust_klasor_id) REFERENCES klasor(proje_id, id),
    CONSTRAINT ck_klasor_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_klasor_amac CHECK (amac IN ('GELISTIRME', 'MODEL', 'YUKLEME_PLANI')),
    CONSTRAINT ck_klasor_ad CHECK (btrim(ad) <> ''),
    CONSTRAINT ck_klasor_kendi_ustu CHECK (ust_klasor_id IS NULL OR ust_klasor_id <> id),
    CONSTRAINT ck_klasor_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

CREATE INDEX ix_klasor_ust ON klasor(proje_id, ust_klasor_id)
    WHERE arsivlenme_zamani IS NULL;

CREATE FUNCTION klasor_dongusunu_engelle() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.ust_klasor_id IS NULL THEN
        RETURN NEW;
    END IF;
    IF EXISTS (
        WITH RECURSIVE ustler(id) AS (
            SELECT NEW.ust_klasor_id
            UNION ALL
            SELECT k.ust_klasor_id
              FROM akis.klasor k
              JOIN ustler u ON u.id = k.id
             WHERE k.ust_klasor_id IS NOT NULL
               AND k.proje_id = NEW.proje_id
        )
        SELECT 1 FROM ustler WHERE id = NEW.id
    ) THEN
        RAISE EXCEPTION 'Klasör ağacı döngü içeremez.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER trg_klasor_dongu
BEFORE INSERT OR UPDATE OF ust_klasor_id, proje_id ON klasor
FOR EACH ROW EXECUTE FUNCTION klasor_dongusunu_engelle();

CREATE TABLE tanim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT REFERENCES proje(id),
    klasor_id BIGINT,
    kapsam VARCHAR(20) NOT NULL DEFAULT 'PROJE',
    tur VARCHAR(40) NOT NULL,
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    arsivlenme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_tanim PRIMARY KEY (id),
    CONSTRAINT uq_tanim_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_proje_id UNIQUE (proje_id, id),
    CONSTRAINT uq_tanim_proje_kod UNIQUE (proje_id, kod),
    CONSTRAINT ck_tanim_kapsam CHECK (
        (kapsam = 'PROJE' AND proje_id IS NOT NULL)
        OR (kapsam = 'SISTEM' AND proje_id IS NULL AND klasor_id IS NULL)
    ),
    CONSTRAINT ck_tanim_sistem_turu CHECK (
        kapsam = 'PROJE' OR tur IN (
            'DEGISKEN', 'SEQUENCE', 'KULLANICI_FONKSIYONU', 'KNOWLEDGE_MODULE'
        )
    ),
    CONSTRAINT fk_tanim_klasor
        FOREIGN KEY (proje_id, klasor_id) REFERENCES klasor(proje_id, id),
    CONSTRAINT ck_tanim_tur CHECK (tur IN (
        'MAPPING', 'YENIDEN_KULLANILABILIR_MAPPING', 'PAKET', 'PROSEDUR',
        'DEGISKEN', 'SEQUENCE', 'KULLANICI_FONKSIYONU', 'KNOWLEDGE_MODULE',
        'LOAD_PLAN'
    )),
    CONSTRAINT ck_tanim_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_tanim_ad CHECK (btrim(ad) <> ''),
    CONSTRAINT ck_tanim_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

CREATE UNIQUE INDEX uq_tanim_sistem_kod ON tanim(kod) WHERE kapsam = 'SISTEM';

CREATE INDEX ix_tanim_klasor ON tanim(proje_id, klasor_id)
    WHERE arsivlenme_zamani IS NULL;

CREATE TABLE tanim_taslagi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT,
    tanim_id BIGINT NOT NULL REFERENCES tanim(id),
    sema_surumu INTEGER NOT NULL,
    icerik JSONB NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_tanim_taslagi PRIMARY KEY (id),
    CONSTRAINT uq_tanim_taslagi_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_taslagi_tanim UNIQUE (tanim_id),
    CONSTRAINT ck_tanim_taslagi_sema CHECK (sema_surumu > 0),
    CONSTRAINT ck_tanim_taslagi_icerik CHECK (jsonb_typeof(icerik) = 'object'),
    CONSTRAINT ck_tanim_taslagi_audit CHECK (
        versiyon_no > 0
        AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani)
    )
);

CREATE TABLE tanim_surumu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT,
    tanim_id BIGINT NOT NULL REFERENCES tanim(id),
    surum_no INTEGER NOT NULL,
    sema_surumu INTEGER NOT NULL,
    icerik_ozeti CHAR(64) NOT NULL,
    icerik JSONB NOT NULL,
    aciklama VARCHAR(2000),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_tanim_surumu PRIMARY KEY (id),
    CONSTRAINT uq_tanim_surumu_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_surumu_no UNIQUE (tanim_id, surum_no),
    CONSTRAINT uq_tanim_surumu_proje_id UNIQUE (proje_id, id),
    CONSTRAINT ck_tanim_surumu_no CHECK (surum_no > 0 AND sema_surumu > 0),
    CONSTRAINT ck_tanim_surumu_ozet CHECK (icerik_ozeti ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_tanim_surumu_icerik CHECK (jsonb_typeof(icerik) = 'object'),
    CONSTRAINT ck_tanim_surumu_audit CHECK (
        versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL
    )
);

CREATE INDEX ix_tanim_surumu_tanim ON tanim_surumu(tanim_id, surum_no DESC);

CREATE TABLE tanim_bagimliligi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT,
    kaynak_tanim_surumu_id BIGINT NOT NULL,
    hedef_tanim_surumu_id BIGINT NOT NULL,
    iliski_turu VARCHAR(30) NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_tanim_bagimliligi PRIMARY KEY (id),
    CONSTRAINT uq_tanim_bagimliligi_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_bagimliligi UNIQUE (
        kaynak_tanim_surumu_id, hedef_tanim_surumu_id, iliski_turu
    ),
    CONSTRAINT fk_tanim_bagimliligi_kaynak
        FOREIGN KEY (kaynak_tanim_surumu_id) REFERENCES tanim_surumu(id),
    CONSTRAINT fk_tanim_bagimliligi_hedef
        FOREIGN KEY (hedef_tanim_surumu_id) REFERENCES tanim_surumu(id),
    CONSTRAINT ck_tanim_bagimliligi_farkli CHECK (
        kaynak_tanim_surumu_id <> hedef_tanim_surumu_id
    ),
    CONSTRAINT ck_tanim_bagimliligi_tur CHECK (iliski_turu IN (
        'CAGIRIR', 'OKUR', 'YAZAR', 'DEGISKEN_KULLANIR', 'SEQUENCE_KULLANIR',
        'FONKSIYON_KULLANIR', 'MODUL_KULLANIR', 'URETILDI'
    )),
    CONSTRAINT ck_tanim_bagimliligi_audit CHECK (
        versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL
    )
);

CREATE FUNCTION tanim_alt_kaydi_kapsamini_dogrula() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    beklenen_proje_id BIGINT;
BEGIN
    SELECT proje_id INTO STRICT beklenen_proje_id
      FROM akis.tanim WHERE id = NEW.tanim_id;
    IF NEW.proje_id IS DISTINCT FROM beklenen_proje_id THEN
        RAISE EXCEPTION 'Tanım alt kaydı farklı proje kapsamında olamaz.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER trg_tanim_taslagi_kapsam
BEFORE INSERT OR UPDATE OF proje_id, tanim_id ON tanim_taslagi
FOR EACH ROW EXECUTE FUNCTION tanim_alt_kaydi_kapsamini_dogrula();

CREATE TRIGGER trg_tanim_surumu_kapsam
BEFORE INSERT OR UPDATE OF proje_id, tanim_id ON tanim_surumu
FOR EACH ROW EXECUTE FUNCTION tanim_alt_kaydi_kapsamini_dogrula();

CREATE FUNCTION tanim_bagimliligi_kapsamini_dogrula() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    kaynak_proje_id BIGINT;
    hedef_proje_id BIGINT;
BEGIN
    SELECT proje_id INTO STRICT kaynak_proje_id
      FROM akis.tanim_surumu WHERE id = NEW.kaynak_tanim_surumu_id;
    SELECT proje_id INTO STRICT hedef_proje_id
      FROM akis.tanim_surumu WHERE id = NEW.hedef_tanim_surumu_id;
    IF kaynak_proje_id IS DISTINCT FROM hedef_proje_id
       OR NEW.proje_id IS DISTINCT FROM kaynak_proje_id THEN
        RAISE EXCEPTION 'Tanım bağımlılığı farklı proje kapsamında olamaz.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER trg_tanim_bagimliligi_kapsam
BEFORE INSERT OR UPDATE OF proje_id, kaynak_tanim_surumu_id, hedef_tanim_surumu_id
ON tanim_bagimliligi
FOR EACH ROW EXECUTE FUNCTION tanim_bagimliligi_kapsamini_dogrula();

CREATE FUNCTION degismez_tanim_kaydini_koru() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Çalıştırılabilir tanım kanıtı değiştirilemez.' USING ERRCODE = '55000';
END
$$;

CREATE TRIGGER trg_tanim_surumu_degismez
BEFORE UPDATE OR DELETE ON tanim_surumu
FOR EACH ROW EXECUTE FUNCTION degismez_tanim_kaydini_koru();

CREATE TRIGGER trg_tanim_bagimliligi_degismez
BEFORE UPDATE OR DELETE ON tanim_bagimliligi
FOR EACH ROW EXECUTE FUNCTION degismez_tanim_kaydini_koru();
