SET search_path TO akis, public;

CREATE TABLE model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    mantiksal_sema_id BIGINT NOT NULL,
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    arsivlenme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_model PRIMARY KEY (id),
    CONSTRAINT uq_model_uuid UNIQUE (uuid),
    CONSTRAINT uq_model_proje_kod UNIQUE (proje_id, kod),
    CONSTRAINT uq_model_proje_id UNIQUE (proje_id, id),
    CONSTRAINT fk_model_mantiksal_sema FOREIGN KEY (proje_id, mantiksal_sema_id)
        REFERENCES mantiksal_sema(proje_id, id),
    CONSTRAINT ck_model_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_model_audit CHECK (versiyon_no > 0 AND
        (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani))
);

CREATE TABLE alt_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    model_id BIGINT NOT NULL,
    ust_alt_model_id BIGINT,
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    arsivlenme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_alt_model PRIMARY KEY (id),
    CONSTRAINT uq_alt_model_uuid UNIQUE (uuid),
    CONSTRAINT uq_alt_model_proje_id UNIQUE (proje_id, id),
    CONSTRAINT uq_alt_model_kod UNIQUE NULLS NOT DISTINCT (model_id, ust_alt_model_id, kod),
    CONSTRAINT fk_alt_model_model FOREIGN KEY (proje_id, model_id) REFERENCES model(proje_id, id),
    CONSTRAINT fk_alt_model_ust FOREIGN KEY (proje_id, ust_alt_model_id) REFERENCES alt_model(proje_id, id),
    CONSTRAINT ck_alt_model_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_alt_model_kendi_ustu CHECK (ust_alt_model_id IS NULL OR ust_alt_model_id <> id),
    CONSTRAINT ck_alt_model_audit CHECK (versiyon_no > 0 AND
        (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani))
);

CREATE TABLE veri_nesnesi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    model_id BIGINT NOT NULL,
    alt_model_id BIGINT,
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    nesne_referansi VARCHAR(1000) NOT NULL,
    tur VARCHAR(20) NOT NULL,
    sorgu_sema_surumu INTEGER,
    sorgu_tanimi JSONB,
    arsivlenme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_veri_nesnesi PRIMARY KEY (id),
    CONSTRAINT uq_veri_nesnesi_uuid UNIQUE (uuid),
    CONSTRAINT uq_veri_nesnesi_model_kod UNIQUE (model_id, kod),
    CONSTRAINT uq_veri_nesnesi_proje_id UNIQUE (proje_id, id),
    CONSTRAINT fk_veri_nesnesi_model FOREIGN KEY (proje_id, model_id) REFERENCES model(proje_id, id),
    CONSTRAINT fk_veri_nesnesi_alt_model FOREIGN KEY (proje_id, alt_model_id) REFERENCES alt_model(proje_id, id),
    CONSTRAINT ck_veri_nesnesi_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_veri_nesnesi_tur CHECK (tur IN ('TABLO', 'GORUNUM', 'SORGU')),
    CONSTRAINT ck_veri_nesnesi_sorgu CHECK (
        (tur = 'SORGU' AND sorgu_sema_surumu > 0 AND jsonb_typeof(sorgu_tanimi) = 'object') OR
        (tur <> 'SORGU' AND sorgu_sema_surumu IS NULL AND sorgu_tanimi IS NULL)),
    CONSTRAINT ck_veri_nesnesi_audit CHECK (versiyon_no > 0 AND
        (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani))
);

CREATE TABLE sema_goruntusu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    veri_nesnesi_id BIGINT NOT NULL,
    fiziksel_sema_id BIGINT NOT NULL,
    baglanti_id BIGINT NOT NULL,
    baglanti_surumu_id BIGINT NOT NULL,
    parmak_izi CHAR(64) NOT NULL,
    motor_surumu VARCHAR(500) NOT NULL,
    kesif_zamani TIMESTAMPTZ NOT NULL,
    ozellik_sema_surumu INTEGER NOT NULL DEFAULT 1,
    ozellik JSONB NOT NULL DEFAULT '{}'::jsonb,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_sema_goruntusu PRIMARY KEY (id),
    CONSTRAINT uq_sema_goruntusu_uuid UNIQUE (uuid),
    CONSTRAINT uq_sema_goruntusu_icerik UNIQUE
        (veri_nesnesi_id, fiziksel_sema_id, baglanti_surumu_id, parmak_izi),
    CONSTRAINT uq_sema_goruntusu_proje_id UNIQUE (proje_id, id),
    CONSTRAINT fk_sema_goruntusu_nesne FOREIGN KEY (proje_id, veri_nesnesi_id)
        REFERENCES veri_nesnesi(proje_id, id),
    CONSTRAINT fk_sema_goruntusu_fiziksel FOREIGN KEY (proje_id, fiziksel_sema_id, baglanti_id)
        REFERENCES fiziksel_sema(proje_id, id, baglanti_id),
    CONSTRAINT fk_sema_goruntusu_surum FOREIGN KEY (proje_id, baglanti_surumu_id, baglanti_id)
        REFERENCES baglanti_surumu(proje_id, id, baglanti_id),
    CONSTRAINT ck_sema_goruntusu_parmak_izi CHECK (parmak_izi ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_sema_goruntusu_ozellik CHECK
        (ozellik_sema_surumu > 0 AND jsonb_typeof(ozellik) = 'object'),
    CONSTRAINT ck_sema_goruntusu_audit CHECK
        (versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE kolon_goruntusu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    sema_goruntusu_id BIGINT NOT NULL,
    kolon_referansi VARCHAR(500) NOT NULL,
    ad VARCHAR(500) NOT NULL,
    uretici_tipi VARCHAR(500) NOT NULL,
    kanonik_tip VARCHAR(40) NOT NULL,
    sira_no INTEGER NOT NULL,
    hassasiyet INTEGER,
    olcek INTEGER,
    uzunluk BIGINT,
    zaman_hassasiyeti INTEGER,
    null_olabilir BOOLEAN NOT NULL,
    varsayilan_ifade TEXT,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_kolon_goruntusu PRIMARY KEY (id),
    CONSTRAINT uq_kolon_goruntusu_uuid UNIQUE (uuid),
    CONSTRAINT uq_kolon_goruntusu_ref UNIQUE (sema_goruntusu_id, kolon_referansi),
    CONSTRAINT uq_kolon_goruntusu_sira UNIQUE (sema_goruntusu_id, sira_no),
    CONSTRAINT uq_kolon_goruntusu_proje_id UNIQUE (proje_id, id),
    CONSTRAINT fk_kolon_goruntusu_sema FOREIGN KEY (proje_id, sema_goruntusu_id)
        REFERENCES sema_goruntusu(proje_id, id),
    CONSTRAINT ck_kolon_goruntusu_sira CHECK (sira_no > 0),
    CONSTRAINT ck_kolon_goruntusu_sayilar CHECK ((uzunluk IS NULL OR uzunluk >= 0)
        AND (hassasiyet IS NULL OR hassasiyet >= 0)
        AND (zaman_hassasiyeti IS NULL OR zaman_hassasiyeti >= 0)),
    CONSTRAINT ck_kolon_goruntusu_audit CHECK
        (versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE kisit_goruntusu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    sema_goruntusu_id BIGINT NOT NULL,
    dis_referans VARCHAR(1000) NOT NULL,
    ad VARCHAR(500) NOT NULL,
    tur VARCHAR(20) NOT NULL,
    etkin_mi BOOLEAN NOT NULL DEFAULT TRUE,
    ayrinti_sema_surumu INTEGER NOT NULL DEFAULT 1,
    ayrinti JSONB NOT NULL DEFAULT '{}'::jsonb,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_kisit_goruntusu PRIMARY KEY (id),
    CONSTRAINT uq_kisit_goruntusu_uuid UNIQUE (uuid),
    CONSTRAINT uq_kisit_goruntusu_ref UNIQUE (sema_goruntusu_id, dis_referans),
    CONSTRAINT uq_kisit_goruntusu_proje_id UNIQUE (proje_id, id),
    CONSTRAINT fk_kisit_goruntusu_sema FOREIGN KEY (proje_id, sema_goruntusu_id)
        REFERENCES sema_goruntusu(proje_id, id),
    CONSTRAINT ck_kisit_goruntusu_tur CHECK (tur IN ('BIRINCIL_ANAHTAR', 'BENZERSIZ', 'YABANCI_ANAHTAR', 'KONTROL')),
    CONSTRAINT ck_kisit_goruntusu_ayrinti CHECK
        (ayrinti_sema_surumu > 0 AND jsonb_typeof(ayrinti) = 'object'),
    CONSTRAINT ck_kisit_goruntusu_audit CHECK
        (versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE kisit_kolonu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    kisit_goruntusu_id BIGINT NOT NULL,
    kolon_goruntusu_id BIGINT NOT NULL,
    sira_no INTEGER NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_kisit_kolonu PRIMARY KEY (id),
    CONSTRAINT uq_kisit_kolonu_uuid UNIQUE (uuid),
    CONSTRAINT uq_kisit_kolonu_sira UNIQUE (kisit_goruntusu_id, sira_no),
    CONSTRAINT uq_kisit_kolonu_kolon UNIQUE (kisit_goruntusu_id, kolon_goruntusu_id),
    CONSTRAINT fk_kisit_kolonu_kisit FOREIGN KEY (proje_id, kisit_goruntusu_id)
        REFERENCES kisit_goruntusu(proje_id, id),
    CONSTRAINT fk_kisit_kolonu_kolon FOREIGN KEY (proje_id, kolon_goruntusu_id)
        REFERENCES kolon_goruntusu(proje_id, id),
    CONSTRAINT ck_kisit_kolonu_sira CHECK (sira_no > 0),
    CONSTRAINT ck_kisit_kolonu_audit CHECK
        (versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE sema_goruntusu_oracle_kaniti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    sema_goruntusu_id BIGINT NOT NULL,
    baglanti_id BIGINT NOT NULL,
    baglanti_surumu_id BIGINT NOT NULL,
    basarili_baglanti_testi_uuid UUID NOT NULL,
    hedef_kimlik_surumu INTEGER NOT NULL,
    hedef_parmak_izi CHAR(64) NOT NULL,
    yakalama_sozlesmesi_surumu INTEGER NOT NULL DEFAULT 1,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_sema_goruntusu_oracle_kaniti PRIMARY KEY (id),
    CONSTRAINT uq_sema_goruntusu_oracle_kaniti_uuid UNIQUE (uuid),
    CONSTRAINT uq_sema_goruntusu_oracle_kaniti_goruntu UNIQUE (sema_goruntusu_id),
    CONSTRAINT fk_oracle_kaniti_goruntu FOREIGN KEY (proje_id, sema_goruntusu_id)
        REFERENCES sema_goruntusu(proje_id, id),
    CONSTRAINT fk_oracle_kaniti_baglanti FOREIGN KEY (proje_id, baglanti_id)
        REFERENCES baglanti(proje_id, id),
    CONSTRAINT fk_oracle_kaniti_surum FOREIGN KEY (proje_id, baglanti_surumu_id, baglanti_id)
        REFERENCES baglanti_surumu(proje_id, id, baglanti_id),
    CONSTRAINT fk_oracle_kaniti_test FOREIGN KEY (baglanti_surumu_id, basarili_baglanti_testi_uuid)
        REFERENCES baglanti_testi(baglanti_surumu_id, uuid),
    CONSTRAINT ck_oracle_kaniti_hedef CHECK (hedef_kimlik_surumu > 0 AND hedef_parmak_izi ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_oracle_kaniti_sozlesme CHECK (yakalama_sozlesmesi_surumu > 0),
    CONSTRAINT ck_oracle_kaniti_audit CHECK
        (versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE tanim_veri_nesnesi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    tanim_surumu_id BIGINT NOT NULL,
    veri_nesnesi_id BIGINT NOT NULL,
    sema_goruntusu_id BIGINT NOT NULL,
    dugum_kodu VARCHAR(100) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_tanim_veri_nesnesi PRIMARY KEY (id),
    CONSTRAINT uq_tanim_veri_nesnesi_uuid UNIQUE (uuid),
    CONSTRAINT uq_tanim_veri_nesnesi_dugum UNIQUE (tanim_surumu_id, dugum_kodu),
    CONSTRAINT uq_tanim_veri_nesnesi_proje_id UNIQUE (proje_id, id),
    CONSTRAINT fk_tanim_veri_nesnesi_surumu FOREIGN KEY (proje_id, tanim_surumu_id)
        REFERENCES tanim_surumu(proje_id, id),
    CONSTRAINT fk_tanim_veri_nesnesi_nesne FOREIGN KEY (proje_id, veri_nesnesi_id)
        REFERENCES veri_nesnesi(proje_id, id),
    CONSTRAINT fk_tanim_veri_nesnesi_goruntu FOREIGN KEY (proje_id, sema_goruntusu_id)
        REFERENCES sema_goruntusu(proje_id, id),
    CONSTRAINT ck_tanim_veri_nesnesi_rol CHECK (rol IN ('KAYNAK', 'HEDEF')),
    CONSTRAINT ck_tanim_veri_nesnesi_dugum CHECK (dugum_kodu ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_tanim_veri_nesnesi_audit CHECK
        (versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE FUNCTION katalog_alt_model_dongusunu_engelle() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.ust_alt_model_id IS NOT NULL AND EXISTS (
        WITH RECURSIVE ustler(id) AS (
            SELECT NEW.ust_alt_model_id UNION ALL
            SELECT a.ust_alt_model_id FROM akis.alt_model a JOIN ustler u ON u.id = a.id
             WHERE a.ust_alt_model_id IS NOT NULL AND a.proje_id = NEW.proje_id
        ) SELECT 1 FROM ustler WHERE id = NEW.id
    ) THEN RAISE EXCEPTION 'Alt model ağacı döngü içeremez.' USING ERRCODE = '23514'; END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_alt_model_dongu BEFORE INSERT OR UPDATE OF ust_alt_model_id, proje_id ON alt_model
FOR EACH ROW EXECUTE FUNCTION katalog_alt_model_dongusunu_engelle();

CREATE FUNCTION katalog_iliski_dogrula() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE goruntu_nesne_id BIGINT; goruntu_surum_id BIGINT; test_sonucu VARCHAR(20);
BEGIN
    IF TG_TABLE_NAME = 'tanim_veri_nesnesi' THEN
        SELECT veri_nesnesi_id INTO STRICT goruntu_nesne_id FROM akis.sema_goruntusu WHERE id = NEW.sema_goruntusu_id;
        IF goruntu_nesne_id <> NEW.veri_nesnesi_id THEN
            RAISE EXCEPTION 'Şema görüntüsü seçilen veri nesnesine ait değildir.' USING ERRCODE = '23514';
        END IF;
    ELSE
        SELECT baglanti_surumu_id INTO STRICT goruntu_surum_id FROM akis.sema_goruntusu WHERE id = NEW.sema_goruntusu_id;
        SELECT sonuc INTO STRICT test_sonucu FROM akis.baglanti_testi
         WHERE baglanti_surumu_id = NEW.baglanti_surumu_id AND uuid = NEW.basarili_baglanti_testi_uuid;
        IF goruntu_surum_id <> NEW.baglanti_surumu_id OR test_sonucu <> 'BASARILI' THEN
            RAISE EXCEPTION 'Oracle kanıtı başarılı test ve görüntü sürümüyle eşleşmelidir.' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_tanim_veri_nesnesi_dogrula BEFORE INSERT OR UPDATE ON tanim_veri_nesnesi
FOR EACH ROW EXECUTE FUNCTION katalog_iliski_dogrula();
CREATE TRIGGER trg_oracle_kaniti_dogrula BEFORE INSERT OR UPDATE ON sema_goruntusu_oracle_kaniti
FOR EACH ROW EXECUTE FUNCTION katalog_iliski_dogrula();

CREATE FUNCTION degismez_katalog_kanitini_koru() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Katalog kanıtı değiştirilemez.' USING ERRCODE = '55000'; END $$;
CREATE TRIGGER trg_sema_goruntusu_degismez BEFORE UPDATE OR DELETE ON sema_goruntusu
FOR EACH ROW EXECUTE FUNCTION degismez_katalog_kanitini_koru();
CREATE TRIGGER trg_kolon_goruntusu_degismez BEFORE UPDATE OR DELETE ON kolon_goruntusu
FOR EACH ROW EXECUTE FUNCTION degismez_katalog_kanitini_koru();
CREATE TRIGGER trg_kisit_goruntusu_degismez BEFORE UPDATE OR DELETE ON kisit_goruntusu
FOR EACH ROW EXECUTE FUNCTION degismez_katalog_kanitini_koru();
CREATE TRIGGER trg_kisit_kolonu_degismez BEFORE UPDATE OR DELETE ON kisit_kolonu
FOR EACH ROW EXECUTE FUNCTION degismez_katalog_kanitini_koru();
CREATE TRIGGER trg_oracle_kaniti_degismez BEFORE UPDATE OR DELETE ON sema_goruntusu_oracle_kaniti
FOR EACH ROW EXECUTE FUNCTION degismez_katalog_kanitini_koru();
CREATE TRIGGER trg_tanim_veri_nesnesi_degismez BEFORE UPDATE OR DELETE ON tanim_veri_nesnesi
FOR EACH ROW EXECUTE FUNCTION degismez_katalog_kanitini_koru();

CREATE INDEX ix_sema_goruntusu_nesne ON sema_goruntusu(proje_id, veri_nesnesi_id, kesif_zamani DESC);
CREATE INDEX ix_tanim_veri_nesnesi_surumu ON tanim_veri_nesnesi(proje_id, tanim_surumu_id);
