SET search_path TO akis, public;

CREATE TABLE dogrulama (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    tanim_surumu_id BIGINT NOT NULL,
    ortam_id BIGINT,
    icerik_ozeti CHAR(64) NOT NULL,
    sonuc VARCHAR(20) NOT NULL,
    hata_sayisi INTEGER NOT NULL DEFAULT 0,
    uyari_sayisi INTEGER NOT NULL DEFAULT 0,
    sonuc_sema_surumu INTEGER NOT NULL DEFAULT 1,
    sonuc_ayrintisi JSONB NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_dogrulama PRIMARY KEY (id),
    CONSTRAINT uq_dogrulama_uuid UNIQUE (uuid),
    CONSTRAINT uq_dogrulama_proje_id UNIQUE (proje_id, id),
    CONSTRAINT fk_dogrulama_tanim_surumu FOREIGN KEY (proje_id, tanim_surumu_id)
        REFERENCES tanim_surumu(proje_id, id),
    CONSTRAINT fk_dogrulama_ortam FOREIGN KEY (proje_id, ortam_id) REFERENCES ortam(proje_id, id),
    CONSTRAINT ck_dogrulama_ozet CHECK (icerik_ozeti ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_dogrulama_sonuc CHECK (sonuc IN ('GECTI', 'UYARI', 'BLOKE')),
    CONSTRAINT ck_dogrulama_sayilar CHECK (hata_sayisi >= 0 AND uyari_sayisi >= 0),
    CONSTRAINT ck_dogrulama_ayrinti CHECK
        (sonuc_sema_surumu > 0 AND jsonb_typeof(sonuc_ayrintisi) = 'object'),
    CONSTRAINT ck_dogrulama_audit CHECK
        (versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE senaryo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    tanim_surumu_id BIGINT NOT NULL,
    dogrulama_id BIGINT NOT NULL,
    surum_no INTEGER NOT NULL,
    plan_sema_surumu INTEGER NOT NULL,
    plan_ozeti CHAR(64) NOT NULL,
    plan JSONB NOT NULL,
    parametre_semasi JSONB NOT NULL DEFAULT '{}'::jsonb,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_senaryo PRIMARY KEY (id),
    CONSTRAINT uq_senaryo_uuid UNIQUE (uuid),
    CONSTRAINT uq_senaryo_surum UNIQUE (tanim_surumu_id, surum_no),
    CONSTRAINT uq_senaryo_plan UNIQUE (tanim_surumu_id, plan_ozeti),
    CONSTRAINT uq_senaryo_proje_id UNIQUE (proje_id, id),
    CONSTRAINT fk_senaryo_tanim_surumu FOREIGN KEY (proje_id, tanim_surumu_id)
        REFERENCES tanim_surumu(proje_id, id),
    CONSTRAINT fk_senaryo_dogrulama FOREIGN KEY (proje_id, dogrulama_id)
        REFERENCES dogrulama(proje_id, id),
    CONSTRAINT ck_senaryo_no CHECK (surum_no > 0 AND plan_sema_surumu > 0),
    CONSTRAINT ck_senaryo_ozet CHECK (plan_ozeti ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_senaryo_json CHECK
        (jsonb_typeof(plan) = 'object' AND jsonb_typeof(parametre_semasi) = 'object'),
    CONSTRAINT ck_senaryo_audit CHECK
        (versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE FUNCTION senaryo_kanitini_dogrula() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE dogrulama_surumu_id BIGINT; dogrulama_ozeti CHAR(64); kaynak_ozeti CHAR(64); dogrulama_sonucu VARCHAR(20);
BEGIN
    SELECT tanim_surumu_id, icerik_ozeti, sonuc INTO STRICT
        dogrulama_surumu_id, dogrulama_ozeti, dogrulama_sonucu
      FROM akis.dogrulama WHERE id = NEW.dogrulama_id;
    SELECT icerik_ozeti INTO STRICT kaynak_ozeti FROM akis.tanim_surumu WHERE id = NEW.tanim_surumu_id;
    IF dogrulama_surumu_id <> NEW.tanim_surumu_id OR dogrulama_ozeti <> kaynak_ozeti
       OR dogrulama_sonucu = 'BLOKE' THEN
        RAISE EXCEPTION 'Senaryo yalnız aynı ve başarılı doğrulama kanıtından üretilebilir.' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_senaryo_kaniti BEFORE INSERT OR UPDATE ON senaryo
FOR EACH ROW EXECUTE FUNCTION senaryo_kanitini_dogrula();

CREATE FUNCTION degismez_senaryo_kanitini_koru() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Doğrulama ve senaryo kanıtı değiştirilemez.' USING ERRCODE = '55000'; END $$;
CREATE TRIGGER trg_dogrulama_degismez BEFORE UPDATE OR DELETE ON dogrulama
FOR EACH ROW EXECUTE FUNCTION degismez_senaryo_kanitini_koru();
CREATE TRIGGER trg_senaryo_degismez BEFORE UPDATE OR DELETE ON senaryo
FOR EACH ROW EXECUTE FUNCTION degismez_senaryo_kanitini_koru();

CREATE INDEX ix_senaryo_tanim_surumu ON senaryo(proje_id, tanim_surumu_id, surum_no DESC);
