SET search_path TO akis, public;

CREATE TABLE yayin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    senaryo_id BIGINT NOT NULL,
    ortam_id BIGINT NOT NULL,
    yayin_no INTEGER NOT NULL,
    durum VARCHAR(20) NOT NULL DEFAULT 'ONAY_BEKLIYOR',
    bagimlilik_ozeti TEXT NOT NULL,
    fiziksel_manifesto JSONB NOT NULL,
    etkinlestirilme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_yayin PRIMARY KEY (id),
    CONSTRAINT uq_yayin_uuid UNIQUE (uuid),
    CONSTRAINT uq_yayin_no UNIQUE (senaryo_id, ortam_id, yayin_no),
    CONSTRAINT uq_yayin_proje_id UNIQUE (proje_id, id),
    CONSTRAINT fk_yayin_senaryo FOREIGN KEY (proje_id, senaryo_id) REFERENCES senaryo(proje_id, id),
    CONSTRAINT fk_yayin_ortam FOREIGN KEY (proje_id, ortam_id) REFERENCES ortam(proje_id, id),
    CONSTRAINT ck_yayin_no CHECK (yayin_no > 0),
    CONSTRAINT ck_yayin_durum CHECK (durum IN ('ONAY_BEKLIYOR', 'AKTIF', 'ASKIDA', 'IPTAL')),
    CONSTRAINT ck_yayin_ozet CHECK (btrim(bagimlilik_ozeti) <> ''),
    CONSTRAINT ck_yayin_manifesto CHECK (jsonb_typeof(fiziksel_manifesto) = 'object'),
    CONSTRAINT ck_yayin_etkinlik CHECK (
        (durum = 'ONAY_BEKLIYOR' AND etkinlestirilme_zamani IS NULL)
        OR (durum IN ('AKTIF', 'ASKIDA', 'IPTAL'))),
    CONSTRAINT ck_yayin_audit CHECK (versiyon_no > 0 AND
        (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani))
);

CREATE TABLE yayin_veri_bagi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    yayin_id BIGINT NOT NULL,
    tanim_veri_nesnesi_id BIGINT NOT NULL,
    sema_eslemesi_id BIGINT NOT NULL,
    fiziksel_sema_id BIGINT NOT NULL,
    baglanti_surumu_id BIGINT NOT NULL,
    sema_goruntusu_id BIGINT NOT NULL,
    fiziksel_kimlik VARCHAR(2000) NOT NULL,
    bag_surumu BIGINT NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_yayin_veri_bagi PRIMARY KEY (id),
    CONSTRAINT uq_yayin_veri_bagi_uuid UNIQUE (uuid),
    CONSTRAINT uq_yayin_veri_bagi UNIQUE (yayin_id, tanim_veri_nesnesi_id),
    CONSTRAINT uq_yayin_veri_bagi_proje_id UNIQUE (proje_id, id),
    CONSTRAINT fk_yayin_veri_bagi_yayin FOREIGN KEY (proje_id, yayin_id) REFERENCES yayin(proje_id, id),
    CONSTRAINT fk_yayin_veri_bagi_tanim FOREIGN KEY (proje_id, tanim_veri_nesnesi_id) REFERENCES tanim_veri_nesnesi(proje_id, id),
    CONSTRAINT fk_yayin_veri_bagi_esleme FOREIGN KEY (sema_eslemesi_id) REFERENCES sema_eslemesi(id),
    CONSTRAINT fk_yayin_veri_bagi_fiziksel FOREIGN KEY (fiziksel_sema_id) REFERENCES fiziksel_sema(id),
    CONSTRAINT fk_yayin_veri_bagi_surum FOREIGN KEY (baglanti_surumu_id) REFERENCES baglanti_surumu(id),
    CONSTRAINT fk_yayin_veri_bagi_goruntu FOREIGN KEY (proje_id, sema_goruntusu_id) REFERENCES sema_goruntusu(proje_id, id),
    CONSTRAINT ck_yayin_veri_bagi_surum CHECK (bag_surumu > 0),
    CONSTRAINT ck_yayin_veri_bagi_audit CHECK
        (versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE yayin_onayi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    yayin_id BIGINT NOT NULL,
    kullanici_id BIGINT NOT NULL REFERENCES kullanici(id),
    plan_ozeti CHAR(64) NOT NULL,
    karar VARCHAR(20) NOT NULL,
    karar_zamani TIMESTAMPTZ NOT NULL,
    gerekce VARCHAR(2000),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_yayin_onayi PRIMARY KEY (id),
    CONSTRAINT uq_yayin_onayi_uuid UNIQUE (uuid),
    CONSTRAINT uq_yayin_onayi_karar UNIQUE (yayin_id, kullanici_id, karar_zamani),
    CONSTRAINT fk_yayin_onayi_yayin FOREIGN KEY (proje_id, yayin_id) REFERENCES yayin(proje_id, id),
    CONSTRAINT ck_yayin_onayi_ozet CHECK (plan_ozeti ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_yayin_onayi_karar CHECK (karar IN ('ONAY', 'RED', 'GERI_CEK')),
    CONSTRAINT ck_yayin_onayi_audit CHECK
        (versiyon_no = 1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE FUNCTION yayin_veri_bagini_dogrula() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE esleme_proje BIGINT; esleme_fiziksel BIGINT; esleme_surum BIGINT; goruntu_nesne BIGINT; bag_nesne BIGINT; goruntu_fiziksel BIGINT; goruntu_surum BIGINT;
BEGIN
 SELECT proje_id,fiziksel_sema_id,baglanti_surumu_id INTO STRICT esleme_proje,esleme_fiziksel,esleme_surum FROM akis.sema_eslemesi WHERE id=NEW.sema_eslemesi_id;
 SELECT veri_nesnesi_id,fiziksel_sema_id,baglanti_surumu_id INTO STRICT goruntu_nesne,goruntu_fiziksel,goruntu_surum FROM akis.sema_goruntusu WHERE id=NEW.sema_goruntusu_id;
 SELECT veri_nesnesi_id INTO STRICT bag_nesne FROM akis.tanim_veri_nesnesi WHERE id=NEW.tanim_veri_nesnesi_id;
 IF esleme_proje<>NEW.proje_id OR esleme_fiziksel<>NEW.fiziksel_sema_id OR esleme_surum<>NEW.baglanti_surumu_id
    OR goruntu_nesne<>bag_nesne OR goruntu_fiziksel<>NEW.fiziksel_sema_id OR goruntu_surum<>NEW.baglanti_surumu_id THEN
  RAISE EXCEPTION 'Yayın veri bağı aynı proje, eşleme ve görüntü zincirine ait olmalıdır.' USING ERRCODE='23514';
 END IF; RETURN NEW;
END $$;
CREATE TRIGGER trg_yayin_veri_bagi_dogrula BEFORE INSERT OR UPDATE ON yayin_veri_bagi FOR EACH ROW EXECUTE FUNCTION yayin_veri_bagini_dogrula();

CREATE FUNCTION degismez_yayin_kanitini_koru() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Yayın kanıtı değiştirilemez.' USING ERRCODE='55000'; END $$;
CREATE TRIGGER trg_yayin_veri_bagi_degismez BEFORE UPDATE OR DELETE ON yayin_veri_bagi FOR EACH ROW EXECUTE FUNCTION degismez_yayin_kanitini_koru();
CREATE TRIGGER trg_yayin_onayi_degismez BEFORE UPDATE OR DELETE ON yayin_onayi FOR EACH ROW EXECUTE FUNCTION degismez_yayin_kanitini_koru();

CREATE INDEX ix_yayin_proje ON yayin(proje_id, olusturulma_zamani DESC);
CREATE INDEX ix_yayin_onayi_yayin ON yayin_onayi(proje_id, yayin_id, karar_zamani DESC);
