SET search_path TO akis, public;

CREATE TABLE is_talebi (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id),
 yayin_id BIGINT NOT NULL, istek_ozeti CHAR(64) NOT NULL, is_turu VARCHAR(20) NOT NULL DEFAULT 'CALISTIR',
 oncelik INTEGER NOT NULL DEFAULT 50, planlanan_zaman TIMESTAMPTZ,
 parametre_sema_surumu INTEGER NOT NULL DEFAULT 1, parametre JSONB NOT NULL DEFAULT '{}'::jsonb,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_is_talebi PRIMARY KEY(id), CONSTRAINT uq_is_talebi_uuid UNIQUE(uuid),
 CONSTRAINT uq_is_talebi_proje_id UNIQUE(proje_id,id),
 CONSTRAINT fk_is_talebi_yayin FOREIGN KEY(proje_id,yayin_id) REFERENCES yayin(proje_id,id),
 CONSTRAINT ck_is_talebi_ozet CHECK(istek_ozeti ~ '^[0-9a-f]{64}$'),
 CONSTRAINT ck_is_talebi_tur CHECK(is_turu IN('CALISTIR','TEST','KESIF','ONIZLEME')),
 CONSTRAINT ck_is_talebi_oncelik CHECK(oncelik BETWEEN 0 AND 100),
 CONSTRAINT ck_is_talebi_parametre CHECK(parametre_sema_surumu>0 AND jsonb_typeof(parametre)='object'),
 CONSTRAINT ck_is_talebi_audit CHECK(versiyon_no>0 AND (guncellenme_zamani IS NULL OR guncellenme_zamani>=olusturulma_zamani))
);

CREATE TABLE calistirma (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id),
 is_talebi_id BIGINT NOT NULL, deneme_no INTEGER NOT NULL, yayin_ozeti CHAR(64) NOT NULL,
 plan_ozeti CHAR(64) NOT NULL, baslatma_turu VARCHAR(20) NOT NULL,
 onceki_calistirma_id BIGINT,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_calistirma PRIMARY KEY(id), CONSTRAINT uq_calistirma_uuid UNIQUE(uuid),
 CONSTRAINT uq_calistirma_deneme UNIQUE(is_talebi_id,deneme_no), CONSTRAINT uq_calistirma_proje_id UNIQUE(proje_id,id),
 CONSTRAINT fk_calistirma_talep FOREIGN KEY(proje_id,is_talebi_id) REFERENCES is_talebi(proje_id,id),
 CONSTRAINT fk_calistirma_onceki FOREIGN KEY(proje_id,onceki_calistirma_id) REFERENCES calistirma(proje_id,id),
 CONSTRAINT ck_calistirma_deneme CHECK(deneme_no>0),
 CONSTRAINT ck_calistirma_ozet CHECK(yayin_ozeti ~ '^[0-9a-f]{64}$' AND plan_ozeti ~ '^[0-9a-f]{64}$'),
 CONSTRAINT ck_calistirma_baslatma CHECK(baslatma_turu IN('ILK','YENIDEN_DENE','DEVAM_ET')),
 CONSTRAINT ck_calistirma_onceki CHECK((baslatma_turu='ILK' AND onceki_calistirma_id IS NULL) OR (baslatma_turu<>'ILK' AND onceki_calistirma_id IS NOT NULL)),
 CONSTRAINT ck_calistirma_audit CHECK(versiyon_no>0 AND (guncellenme_zamani IS NULL OR guncellenme_zamani>=olusturulma_zamani))
);

CREATE TABLE calistirma_durumu (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id), calistirma_id BIGINT NOT NULL,
 durum VARCHAR(30) NOT NULL DEFAULT 'BEKLIYOR', nesil_no BIGINT NOT NULL DEFAULT 0,
 hedef_nesil_no BIGINT, son_olay_no BIGINT NOT NULL DEFAULT 0, isleyici_referansi VARCHAR(200),
 kiralama_bitis_zamani TIMESTAMPTZ, yasam_sinyali_zamani TIMESTAMPTZ,
 baslama_zamani TIMESTAMPTZ, bitis_zamani TIMESTAMPTZ, iptal_isteme_zamani TIMESTAMPTZ,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_calistirma_durumu PRIMARY KEY(id), CONSTRAINT uq_calistirma_durumu_uuid UNIQUE(uuid),
 CONSTRAINT uq_calistirma_durumu_calistirma UNIQUE(calistirma_id), CONSTRAINT uq_calistirma_durumu_proje_id UNIQUE(proje_id,id),
 CONSTRAINT fk_calistirma_durumu_calistirma FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 CONSTRAINT ck_calistirma_durumu CHECK(durum IN('BEKLIYOR','SAHIPLENILDI','CALISIYOR','IPTAL_ISTENDI','BASARILI','BASARISIZ','IPTAL','SONUCU_BILINMIYOR')),
 CONSTRAINT ck_calistirma_durumu_sayac CHECK(nesil_no>=0 AND son_olay_no>=0),
 CONSTRAINT ck_calistirma_durumu_zaman CHECK(bitis_zamani IS NULL OR baslama_zamani IS NULL OR bitis_zamani>=baslama_zamani),
 CONSTRAINT ck_calistirma_durumu_audit CHECK(versiyon_no>0 AND (guncellenme_zamani IS NULL OR guncellenme_zamani>=olusturulma_zamani))
);

CREATE TABLE calistirma_adimi (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id), calistirma_id BIGINT NOT NULL,
 ust_adim_id BIGINT, adim_kodu VARCHAR(100) NOT NULL, tur VARCHAR(30) NOT NULL, sira_no INTEGER NOT NULL, ad VARCHAR(200) NOT NULL,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_calistirma_adimi PRIMARY KEY(id), CONSTRAINT uq_calistirma_adimi_uuid UNIQUE(uuid),
 CONSTRAINT uq_calistirma_adimi_kod UNIQUE(calistirma_id,adim_kodu), CONSTRAINT uq_calistirma_adimi_sira UNIQUE NULLS NOT DISTINCT(calistirma_id,ust_adim_id,sira_no),
 CONSTRAINT uq_calistirma_adimi_proje_id UNIQUE(proje_id,id),
 CONSTRAINT fk_calistirma_adimi_calistirma FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 CONSTRAINT fk_calistirma_adimi_ust FOREIGN KEY(proje_id,ust_adim_id) REFERENCES calistirma_adimi(proje_id,id),
 CONSTRAINT ck_calistirma_adimi_tur CHECK(tur IN('ON_KONTROL','MAPPING','PROSEDUR','DEGISKEN','PAKET','LOAD_PLAN','KAYNAK_OKUMA','HEDEF_YAZMA','DOGRULAMA','YAYINLAMA','MUTABAKAT')),
 CONSTRAINT ck_calistirma_adimi_sira CHECK(sira_no>0),
 CONSTRAINT ck_calistirma_adimi_audit CHECK(versiyon_no=1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE calistirma_olayi (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id), calistirma_id BIGINT NOT NULL,
 calistirma_adimi_id BIGINT, olay_no BIGINT NOT NULL, tur VARCHAR(100) NOT NULL, olay_zamani TIMESTAMPTZ NOT NULL,
 veri_sema_surumu INTEGER NOT NULL DEFAULT 1, veri JSONB NOT NULL DEFAULT '{}'::jsonb,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_calistirma_olayi PRIMARY KEY(id), CONSTRAINT uq_calistirma_olayi_uuid UNIQUE(uuid),
 CONSTRAINT uq_calistirma_olayi_no UNIQUE(calistirma_id,olay_no),
 CONSTRAINT fk_calistirma_olayi_calistirma FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 CONSTRAINT fk_calistirma_olayi_adim FOREIGN KEY(proje_id,calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id,id),
 CONSTRAINT ck_calistirma_olayi_no CHECK(olay_no>0),
 CONSTRAINT ck_calistirma_olayi_veri CHECK(veri_sema_surumu>0 AND jsonb_typeof(veri)='object'),
 CONSTRAINT ck_calistirma_olayi_audit CHECK(versiyon_no=1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE istek_anahtari (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id), kullanici_id BIGINT NOT NULL REFERENCES kullanici(id),
 is_talebi_id BIGINT, kapsam VARCHAR(100) NOT NULL, anahtar_ozeti CHAR(64) NOT NULL, istek_ozeti CHAR(64) NOT NULL,
 durum VARCHAR(20) NOT NULL, sona_erme_zamani TIMESTAMPTZ NOT NULL, yanit_sema_surumu INTEGER, yanit JSONB,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_istek_anahtari PRIMARY KEY(id), CONSTRAINT uq_istek_anahtari_uuid UNIQUE(uuid),
 CONSTRAINT uq_istek_anahtari UNIQUE(proje_id,kullanici_id,kapsam,anahtar_ozeti),
 CONSTRAINT fk_istek_anahtari_talep FOREIGN KEY(proje_id,is_talebi_id) REFERENCES is_talebi(proje_id,id),
 CONSTRAINT ck_istek_anahtari_ozet CHECK(anahtar_ozeti ~ '^[0-9a-f]{64}$' AND istek_ozeti ~ '^[0-9a-f]{64}$'),
 CONSTRAINT ck_istek_anahtari_durum CHECK(durum IN('ISLENIYOR','TAMAMLANDI','BASARISIZ')),
 CONSTRAINT ck_istek_anahtari_yanit CHECK((yanit IS NULL AND yanit_sema_surumu IS NULL) OR (yanit_sema_surumu>0 AND jsonb_typeof(yanit)='object')),
 CONSTRAINT ck_istek_anahtari_audit CHECK(versiyon_no>0 AND (guncellenme_zamani IS NULL OR guncellenme_zamani>=olusturulma_zamani))
);

CREATE TABLE prosedur_adim_kaniti (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id), calistirma_id BIGINT NOT NULL, calistirma_adimi_id BIGINT NOT NULL,
 sira_no INTEGER NOT NULL, runtime_plan_ozeti CHAR(64) NOT NULL, komut_ozeti CHAR(64) NOT NULL,
 baglanti_rolu VARCHAR(20) NOT NULL, risk VARCHAR(20) NOT NULL, hata_politikasi VARCHAR(20) NOT NULL,
 tanim_veri_nesnesi_uuid UUID NOT NULL, baglanti_surumu_uuid UUID NOT NULL, sema_goruntusu_uuid UUID NOT NULL, sema_parmak_izi CHAR(64) NOT NULL,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_prosedur_adim_kaniti PRIMARY KEY(id), CONSTRAINT uq_prosedur_adim_kaniti_uuid UNIQUE(uuid),
 CONSTRAINT uq_prosedur_adim_kaniti_adim UNIQUE(calistirma_adimi_id), CONSTRAINT uq_prosedur_adim_kaniti_sira UNIQUE(calistirma_id,sira_no),
 CONSTRAINT uq_prosedur_adim_kaniti_proje_id UNIQUE(proje_id,id),
 CONSTRAINT fk_prosedur_adim_kaniti_calistirma FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 CONSTRAINT fk_prosedur_adim_kaniti_adim FOREIGN KEY(proje_id,calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id,id),
 CONSTRAINT ck_prosedur_adim_kaniti_rol CHECK(baglanti_rolu IN('SOURCE','TARGET')),
 CONSTRAINT ck_prosedur_adim_kaniti_risk CHECK(risk IN('READ_ONLY','DML','DDL','DESTRUCTIVE')),
 CONSTRAINT ck_prosedur_adim_kaniti_hata CHECK(hata_politikasi IN('STOP','CONTINUE')),
 CONSTRAINT ck_prosedur_adim_kaniti_audit CHECK(versiyon_no=1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE prosedur_adim_durumu (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id), calistirma_id BIGINT NOT NULL,
 calistirma_adimi_id BIGINT NOT NULL, prosedur_adim_kaniti_id BIGINT NOT NULL, durum VARCHAR(30) NOT NULL DEFAULT 'BEKLIYOR',
 son_olay_no BIGINT, baslama_zamani TIMESTAMPTZ, bitis_zamani TIMESTAMPTZ, satir_sayisi BIGINT, bayt_sayisi BIGINT, hata_kodu VARCHAR(100),
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_prosedur_adim_durumu PRIMARY KEY(id), CONSTRAINT uq_prosedur_adim_durumu_uuid UNIQUE(uuid),
 CONSTRAINT uq_prosedur_adim_durumu_adim UNIQUE(calistirma_adimi_id), CONSTRAINT uq_prosedur_adim_durumu_kanit UNIQUE(prosedur_adim_kaniti_id),
 CONSTRAINT fk_prosedur_adim_durumu_calistirma FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 CONSTRAINT fk_prosedur_adim_durumu_adim FOREIGN KEY(proje_id,calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id,id),
 CONSTRAINT fk_prosedur_adim_durumu_kanit FOREIGN KEY(proje_id,prosedur_adim_kaniti_id) REFERENCES prosedur_adim_kaniti(proje_id,id),
 CONSTRAINT ck_prosedur_adim_durumu CHECK(durum IN('BEKLIYOR','CALISIYOR','BASARILI','HATA_DEVAM','BASARISIZ','SONUC_BELIRSIZ','ATLANDI')),
 CONSTRAINT ck_prosedur_adim_durumu_sayim CHECK((satir_sayisi IS NULL OR satir_sayisi>=0) AND (bayt_sayisi IS NULL OR bayt_sayisi>=0)),
 CONSTRAINT ck_prosedur_adim_durumu_audit CHECK(versiyon_no>0 AND (guncellenme_zamani IS NULL OR guncellenme_zamani>=olusturulma_zamani))
);

CREATE FUNCTION degismez_calistirma_kanitini_koru() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Çalıştırma kanıtı değiştirilemez.' USING ERRCODE='55000'; END $$;
CREATE TRIGGER trg_calistirma_olayi_degismez BEFORE UPDATE OR DELETE ON calistirma_olayi FOR EACH ROW EXECUTE FUNCTION degismez_calistirma_kanitini_koru();
CREATE TRIGGER trg_prosedur_adim_kaniti_degismez BEFORE UPDATE OR DELETE ON prosedur_adim_kaniti FOR EACH ROW EXECUTE FUNCTION degismez_calistirma_kanitini_koru();

CREATE INDEX ix_calistirma_proje ON calistirma(proje_id,olusturulma_zamani DESC);
CREATE INDEX ix_calistirma_olayi_run ON calistirma_olayi(proje_id,calistirma_id,olay_no);
CREATE INDEX ix_calistirma_adimi_agac ON calistirma_adimi(proje_id,calistirma_id,ust_adim_id,sira_no);
