SET search_path TO akis, public;

CREATE TABLE denetim_olayi (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT REFERENCES proje(id), kullanici_id BIGINT REFERENCES kullanici(id),
 dis_nesne_uuid UUID, korelasyon_kodu VARCHAR(200) NOT NULL, aktor_turu VARCHAR(20) NOT NULL,
 eylem_kodu VARCHAR(100) NOT NULL, sonuc VARCHAR(20) NOT NULL, olay_zamani TIMESTAMPTZ NOT NULL,
 ayrinti_sema_surumu INTEGER NOT NULL DEFAULT 1, ayrinti JSONB NOT NULL DEFAULT '{}'::jsonb,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_denetim_olayi PRIMARY KEY(id), CONSTRAINT uq_denetim_olayi_uuid UNIQUE(uuid),
 CONSTRAINT ck_denetim_olayi_aktor CHECK(aktor_turu IN('KULLANICI','SISTEM')),
 CONSTRAINT ck_denetim_olayi_sonuc CHECK(sonuc IN('BASARILI','RED','BASARISIZ')),
 CONSTRAINT ck_denetim_olayi_ayrinti CHECK(ayrinti_sema_surumu>0 AND jsonb_typeof(ayrinti)='object'),
 CONSTRAINT ck_denetim_olayi_audit CHECK(versiyon_no=1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE FUNCTION degismez_denetim_olayini_koru() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Denetim olayı değiştirilemez.' USING ERRCODE='55000';END $$;
CREATE TRIGGER trg_denetim_olayi_degismez BEFORE UPDATE OR DELETE ON denetim_olayi FOR EACH ROW EXECUTE FUNCTION degismez_denetim_olayini_koru();
CREATE INDEX ix_denetim_olayi_proje ON denetim_olayi(proje_id,olay_zamani DESC);
