SET search_path TO akis, public;

CREATE TABLE worker_profili (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, kod VARCHAR(100) NOT NULL, ad VARCHAR(200) NOT NULL,
 etkin BOOLEAN NOT NULL DEFAULT TRUE, yetenek_sema_surumu INTEGER NOT NULL DEFAULT 1,
 yetenek JSONB NOT NULL DEFAULT '{}'::jsonb,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_worker_profili PRIMARY KEY(id), CONSTRAINT uq_worker_profili_uuid UNIQUE(uuid),
 CONSTRAINT uq_worker_profili_kod UNIQUE(kod),
 CONSTRAINT ck_worker_profili_yetenek CHECK(yetenek_sema_surumu>0 AND jsonb_typeof(yetenek)='object'),
 CONSTRAINT ck_worker_profili_audit CHECK(versiyon_no>0 AND (guncellenme_zamani IS NULL OR guncellenme_zamani>=olusturulma_zamani))
);

CREATE TABLE hedef_kaynagi (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, calistirma_id BIGINT REFERENCES calistirma(id),
 fiziksel_ozet CHAR(64) NOT NULL, kimlik_surumu INTEGER NOT NULL, durum VARCHAR(20) NOT NULL DEFAULT 'BOS',
 nesil_no BIGINT NOT NULL DEFAULT 0, kiralama_bitis_zamani TIMESTAMPTZ,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_hedef_kaynagi PRIMARY KEY(id), CONSTRAINT uq_hedef_kaynagi_uuid UNIQUE(uuid),
 CONSTRAINT uq_hedef_kaynagi_ozet UNIQUE(fiziksel_ozet,kimlik_surumu),
 CONSTRAINT ck_hedef_kaynagi_ozet CHECK(fiziksel_ozet ~ '^[0-9a-f]{64}$' AND kimlik_surumu>0),
 CONSTRAINT ck_hedef_kaynagi_durum CHECK(durum IN('BOS','SAHIPLENILDI','ASKIDA')),
 CONSTRAINT ck_hedef_kaynagi_nesil CHECK(nesil_no>=0),
 CONSTRAINT ck_hedef_kaynagi_sahip CHECK((durum='SAHIPLENILDI' AND calistirma_id IS NOT NULL AND kiralama_bitis_zamani IS NOT NULL) OR (durum<>'SAHIPLENILDI' AND calistirma_id IS NULL AND kiralama_bitis_zamani IS NULL)),
 CONSTRAINT ck_hedef_kaynagi_audit CHECK(versiyon_no>0 AND (guncellenme_zamani IS NULL OR guncellenme_zamani>=olusturulma_zamani))
);

ALTER TABLE calistirma_durumu DROP CONSTRAINT ck_calistirma_durumu;
ALTER TABLE calistirma_durumu
 ADD COLUMN hedef_kaynagi_id BIGINT REFERENCES hedef_kaynagi(id),
 ADD COLUMN worker_profili_id BIGINT REFERENCES worker_profili(id),
 ADD CONSTRAINT ck_calistirma_durumu CHECK(durum IN('BEKLIYOR','SAHIPLENILDI','CALISIYOR','YAYINLANIYOR','IPTAL_ISTENDI','MUTABAKAT','BASARILI','BASARISIZ','IPTAL','SONUC_BELIRSIZ'));

CREATE OR REPLACE FUNCTION calistirma_sahiplen(p_worker_profili_uuid UUID,p_isleyici_referansi TEXT,p_kiralama_saniyesi INTEGER)
RETURNS TABLE(calistirma_uuid UUID,nesil_no BIGINT,yayin_ozeti TEXT,plan_ozeti TEXT,kiralama_bitis_zamani TIMESTAMPTZ)
LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_worker BIGINT; v_durum calistirma_durumu%ROWTYPE;
BEGIN
 IF p_kiralama_saniyesi NOT BETWEEN 30 AND 300 OR length(btrim(p_isleyici_referansi)) NOT BETWEEN 1 AND 200 THEN RETURN; END IF;
 SELECT id INTO v_worker FROM worker_profili WHERE uuid=p_worker_profili_uuid AND etkin FOR UPDATE;
 IF NOT FOUND THEN RETURN; END IF;
 SELECT cd.* INTO v_durum FROM calistirma_durumu cd JOIN calistirma c ON c.id=cd.calistirma_id
  WHERE cd.durum='BEKLIYOR' AND cd.hedef_kaynagi_id IS NULL
  ORDER BY (SELECT it.oncelik FROM is_talebi it WHERE it.id=c.is_talebi_id) DESC,c.olusturulma_zamani,c.id
  FOR UPDATE OF cd SKIP LOCKED LIMIT 1;
 IF NOT FOUND THEN RETURN; END IF;
 UPDATE calistirma_durumu cd SET durum='SAHIPLENILDI',worker_profili_id=v_worker,isleyici_referansi=btrim(p_isleyici_referansi),
  nesil_no=cd.nesil_no+1,kiralama_bitis_zamani=clock_timestamp()+make_interval(secs=>p_kiralama_saniyesi),
  yasam_sinyali_zamani=clock_timestamp(),guncellenme_zamani=clock_timestamp(),versiyon_no=cd.versiyon_no+1
  WHERE cd.id=v_durum.id RETURNING cd.* INTO v_durum;
 UPDATE calistirma_durumu cd SET son_olay_no=cd.son_olay_no+1 WHERE cd.id=v_durum.id RETURNING cd.* INTO v_durum;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri)
 VALUES(v_durum.proje_id,v_durum.calistirma_id,v_durum.son_olay_no,'RUN_CLAIMED',clock_timestamp(),jsonb_build_object('generation',v_durum.nesil_no,'workerReference',v_durum.isleyici_referansi,'workerProfileUuid',p_worker_profili_uuid));
 RETURN QUERY SELECT c.uuid,v_durum.nesil_no,c.yayin_ozeti::TEXT,c.plan_ozeti::TEXT,v_durum.kiralama_bitis_zamani FROM calistirma c WHERE c.id=v_durum.calistirma_id;
END $$;

CREATE OR REPLACE FUNCTION calistirma_yasam_sinyali(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_nesil_no BIGINT,p_kiralama_saniyesi INTEGER)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_sayi INTEGER;
BEGIN
 IF p_kiralama_saniyesi NOT BETWEEN 30 AND 300 THEN RETURN FALSE; END IF;
 UPDATE calistirma_durumu cd SET kiralama_bitis_zamani=clock_timestamp()+make_interval(secs=>p_kiralama_saniyesi),yasam_sinyali_zamani=clock_timestamp(),guncellenme_zamani=clock_timestamp(),versiyon_no=cd.versiyon_no+1
 FROM calistirma c WHERE c.id=cd.calistirma_id AND c.uuid=p_calistirma_uuid AND cd.durum IN('SAHIPLENILDI','CALISIYOR','YAYINLANIYOR')
 AND cd.isleyici_referansi=p_isleyici_referansi AND cd.nesil_no=p_nesil_no AND cd.kiralama_bitis_zamani>clock_timestamp();
 GET DIAGNOSTICS v_sayi=ROW_COUNT; RETURN v_sayi=1;
END $$;

CREATE OR REPLACE FUNCTION hedef_kaynagi_sahiplen(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_calistirma_nesil_no BIGINT,p_fiziksel_ozet TEXT,p_kimlik_surumu INTEGER)
RETURNS TABLE(hedef_kaynagi_uuid UUID,hedef_nesil_no BIGINT)
LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_durum calistirma_durumu%ROWTYPE; v_hedef hedef_kaynagi%ROWTYPE;
BEGIN
 IF p_fiziksel_ozet !~ '^[0-9a-f]{64}$' OR p_kimlik_surumu<1 THEN RETURN; END IF;
 SELECT cd.* INTO v_durum FROM calistirma_durumu cd JOIN calistirma c ON c.id=cd.calistirma_id
  WHERE c.uuid=p_calistirma_uuid AND cd.durum='SAHIPLENILDI' AND cd.isleyici_referansi=p_isleyici_referansi
  AND cd.nesil_no=p_calistirma_nesil_no AND cd.kiralama_bitis_zamani>clock_timestamp() FOR UPDATE OF cd;
 IF NOT FOUND THEN RETURN; END IF;
 IF v_durum.hedef_kaynagi_id IS NOT NULL THEN
  SELECT * INTO v_hedef FROM hedef_kaynagi WHERE id=v_durum.hedef_kaynagi_id FOR UPDATE;
  IF v_hedef.fiziksel_ozet=p_fiziksel_ozet AND v_hedef.kimlik_surumu=p_kimlik_surumu
     AND v_hedef.durum='SAHIPLENILDI' AND v_hedef.calistirma_id=v_durum.calistirma_id
     AND v_hedef.nesil_no=v_durum.hedef_nesil_no AND v_hedef.kiralama_bitis_zamani>clock_timestamp() THEN
   RETURN QUERY SELECT v_hedef.uuid,v_hedef.nesil_no;
  END IF;
  RETURN;
 END IF;
 INSERT INTO hedef_kaynagi(fiziksel_ozet,kimlik_surumu) VALUES(p_fiziksel_ozet,p_kimlik_surumu)
  ON CONFLICT(fiziksel_ozet,kimlik_surumu) DO NOTHING;
 SELECT * INTO v_hedef FROM hedef_kaynagi WHERE fiziksel_ozet=p_fiziksel_ozet AND kimlik_surumu=p_kimlik_surumu FOR UPDATE;
 IF v_hedef.durum<>'BOS' THEN RETURN; END IF;
 UPDATE hedef_kaynagi hk SET durum='SAHIPLENILDI',calistirma_id=v_durum.calistirma_id,nesil_no=hk.nesil_no+1,
  kiralama_bitis_zamani=v_durum.kiralama_bitis_zamani,guncellenme_zamani=clock_timestamp(),versiyon_no=hk.versiyon_no+1
  WHERE hk.id=v_hedef.id RETURNING hk.* INTO v_hedef;
 UPDATE calistirma_durumu cd SET hedef_kaynagi_id=v_hedef.id,hedef_nesil_no=v_hedef.nesil_no,guncellenme_zamani=clock_timestamp(),versiyon_no=cd.versiyon_no+1 WHERE cd.id=v_durum.id;
 RETURN QUERY SELECT v_hedef.uuid,v_hedef.nesil_no;
END $$;

REVOKE ALL ON FUNCTION calistirma_sahiplen(UUID,TEXT,INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION calistirma_yasam_sinyali(UUID,TEXT,BIGINT,INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION hedef_kaynagi_sahiplen(UUID,TEXT,BIGINT,TEXT,INTEGER) FROM PUBLIC;
