SET search_path TO akis, public;

CREATE TABLE pilot_yayin_niyeti (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id), is_talebi_id BIGINT NOT NULL,
 calistirma_id BIGINT NOT NULL, calistirma_adimi_id BIGINT NOT NULL, calistirma_nesil_no BIGINT NOT NULL,
 isleyici_referansi VARCHAR(200) NOT NULL, deneme_no INTEGER NOT NULL, hedef_kaynagi_id BIGINT NOT NULL REFERENCES hedef_kaynagi(id),
 hedef_nesil_no BIGINT NOT NULL, hedef_fiziksel_ozeti CHAR(64) NOT NULL, hedef_kimlik_surumu INTEGER NOT NULL,
 yayin_ozeti CHAR(64) NOT NULL, plan_ozeti CHAR(64) NOT NULL, runtime_plan_ozeti CHAR(64) NOT NULL,
 yayin_anahtari_ozeti CHAR(64) NOT NULL, payload_ozeti CHAR(64) NOT NULL, satir_sayisi BIGINT NOT NULL, bayt_sayisi BIGINT NOT NULL,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_pilot_yayin_niyeti PRIMARY KEY(id), CONSTRAINT uq_pilot_yayin_niyeti_uuid UNIQUE(uuid),
 CONSTRAINT uq_pilot_yayin_niyeti_run UNIQUE(calistirma_id), CONSTRAINT uq_pilot_yayin_niyeti_operasyon UNIQUE(hedef_kaynagi_id,yayin_anahtari_ozeti),
 CONSTRAINT fk_pilot_yayin_niyeti_run FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 CONSTRAINT fk_pilot_yayin_niyeti_adim FOREIGN KEY(proje_id,calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id,id),
 CONSTRAINT ck_pilot_yayin_niyeti_sayim CHECK(calistirma_nesil_no>0 AND hedef_nesil_no>0 AND hedef_kimlik_surumu>0 AND deneme_no>0 AND satir_sayisi>=0 AND bayt_sayisi>=0),
 CONSTRAINT ck_pilot_yayin_niyeti_ozet CHECK(hedef_fiziksel_ozeti~'^[0-9a-f]{64}$' AND yayin_ozeti~'^[0-9a-f]{64}$' AND plan_ozeti~'^[0-9a-f]{64}$' AND runtime_plan_ozeti~'^[0-9a-f]{64}$' AND yayin_anahtari_ozeti~'^[0-9a-f]{64}$' AND payload_ozeti~'^[0-9a-f]{64}$'),
 CONSTRAINT ck_pilot_yayin_niyeti_audit CHECK(versiyon_no=1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TABLE kontrol_noktasi (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id), calistirma_id BIGINT NOT NULL,
 calistirma_adimi_id BIGINT NOT NULL, hedef_kaynagi_id BIGINT NOT NULL REFERENCES hedef_kaynagi(id), hedef_nesil_no BIGINT NOT NULL,
 mutabakat_hedef_nesil_no BIGINT, kapsam_ozeti CHAR(64) NOT NULL, bolum VARCHAR(40) NOT NULL, sira_no BIGINT NOT NULL,
 paket_anahtari TEXT NOT NULL, hedef_defter_referansi CHAR(64) NOT NULL, payload_ozeti CHAR(64), tur VARCHAR(30) NOT NULL,
 dogrulama_zamani TIMESTAMPTZ NOT NULL, imlec_sema_surumu INTEGER NOT NULL DEFAULT 1, imlec JSONB NOT NULL,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_kontrol_noktasi PRIMARY KEY(id), CONSTRAINT uq_kontrol_noktasi_uuid UNIQUE(uuid),
 CONSTRAINT uq_kontrol_noktasi_sira UNIQUE(calistirma_id,calistirma_adimi_id,bolum,sira_no),
 CONSTRAINT fk_kontrol_noktasi_run FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 CONSTRAINT fk_kontrol_noktasi_adim FOREIGN KEY(proje_id,calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id,id),
 CONSTRAINT ck_kontrol_noktasi_tur CHECK(tur IN('BATCH','PUBLISH','WATERMARK')),
 CONSTRAINT ck_kontrol_noktasi_imlec CHECK(sira_no>0 AND hedef_nesil_no>0 AND imlec_sema_surumu>0 AND jsonb_typeof(imlec)='object'),
 CONSTRAINT ck_kontrol_noktasi_audit CHECK(versiyon_no=1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);

CREATE TRIGGER trg_pilot_yayin_niyeti_degismez BEFORE UPDATE OR DELETE ON pilot_yayin_niyeti FOR EACH ROW EXECUTE FUNCTION degismez_calistirma_kanitini_koru();
CREATE TRIGGER trg_kontrol_noktasi_degismez BEFORE UPDATE OR DELETE ON kontrol_noktasi FOR EACH ROW EXECUTE FUNCTION degismez_calistirma_kanitini_koru();

CREATE FUNCTION calistirma_calismaya_baslat(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_calistirma_nesil_no BIGINT,p_hedef_kaynagi_uuid UUID,p_hedef_nesil_no BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE;v_d calistirma_durumu%ROWTYPE;v_h hedef_kaynagi%ROWTYPE;v_pre BIGINT;v_pub BIGINT;
BEGIN
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid; IF NOT FOUND THEN RETURN FALSE;END IF;
 SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 SELECT * INTO v_h FROM hedef_kaynagi WHERE id=v_d.hedef_kaynagi_id AND uuid=p_hedef_kaynagi_uuid FOR UPDATE;
 IF v_d.durum='CALISIYOR' AND v_d.nesil_no=p_calistirma_nesil_no AND v_d.isleyici_referansi=p_isleyici_referansi THEN RETURN TRUE;END IF;
 IF v_d.durum<>'SAHIPLENILDI' OR v_d.nesil_no<>p_calistirma_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi OR v_d.kiralama_bitis_zamani<=clock_timestamp()
 OR v_h.durum<>'SAHIPLENILDI' OR v_h.calistirma_id<>v_c.id OR v_h.nesil_no<>p_hedef_nesil_no OR v_h.kiralama_bitis_zamani<=clock_timestamp() THEN RETURN FALSE;END IF;
 INSERT INTO calistirma_adimi(proje_id,calistirma_id,adim_kodu,tur,sira_no,ad) VALUES(v_c.proje_id,v_c.id,'PILOT_PREFLIGHT','ON_KONTROL',1,'Pilot preflight') RETURNING id INTO v_pre;
 INSERT INTO calistirma_adimi(proje_id,calistirma_id,adim_kodu,tur,sira_no,ad) VALUES(v_c.proje_id,v_c.id,'PILOT_PUBLISH','YAYINLAMA',2,'Pilot publish') RETURNING id INTO v_pub;
 UPDATE calistirma_durumu SET durum='CALISIYOR',baslama_zamani=coalesce(baslama_zamani,clock_timestamp()),son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_d.id RETURNING * INTO v_d;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,calistirma_adimi_id,olay_no,tur,olay_zamani,veri) VALUES(v_c.proje_id,v_c.id,v_pre,v_d.son_olay_no,'PREFLIGHT_COMPLETED',clock_timestamp(),jsonb_build_object('generation',p_calistirma_nesil_no,'targetGeneration',p_hedef_nesil_no)); RETURN TRUE;
END $$;

CREATE FUNCTION calistirma_yayina_gec(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_calistirma_nesil_no BIGINT,p_hedef_kaynagi_uuid UUID,p_hedef_nesil_no BIGINT,p_runtime_plan_ozeti TEXT,p_yayin_anahtari_ozeti TEXT,p_payload_ozeti TEXT,p_satir_sayisi BIGINT,p_bayt_sayisi BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE;v_d calistirma_durumu%ROWTYPE;v_h hedef_kaynagi%ROWTYPE;v_adim BIGINT;v_talep BIGINT;
BEGIN
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid;IF NOT FOUND THEN RETURN FALSE;END IF;SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;SELECT * INTO v_h FROM hedef_kaynagi WHERE id=v_d.hedef_kaynagi_id AND uuid=p_hedef_kaynagi_uuid FOR UPDATE;
 IF v_d.durum='YAYINLANIYOR' THEN RETURN EXISTS(SELECT 1 FROM pilot_yayin_niyeti WHERE calistirma_id=v_c.id AND runtime_plan_ozeti=p_runtime_plan_ozeti AND yayin_anahtari_ozeti=p_yayin_anahtari_ozeti AND payload_ozeti=p_payload_ozeti AND satir_sayisi=p_satir_sayisi AND bayt_sayisi=p_bayt_sayisi);END IF;
 IF v_d.durum<>'CALISIYOR' OR v_d.nesil_no<>p_calistirma_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi OR v_d.kiralama_bitis_zamani<=clock_timestamp() OR v_h.nesil_no<>p_hedef_nesil_no OR v_h.durum<>'SAHIPLENILDI' THEN RETURN FALSE;END IF;
 SELECT id INTO v_adim FROM calistirma_adimi WHERE calistirma_id=v_c.id AND adim_kodu='PILOT_PUBLISH';SELECT id INTO v_talep FROM is_talebi WHERE id=v_c.is_talebi_id;
 INSERT INTO pilot_yayin_niyeti(proje_id,is_talebi_id,calistirma_id,calistirma_adimi_id,calistirma_nesil_no,isleyici_referansi,deneme_no,hedef_kaynagi_id,hedef_nesil_no,hedef_fiziksel_ozeti,hedef_kimlik_surumu,yayin_ozeti,plan_ozeti,runtime_plan_ozeti,yayin_anahtari_ozeti,payload_ozeti,satir_sayisi,bayt_sayisi)
 VALUES(v_c.proje_id,v_talep,v_c.id,v_adim,p_calistirma_nesil_no,p_isleyici_referansi,v_c.deneme_no,v_h.id,p_hedef_nesil_no,v_h.fiziksel_ozet,v_h.kimlik_surumu,v_c.yayin_ozeti,v_c.plan_ozeti,p_runtime_plan_ozeti,p_yayin_anahtari_ozeti,p_payload_ozeti,p_satir_sayisi,p_bayt_sayisi);
 UPDATE calistirma_durumu SET durum='YAYINLANIYOR',son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_d.id RETURNING * INTO v_d;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,calistirma_adimi_id,olay_no,tur,olay_zamani,veri) VALUES(v_c.proje_id,v_c.id,v_adim,v_d.son_olay_no,'PUBLISH_STARTED',clock_timestamp(),jsonb_build_object('generation',p_calistirma_nesil_no,'targetGeneration',p_hedef_nesil_no,'runtimePlanHash',p_runtime_plan_ozeti,'publishKeyHash',p_yayin_anahtari_ozeti,'payloadHash',p_payload_ozeti,'rowCount',p_satir_sayisi,'byteCount',p_bayt_sayisi));RETURN TRUE;
END $$;

CREATE FUNCTION calistirma_guvenli_hata_ile_sonlandir(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_calistirma_nesil_no BIGINT,p_hedef_kaynagi_uuid UUID,p_hedef_nesil_no BIGINT,p_hata_kodu TEXT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE;v_d calistirma_durumu%ROWTYPE;v_h hedef_kaynagi%ROWTYPE;
BEGIN SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid;IF NOT FOUND THEN RETURN FALSE;END IF;SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 IF v_d.durum='BASARISIZ' THEN RETURN TRUE;END IF;IF v_d.durum NOT IN('SAHIPLENILDI','CALISIYOR') OR v_d.nesil_no<>p_calistirma_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi OR v_d.kiralama_bitis_zamani<=clock_timestamp() THEN RETURN FALSE;END IF;
 IF v_d.hedef_kaynagi_id IS NOT NULL THEN SELECT * INTO v_h FROM hedef_kaynagi WHERE id=v_d.hedef_kaynagi_id FOR UPDATE;IF v_h.uuid<>p_hedef_kaynagi_uuid OR v_h.nesil_no<>p_hedef_nesil_no THEN RETURN FALSE;END IF;UPDATE hedef_kaynagi SET durum='BOS',calistirma_id=NULL,kiralama_bitis_zamani=NULL,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_h.id;END IF;
 UPDATE calistirma_durumu SET durum='BASARISIZ',kiralama_bitis_zamani=NULL,bitis_zamani=clock_timestamp(),son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_d.id RETURNING * INTO v_d;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri) VALUES(v_c.proje_id,v_c.id,v_d.son_olay_no,'RUN_FAILED_SAFE',clock_timestamp(),jsonb_build_object('generation',p_calistirma_nesil_no,'workerReference',p_isleyici_referansi,'targetResourceUuid',p_hedef_kaynagi_uuid,'targetGeneration',p_hedef_nesil_no,'errorCode',p_hata_kodu,'rollbackConfirmed',true));RETURN TRUE;END $$;

CREATE FUNCTION calistirma_sonucu_belirsiz_isaretle(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_calistirma_nesil_no BIGINT,p_hedef_kaynagi_uuid UUID,p_hedef_nesil_no BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE;v_d calistirma_durumu%ROWTYPE;v_h hedef_kaynagi%ROWTYPE;
BEGIN SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid;IF NOT FOUND THEN RETURN FALSE;END IF;SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;SELECT * INTO v_h FROM hedef_kaynagi WHERE id=v_d.hedef_kaynagi_id AND uuid=p_hedef_kaynagi_uuid FOR UPDATE;
 IF v_d.durum='SONUC_BELIRSIZ' THEN RETURN TRUE;END IF;IF v_d.durum<>'YAYINLANIYOR' OR v_d.nesil_no<>p_calistirma_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi OR v_h.nesil_no<>p_hedef_nesil_no THEN RETURN FALSE;END IF;
 UPDATE hedef_kaynagi SET durum='ASKIDA',calistirma_id=NULL,kiralama_bitis_zamani=NULL,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_h.id;
 UPDATE calistirma_durumu SET durum='SONUC_BELIRSIZ',kiralama_bitis_zamani=NULL,bitis_zamani=clock_timestamp(),son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_d.id RETURNING * INTO v_d;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri) VALUES(v_c.proje_id,v_c.id,v_d.son_olay_no,'RESULT_UNCERTAIN',clock_timestamp(),jsonb_build_object('targetGeneration',p_hedef_nesil_no,'requiresReconciliation',true));RETURN TRUE;END $$;

CREATE FUNCTION calistirma_basarili_tamamla(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_calistirma_nesil_no BIGINT,p_hedef_kaynagi_uuid UUID,p_hedef_nesil_no BIGINT,p_runtime_plan_ozeti TEXT,p_yayin_anahtari_ozeti TEXT,p_payload_ozeti TEXT,p_satir_sayisi BIGINT,p_bayt_sayisi BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE;v_d calistirma_durumu%ROWTYPE;v_h hedef_kaynagi%ROWTYPE;v_adim BIGINT;
BEGIN SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid;IF NOT FOUND THEN RETURN FALSE;END IF;SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;IF v_d.durum='BASARILI' THEN RETURN TRUE;END IF;SELECT * INTO v_h FROM hedef_kaynagi WHERE id=v_d.hedef_kaynagi_id AND uuid=p_hedef_kaynagi_uuid FOR UPDATE;
 IF v_d.durum<>'YAYINLANIYOR' OR v_d.nesil_no<>p_calistirma_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi OR v_h.nesil_no<>p_hedef_nesil_no OR NOT EXISTS(SELECT 1 FROM pilot_yayin_niyeti WHERE calistirma_id=v_c.id AND runtime_plan_ozeti=p_runtime_plan_ozeti AND yayin_anahtari_ozeti=p_yayin_anahtari_ozeti AND payload_ozeti=p_payload_ozeti AND satir_sayisi=p_satir_sayisi AND bayt_sayisi=p_bayt_sayisi) THEN RETURN FALSE;END IF;
 SELECT id INTO v_adim FROM calistirma_adimi WHERE calistirma_id=v_c.id AND adim_kodu='PILOT_PUBLISH';INSERT INTO kontrol_noktasi(proje_id,calistirma_id,calistirma_adimi_id,hedef_kaynagi_id,hedef_nesil_no,kapsam_ozeti,bolum,sira_no,paket_anahtari,hedef_defter_referansi,payload_ozeti,tur,dogrulama_zamani,imlec) VALUES(v_c.proje_id,v_c.id,v_adim,v_h.id,p_hedef_nesil_no,p_runtime_plan_ozeti,'PILOT',1,p_yayin_anahtari_ozeti,p_yayin_anahtari_ozeti,p_payload_ozeti,'PUBLISH',clock_timestamp(),jsonb_build_object('rowCount',p_satir_sayisi,'byteCount',p_bayt_sayisi));
 UPDATE hedef_kaynagi SET durum='BOS',calistirma_id=NULL,kiralama_bitis_zamani=NULL,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_h.id;
 UPDATE calistirma_durumu SET durum='BASARILI',kiralama_bitis_zamani=NULL,bitis_zamani=clock_timestamp(),son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_d.id RETURNING * INTO v_d;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,calistirma_adimi_id,olay_no,tur,olay_zamani,veri) VALUES(v_c.proje_id,v_c.id,v_adim,v_d.son_olay_no,'RUN_SUCCEEDED',clock_timestamp(),jsonb_build_object('targetGeneration',p_hedef_nesil_no,'rowCount',p_satir_sayisi,'byteCount',p_bayt_sayisi));RETURN TRUE;END $$;

REVOKE ALL ON FUNCTION calistirma_calismaya_baslat(UUID,TEXT,BIGINT,UUID,BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION calistirma_yayina_gec(UUID,TEXT,BIGINT,UUID,BIGINT,TEXT,TEXT,TEXT,BIGINT,BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION calistirma_guvenli_hata_ile_sonlandir(UUID,TEXT,BIGINT,UUID,BIGINT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION calistirma_sonucu_belirsiz_isaretle(UUID,TEXT,BIGINT,UUID,BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION calistirma_basarili_tamamla(UUID,TEXT,BIGINT,UUID,BIGINT,TEXT,TEXT,TEXT,BIGINT,BIGINT) FROM PUBLIC;
