SET search_path TO akis, public;

ALTER TABLE calistirma_durumu DROP CONSTRAINT ck_calistirma_durumu;
ALTER TABLE calistirma_durumu ADD CONSTRAINT ck_calistirma_durumu CHECK(durum IN('BEKLIYOR','SAHIPLENILDI','CALISIYOR','YAYINLANIYOR','IPTAL_ISTENDI','MUTABAKAT','BASARILI','BASARISIZ','IPTAL','SONUC_BELIRSIZ','YENIDEN_DENENEBILIR','MUDAHALE_GEREKLI'));

CREATE TABLE mutabakat_kaniti (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY, proje_id BIGINT NOT NULL REFERENCES proje(id), calistirma_id BIGINT NOT NULL,
 kontrol_noktasi_id BIGINT REFERENCES kontrol_noktasi(id), hedef_kaynagi_id BIGINT NOT NULL REFERENCES hedef_kaynagi(id),
 yayin_hedef_nesil_no BIGINT NOT NULL, mutabakat_hedef_nesil_no BIGINT NOT NULL, sonuc VARCHAR(30) NOT NULL,
 runtime_plan_ozeti CHAR(64), yayin_anahtari_ozeti CHAR(64), payload_ozeti CHAR(64), satir_sayisi BIGINT, bayt_sayisi BIGINT,
 uuid UUID NOT NULL DEFAULT gen_random_uuid(), olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id), guncellenme_zamani TIMESTAMPTZ,
 guncelleyen_kullanici_id BIGINT REFERENCES kullanici(id), versiyon_no BIGINT NOT NULL DEFAULT 1,
 CONSTRAINT pk_mutabakat_kaniti PRIMARY KEY(id),CONSTRAINT uq_mutabakat_kaniti_uuid UNIQUE(uuid),
 CONSTRAINT uq_mutabakat_kaniti_run UNIQUE(calistirma_id),
 CONSTRAINT fk_mutabakat_kaniti_run FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 CONSTRAINT ck_mutabakat_kaniti_sonuc CHECK(sonuc IN('PUBLISHED','NOT_PUBLISHED','CONFLICT')),
 CONSTRAINT ck_mutabakat_kaniti_nesil CHECK(yayin_hedef_nesil_no>0 AND mutabakat_hedef_nesil_no=yayin_hedef_nesil_no+1),
 CONSTRAINT ck_mutabakat_kaniti_icerik CHECK((sonuc='PUBLISHED' AND kontrol_noktasi_id IS NOT NULL AND runtime_plan_ozeti~'^[0-9a-f]{64}$' AND yayin_anahtari_ozeti~'^[0-9a-f]{64}$' AND payload_ozeti~'^[0-9a-f]{64}$' AND satir_sayisi>=0 AND bayt_sayisi>=0) OR (sonuc<>'PUBLISHED' AND kontrol_noktasi_id IS NULL AND runtime_plan_ozeti IS NULL AND yayin_anahtari_ozeti IS NULL AND payload_ozeti IS NULL AND satir_sayisi IS NULL AND bayt_sayisi IS NULL)),
 CONSTRAINT ck_mutabakat_kaniti_audit CHECK(versiyon_no=1 AND guncellenme_zamani IS NULL AND guncelleyen_kullanici_id IS NULL)
);
CREATE TRIGGER trg_mutabakat_kaniti_degismez BEFORE UPDATE OR DELETE ON mutabakat_kaniti FOR EACH ROW EXECUTE FUNCTION degismez_calistirma_kanitini_koru();

CREATE FUNCTION calistirma_mutabakat_sahiplen(p_calistirma_uuid UUID,p_worker_profili_uuid UUID,p_isleyici_referansi TEXT,p_kiralama_saniyesi INTEGER)
RETURNS TABLE(calistirma_nesil_no BIGINT,hedef_kaynagi_uuid UUID,hedef_nesil_no BIGINT,kiralama_bitis_zamani TIMESTAMPTZ)
LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE;v_d calistirma_durumu%ROWTYPE;v_h hedef_kaynagi%ROWTYPE;v_w BIGINT;
BEGIN IF p_kiralama_saniyesi NOT BETWEEN 30 AND 300 THEN RETURN;END IF;SELECT id INTO v_w FROM worker_profili WHERE uuid=p_worker_profili_uuid AND etkin;IF NOT FOUND THEN RETURN;END IF;SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid;IF NOT FOUND THEN RETURN;END IF;SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;SELECT * INTO v_h FROM hedef_kaynagi WHERE id=v_d.hedef_kaynagi_id FOR UPDATE;
 IF v_d.durum='MUTABAKAT' AND v_d.isleyici_referansi=p_isleyici_referansi AND v_d.kiralama_bitis_zamani>clock_timestamp() THEN RETURN QUERY SELECT v_d.nesil_no,v_h.uuid,v_h.nesil_no,v_d.kiralama_bitis_zamani;RETURN;END IF;
 IF v_d.durum<>'SONUC_BELIRSIZ' OR v_h.durum<>'ASKIDA' OR v_h.nesil_no<>v_d.hedef_nesil_no THEN RETURN;END IF;
 UPDATE hedef_kaynagi SET nesil_no=nesil_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_h.id RETURNING * INTO v_h;
 UPDATE calistirma_durumu SET durum='MUTABAKAT',worker_profili_id=v_w,isleyici_referansi=p_isleyici_referansi,nesil_no=nesil_no+1,hedef_nesil_no=v_h.nesil_no,kiralama_bitis_zamani=clock_timestamp()+make_interval(secs=>p_kiralama_saniyesi),yasam_sinyali_zamani=clock_timestamp(),bitis_zamani=NULL,son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_d.id RETURNING * INTO v_d;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri) VALUES(v_c.proje_id,v_c.id,v_d.son_olay_no,'RECONCILIATION_CLAIMED',clock_timestamp(),jsonb_build_object('generation',v_d.nesil_no,'targetGeneration',v_h.nesil_no,'workerReference',p_isleyici_referansi));RETURN QUERY SELECT v_d.nesil_no,v_h.uuid,v_h.nesil_no,v_d.kiralama_bitis_zamani;
END $$;

CREATE FUNCTION calistirma_mutabakat_yasam_sinyali(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_nesil_no BIGINT,p_kiralama_saniyesi INTEGER)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_sayi INTEGER;BEGIN IF p_kiralama_saniyesi NOT BETWEEN 30 AND 300 THEN RETURN FALSE;END IF;UPDATE calistirma_durumu d SET kiralama_bitis_zamani=clock_timestamp()+make_interval(secs=>p_kiralama_saniyesi),yasam_sinyali_zamani=clock_timestamp(),guncellenme_zamani=clock_timestamp(),versiyon_no=d.versiyon_no+1 FROM calistirma c WHERE c.id=d.calistirma_id AND c.uuid=p_calistirma_uuid AND d.durum='MUTABAKAT' AND d.isleyici_referansi=p_isleyici_referansi AND d.nesil_no=p_nesil_no AND d.kiralama_bitis_zamani>clock_timestamp();GET DIAGNOSTICS v_sayi=ROW_COUNT;RETURN v_sayi=1;END $$;

CREATE FUNCTION calistirma_mutabakat_sonlandir(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_calistirma_nesil_no BIGINT,p_hedef_kaynagi_uuid UUID,p_hedef_nesil_no BIGINT,p_sonuc TEXT,p_runtime_plan_ozeti TEXT,p_yayin_anahtari_ozeti TEXT,p_payload_ozeti TEXT,p_satir_sayisi BIGINT,p_bayt_sayisi BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE;v_d calistirma_durumu%ROWTYPE;v_h hedef_kaynagi%ROWTYPE;v_p pilot_yayin_niyeti%ROWTYPE;v_kn BIGINT;v_run VARCHAR(30);v_target VARCHAR(20);
BEGIN SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid;IF NOT FOUND THEN RETURN FALSE;END IF;IF EXISTS(SELECT 1 FROM mutabakat_kaniti WHERE calistirma_id=v_c.id AND sonuc=p_sonuc) THEN RETURN TRUE;END IF;SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;SELECT * INTO v_h FROM hedef_kaynagi WHERE id=v_d.hedef_kaynagi_id AND uuid=p_hedef_kaynagi_uuid FOR UPDATE;SELECT * INTO v_p FROM pilot_yayin_niyeti WHERE calistirma_id=v_c.id;
 IF v_d.durum<>'MUTABAKAT' OR v_d.nesil_no<>p_calistirma_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi OR v_d.kiralama_bitis_zamani<=clock_timestamp() OR v_h.durum<>'ASKIDA' OR v_h.nesil_no<>p_hedef_nesil_no OR p_hedef_nesil_no<>v_p.hedef_nesil_no+1 OR p_sonuc NOT IN('PUBLISHED','NOT_PUBLISHED','CONFLICT') THEN RETURN FALSE;END IF;
 IF p_sonuc='PUBLISHED' THEN IF v_p.runtime_plan_ozeti<>p_runtime_plan_ozeti OR v_p.yayin_anahtari_ozeti<>p_yayin_anahtari_ozeti OR v_p.payload_ozeti<>p_payload_ozeti OR v_p.satir_sayisi<>p_satir_sayisi OR v_p.bayt_sayisi<>p_bayt_sayisi THEN RETURN FALSE;END IF;SELECT id INTO v_kn FROM kontrol_noktasi WHERE calistirma_id=v_c.id AND hedef_nesil_no=v_p.hedef_nesil_no;IF v_kn IS NULL THEN INSERT INTO kontrol_noktasi(proje_id,calistirma_id,calistirma_adimi_id,hedef_kaynagi_id,hedef_nesil_no,kapsam_ozeti,bolum,sira_no,paket_anahtari,hedef_defter_referansi,payload_ozeti,tur,dogrulama_zamani,imlec) VALUES(v_c.proje_id,v_c.id,v_p.calistirma_adimi_id,v_h.id,v_p.hedef_nesil_no,p_runtime_plan_ozeti,'PILOT',1,p_yayin_anahtari_ozeti,p_yayin_anahtari_ozeti,p_payload_ozeti,'PUBLISH',clock_timestamp(),jsonb_build_object('rowCount',p_satir_sayisi,'byteCount',p_bayt_sayisi)) RETURNING id INTO v_kn;END IF;v_run='BASARILI';v_target='BOS';ELSIF p_sonuc='NOT_PUBLISHED' THEN v_run='YENIDEN_DENENEBILIR';v_target='BOS';ELSE v_run='MUDAHALE_GEREKLI';v_target='ASKIDA';END IF;
 INSERT INTO mutabakat_kaniti(proje_id,calistirma_id,kontrol_noktasi_id,hedef_kaynagi_id,yayin_hedef_nesil_no,mutabakat_hedef_nesil_no,sonuc,runtime_plan_ozeti,yayin_anahtari_ozeti,payload_ozeti,satir_sayisi,bayt_sayisi) VALUES(v_c.proje_id,v_c.id,v_kn,v_h.id,v_p.hedef_nesil_no,p_hedef_nesil_no,p_sonuc,p_runtime_plan_ozeti,p_yayin_anahtari_ozeti,p_payload_ozeti,p_satir_sayisi,p_bayt_sayisi);
 UPDATE hedef_kaynagi SET durum=v_target,calistirma_id=NULL,kiralama_bitis_zamani=NULL,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_h.id;UPDATE calistirma_durumu SET durum=v_run,kiralama_bitis_zamani=NULL,bitis_zamani=clock_timestamp(),son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_d.id RETURNING * INTO v_d;INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri) VALUES(v_c.proje_id,v_c.id,v_d.son_olay_no,'RECONCILIATION_COMPLETED',clock_timestamp(),jsonb_build_object('outcome',p_sonuc,'targetStatus',v_target));RETURN TRUE;
END $$;

REVOKE ALL ON FUNCTION calistirma_mutabakat_sahiplen(UUID,UUID,TEXT,INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION calistirma_mutabakat_yasam_sinyali(UUID,TEXT,BIGINT,INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION calistirma_mutabakat_sonlandir(UUID,TEXT,BIGINT,UUID,BIGINT,TEXT,TEXT,TEXT,TEXT,BIGINT,BIGINT) FROM PUBLIC;
