SET search_path TO akis, public;

-- Naming metadata only; no Oracle objects are created by this migration.
CREATE TABLE calisma_nesnesi_prefix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proje_id BIGINT NOT NULL,
    baglanti_id BIGINT NOT NULL,
    fiziksel_sema_id BIGINT,
    loading_prefix VARCHAR(8) NOT NULL,
    integration_prefix VARCHAR(8) NOT NULL,
    error_prefix VARCHAR(8) NOT NULL,
    versiyon_no BIGINT NOT NULL DEFAULT 1 CHECK (versiyon_no > 0),
    guncellenme_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (proje_id, baglanti_id) REFERENCES baglanti(proje_id, id),
    FOREIGN KEY (proje_id, fiziksel_sema_id, baglanti_id) REFERENCES fiziksel_sema(proje_id, id, baglanti_id),
    CHECK (loading_prefix ~ '^[A-Z][A-Z0-9_$]{0,7}$'),
    CHECK (integration_prefix ~ '^[A-Z][A-Z0-9_$]{0,7}$'),
    CHECK (error_prefix ~ '^[A-Z][A-Z0-9_$]{0,7}$'),
    CHECK (loading_prefix <> integration_prefix AND loading_prefix <> error_prefix AND integration_prefix <> error_prefix)
);
CREATE UNIQUE INDEX uq_work_prefix_connection ON calisma_nesnesi_prefix(proje_id, baglanti_id) WHERE fiziksel_sema_id IS NULL;
CREATE UNIQUE INDEX uq_work_prefix_schema ON calisma_nesnesi_prefix(proje_id, fiziksel_sema_id) WHERE fiziksel_sema_id IS NOT NULL;
