SET search_path TO akis, public;

-- Registered identity, not prefix matching, controls lifecycle. No business database DDL here.
CREATE TABLE km_work_object (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
 proje_id BIGINT NOT NULL,
 calistirma_id BIGINT NOT NULL,
 generation BIGINT NOT NULL CHECK(generation > 0),
 worker_reference VARCHAR(200) NOT NULL,
 slot VARCHAR(64) NOT NULL CHECK(slot ~ '^[A-Z][A-Z0-9_]{0,63}$'),
 database_identity VARCHAR(512) NOT NULL,
 owner_name VARCHAR(128) NOT NULL,
 object_name VARCHAR(30) NOT NULL CHECK(object_name LIKE 'AKIS\_%' ESCAPE '\'),
 object_id BIGINT,
 structure_hash CHAR(64) NOT NULL CHECK(structure_hash ~ '^[0-9a-f]{64}$'),
 state VARCHAR(24) NOT NULL DEFAULT 'ALLOCATED' CHECK(state IN
   ('ALLOCATED','CREATING','READY','LOADING','SEALED','CONSUMED','CLEANUP_PENDING','DROPPED','REVIEW_REQUIRED')),
 row_count BIGINT CHECK(row_count >= 0),
 logical_bytes BIGINT CHECK(logical_bytes >= 0),
 payload_hash CHAR(64) CHECK(payload_hash ~ '^[0-9a-f]{64}$'),
 created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 UNIQUE(calistirma_id,generation,slot),
 UNIQUE(database_identity,owner_name,object_name),
 CHECK(state NOT IN ('SEALED','CONSUMED','CLEANUP_PENDING','DROPPED') OR
       (object_id IS NOT NULL AND row_count IS NOT NULL AND logical_bytes IS NOT NULL AND payload_hash IS NOT NULL))
);
CREATE INDEX ix_km_work_run ON km_work_object(proje_id,calistirma_id);
