SET search_path TO akis, public;

-- Statement execution and transaction durability are deliberately separate facts.
ALTER TABLE prosedur_adim_durumu
    ADD COLUMN transaction_outcome VARCHAR(30) NOT NULL DEFAULT 'NOT_ATTEMPTED',
    ADD COLUMN durable_commit_reference VARCHAR(200),
    ADD CONSTRAINT ck_prosedur_adim_transaction_outcome CHECK(transaction_outcome IN
      ('NOT_ATTEMPTED','EXECUTED_UNCOMMITTED','COMMIT_CONFIRMED','ROLLBACK_CONFIRMED','OUTCOME_UNKNOWN')),
    ADD CONSTRAINT ck_prosedur_adim_commit_reference CHECK(
      (transaction_outcome='COMMIT_CONFIRMED' AND durable_commit_reference IS NOT NULL)
      OR (transaction_outcome<>'COMMIT_CONFIRMED' AND durable_commit_reference IS NULL));

CREATE TABLE islem_grubu_kaniti (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
 proje_id BIGINT NOT NULL,
 is_talebi_id BIGINT NOT NULL,
 calistirma_id BIGINT NOT NULL,
 grup_kodu VARCHAR(100) NOT NULL,
 baglanti_surumu_uuid UUID NOT NULL,
 kanal INTEGER NOT NULL CHECK(kanal BETWEEN 0 AND 9),
 uye_adim_kodlari JSONB NOT NULL CHECK(jsonb_typeof(uye_adim_kodlari)='array'),
 izolasyon VARCHAR(30) NOT NULL,
 commit_siniri VARCHAR(30) NOT NULL CHECK(commit_siniri IN('PER_STATEMENT','END_OF_GROUP')),
 operasyon_anahtari_ozeti CHAR(64) NOT NULL CHECK(operasyon_anahtari_ozeti ~ '^[0-9a-f]{64}$'),
 runtime_plan_ozeti CHAR(64) NOT NULL CHECK(runtime_plan_ozeti ~ '^[0-9a-f]{64}$'),
 olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
 FOREIGN KEY(proje_id,is_talebi_id) REFERENCES is_talebi(proje_id,id),
 FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 UNIQUE(proje_id,id),
 UNIQUE(calistirma_id,grup_kodu),
 UNIQUE(is_talebi_id,operasyon_anahtari_ozeti)
);

CREATE TABLE islem_grubu_durumu (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
 proje_id BIGINT NOT NULL,
 islem_grubu_kaniti_id BIGINT NOT NULL,
 outcome VARCHAR(30) NOT NULL DEFAULT 'NOT_ATTEMPTED' CHECK(outcome IN
   ('NOT_ATTEMPTED','EXECUTED_UNCOMMITTED','COMMIT_CONFIRMED','ROLLBACK_CONFIRMED','OUTCOME_UNKNOWN')),
 dispatch_zamani TIMESTAMPTZ,
 sonuc_zamani TIMESTAMPTZ,
 durable_commit_reference VARCHAR(200),
 hata_kodu VARCHAR(100),
 versiyon_no BIGINT NOT NULL DEFAULT 1 CHECK(versiyon_no>0),
 guncellenme_zamani TIMESTAMPTZ,
 FOREIGN KEY(proje_id,islem_grubu_kaniti_id) REFERENCES islem_grubu_kaniti(proje_id,id),
 UNIQUE(islem_grubu_kaniti_id),
 CHECK((outcome='COMMIT_CONFIRMED' AND durable_commit_reference IS NOT NULL)
       OR (outcome<>'COMMIT_CONFIRMED' AND durable_commit_reference IS NULL))
);
CREATE TRIGGER trg_islem_grubu_kaniti_degismez
 BEFORE UPDATE OR DELETE ON islem_grubu_kaniti
 FOR EACH ROW EXECUTE FUNCTION degismez_calistirma_kanitini_koru();

CREATE INDEX ix_islem_grubu_run ON islem_grubu_kaniti(proje_id,calistirma_id);

-- Read-only receipt lookup is separate from dispatch authorization. Every mutating
-- transition below re-checks the current worker/lease/run/target generation tuple.
CREATE FUNCTION prosedur_islem_grubunu_yurutuldu_isaretle(
 p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_calistirma_nesil_no BIGINT,
 p_hedef_kaynagi_uuid UUID,p_hedef_nesil_no BIGINT,p_grup_kodu TEXT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE;v_d calistirma_durumu%ROWTYPE;v_h hedef_kaynagi%ROWTYPE;
 v_g islem_grubu_kaniti%ROWTYPE;v_s islem_grubu_durumu%ROWTYPE;
BEGIN
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid; IF NOT FOUND THEN RETURN FALSE;END IF;
 SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 IF NOT FOUND THEN RETURN FALSE;END IF;
 SELECT * INTO v_h FROM hedef_kaynagi WHERE id=v_d.hedef_kaynagi_id AND uuid=p_hedef_kaynagi_uuid FOR UPDATE;
 IF NOT FOUND THEN RETURN FALSE;END IF;
 SELECT * INTO v_g FROM islem_grubu_kaniti WHERE calistirma_id=v_c.id AND grup_kodu=p_grup_kodu;
 IF NOT FOUND THEN RETURN FALSE;END IF;
 SELECT * INTO v_s FROM islem_grubu_durumu WHERE islem_grubu_kaniti_id=v_g.id FOR UPDATE;
 IF NOT FOUND THEN RETURN FALSE;END IF;
 IF v_d.durum<>'CALISIYOR' OR v_d.nesil_no<>p_calistirma_nesil_no
    OR v_d.isleyici_referansi<>p_isleyici_referansi OR v_d.kiralama_bitis_zamani<=clock_timestamp()
    OR v_h.durum<>'SAHIPLENILDI' OR v_h.calistirma_id<>v_c.id
    OR v_h.nesil_no<>p_hedef_nesil_no OR v_h.kiralama_bitis_zamani<=clock_timestamp()
    OR v_s.outcome NOT IN('NOT_ATTEMPTED','EXECUTED_UNCOMMITTED') THEN RETURN FALSE;END IF;
 UPDATE islem_grubu_durumu SET outcome='EXECUTED_UNCOMMITTED',
   dispatch_zamani=coalesce(dispatch_zamani,clock_timestamp()),guncellenme_zamani=clock_timestamp(),
   versiyon_no=versiyon_no+1 WHERE id=v_s.id;
 UPDATE prosedur_adim_durumu sd SET transaction_outcome='EXECUTED_UNCOMMITTED',
   durable_commit_reference=NULL,guncellenme_zamani=clock_timestamp(),versiyon_no=sd.versiyon_no+1
 FROM calistirma_adimi a WHERE a.id=sd.calistirma_adimi_id AND a.calistirma_id=v_c.id
   AND a.adim_kodu IN(SELECT jsonb_array_elements_text(v_g.uye_adim_kodlari));
 RETURN TRUE;
END $$;

CREATE FUNCTION prosedur_islem_grubunu_sonlandir(
 p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_calistirma_nesil_no BIGINT,
 p_hedef_kaynagi_uuid UUID,p_hedef_nesil_no BIGINT,p_grup_kodu TEXT,
 p_outcome TEXT,p_commit_reference TEXT,p_hata_kodu TEXT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE;v_d calistirma_durumu%ROWTYPE;v_h hedef_kaynagi%ROWTYPE;
 v_g islem_grubu_kaniti%ROWTYPE;v_s islem_grubu_durumu%ROWTYPE;
BEGIN
 IF p_outcome NOT IN('COMMIT_CONFIRMED','ROLLBACK_CONFIRMED','OUTCOME_UNKNOWN') THEN RETURN FALSE;END IF;
 IF (p_outcome='COMMIT_CONFIRMED')<>(p_commit_reference IS NOT NULL AND length(p_commit_reference)>0) THEN RETURN FALSE;END IF;
 IF p_commit_reference IS NOT NULL AND length(p_commit_reference)>200 THEN RETURN FALSE;END IF;
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid; IF NOT FOUND THEN RETURN FALSE;END IF;
 SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 IF NOT FOUND THEN RETURN FALSE;END IF;
 SELECT * INTO v_h FROM hedef_kaynagi WHERE id=v_d.hedef_kaynagi_id AND uuid=p_hedef_kaynagi_uuid FOR UPDATE;
 IF NOT FOUND THEN RETURN FALSE;END IF;
 SELECT * INTO v_g FROM islem_grubu_kaniti WHERE calistirma_id=v_c.id AND grup_kodu=p_grup_kodu;
 IF NOT FOUND THEN RETURN FALSE;END IF;
 SELECT * INTO v_s FROM islem_grubu_durumu WHERE islem_grubu_kaniti_id=v_g.id FOR UPDATE;
 IF NOT FOUND THEN RETURN FALSE;END IF;
 IF v_d.durum<>'CALISIYOR' OR v_d.nesil_no<>p_calistirma_nesil_no
    OR v_d.isleyici_referansi<>p_isleyici_referansi
    OR v_d.kiralama_bitis_zamani<=clock_timestamp()
    OR v_h.durum<>'SAHIPLENILDI' OR v_h.nesil_no<>p_hedef_nesil_no
    OR v_h.calistirma_id<>v_c.id OR v_h.kiralama_bitis_zamani<=clock_timestamp()
    THEN RETURN FALSE;END IF;
 IF v_s.outcome=p_outcome THEN RETURN (p_outcome<>'COMMIT_CONFIRMED'
    OR v_s.durable_commit_reference=p_commit_reference);END IF;
 IF v_s.outcome<>'EXECUTED_UNCOMMITTED' THEN RETURN FALSE;END IF;
 UPDATE islem_grubu_durumu SET outcome=p_outcome,sonuc_zamani=clock_timestamp(),
   durable_commit_reference=p_commit_reference,hata_kodu=p_hata_kodu,
   guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_s.id;
 UPDATE prosedur_adim_durumu sd SET transaction_outcome=p_outcome,
   durable_commit_reference=p_commit_reference,guncellenme_zamani=clock_timestamp(),versiyon_no=sd.versiyon_no+1
 FROM calistirma_adimi a WHERE a.id=sd.calistirma_adimi_id AND a.calistirma_id=v_c.id
   AND a.adim_kodu IN(SELECT jsonb_array_elements_text(v_g.uye_adim_kodlari));
 RETURN TRUE;
END $$;

REVOKE ALL ON FUNCTION prosedur_islem_grubunu_yurutuldu_isaretle(UUID,TEXT,BIGINT,UUID,BIGINT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION prosedur_islem_grubunu_sonlandir(UUID,TEXT,BIGINT,UUID,BIGINT,TEXT,TEXT,TEXT,TEXT) FROM PUBLIC;
