SET search_path TO akis, public;

CREATE TABLE calistirma_girdi_goruntusu (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
 proje_id BIGINT NOT NULL,
 is_talebi_id BIGINT NOT NULL,
 calistirma_id BIGINT NOT NULL,
 sozlesme_surumu INTEGER NOT NULL CHECK(sozlesme_surumu>0),
 yayin_ozeti CHAR(64) NOT NULL CHECK(yayin_ozeti ~ '^[0-9a-f]{64}$'),
 runtime_plan_ozeti CHAR(64) NOT NULL CHECK(runtime_plan_ozeti ~ '^[0-9a-f]{64}$'),
 tanim_surumu_uuid UUID NOT NULL,
 degisken_surumleri JSONB CHECK(degisken_surumleri IS NULL OR jsonb_typeof(degisken_surumleri)='array'),
 tipli_parametreler JSONB CHECK(tipli_parametreler IS NULL OR jsonb_typeof(tipli_parametreler)='object'),
 cozulmus_degiskenler JSONB CHECK(cozulmus_degiskenler IS NULL OR jsonb_typeof(cozulmus_degiskenler)='object'),
 binding_surumu_uuids JSONB CHECK(binding_surumu_uuids IS NULL OR jsonb_typeof(binding_surumu_uuids)='array'),
 kaynak_scn VARCHAR(100),
 kaynak_goruntu_ozeti CHAR(64),
 girdi_ozeti CHAR(64) CHECK(girdi_ozeti ~ '^[0-9a-f]{64}$'),
 cozumleme_tokeni UUID NOT NULL,
 versiyon_no BIGINT NOT NULL DEFAULT 1 CHECK(versiyon_no>0),
 durum VARCHAR(20) NOT NULL CHECK(durum IN('RESOLVING','COMPLETE','FAILED')),
 olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 tamamlanma_zamani TIMESTAMPTZ,
 olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
 FOREIGN KEY(proje_id,is_talebi_id) REFERENCES is_talebi(proje_id,id),
 FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 UNIQUE(proje_id,id),
 UNIQUE(is_talebi_id),
 UNIQUE(calistirma_id),
 CHECK((durum='COMPLETE' AND tamamlanma_zamani IS NOT NULL AND girdi_ozeti IS NOT NULL
        AND degisken_surumleri IS NOT NULL AND tipli_parametreler IS NOT NULL
        AND cozulmus_degiskenler IS NOT NULL AND binding_surumu_uuids IS NOT NULL)
       OR (durum<>'COMPLETE' AND tamamlanma_zamani IS NULL)),
 CHECK((kaynak_scn IS NULL AND kaynak_goruntu_ozeti IS NULL)
       OR (kaynak_scn IS NOT NULL AND kaynak_goruntu_ozeti ~ '^[0-9a-f]{64}$'))
);

CREATE TABLE kurtarma_talebi (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
 proje_id BIGINT NOT NULL,
 is_talebi_id BIGINT NOT NULL,
 onceki_calistirma_id BIGINT NOT NULL,
 yeni_calistirma_id BIGINT,
 eylem VARCHAR(30) NOT NULL CHECK(eylem IN
   ('RETRY_FAILED_UNIT','RESUME','RESTART','CANCEL','RECONCILE')),
 kanit_surumu INTEGER NOT NULL CHECK(kanit_surumu>0),
 beklenen_durum_surumu BIGINT NOT NULL CHECK(beklenen_durum_surumu>=0),
 plan_ozeti CHAR(64) NOT NULL CHECK(plan_ozeti ~ '^[0-9a-f]{64}$'),
 karar_ozeti CHAR(64) NOT NULL CHECK(karar_ozeti ~ '^[0-9a-f]{64}$'),
 istek_ozeti CHAR(64) NOT NULL CHECK(istek_ozeti ~ '^[0-9a-f]{64}$'),
 idempotency_anahtar_ozeti CHAR(64) NOT NULL CHECK(idempotency_anahtar_ozeti ~ '^[0-9a-f]{64}$'),
 birimler JSONB NOT NULL CHECK(jsonb_typeof(birimler)='array'),
 nedenler JSONB NOT NULL CHECK(jsonb_typeof(nedenler)='array'),
 durum VARCHAR(20) NOT NULL DEFAULT 'REQUESTED' CHECK(durum IN
   ('REQUESTED','APPLIED','REJECTED','STALE')),
 olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 olusturan_kullanici_id BIGINT NOT NULL REFERENCES kullanici(id),
 FOREIGN KEY(proje_id,is_talebi_id) REFERENCES is_talebi(proje_id,id),
 FOREIGN KEY(proje_id,onceki_calistirma_id) REFERENCES calistirma(proje_id,id),
 FOREIGN KEY(proje_id,yeni_calistirma_id) REFERENCES calistirma(proje_id,id),
 UNIQUE(proje_id,id),
 UNIQUE(proje_id,onceki_calistirma_id,olusturan_kullanici_id,idempotency_anahtar_ozeti),
 CHECK((durum='APPLIED' AND eylem IN('RETRY_FAILED_UNIT','RESUME','RESTART')
        AND yeni_calistirma_id IS NOT NULL)
       OR (durum='APPLIED' AND eylem IN('CANCEL','RECONCILE'))
       OR (durum<>'APPLIED' AND yeni_calistirma_id IS NULL))
);

CREATE TABLE veri_yukleme_plani (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
 proje_id BIGINT NOT NULL,
 is_talebi_id BIGINT NOT NULL,
 adim_kodu VARCHAR(100) NOT NULL,
 girdi_goruntusu_id BIGINT NOT NULL,
 sozlesme_surumu INTEGER NOT NULL CHECK(sozlesme_surumu>0),
 kaynak_scn VARCHAR(100) NOT NULL,
 kaynak_sozlesmesi JSONB NOT NULL CHECK(jsonb_typeof(kaynak_sozlesmesi)='object'),
 hedef_sozlesmesi JSONB NOT NULL CHECK(jsonb_typeof(hedef_sozlesmesi)='object'),
 anahtar_sozlesmesi JSONB NOT NULL CHECK(jsonb_typeof(anahtar_sozlesmesi)='object'),
 bolumleme_surumu VARCHAR(50) NOT NULL,
 satir_butcesi BIGINT NOT NULL CHECK(satir_butcesi>0),
 bayt_butcesi BIGINT NOT NULL CHECK(bayt_butcesi>0),
 plan_ozeti CHAR(64) NOT NULL CHECK(plan_ozeti ~ '^[0-9a-f]{64}$'),
 olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(proje_id,is_talebi_id) REFERENCES is_talebi(proje_id,id),
 FOREIGN KEY(proje_id,girdi_goruntusu_id) REFERENCES calistirma_girdi_goruntusu(proje_id,id),
 UNIQUE(proje_id,id),
 UNIQUE(is_talebi_id,adim_kodu)
);

CREATE TABLE yukleme_bolumu (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
 proje_id BIGINT NOT NULL,
 veri_yukleme_plani_id BIGINT NOT NULL,
 bolum_kodu VARCHAR(80) NOT NULL,
 alt_sinir JSONB,
 ust_sinir JSONB,
 durum VARCHAR(20) NOT NULL DEFAULT 'PLANNED' CHECK(durum IN
   ('PLANNED','ACTIVE','COMPLETE','FAILED','BLOCKED')),
 olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(proje_id,veri_yukleme_plani_id) REFERENCES veri_yukleme_plani(proje_id,id),
 UNIQUE(proje_id,id),
 UNIQUE(veri_yukleme_plani_id,bolum_kodu),
 CHECK((alt_sinir IS NULL OR jsonb_typeof(alt_sinir)='object')
       AND (ust_sinir IS NULL OR jsonb_typeof(ust_sinir)='object'))
);

CREATE TABLE yukleme_parcasi (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
 proje_id BIGINT NOT NULL,
 yukleme_bolumu_id BIGINT NOT NULL,
 workspace_uuid UUID NOT NULL,
 sira_no BIGINT NOT NULL CHECK(sira_no>0),
 work_unit_key CHAR(64) NOT NULL CHECK(work_unit_key ~ '^[0-9a-f]{64}$'),
 runtime_plan_ozeti CHAR(64) NOT NULL CHECK(runtime_plan_ozeti ~ '^[0-9a-f]{64}$'),
 girdi_ozeti CHAR(64) NOT NULL CHECK(girdi_ozeti ~ '^[0-9a-f]{64}$'),
 alt_sinir JSONB,
 ust_sinir JSONB,
 son_anahtar JSONB,
 payload_ozeti CHAR(64) NOT NULL CHECK(payload_ozeti ~ '^[0-9a-f]{64}$'),
 girdi_satir_sayisi BIGINT NOT NULL CHECK(girdi_satir_sayisi>=0),
 girdi_bayt_sayisi BIGINT NOT NULL CHECK(girdi_bayt_sayisi>=0),
 hedef_defter_referansi VARCHAR(200),
 son_hata_kodu VARCHAR(100),
 durum VARCHAR(30) NOT NULL DEFAULT 'INTENT_RECORDED' CHECK(durum IN
   ('INTENT_RECORDED','DISPATCHED','COMMIT_CONFIRMED','ROLLBACK_CONFIRMED','OUTCOME_UNKNOWN','BLOCKED')),
 kontrol_noktasi_id BIGINT REFERENCES kontrol_noktasi(id),
 olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(proje_id,yukleme_bolumu_id) REFERENCES yukleme_bolumu(proje_id,id),
 UNIQUE(proje_id,id),
 UNIQUE(yukleme_bolumu_id,sira_no),
 UNIQUE(work_unit_key),
 CHECK((alt_sinir IS NULL OR jsonb_typeof(alt_sinir)='object')
       AND (ust_sinir IS NULL OR jsonb_typeof(ust_sinir)='object')
       AND (son_anahtar IS NULL OR jsonb_typeof(son_anahtar)='object')),
 CHECK((durum='COMMIT_CONFIRMED' AND hedef_defter_referansi IS NOT NULL AND son_hata_kodu IS NULL)
       OR (durum IN('ROLLBACK_CONFIRMED','OUTCOME_UNKNOWN','BLOCKED') AND son_hata_kodu IS NOT NULL AND hedef_defter_referansi IS NULL)
       OR (durum IN('INTENT_RECORDED','DISPATCHED') AND hedef_defter_referansi IS NULL AND son_hata_kodu IS NULL))
);

CREATE TABLE yukleme_parca_deneme (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
 proje_id BIGINT NOT NULL,
 yukleme_parcasi_id BIGINT NOT NULL,
 calistirma_id BIGINT NOT NULL,
 deneme_no INTEGER NOT NULL CHECK(deneme_no>0),
 calistirma_nesil_no BIGINT NOT NULL CHECK(calistirma_nesil_no>0),
 isleyici_referansi VARCHAR(200) NOT NULL,
 outcome VARCHAR(30) NOT NULL CHECK(outcome IN
   ('NOT_ATTEMPTED','EXECUTED_UNCOMMITTED','COMMIT_CONFIRMED','ROLLBACK_CONFIRMED','OUTCOME_UNKNOWN')),
 baslama_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 bitis_zamani TIMESTAMPTZ,
 hata_kodu VARCHAR(100),
 FOREIGN KEY(proje_id,yukleme_parcasi_id) REFERENCES yukleme_parcasi(proje_id,id),
 FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 UNIQUE(yukleme_parcasi_id,calistirma_id,deneme_no)
);

CREATE TRIGGER trg_veri_yukleme_plani_degismez BEFORE UPDATE OR DELETE ON veri_yukleme_plani
 FOR EACH ROW EXECUTE FUNCTION degismez_calistirma_kanitini_koru();
CREATE INDEX ix_kurtarma_onceki ON kurtarma_talebi(proje_id,onceki_calistirma_id,olusturulma_zamani DESC);
CREATE INDEX ix_yukleme_parcasi_cursor ON yukleme_parcasi(yukleme_bolumu_id,sira_no);
CREATE INDEX ix_yukleme_deneme_run ON yukleme_parca_deneme(proje_id,calistirma_id,id);
