SET search_path TO akis, public;

ALTER TABLE km_work_object DROP CONSTRAINT IF EXISTS km_work_object_state_check;
ALTER TABLE km_work_object ADD CONSTRAINT ck_km_work_object_state CHECK(state IN
 ('ALLOCATED','RESERVED','CREATING','READY','LOADING','LOADED','SEALED','VALIDATED',
  'PUBLISHED','CONSUMED','CLEANUP_PENDING','CLEANED','DROPPED','OUTCOME_UNKNOWN',
  'QUARANTINED','REVIEW_REQUIRED'));
ALTER TABLE km_work_object
 ADD COLUMN workspace_uuid UUID NOT NULL DEFAULT gen_random_uuid(),
 ADD COLUMN ddl_lock_reference VARCHAR(200),
 ADD COLUMN retention_until TIMESTAMPTZ,
 ADD COLUMN cleanup_allowed BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN lifecycle_version BIGINT NOT NULL DEFAULT 1 CHECK(lifecycle_version>0),
 ADD CONSTRAINT uq_km_work_workspace_slot UNIQUE(workspace_uuid,slot),
 ADD CONSTRAINT ck_km_work_cleanup CHECK(
   NOT cleanup_allowed OR state IN('CLEANUP_PENDING','CLEANED','DROPPED'));

CREATE TABLE km_work_object_lifecycle_event (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
 proje_id BIGINT NOT NULL,
 calistirma_id BIGINT NOT NULL,
 km_work_object_id BIGINT NOT NULL REFERENCES km_work_object(id),
 event_number BIGINT NOT NULL CHECK(event_number>0),
 from_state VARCHAR(24),
 to_state VARCHAR(24) NOT NULL,
 owner_generation BIGINT NOT NULL CHECK(owner_generation>0),
 worker_reference VARCHAR(200) NOT NULL,
 database_object_id BIGINT,
 structure_hash CHAR(64) NOT NULL CHECK(structure_hash ~ '^[0-9a-f]{64}$'),
 reason_code VARCHAR(100),
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
 FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id),
 UNIQUE(km_work_object_id,event_number)
);
CREATE TRIGGER trg_km_work_lifecycle_degismez
 BEFORE UPDATE OR DELETE ON km_work_object_lifecycle_event
 FOR EACH ROW EXECUTE FUNCTION degismez_calistirma_kanitini_koru();

CREATE INDEX ix_km_work_retention
 ON km_work_object(state,retention_until)
 WHERE state IN('CLEANUP_PENDING','OUTCOME_UNKNOWN','QUARANTINED','REVIEW_REQUIRED');
