SET search_path TO akis, public;

CREATE TABLE calisma_prefix_migration_kaydi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    baglanti_id BIGINT NOT NULL,
    durum VARCHAR(20) NOT NULL CHECK (durum IN ('TASINDI','SECIM_GEREKLI')),
    eski_degerler JSONB NOT NULL,
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (proje_id,baglanti_id) REFERENCES baglanti(proje_id,id)
);

INSERT INTO calisma_prefix_migration_kaydi(proje_id,baglanti_id,durum,eski_degerler)
SELECT p.proje_id,fs.baglanti_id,
       CASE WHEN count(DISTINCT (p.loading_prefix,p.integration_prefix,p.error_prefix))=1 THEN 'TASINDI' ELSE 'SECIM_GEREKLI' END,
       jsonb_agg(jsonb_build_object('physicalSchemaId',p.fiziksel_sema_id,'loading',p.loading_prefix,'integration',p.integration_prefix,'error',p.error_prefix) ORDER BY p.fiziksel_sema_id)
  FROM calisma_nesnesi_prefix p
  JOIN fiziksel_sema fs ON fs.proje_id=p.proje_id AND fs.id=p.fiziksel_sema_id
 WHERE p.fiziksel_sema_id IS NOT NULL
 GROUP BY p.proje_id,fs.baglanti_id;

INSERT INTO calisma_nesnesi_prefix(proje_id,baglanti_id,fiziksel_sema_id,loading_prefix,integration_prefix,error_prefix)
SELECT p.proje_id,fs.baglanti_id,NULL,min(p.loading_prefix),min(p.integration_prefix),min(p.error_prefix)
  FROM calisma_nesnesi_prefix p
  JOIN fiziksel_sema fs ON fs.proje_id=p.proje_id AND fs.id=p.fiziksel_sema_id
 WHERE p.fiziksel_sema_id IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM calisma_nesnesi_prefix c WHERE c.proje_id=p.proje_id AND c.baglanti_id=fs.baglanti_id AND c.fiziksel_sema_id IS NULL)
 GROUP BY p.proje_id,fs.baglanti_id
HAVING count(DISTINCT (p.loading_prefix,p.integration_prefix,p.error_prefix))=1;

DELETE FROM calisma_nesnesi_prefix WHERE fiziksel_sema_id IS NOT NULL;

DROP INDEX IF EXISTS uq_work_prefix_schema;

ALTER TABLE calisma_nesnesi_prefix
    ADD CONSTRAINT ck_work_prefix_connection_scope
    CHECK (fiziksel_sema_id IS NULL);
