-- Sistem genelinde (proje bağımsız) veritabanı yapı metadatasını tutan tanım katmanı.
-- Şema -> tablo -> kolon -> kısıt -> ilişki -> indeks -> sequence hiyerarşisini temsil eder.
-- Bu tablolar kendi kendini de belgeler: kendi şema/tablo/kolon kayıtları
-- akis.tablo_tanimlari / akis.kolon_tanimlari içine eklenir.
--
-- Standart kolon sırası (bu dosyadaki ve sonraki tüm *_tanimlari tabloları için):
--   1) id
--   2) üst tabloya FK (varsa)
--   3) sira_no (üst içinde sıralama gerekiyorsa)
--   4) ad
--   5) aciklama
--   6) tabloya özgü diğer iş alanları
--   7) audit bloğu (hep bu sırayla): uuid, olusturulma_zamani, olusturan_kullanici_id,
--      guncellenme_zamani, guncelleyen_kullanici_id

CREATE TABLE akis.sema_tanimlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    CONSTRAINT pk_sema_tanimlari PRIMARY KEY (id),
    CONSTRAINT uq_sema_tanimlari_uuid UNIQUE (uuid),
    CONSTRAINT uq_sema_tanimlari_ad UNIQUE (ad),
    CONSTRAINT ck_sema_tanimlari_ad CHECK (ad ~ '^[a-z][a-z0-9_]{0,99}$'),
    CONSTRAINT ck_sema_tanimlari_audit CHECK (
        guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani
    )
);

COMMENT ON TABLE akis.sema_tanimlari IS 'Sistemdeki veritabanı şemalarının (namespace) metadata tanımı.';
COMMENT ON COLUMN akis.sema_tanimlari.id IS 'Yüzeysel (surrogate) birincil anahtar.';
COMMENT ON COLUMN akis.sema_tanimlari.ad IS 'Veritabanındaki gerçek şema adı (ayrı bir kod/etiket tutulmaz).';
COMMENT ON COLUMN akis.sema_tanimlari.aciklama IS 'Şemanın iş amacı/kapsamı.';
COMMENT ON COLUMN akis.sema_tanimlari.uuid IS 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.';
COMMENT ON COLUMN akis.sema_tanimlari.olusturulma_zamani IS 'Kaydın oluşturulma zamanı.';
COMMENT ON COLUMN akis.sema_tanimlari.olusturan_kullanici_id IS 'Kaydı oluşturan kullanıcı.';
COMMENT ON COLUMN akis.sema_tanimlari.guncellenme_zamani IS 'Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).';
COMMENT ON COLUMN akis.sema_tanimlari.guncelleyen_kullanici_id IS 'Kaydı son güncelleyen kullanıcı.';

INSERT INTO akis.sema_tanimlari (ad, aciklama) VALUES
    ('akis', 'Akış uygulamasının kendi Postgres şeması (akis-baseline migration''larıyla oluşan tüm tablolar).');

CREATE TABLE akis.tablo_tanimlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sema_tanimi_id BIGINT NOT NULL REFERENCES akis.sema_tanimlari(id),
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    CONSTRAINT pk_tablo_tanimlari PRIMARY KEY (id),
    CONSTRAINT uq_tablo_tanimlari_uuid UNIQUE (uuid),
    CONSTRAINT uq_tablo_tanimlari_sema_ad UNIQUE (sema_tanimi_id, ad),
    CONSTRAINT ck_tablo_tanimlari_ad CHECK (ad ~ '^[a-z][a-z0-9_]{0,99}$'),
    CONSTRAINT ck_tablo_tanimlari_audit CHECK (
        guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani
    )
);

COMMENT ON TABLE akis.tablo_tanimlari IS 'Bir şemaya ait tabloların metadata tanımı.';
COMMENT ON COLUMN akis.tablo_tanimlari.id IS 'Yüzeysel (surrogate) birincil anahtar.';
COMMENT ON COLUMN akis.tablo_tanimlari.sema_tanimi_id IS 'Ait olduğu şema tanımı.';
COMMENT ON COLUMN akis.tablo_tanimlari.ad IS 'Veritabanındaki gerçek tablo adı (ayrı bir kod/etiket tutulmaz).';
COMMENT ON COLUMN akis.tablo_tanimlari.aciklama IS 'Tablonun iş amacı/kapsamı.';
COMMENT ON COLUMN akis.tablo_tanimlari.uuid IS 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.';
COMMENT ON COLUMN akis.tablo_tanimlari.olusturulma_zamani IS 'Kaydın oluşturulma zamanı.';
COMMENT ON COLUMN akis.tablo_tanimlari.olusturan_kullanici_id IS 'Kaydı oluşturan kullanıcı.';
COMMENT ON COLUMN akis.tablo_tanimlari.guncellenme_zamani IS 'Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).';
COMMENT ON COLUMN akis.tablo_tanimlari.guncelleyen_kullanici_id IS 'Kaydı son güncelleyen kullanıcı.';

-- Self-hosting: bu metadata sisteminin kendi tabloları da tablo_tanimlari içinde belgelenir.
INSERT INTO akis.tablo_tanimlari (sema_tanimi_id, ad, aciklama)
SELECT s.id, v.ad, v.aciklama
FROM akis.sema_tanimlari s
CROSS JOIN (VALUES
    ('sema_tanimlari', 'Sistemdeki veritabanı şemalarının (namespace) metadata tanımını tutar.'),
    ('tablo_tanimlari', 'Sistemdeki tüm tabloların/view''ların metadata tanımını tutar.')
) AS v(ad, aciklama)
WHERE s.ad = 'akis';

CREATE TABLE akis.kolon_tanimlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tablo_tanimi_id BIGINT NOT NULL REFERENCES akis.tablo_tanimlari(id),
    sira_no INTEGER NOT NULL,
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    veri_tipi VARCHAR(40) NOT NULL,
    uzunluk BIGINT,
    zorunlu_mu BOOLEAN NOT NULL DEFAULT FALSE,
    varsayilan_deger VARCHAR(500),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    CONSTRAINT pk_kolon_tanimlari PRIMARY KEY (id),
    CONSTRAINT uq_kolon_tanimlari_uuid UNIQUE (uuid),
    CONSTRAINT uq_kolon_tanimlari_tablo_ad UNIQUE (tablo_tanimi_id, ad),
    CONSTRAINT uq_kolon_tanimlari_tablo_sira UNIQUE (tablo_tanimi_id, sira_no),
    CONSTRAINT ck_kolon_tanimlari_ad CHECK (ad ~ '^[a-z][a-z0-9_]{0,99}$'),
    CONSTRAINT ck_kolon_tanimlari_sira_no CHECK (sira_no > 0),
    CONSTRAINT ck_kolon_tanimlari_audit CHECK (
        guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani
    )
);

COMMENT ON TABLE akis.kolon_tanimlari IS 'Bir tabloya ait kolonların veri yapısı metadata tanımı.';
COMMENT ON COLUMN akis.kolon_tanimlari.id IS 'Yüzeysel (surrogate) birincil anahtar.';
COMMENT ON COLUMN akis.kolon_tanimlari.tablo_tanimi_id IS 'Ait olduğu tablo tanımı.';
COMMENT ON COLUMN akis.kolon_tanimlari.ad IS 'Veritabanındaki gerçek kolon adı (ayrı bir kod/etiket tutulmaz).';
COMMENT ON COLUMN akis.kolon_tanimlari.aciklama IS 'Kolonun iş anlamı.';
COMMENT ON COLUMN akis.kolon_tanimlari.veri_tipi IS 'Postgres veri tipi adı (örn. bigint, character varying, uuid, timestamptz, text, boolean).';
COMMENT ON COLUMN akis.kolon_tanimlari.uzunluk IS 'Karakter/byte uzunluğu (varsa).';
COMMENT ON COLUMN akis.kolon_tanimlari.zorunlu_mu IS 'NOT NULL kısıtına tabi mi.';
COMMENT ON COLUMN akis.kolon_tanimlari.varsayilan_deger IS 'DEFAULT ifadesi (varsa), metin olarak.';
COMMENT ON COLUMN akis.kolon_tanimlari.sira_no IS 'Tablo içindeki sütun sırası.';
COMMENT ON COLUMN akis.kolon_tanimlari.uuid IS 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.';
COMMENT ON COLUMN akis.kolon_tanimlari.olusturulma_zamani IS 'Kaydın oluşturulma zamanı.';
COMMENT ON COLUMN akis.kolon_tanimlari.olusturan_kullanici_id IS 'Kaydı oluşturan kullanıcı.';
COMMENT ON COLUMN akis.kolon_tanimlari.guncellenme_zamani IS 'Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).';
COMMENT ON COLUMN akis.kolon_tanimlari.guncelleyen_kullanici_id IS 'Kaydı son güncelleyen kullanıcı.';

-- Self-hosting: sema_tanimlari tablosunun kendi kolonları.
INSERT INTO akis.kolon_tanimlari (
    tablo_tanimi_id, ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no
)
SELECT t.id, v.ad, v.aciklama, v.veri_tipi, v.uzunluk, v.zorunlu_mu, v.varsayilan_deger, v.sira_no
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('id', 'Yüzeysel (surrogate) birincil anahtar.', 'bigint', NULL::BIGINT, TRUE, 'identity', 1),
    ('ad', 'Veritabanındaki gerçek şema adı.', 'character varying', 200, TRUE, NULL, 2),
    ('aciklama', 'Şemanın iş amacı/kapsamı.', 'character varying', 2000, FALSE, NULL, 3),
    ('uuid', 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.', 'uuid', NULL, TRUE, 'gen_random_uuid()', 4),
    ('olusturulma_zamani', 'Kaydın oluşturulma zamanı.', 'timestamptz', NULL, TRUE, 'CURRENT_TIMESTAMP', 5),
    ('olusturan_kullanici_id', 'Kaydı oluşturan kullanıcı.', 'bigint', NULL, FALSE, NULL, 6),
    ('guncellenme_zamani', 'Kaydın son güncellenme zamanı.', 'timestamptz', NULL, FALSE, NULL, 7),
    ('guncelleyen_kullanici_id', 'Kaydı son güncelleyen kullanıcı.', 'bigint', NULL, FALSE, NULL, 8)
) AS v(ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no)
WHERE t.ad = 'sema_tanimlari';

-- Self-hosting: tablo_tanimlari tablosunun kendi kolonları.
INSERT INTO akis.kolon_tanimlari (
    tablo_tanimi_id, ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no
)
SELECT t.id, v.ad, v.aciklama, v.veri_tipi, v.uzunluk, v.zorunlu_mu, v.varsayilan_deger, v.sira_no
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('id', 'Yüzeysel (surrogate) birincil anahtar.', 'bigint', NULL::BIGINT, TRUE, 'identity', 1),
    ('sema_tanimi_id', 'Ait olduğu şema tanımı.', 'bigint', NULL, TRUE, NULL, 2),
    ('ad', 'Veritabanındaki gerçek tablo adı.', 'character varying', 200, TRUE, NULL, 3),
    ('aciklama', 'Tablonun iş amacı/kapsamı.', 'character varying', 2000, FALSE, NULL, 4),
    ('uuid', 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.', 'uuid', NULL, TRUE, 'gen_random_uuid()', 5),
    ('olusturulma_zamani', 'Kaydın oluşturulma zamanı.', 'timestamptz', NULL, TRUE, 'CURRENT_TIMESTAMP', 6),
    ('olusturan_kullanici_id', 'Kaydı oluşturan kullanıcı.', 'bigint', NULL, FALSE, NULL, 7),
    ('guncellenme_zamani', 'Kaydın son güncellenme zamanı.', 'timestamptz', NULL, FALSE, NULL, 8),
    ('guncelleyen_kullanici_id', 'Kaydı son güncelleyen kullanıcı.', 'bigint', NULL, FALSE, NULL, 9)
) AS v(ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no)
WHERE t.ad = 'tablo_tanimlari';

-- Self-hosting: kolon_tanimlari tablosunun kendisi de tablo_tanimlari'na eklenir.
INSERT INTO akis.tablo_tanimlari (sema_tanimi_id, ad, aciklama)
SELECT s.id, 'kolon_tanimlari', 'Sistemdeki tüm tabloların kolonlarının veri yapısı metadata tanımını tutar.'
FROM akis.sema_tanimlari s
WHERE s.ad = 'akis';

-- Self-hosting: kolon_tanimlari tablosunun kendi kolonları.
INSERT INTO akis.kolon_tanimlari (
    tablo_tanimi_id, ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no
)
SELECT t.id, v.ad, v.aciklama, v.veri_tipi, v.uzunluk, v.zorunlu_mu, v.varsayilan_deger, v.sira_no
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('id', 'Yüzeysel (surrogate) birincil anahtar.', 'bigint', NULL::BIGINT, TRUE, 'identity', 1),
    ('tablo_tanimi_id', 'Ait olduğu tablo tanımı.', 'bigint', NULL, TRUE, NULL, 2),
    ('sira_no', 'Tablo içindeki sütun sırası.', 'integer', NULL, TRUE, NULL, 3),
    ('ad', 'Veritabanındaki gerçek kolon adı.', 'character varying', 200, TRUE, NULL, 4),
    ('aciklama', 'Kolonun iş anlamı.', 'character varying', 2000, FALSE, NULL, 5),
    ('veri_tipi', 'Postgres veri tipi adı.', 'character varying', 40, TRUE, NULL, 6),
    ('uzunluk', 'Karakter/byte uzunluğu (varsa).', 'bigint', NULL, FALSE, NULL, 7),
    ('zorunlu_mu', 'NOT NULL kısıtına tabi mi.', 'boolean', NULL, TRUE, 'false', 8),
    ('varsayilan_deger', 'DEFAULT ifadesi (varsa), metin olarak.', 'character varying', 500, FALSE, NULL, 9),
    ('uuid', 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.', 'uuid', NULL, TRUE, 'gen_random_uuid()', 10),
    ('olusturulma_zamani', 'Kaydın oluşturulma zamanı.', 'timestamptz', NULL, TRUE, 'CURRENT_TIMESTAMP', 11),
    ('olusturan_kullanici_id', 'Kaydı oluşturan kullanıcı.', 'bigint', NULL, FALSE, NULL, 12),
    ('guncellenme_zamani', 'Kaydın son güncellenme zamanı.', 'timestamptz', NULL, FALSE, NULL, 13),
    ('guncelleyen_kullanici_id', 'Kaydı son güncelleyen kullanıcı.', 'bigint', NULL, FALSE, NULL, 14)
) AS v(ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no)
WHERE t.ad = 'kolon_tanimlari';

CREATE TABLE akis.kisit_tanimlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tablo_tanimi_id BIGINT NOT NULL REFERENCES akis.tablo_tanimlari(id),
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    tur VARCHAR(20) NOT NULL,
    check_ifadesi VARCHAR(2000),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    CONSTRAINT pk_kisit_tanimlari PRIMARY KEY (id),
    CONSTRAINT uq_kisit_tanimlari_uuid UNIQUE (uuid),
    CONSTRAINT uq_kisit_tanimlari_tablo_ad UNIQUE (tablo_tanimi_id, ad),
    CONSTRAINT ck_kisit_tanimlari_ad CHECK (ad ~ '^[a-z][a-z0-9_]{0,99}$'),
    CONSTRAINT ck_kisit_tanimlari_tur CHECK (tur IN ('PRIMARY_KEY', 'UNIQUE', 'CHECK', 'FOREIGN_KEY')),
    CONSTRAINT ck_kisit_tanimlari_check_ifadesi CHECK (
        tur <> 'CHECK' OR check_ifadesi IS NOT NULL
    ),
    CONSTRAINT ck_kisit_tanimlari_audit CHECK (
        guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani
    )
);

COMMENT ON TABLE akis.kisit_tanimlari IS 'Bir tabloya ait kısıtların (PK/UNIQUE/CHECK/FK-kaynak) metadata tanımı.';
COMMENT ON COLUMN akis.kisit_tanimlari.id IS 'Yüzeysel (surrogate) birincil anahtar.';
COMMENT ON COLUMN akis.kisit_tanimlari.tablo_tanimi_id IS 'Ait olduğu tablo tanımı.';
COMMENT ON COLUMN akis.kisit_tanimlari.ad IS 'Veritabanındaki gerçek kısıt adı (ayrı bir kod/etiket tutulmaz).';
COMMENT ON COLUMN akis.kisit_tanimlari.aciklama IS 'Kısıtın iş anlamı.';
COMMENT ON COLUMN akis.kisit_tanimlari.tur IS 'PRIMARY_KEY, UNIQUE, CHECK veya FOREIGN_KEY.';
COMMENT ON COLUMN akis.kisit_tanimlari.check_ifadesi IS 'tur=CHECK ise kısıtın SQL ifadesi.';
COMMENT ON COLUMN akis.kisit_tanimlari.uuid IS 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.';
COMMENT ON COLUMN akis.kisit_tanimlari.olusturulma_zamani IS 'Kaydın oluşturulma zamanı.';
COMMENT ON COLUMN akis.kisit_tanimlari.olusturan_kullanici_id IS 'Kaydı oluşturan kullanıcı.';
COMMENT ON COLUMN akis.kisit_tanimlari.guncellenme_zamani IS 'Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).';
COMMENT ON COLUMN akis.kisit_tanimlari.guncelleyen_kullanici_id IS 'Kaydı son güncelleyen kullanıcı.';

-- Self-hosting: kisit_tanimlari tablosunun kendisi de tablo_tanimlari'na eklenir.
INSERT INTO akis.tablo_tanimlari (sema_tanimi_id, ad, aciklama)
SELECT s.id, 'kisit_tanimlari', 'Sistemdeki tüm tabloların kısıtlarının (PK/UNIQUE/CHECK/FK-kaynak) metadata tanımını tutar.'
FROM akis.sema_tanimlari s
WHERE s.ad = 'akis';

-- Self-hosting: kisit_tanimlari tablosunun kendi kolonları.
INSERT INTO akis.kolon_tanimlari (
    tablo_tanimi_id, ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no
)
SELECT t.id, v.ad, v.aciklama, v.veri_tipi, v.uzunluk, v.zorunlu_mu, v.varsayilan_deger, v.sira_no
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('id', 'Yüzeysel (surrogate) birincil anahtar.', 'bigint', NULL::BIGINT, TRUE, 'identity', 1),
    ('tablo_tanimi_id', 'Ait olduğu tablo tanımı.', 'bigint', NULL, TRUE, NULL, 2),
    ('ad', 'Veritabanındaki gerçek kısıt adı.', 'character varying', 200, TRUE, NULL, 3),
    ('aciklama', 'Kısıtın iş anlamı.', 'character varying', 2000, FALSE, NULL, 4),
    ('tur', 'PRIMARY_KEY, UNIQUE, CHECK veya FOREIGN_KEY.', 'character varying', 20, TRUE, NULL, 5),
    ('check_ifadesi', 'tur=CHECK ise kısıtın SQL ifadesi.', 'character varying', 2000, FALSE, NULL, 6),
    ('uuid', 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.', 'uuid', NULL, TRUE, 'gen_random_uuid()', 7),
    ('olusturulma_zamani', 'Kaydın oluşturulma zamanı.', 'timestamptz', NULL, TRUE, 'CURRENT_TIMESTAMP', 8),
    ('olusturan_kullanici_id', 'Kaydı oluşturan kullanıcı.', 'bigint', NULL, FALSE, NULL, 9),
    ('guncellenme_zamani', 'Kaydın son güncellenme zamanı.', 'timestamptz', NULL, FALSE, NULL, 10),
    ('guncelleyen_kullanici_id', 'Kaydı son güncelleyen kullanıcı.', 'bigint', NULL, FALSE, NULL, 11)
) AS v(ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no)
WHERE t.ad = 'kisit_tanimlari';

-- Self-hosting: sema_tanimlari, tablo_tanimlari ve kolon_tanimlari'nın kendi kısıtları.
-- (Bu üç tablonun kullanici(id)'ye giden FK'leri, kullanici henüz bu sistemde tablo
-- olarak kayıtlı olmadığından burada kısıt kaydı açılmaz; sadece kendi içindeki
-- PK/UNIQUE/CHECK kısıtları ve bu sistem içi hedefe sahip FK'ler eklenir.)
INSERT INTO akis.kisit_tanimlari (tablo_tanimi_id, ad, aciklama, tur, check_ifadesi)
SELECT t.id, v.ad, v.aciklama, v.tur, v.check_ifadesi
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('sema_tanimlari', 'pk_sema_tanimlari', 'Birincil anahtar.', 'PRIMARY_KEY', NULL),
    ('sema_tanimlari', 'uq_sema_tanimlari_uuid', 'uuid benzersizliği.', 'UNIQUE', NULL),
    ('sema_tanimlari', 'uq_sema_tanimlari_ad', 'ad benzersizliği (gerçek şema adı).', 'UNIQUE', NULL),
    ('sema_tanimlari', 'ck_sema_tanimlari_ad', 'ad küçük harf tanımlayıcı biçiminde olmalı.', 'CHECK', 'ad ~ ''^[a-z][a-z0-9_]{0,99}$'''),
    ('sema_tanimlari', 'ck_sema_tanimlari_audit', 'guncellenme_zamani olusturulma_zamani''dan önce olamaz.', 'CHECK', 'guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani'),

    ('tablo_tanimlari', 'pk_tablo_tanimlari', 'Birincil anahtar.', 'PRIMARY_KEY', NULL),
    ('tablo_tanimlari', 'uq_tablo_tanimlari_uuid', 'uuid benzersizliği.', 'UNIQUE', NULL),
    ('tablo_tanimlari', 'uq_tablo_tanimlari_sema_ad', 'Şema içinde ad benzersizliği.', 'UNIQUE', NULL),
    ('tablo_tanimlari', 'ck_tablo_tanimlari_ad', 'ad küçük harf tanımlayıcı biçiminde olmalı.', 'CHECK', 'ad ~ ''^[a-z][a-z0-9_]{0,99}$'''),
    ('tablo_tanimlari', 'ck_tablo_tanimlari_audit', 'guncellenme_zamani olusturulma_zamani''dan önce olamaz.', 'CHECK', 'guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani'),
    ('tablo_tanimlari', 'tablo_tanimlari_sema_tanimi_id_fkey', 'sema_tanimlari''na referans (kaynak uç).', 'FOREIGN_KEY', NULL),

    ('kolon_tanimlari', 'pk_kolon_tanimlari', 'Birincil anahtar.', 'PRIMARY_KEY', NULL),
    ('kolon_tanimlari', 'uq_kolon_tanimlari_uuid', 'uuid benzersizliği.', 'UNIQUE', NULL),
    ('kolon_tanimlari', 'uq_kolon_tanimlari_tablo_ad', 'Tablo içinde ad benzersizliği.', 'UNIQUE', NULL),
    ('kolon_tanimlari', 'uq_kolon_tanimlari_tablo_sira', 'Tablo içinde sira_no benzersizliği.', 'UNIQUE', NULL),
    ('kolon_tanimlari', 'ck_kolon_tanimlari_ad', 'ad küçük harf tanımlayıcı biçiminde olmalı.', 'CHECK', 'ad ~ ''^[a-z][a-z0-9_]{0,99}$'''),
    ('kolon_tanimlari', 'ck_kolon_tanimlari_sira_no', 'sira_no pozitif olmalı.', 'CHECK', 'sira_no > 0'),
    ('kolon_tanimlari', 'ck_kolon_tanimlari_audit', 'guncellenme_zamani olusturulma_zamani''dan önce olamaz.', 'CHECK', 'guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani'),
    ('kolon_tanimlari', 'kolon_tanimlari_tablo_tanimi_id_fkey', 'tablo_tanimlari''na referans (kaynak uç).', 'FOREIGN_KEY', NULL)
) AS v(tablo_ad, ad, aciklama, tur, check_ifadesi)
WHERE t.ad = v.tablo_ad;

CREATE TABLE akis.kisit_kolon_tanimlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kisit_tanimi_id BIGINT NOT NULL REFERENCES akis.kisit_tanimlari(id),
    kolon_tanimi_id BIGINT NOT NULL REFERENCES akis.kolon_tanimlari(id),
    sira_no INTEGER NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    CONSTRAINT pk_kisit_kolon_tanimlari PRIMARY KEY (id),
    CONSTRAINT uq_kisit_kolon_tanimlari_uuid UNIQUE (uuid),
    CONSTRAINT uq_kisit_kolon_tanimlari_kisit_sira UNIQUE (kisit_tanimi_id, sira_no),
    CONSTRAINT uq_kisit_kolon_tanimlari_kisit_kolon UNIQUE (kisit_tanimi_id, kolon_tanimi_id),
    CONSTRAINT ck_kisit_kolon_tanimlari_sira_no CHECK (sira_no > 0),
    CONSTRAINT ck_kisit_kolon_tanimlari_audit CHECK (
        guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani
    )
);

COMMENT ON TABLE akis.kisit_kolon_tanimlari IS 'Bir kısıtın (PK/UNIQUE/FK-kaynak) kapsadığı kolon(lar), sırasıyla.';
COMMENT ON COLUMN akis.kisit_kolon_tanimlari.id IS 'Yüzeysel (surrogate) birincil anahtar.';
COMMENT ON COLUMN akis.kisit_kolon_tanimlari.kisit_tanimi_id IS 'Ait olduğu kısıt tanımı.';
COMMENT ON COLUMN akis.kisit_kolon_tanimlari.kolon_tanimi_id IS 'Kısıtın kapsadığı kolon tanımı.';
COMMENT ON COLUMN akis.kisit_kolon_tanimlari.sira_no IS 'Kısıt içindeki kolon sırası (kompozit anahtarlar için).';
COMMENT ON COLUMN akis.kisit_kolon_tanimlari.uuid IS 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.';
COMMENT ON COLUMN akis.kisit_kolon_tanimlari.olusturulma_zamani IS 'Kaydın oluşturulma zamanı.';
COMMENT ON COLUMN akis.kisit_kolon_tanimlari.olusturan_kullanici_id IS 'Kaydı oluşturan kullanıcı.';
COMMENT ON COLUMN akis.kisit_kolon_tanimlari.guncellenme_zamani IS 'Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).';
COMMENT ON COLUMN akis.kisit_kolon_tanimlari.guncelleyen_kullanici_id IS 'Kaydı son güncelleyen kullanıcı.';

-- Self-hosting: kisit_kolon_tanimlari tablosunun kendisi de tablo_tanimlari'na eklenir.
INSERT INTO akis.tablo_tanimlari (sema_tanimi_id, ad, aciklama)
SELECT s.id, 'kisit_kolon_tanimlari', 'Bir kısıtın kapsadığı kolon(lar)ın, sırasıyla, metadata tanımını tutar.'
FROM akis.sema_tanimlari s
WHERE s.ad = 'akis';

-- Self-hosting: kisit_kolon_tanimlari tablosunun kendi kolonları.
INSERT INTO akis.kolon_tanimlari (
    tablo_tanimi_id, ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no
)
SELECT t.id, v.ad, v.aciklama, v.veri_tipi, v.uzunluk, v.zorunlu_mu, v.varsayilan_deger, v.sira_no
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('id', 'Yüzeysel (surrogate) birincil anahtar.', 'bigint', NULL::BIGINT, TRUE, 'identity', 1),
    ('kisit_tanimi_id', 'Ait olduğu kısıt tanımı.', 'bigint', NULL, TRUE, NULL, 2),
    ('kolon_tanimi_id', 'Kısıtın kapsadığı kolon tanımı.', 'bigint', NULL, TRUE, NULL, 3),
    ('sira_no', 'Kısıt içindeki kolon sırası.', 'integer', NULL, TRUE, NULL, 4),
    ('uuid', 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.', 'uuid', NULL, TRUE, 'gen_random_uuid()', 5),
    ('olusturulma_zamani', 'Kaydın oluşturulma zamanı.', 'timestamptz', NULL, TRUE, 'CURRENT_TIMESTAMP', 6),
    ('olusturan_kullanici_id', 'Kaydı oluşturan kullanıcı.', 'bigint', NULL, FALSE, NULL, 7),
    ('guncellenme_zamani', 'Kaydın son güncellenme zamanı.', 'timestamptz', NULL, FALSE, NULL, 8),
    ('guncelleyen_kullanici_id', 'Kaydı son güncelleyen kullanıcı.', 'bigint', NULL, FALSE, NULL, 9)
) AS v(ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no)
WHERE t.ad = 'kisit_kolon_tanimlari';

-- Self-hosting: kisit_kolon_tanimlari tablosunun kendi kısıtları.
INSERT INTO akis.kisit_tanimlari (tablo_tanimi_id, ad, aciklama, tur, check_ifadesi)
SELECT t.id, v.ad, v.aciklama, v.tur, v.check_ifadesi
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('pk_kisit_kolon_tanimlari', 'Birincil anahtar.', 'PRIMARY_KEY', NULL),
    ('uq_kisit_kolon_tanimlari_uuid', 'uuid benzersizliği.', 'UNIQUE', NULL),
    ('uq_kisit_kolon_tanimlari_kisit_sira', 'Kısıt içinde sira_no benzersizliği.', 'UNIQUE', NULL),
    ('uq_kisit_kolon_tanimlari_kisit_kolon', 'Kısıt içinde kolon benzersizliği.', 'UNIQUE', NULL),
    ('ck_kisit_kolon_tanimlari_sira_no', 'sira_no pozitif olmalı.', 'CHECK', 'sira_no > 0'),
    ('ck_kisit_kolon_tanimlari_audit', 'guncellenme_zamani olusturulma_zamani''dan önce olamaz.', 'CHECK', 'guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani'),
    ('kisit_kolon_tanimlari_kisit_tanimi_id_fkey', 'kisit_tanimlari''na referans (kaynak uç).', 'FOREIGN_KEY', NULL),
    ('kisit_kolon_tanimlari_kolon_tanimi_id_fkey', 'kolon_tanimlari''na referans (kaynak uç).', 'FOREIGN_KEY', NULL)
) AS v(ad, aciklama, tur, check_ifadesi)
WHERE t.ad = 'kisit_kolon_tanimlari';

-- Self-hosting: sema/tablo/kolon_tanimlari'ndaki kompozit ve tekil kısıtların kapsadığı kolonlar.
INSERT INTO akis.kisit_kolon_tanimlari (kisit_tanimi_id, kolon_tanimi_id, sira_no)
SELECT kt.id, kl.id, v.sira_no
FROM (VALUES
    ('sema_tanimlari', 'pk_sema_tanimlari', 'id', 1),
    ('sema_tanimlari', 'uq_sema_tanimlari_uuid', 'uuid', 1),
    ('sema_tanimlari', 'uq_sema_tanimlari_ad', 'ad', 1),

    ('tablo_tanimlari', 'pk_tablo_tanimlari', 'id', 1),
    ('tablo_tanimlari', 'uq_tablo_tanimlari_uuid', 'uuid', 1),
    ('tablo_tanimlari', 'uq_tablo_tanimlari_sema_ad', 'sema_tanimi_id', 1),
    ('tablo_tanimlari', 'uq_tablo_tanimlari_sema_ad', 'ad', 2),
    ('tablo_tanimlari', 'tablo_tanimlari_sema_tanimi_id_fkey', 'sema_tanimi_id', 1),

    ('kolon_tanimlari', 'pk_kolon_tanimlari', 'id', 1),
    ('kolon_tanimlari', 'uq_kolon_tanimlari_uuid', 'uuid', 1),
    ('kolon_tanimlari', 'uq_kolon_tanimlari_tablo_ad', 'tablo_tanimi_id', 1),
    ('kolon_tanimlari', 'uq_kolon_tanimlari_tablo_ad', 'ad', 2),
    ('kolon_tanimlari', 'uq_kolon_tanimlari_tablo_sira', 'tablo_tanimi_id', 1),
    ('kolon_tanimlari', 'uq_kolon_tanimlari_tablo_sira', 'sira_no', 2),
    ('kolon_tanimlari', 'kolon_tanimlari_tablo_tanimi_id_fkey', 'tablo_tanimi_id', 1),

    ('kisit_kolon_tanimlari', 'pk_kisit_kolon_tanimlari', 'id', 1),
    ('kisit_kolon_tanimlari', 'uq_kisit_kolon_tanimlari_uuid', 'uuid', 1),
    ('kisit_kolon_tanimlari', 'uq_kisit_kolon_tanimlari_kisit_sira', 'kisit_tanimi_id', 1),
    ('kisit_kolon_tanimlari', 'uq_kisit_kolon_tanimlari_kisit_sira', 'sira_no', 2),
    ('kisit_kolon_tanimlari', 'uq_kisit_kolon_tanimlari_kisit_kolon', 'kisit_tanimi_id', 1),
    ('kisit_kolon_tanimlari', 'uq_kisit_kolon_tanimlari_kisit_kolon', 'kolon_tanimi_id', 2),
    ('kisit_kolon_tanimlari', 'kisit_kolon_tanimlari_kisit_tanimi_id_fkey', 'kisit_tanimi_id', 1),
    ('kisit_kolon_tanimlari', 'kisit_kolon_tanimlari_kolon_tanimi_id_fkey', 'kolon_tanimi_id', 1)
) AS v(tablo_ad, kisit_ad, kolon_ad, sira_no)
JOIN akis.tablo_tanimlari t ON t.ad = v.tablo_ad
JOIN akis.kisit_tanimlari kt ON kt.tablo_tanimi_id = t.id AND kt.ad = v.kisit_ad
JOIN akis.kolon_tanimlari kl ON kl.tablo_tanimi_id = t.id AND kl.ad = v.kolon_ad;

-- Self-hosting: kisit_tanimlari tablosunun kendi kısıtları (ilk kısıt self-hosting turunda atlanmıştı).
INSERT INTO akis.kisit_tanimlari (tablo_tanimi_id, ad, aciklama, tur, check_ifadesi)
SELECT t.id, v.ad, v.aciklama, v.tur, v.check_ifadesi
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('pk_kisit_tanimlari', 'Birincil anahtar.', 'PRIMARY_KEY', NULL),
    ('uq_kisit_tanimlari_uuid', 'uuid benzersizliği.', 'UNIQUE', NULL),
    ('uq_kisit_tanimlari_tablo_ad', 'Tablo içinde ad benzersizliği.', 'UNIQUE', NULL),
    ('ck_kisit_tanimlari_ad', 'ad küçük harf tanımlayıcı biçiminde olmalı.', 'CHECK', 'ad ~ ''^[a-z][a-z0-9_]{0,99}$'''),
    ('ck_kisit_tanimlari_tur', 'tur izin verilen sözlükte olmalı.', 'CHECK', 'tur IN (''PRIMARY_KEY'', ''UNIQUE'', ''CHECK'', ''FOREIGN_KEY'')'),
    ('ck_kisit_tanimlari_check_ifadesi', 'tur=CHECK ise check_ifadesi zorunlu.', 'CHECK', 'tur <> ''CHECK'' OR check_ifadesi IS NOT NULL'),
    ('ck_kisit_tanimlari_audit', 'guncellenme_zamani olusturulma_zamani''dan önce olamaz.', 'CHECK', 'guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani'),
    ('kisit_tanimlari_tablo_tanimi_id_fkey', 'tablo_tanimlari''na referans (kaynak uç).', 'FOREIGN_KEY', NULL)
) AS v(ad, aciklama, tur, check_ifadesi)
WHERE t.ad = 'kisit_tanimlari';

-- Self-hosting: kisit_tanimlari'nın kendi kısıtlarının kapsadığı kolonlar.
INSERT INTO akis.kisit_kolon_tanimlari (kisit_tanimi_id, kolon_tanimi_id, sira_no)
SELECT kt.id, kl.id, v.sira_no
FROM (VALUES
    ('pk_kisit_tanimlari', 'id', 1),
    ('uq_kisit_tanimlari_uuid', 'uuid', 1),
    ('uq_kisit_tanimlari_tablo_ad', 'tablo_tanimi_id', 1),
    ('uq_kisit_tanimlari_tablo_ad', 'ad', 2),
    ('kisit_tanimlari_tablo_tanimi_id_fkey', 'tablo_tanimi_id', 1)
) AS v(kisit_ad, kolon_ad, sira_no)
JOIN akis.tablo_tanimlari t ON t.ad = 'kisit_tanimlari'
JOIN akis.kisit_tanimlari kt ON kt.tablo_tanimi_id = t.id AND kt.ad = v.kisit_ad
JOIN akis.kolon_tanimlari kl ON kl.tablo_tanimi_id = t.id AND kl.ad = v.kolon_ad;

CREATE TABLE akis.iliski_tanimlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kaynak_kisit_tanimi_id BIGINT NOT NULL REFERENCES akis.kisit_tanimlari(id),
    hedef_tablo_tanimi_id BIGINT NOT NULL REFERENCES akis.tablo_tanimlari(id),
    hedef_kisit_tanimi_id BIGINT NOT NULL REFERENCES akis.kisit_tanimlari(id),
    silme_kurali VARCHAR(20) NOT NULL DEFAULT 'RESTRICT',
    guncelleme_kurali VARCHAR(20) NOT NULL DEFAULT 'RESTRICT',
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    CONSTRAINT pk_iliski_tanimlari PRIMARY KEY (id),
    CONSTRAINT uq_iliski_tanimlari_uuid UNIQUE (uuid),
    CONSTRAINT uq_iliski_tanimlari_kaynak_kisit UNIQUE (kaynak_kisit_tanimi_id),
    CONSTRAINT ck_iliski_tanimlari_silme_kurali CHECK (
        silme_kurali IN ('CASCADE', 'RESTRICT', 'SET_NULL', 'SET_DEFAULT', 'NO_ACTION')
    ),
    CONSTRAINT ck_iliski_tanimlari_guncelleme_kurali CHECK (
        guncelleme_kurali IN ('CASCADE', 'RESTRICT', 'SET_NULL', 'SET_DEFAULT', 'NO_ACTION')
    ),
    CONSTRAINT ck_iliski_tanimlari_audit CHECK (
        guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani
    )
);

COMMENT ON TABLE akis.iliski_tanimlari IS 'Foreign key ilişkileri: bir FK kısıtının (kaynak) hangi tabloya/kısıta (hedef) referans verdiği ve referans kuralları.';
COMMENT ON COLUMN akis.iliski_tanimlari.id IS 'Yüzeysel (surrogate) birincil anahtar.';
COMMENT ON COLUMN akis.iliski_tanimlari.kaynak_kisit_tanimi_id IS 'FK kısıtının kendisi (kisit_tanimlari.tur=FOREIGN_KEY); ad/açıklama oradan gelir, burada tekrar tutulmaz.';
COMMENT ON COLUMN akis.iliski_tanimlari.hedef_tablo_tanimi_id IS 'Referans verilen tablo.';
COMMENT ON COLUMN akis.iliski_tanimlari.hedef_kisit_tanimi_id IS 'Referans verilen kısıt (tur=PRIMARY_KEY veya UNIQUE olmalı).';
COMMENT ON COLUMN akis.iliski_tanimlari.silme_kurali IS 'ON DELETE davranışı.';
COMMENT ON COLUMN akis.iliski_tanimlari.guncelleme_kurali IS 'ON UPDATE davranışı.';
COMMENT ON COLUMN akis.iliski_tanimlari.uuid IS 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.';
COMMENT ON COLUMN akis.iliski_tanimlari.olusturulma_zamani IS 'Kaydın oluşturulma zamanı.';
COMMENT ON COLUMN akis.iliski_tanimlari.olusturan_kullanici_id IS 'Kaydı oluşturan kullanıcı.';
COMMENT ON COLUMN akis.iliski_tanimlari.guncellenme_zamani IS 'Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).';
COMMENT ON COLUMN akis.iliski_tanimlari.guncelleyen_kullanici_id IS 'Kaydı son güncelleyen kullanıcı.';

-- Self-hosting: iliski_tanimlari tablosunun kendisi de tablo_tanimlari'na eklenir.
INSERT INTO akis.tablo_tanimlari (sema_tanimi_id, ad, aciklama)
SELECT s.id, 'iliski_tanimlari', 'FK ilişkilerinin (kaynak kısıt -> hedef tablo/kısıt) metadata tanımını tutar.'
FROM akis.sema_tanimlari s
WHERE s.ad = 'akis';

-- Self-hosting: iliski_tanimlari tablosunun kendi kolonları.
INSERT INTO akis.kolon_tanimlari (
    tablo_tanimi_id, ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no
)
SELECT t.id, v.ad, v.aciklama, v.veri_tipi, v.uzunluk, v.zorunlu_mu, v.varsayilan_deger, v.sira_no
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('id', 'Yüzeysel (surrogate) birincil anahtar.', 'bigint', NULL::BIGINT, TRUE, 'identity', 1),
    ('kaynak_kisit_tanimi_id', 'FK kısıtının kendisi (kaynak uç).', 'bigint', NULL, TRUE, NULL, 2),
    ('hedef_tablo_tanimi_id', 'Referans verilen tablo.', 'bigint', NULL, TRUE, NULL, 3),
    ('hedef_kisit_tanimi_id', 'Referans verilen kısıt (PK/UNIQUE).', 'bigint', NULL, TRUE, NULL, 4),
    ('silme_kurali', 'ON DELETE davranışı.', 'character varying', 20, TRUE, 'RESTRICT', 5),
    ('guncelleme_kurali', 'ON UPDATE davranışı.', 'character varying', 20, TRUE, 'RESTRICT', 6),
    ('uuid', 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.', 'uuid', NULL, TRUE, 'gen_random_uuid()', 7),
    ('olusturulma_zamani', 'Kaydın oluşturulma zamanı.', 'timestamptz', NULL, TRUE, 'CURRENT_TIMESTAMP', 8),
    ('olusturan_kullanici_id', 'Kaydı oluşturan kullanıcı.', 'bigint', NULL, FALSE, NULL, 9),
    ('guncellenme_zamani', 'Kaydın son güncellenme zamanı.', 'timestamptz', NULL, FALSE, NULL, 10),
    ('guncelleyen_kullanici_id', 'Kaydı son güncelleyen kullanıcı.', 'bigint', NULL, FALSE, NULL, 11)
) AS v(ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no)
WHERE t.ad = 'iliski_tanimlari';

-- Sistem içi hedefi olan mevcut FK kısıtları için iliski_tanimlari kayıtları:
-- tablo_tanimlari -> sema_tanimlari, kolon_tanimlari -> tablo_tanimlari,
-- kisit_tanimlari -> tablo_tanimlari, kisit_kolon_tanimlari -> kisit_tanimlari / kolon_tanimlari.
INSERT INTO akis.iliski_tanimlari (
    kaynak_kisit_tanimi_id, hedef_tablo_tanimi_id, hedef_kisit_tanimi_id
)
SELECT kaynak.id, hedef_t.id, hedef_kisit.id
FROM (VALUES
    ('tablo_tanimlari', 'tablo_tanimlari_sema_tanimi_id_fkey', 'sema_tanimlari', 'pk_sema_tanimlari'),
    ('kolon_tanimlari', 'kolon_tanimlari_tablo_tanimi_id_fkey', 'tablo_tanimlari', 'pk_tablo_tanimlari'),
    ('kisit_tanimlari', 'kisit_tanimlari_tablo_tanimi_id_fkey', 'tablo_tanimlari', 'pk_tablo_tanimlari'),
    ('kisit_kolon_tanimlari', 'kisit_kolon_tanimlari_kisit_tanimi_id_fkey', 'kisit_tanimlari', 'pk_kisit_tanimlari'),
    ('kisit_kolon_tanimlari', 'kisit_kolon_tanimlari_kolon_tanimi_id_fkey', 'kolon_tanimlari', 'pk_kolon_tanimlari')
) AS v(kaynak_tablo_ad, kaynak_kisit_ad, hedef_tablo_ad, hedef_kisit_ad)
JOIN akis.tablo_tanimlari kaynak_t ON kaynak_t.ad = v.kaynak_tablo_ad
JOIN akis.kisit_tanimlari kaynak ON kaynak.tablo_tanimi_id = kaynak_t.id AND kaynak.ad = v.kaynak_kisit_ad
JOIN akis.tablo_tanimlari hedef_t ON hedef_t.ad = v.hedef_tablo_ad
JOIN akis.kisit_tanimlari hedef_kisit ON hedef_kisit.tablo_tanimi_id = hedef_t.id AND hedef_kisit.ad = v.hedef_kisit_ad;

-- Self-hosting: iliski_tanimlari tablosunun kendi kısıtları (hedefleri sistem içi).
INSERT INTO akis.kisit_tanimlari (tablo_tanimi_id, ad, aciklama, tur, check_ifadesi)
SELECT t.id, v.ad, v.aciklama, v.tur, v.check_ifadesi
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('pk_iliski_tanimlari', 'Birincil anahtar.', 'PRIMARY_KEY', NULL),
    ('uq_iliski_tanimlari_uuid', 'uuid benzersizliği.', 'UNIQUE', NULL),
    ('uq_iliski_tanimlari_kaynak_kisit', 'Bir FK kısıtı en fazla bir ilişki tanımına sahip olabilir.', 'UNIQUE', NULL),
    ('ck_iliski_tanimlari_silme_kurali', 'silme_kurali izin verilen sözlükte olmalı.', 'CHECK', 'silme_kurali IN (''CASCADE'', ''RESTRICT'', ''SET_NULL'', ''SET_DEFAULT'', ''NO_ACTION'')'),
    ('ck_iliski_tanimlari_guncelleme_kurali', 'guncelleme_kurali izin verilen sözlükte olmalı.', 'CHECK', 'guncelleme_kurali IN (''CASCADE'', ''RESTRICT'', ''SET_NULL'', ''SET_DEFAULT'', ''NO_ACTION'')'),
    ('ck_iliski_tanimlari_audit', 'guncellenme_zamani olusturulma_zamani''dan önce olamaz.', 'CHECK', 'guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani'),
    ('iliski_tanimlari_kaynak_kisit_tanimi_id_fkey', 'kisit_tanimlari''na referans (FK kısıtının kendisi).', 'FOREIGN_KEY', NULL),
    ('iliski_tanimlari_hedef_tablo_tanimi_id_fkey', 'tablo_tanimlari''na referans (hedef tablo).', 'FOREIGN_KEY', NULL),
    ('iliski_tanimlari_hedef_kisit_tanimi_id_fkey', 'kisit_tanimlari''na referans (hedef kısıt).', 'FOREIGN_KEY', NULL)
) AS v(ad, aciklama, tur, check_ifadesi)
WHERE t.ad = 'iliski_tanimlari';

-- Self-hosting: iliski_tanimlari'nın kendi kısıtlarının kapsadığı kolonlar.
INSERT INTO akis.kisit_kolon_tanimlari (kisit_tanimi_id, kolon_tanimi_id, sira_no)
SELECT kt.id, kl.id, v.sira_no
FROM (VALUES
    ('pk_iliski_tanimlari', 'id', 1),
    ('uq_iliski_tanimlari_uuid', 'uuid', 1),
    ('uq_iliski_tanimlari_kaynak_kisit', 'kaynak_kisit_tanimi_id', 1),
    ('iliski_tanimlari_kaynak_kisit_tanimi_id_fkey', 'kaynak_kisit_tanimi_id', 1),
    ('iliski_tanimlari_hedef_tablo_tanimi_id_fkey', 'hedef_tablo_tanimi_id', 1),
    ('iliski_tanimlari_hedef_kisit_tanimi_id_fkey', 'hedef_kisit_tanimi_id', 1)
) AS v(kisit_ad, kolon_ad, sira_no)
JOIN akis.tablo_tanimlari t ON t.ad = 'iliski_tanimlari'
JOIN akis.kisit_tanimlari kt ON kt.tablo_tanimi_id = t.id AND kt.ad = v.kisit_ad
JOIN akis.kolon_tanimlari kl ON kl.tablo_tanimi_id = t.id AND kl.ad = v.kolon_ad;

CREATE TABLE akis.iliski_kolon_tanimlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    iliski_tanimi_id BIGINT NOT NULL REFERENCES akis.iliski_tanimlari(id),
    kaynak_kolon_tanimi_id BIGINT NOT NULL REFERENCES akis.kolon_tanimlari(id),
    hedef_kolon_tanimi_id BIGINT NOT NULL REFERENCES akis.kolon_tanimlari(id),
    sira_no INTEGER NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    CONSTRAINT pk_iliski_kolon_tanimlari PRIMARY KEY (id),
    CONSTRAINT uq_iliski_kolon_tanimlari_uuid UNIQUE (uuid),
    CONSTRAINT uq_iliski_kolon_tanimlari_iliski_sira UNIQUE (iliski_tanimi_id, sira_no),
    CONSTRAINT ck_iliski_kolon_tanimlari_sira_no CHECK (sira_no > 0),
    CONSTRAINT ck_iliski_kolon_tanimlari_audit CHECK (
        guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani
    )
);

COMMENT ON TABLE akis.iliski_kolon_tanimlari IS 'Bir FK ilişkisinin kaynak/hedef kolon eşleşmeleri, sırasıyla (kompozit FK''ler için).';
COMMENT ON COLUMN akis.iliski_kolon_tanimlari.id IS 'Yüzeysel (surrogate) birincil anahtar.';
COMMENT ON COLUMN akis.iliski_kolon_tanimlari.iliski_tanimi_id IS 'Ait olduğu ilişki tanımı.';
COMMENT ON COLUMN akis.iliski_kolon_tanimlari.kaynak_kolon_tanimi_id IS 'Kaynak taraftaki kolon.';
COMMENT ON COLUMN akis.iliski_kolon_tanimlari.hedef_kolon_tanimi_id IS 'Hedef taraftaki kolon.';
COMMENT ON COLUMN akis.iliski_kolon_tanimlari.sira_no IS 'Eşleşme sırası (kompozit FK''ler için).';
COMMENT ON COLUMN akis.iliski_kolon_tanimlari.uuid IS 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.';
COMMENT ON COLUMN akis.iliski_kolon_tanimlari.olusturulma_zamani IS 'Kaydın oluşturulma zamanı.';
COMMENT ON COLUMN akis.iliski_kolon_tanimlari.olusturan_kullanici_id IS 'Kaydı oluşturan kullanıcı.';
COMMENT ON COLUMN akis.iliski_kolon_tanimlari.guncellenme_zamani IS 'Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).';
COMMENT ON COLUMN akis.iliski_kolon_tanimlari.guncelleyen_kullanici_id IS 'Kaydı son güncelleyen kullanıcı.';

-- Self-hosting: iliski_kolon_tanimlari tablosunun kendisi de tablo_tanimlari'na eklenir.
INSERT INTO akis.tablo_tanimlari (sema_tanimi_id, ad, aciklama)
SELECT s.id, 'iliski_kolon_tanimlari', 'Bir FK ilişkisinin kaynak/hedef kolon eşleşmelerinin, sırasıyla, metadata tanımını tutar.'
FROM akis.sema_tanimlari s
WHERE s.ad = 'akis';

-- Self-hosting: iliski_kolon_tanimlari tablosunun kendi kolonları.
INSERT INTO akis.kolon_tanimlari (
    tablo_tanimi_id, ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no
)
SELECT t.id, v.ad, v.aciklama, v.veri_tipi, v.uzunluk, v.zorunlu_mu, v.varsayilan_deger, v.sira_no
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('id', 'Yüzeysel (surrogate) birincil anahtar.', 'bigint', NULL::BIGINT, TRUE, 'identity', 1),
    ('iliski_tanimi_id', 'Ait olduğu ilişki tanımı.', 'bigint', NULL, TRUE, NULL, 2),
    ('kaynak_kolon_tanimi_id', 'Kaynak taraftaki kolon.', 'bigint', NULL, TRUE, NULL, 3),
    ('hedef_kolon_tanimi_id', 'Hedef taraftaki kolon.', 'bigint', NULL, TRUE, NULL, 4),
    ('sira_no', 'Eşleşme sırası.', 'integer', NULL, TRUE, NULL, 5),
    ('uuid', 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.', 'uuid', NULL, TRUE, 'gen_random_uuid()', 6),
    ('olusturulma_zamani', 'Kaydın oluşturulma zamanı.', 'timestamptz', NULL, TRUE, 'CURRENT_TIMESTAMP', 7),
    ('olusturan_kullanici_id', 'Kaydı oluşturan kullanıcı.', 'bigint', NULL, FALSE, NULL, 8),
    ('guncellenme_zamani', 'Kaydın son güncellenme zamanı.', 'timestamptz', NULL, FALSE, NULL, 9),
    ('guncelleyen_kullanici_id', 'Kaydı son güncelleyen kullanıcı.', 'bigint', NULL, FALSE, NULL, 10)
) AS v(ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no)
WHERE t.ad = 'iliski_kolon_tanimlari';

-- Sistem içindeki mevcut (tek kolonlu) FK ilişkilerinin kaynak/hedef kolon eşleşmeleri.
INSERT INTO akis.iliski_kolon_tanimlari (iliski_tanimi_id, kaynak_kolon_tanimi_id, hedef_kolon_tanimi_id, sira_no)
SELECT il.id, kk.id, hk.id, v.sira_no
FROM (VALUES
    ('tablo_tanimlari_sema_tanimi_id_fkey', 'tablo_tanimlari', 'sema_tanimi_id', 'sema_tanimlari', 'id', 1),
    ('kolon_tanimlari_tablo_tanimi_id_fkey', 'kolon_tanimlari', 'tablo_tanimi_id', 'tablo_tanimlari', 'id', 1),
    ('kisit_tanimlari_tablo_tanimi_id_fkey', 'kisit_tanimlari', 'tablo_tanimi_id', 'tablo_tanimlari', 'id', 1),
    ('kisit_kolon_tanimlari_kisit_tanimi_id_fkey', 'kisit_kolon_tanimlari', 'kisit_tanimi_id', 'kisit_tanimlari', 'id', 1),
    ('kisit_kolon_tanimlari_kolon_tanimi_id_fkey', 'kisit_kolon_tanimlari', 'kolon_tanimi_id', 'kolon_tanimlari', 'id', 1)
) AS v(kaynak_kisit_ad, kaynak_tablo_ad, kaynak_kolon_ad, hedef_tablo_ad, hedef_kolon_ad, sira_no)
JOIN akis.kisit_tanimlari kt ON kt.ad = v.kaynak_kisit_ad
JOIN akis.iliski_tanimlari il ON il.kaynak_kisit_tanimi_id = kt.id
JOIN akis.tablo_tanimlari kt_t ON kt_t.ad = v.kaynak_tablo_ad
JOIN akis.kolon_tanimlari kk ON kk.tablo_tanimi_id = kt_t.id AND kk.ad = v.kaynak_kolon_ad
JOIN akis.tablo_tanimlari ht_t ON ht_t.ad = v.hedef_tablo_ad
JOIN akis.kolon_tanimlari hk ON hk.tablo_tanimi_id = ht_t.id AND hk.ad = v.hedef_kolon_ad;

CREATE TABLE akis.indeks_tanimlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tablo_tanimi_id BIGINT NOT NULL REFERENCES akis.tablo_tanimlari(id),
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    tur VARCHAR(20) NOT NULL DEFAULT 'BTREE',
    benzersiz_mi BOOLEAN NOT NULL DEFAULT FALSE,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    CONSTRAINT pk_indeks_tanimlari PRIMARY KEY (id),
    CONSTRAINT uq_indeks_tanimlari_uuid UNIQUE (uuid),
    CONSTRAINT uq_indeks_tanimlari_tablo_ad UNIQUE (tablo_tanimi_id, ad),
    CONSTRAINT ck_indeks_tanimlari_ad CHECK (ad ~ '^[a-z][a-z0-9_]{0,99}$'),
    CONSTRAINT ck_indeks_tanimlari_tur CHECK (tur IN ('BTREE', 'HASH', 'GIN', 'GIST', 'BRIN')),
    CONSTRAINT ck_indeks_tanimlari_audit CHECK (
        guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani
    )
);

COMMENT ON TABLE akis.indeks_tanimlari IS 'Bir tabloya ait indekslerin metadata tanımı.';
COMMENT ON COLUMN akis.indeks_tanimlari.id IS 'Yüzeysel (surrogate) birincil anahtar.';
COMMENT ON COLUMN akis.indeks_tanimlari.tablo_tanimi_id IS 'Ait olduğu tablo tanımı.';
COMMENT ON COLUMN akis.indeks_tanimlari.ad IS 'Veritabanındaki gerçek indeks adı (ayrı bir kod/etiket tutulmaz).';
COMMENT ON COLUMN akis.indeks_tanimlari.aciklama IS 'İndeksin amacı.';
COMMENT ON COLUMN akis.indeks_tanimlari.tur IS 'BTREE, HASH, GIN, GIST veya BRIN.';
COMMENT ON COLUMN akis.indeks_tanimlari.benzersiz_mi IS 'UNIQUE indeks mi.';
COMMENT ON COLUMN akis.indeks_tanimlari.uuid IS 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.';
COMMENT ON COLUMN akis.indeks_tanimlari.olusturulma_zamani IS 'Kaydın oluşturulma zamanı.';
COMMENT ON COLUMN akis.indeks_tanimlari.olusturan_kullanici_id IS 'Kaydı oluşturan kullanıcı.';
COMMENT ON COLUMN akis.indeks_tanimlari.guncellenme_zamani IS 'Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).';
COMMENT ON COLUMN akis.indeks_tanimlari.guncelleyen_kullanici_id IS 'Kaydı son güncelleyen kullanıcı.';

-- Self-hosting: indeks_tanimlari tablosunun kendisi de tablo_tanimlari'na eklenir.
INSERT INTO akis.tablo_tanimlari (sema_tanimi_id, ad, aciklama)
SELECT s.id, 'indeks_tanimlari', 'Sistemdeki tüm tabloların indekslerinin metadata tanımını tutar.'
FROM akis.sema_tanimlari s
WHERE s.ad = 'akis';

-- Self-hosting: indeks_tanimlari tablosunun kendi kolonları.
INSERT INTO akis.kolon_tanimlari (
    tablo_tanimi_id, ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no
)
SELECT t.id, v.ad, v.aciklama, v.veri_tipi, v.uzunluk, v.zorunlu_mu, v.varsayilan_deger, v.sira_no
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('id', 'Yüzeysel (surrogate) birincil anahtar.', 'bigint', NULL::BIGINT, TRUE, 'identity', 1),
    ('tablo_tanimi_id', 'Ait olduğu tablo tanımı.', 'bigint', NULL, TRUE, NULL, 2),
    ('ad', 'Veritabanındaki gerçek indeks adı.', 'character varying', 200, TRUE, NULL, 3),
    ('aciklama', 'İndeksin amacı.', 'character varying', 2000, FALSE, NULL, 4),
    ('tur', 'BTREE, HASH, GIN, GIST veya BRIN.', 'character varying', 20, TRUE, 'BTREE', 5),
    ('benzersiz_mi', 'UNIQUE indeks mi.', 'boolean', NULL, TRUE, 'false', 6),
    ('uuid', 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.', 'uuid', NULL, TRUE, 'gen_random_uuid()', 7),
    ('olusturulma_zamani', 'Kaydın oluşturulma zamanı.', 'timestamptz', NULL, TRUE, 'CURRENT_TIMESTAMP', 8),
    ('olusturan_kullanici_id', 'Kaydı oluşturan kullanıcı.', 'bigint', NULL, FALSE, NULL, 9),
    ('guncellenme_zamani', 'Kaydın son güncellenme zamanı.', 'timestamptz', NULL, FALSE, NULL, 10),
    ('guncelleyen_kullanici_id', 'Kaydı son güncelleyen kullanıcı.', 'bigint', NULL, FALSE, NULL, 11)
) AS v(ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no)
WHERE t.ad = 'indeks_tanimlari';

-- PostgreSQL her PRIMARY KEY/UNIQUE kısıtı için aynı adda bir benzersiz btree indeks
-- oluşturur; bu fiziksel gerçeğe dayanarak indeks kayıtları kisit_tanimlari'ndan türetilir.
INSERT INTO akis.indeks_tanimlari (tablo_tanimi_id, ad, aciklama, tur, benzersiz_mi)
SELECT tablo_tanimi_id, ad,
       'PostgreSQL''in ' || ad || ' kısıtı için otomatik oluşturduğu benzersiz indeks.',
       'BTREE', TRUE
FROM akis.kisit_tanimlari
WHERE tur IN ('PRIMARY_KEY', 'UNIQUE');

CREATE TABLE akis.indeks_kolon_tanimlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    indeks_tanimi_id BIGINT NOT NULL REFERENCES akis.indeks_tanimlari(id),
    kolon_tanimi_id BIGINT NOT NULL REFERENCES akis.kolon_tanimlari(id),
    sira_no INTEGER NOT NULL,
    siralama VARCHAR(4) NOT NULL DEFAULT 'ASC',
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    CONSTRAINT pk_indeks_kolon_tanimlari PRIMARY KEY (id),
    CONSTRAINT uq_indeks_kolon_tanimlari_uuid UNIQUE (uuid),
    CONSTRAINT uq_indeks_kolon_tanimlari_indeks_sira UNIQUE (indeks_tanimi_id, sira_no),
    CONSTRAINT uq_indeks_kolon_tanimlari_indeks_kolon UNIQUE (indeks_tanimi_id, kolon_tanimi_id),
    CONSTRAINT ck_indeks_kolon_tanimlari_sira_no CHECK (sira_no > 0),
    CONSTRAINT ck_indeks_kolon_tanimlari_siralama CHECK (siralama IN ('ASC', 'DESC')),
    CONSTRAINT ck_indeks_kolon_tanimlari_audit CHECK (
        guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani
    )
);

COMMENT ON TABLE akis.indeks_kolon_tanimlari IS 'Bir indeksin kapsadığı kolon(lar), sırasıyla (kompozit indeksler için).';
COMMENT ON COLUMN akis.indeks_kolon_tanimlari.id IS 'Yüzeysel (surrogate) birincil anahtar.';
COMMENT ON COLUMN akis.indeks_kolon_tanimlari.indeks_tanimi_id IS 'Ait olduğu indeks tanımı.';
COMMENT ON COLUMN akis.indeks_kolon_tanimlari.kolon_tanimi_id IS 'İndeksin kapsadığı kolon tanımı.';
COMMENT ON COLUMN akis.indeks_kolon_tanimlari.sira_no IS 'İndeks içindeki kolon sırası.';
COMMENT ON COLUMN akis.indeks_kolon_tanimlari.siralama IS 'ASC veya DESC.';
COMMENT ON COLUMN akis.indeks_kolon_tanimlari.uuid IS 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.';
COMMENT ON COLUMN akis.indeks_kolon_tanimlari.olusturulma_zamani IS 'Kaydın oluşturulma zamanı.';
COMMENT ON COLUMN akis.indeks_kolon_tanimlari.olusturan_kullanici_id IS 'Kaydı oluşturan kullanıcı.';
COMMENT ON COLUMN akis.indeks_kolon_tanimlari.guncellenme_zamani IS 'Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).';
COMMENT ON COLUMN akis.indeks_kolon_tanimlari.guncelleyen_kullanici_id IS 'Kaydı son güncelleyen kullanıcı.';

-- Self-hosting: indeks_kolon_tanimlari tablosunun kendisi de tablo_tanimlari'na eklenir.
INSERT INTO akis.tablo_tanimlari (sema_tanimi_id, ad, aciklama)
SELECT s.id, 'indeks_kolon_tanimlari', 'Bir indeksin kapsadığı kolon(lar)ın, sırasıyla, metadata tanımını tutar.'
FROM akis.sema_tanimlari s
WHERE s.ad = 'akis';

-- Self-hosting: indeks_kolon_tanimlari tablosunun kendi kolonları.
INSERT INTO akis.kolon_tanimlari (
    tablo_tanimi_id, ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no
)
SELECT t.id, v.ad, v.aciklama, v.veri_tipi, v.uzunluk, v.zorunlu_mu, v.varsayilan_deger, v.sira_no
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('id', 'Yüzeysel (surrogate) birincil anahtar.', 'bigint', NULL::BIGINT, TRUE, 'identity', 1),
    ('indeks_tanimi_id', 'Ait olduğu indeks tanımı.', 'bigint', NULL, TRUE, NULL, 2),
    ('kolon_tanimi_id', 'İndeksin kapsadığı kolon tanımı.', 'bigint', NULL, TRUE, NULL, 3),
    ('sira_no', 'İndeks içindeki kolon sırası.', 'integer', NULL, TRUE, NULL, 4),
    ('siralama', 'ASC veya DESC.', 'character varying', 4, TRUE, 'ASC', 5),
    ('uuid', 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.', 'uuid', NULL, TRUE, 'gen_random_uuid()', 6),
    ('olusturulma_zamani', 'Kaydın oluşturulma zamanı.', 'timestamptz', NULL, TRUE, 'CURRENT_TIMESTAMP', 7),
    ('olusturan_kullanici_id', 'Kaydı oluşturan kullanıcı.', 'bigint', NULL, FALSE, NULL, 8),
    ('guncellenme_zamani', 'Kaydın son güncellenme zamanı.', 'timestamptz', NULL, FALSE, NULL, 9),
    ('guncelleyen_kullanici_id', 'Kaydı son güncelleyen kullanıcı.', 'bigint', NULL, FALSE, NULL, 10)
) AS v(ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no)
WHERE t.ad = 'indeks_kolon_tanimlari';

-- kisit_kolon_tanimlari (PK/UNIQUE kısıtlarının kolonları), aynı fiziksel gerçeğe
-- dayanarak indeks_kolon_tanimlari'na aktarılır (indeks adı = kısıt adı).
INSERT INTO akis.indeks_kolon_tanimlari (indeks_tanimi_id, kolon_tanimi_id, sira_no, siralama)
SELECT idx.id, kk.kolon_tanimi_id, kk.sira_no, 'ASC'
FROM akis.kisit_kolon_tanimlari kk
JOIN akis.kisit_tanimlari kt ON kt.id = kk.kisit_tanimi_id AND kt.tur IN ('PRIMARY_KEY', 'UNIQUE')
JOIN akis.indeks_tanimlari idx ON idx.tablo_tanimi_id = kt.tablo_tanimi_id AND idx.ad = kt.ad;

CREATE TABLE akis.sira_tanimlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sema_tanimi_id BIGINT NOT NULL REFERENCES akis.sema_tanimlari(id),
    ad VARCHAR(200) NOT NULL,
    aciklama VARCHAR(2000),
    baslangic_degeri BIGINT NOT NULL DEFAULT 1,
    artis_miktari BIGINT NOT NULL DEFAULT 1,
    min_deger BIGINT,
    max_deger BIGINT,
    dongusel_mi BOOLEAN NOT NULL DEFAULT FALSE,
    sahibi_kolon_tanimi_id BIGINT REFERENCES akis.kolon_tanimlari(id),
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    guncellenme_zamani TIMESTAMPTZ,
    guncelleyen_kullanici_id BIGINT REFERENCES akis.kullanici(id),
    CONSTRAINT pk_sira_tanimlari PRIMARY KEY (id),
    CONSTRAINT uq_sira_tanimlari_uuid UNIQUE (uuid),
    CONSTRAINT uq_sira_tanimlari_sema_ad UNIQUE (sema_tanimi_id, ad),
    CONSTRAINT ck_sira_tanimlari_ad CHECK (ad ~ '^[a-z][a-z0-9_]{0,99}$'),
    CONSTRAINT ck_sira_tanimlari_artis_miktari CHECK (artis_miktari <> 0),
    CONSTRAINT ck_sira_tanimlari_araliq CHECK (
        min_deger IS NULL OR max_deger IS NULL OR min_deger <= max_deger
    ),
    CONSTRAINT ck_sira_tanimlari_audit CHECK (
        guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani
    )
);

COMMENT ON TABLE akis.sira_tanimlari IS 'Sequence (sıra) tanımları — identity/serial kolonların arkasındaki sayaç.';
COMMENT ON COLUMN akis.sira_tanimlari.id IS 'Yüzeysel (surrogate) birincil anahtar.';
COMMENT ON COLUMN akis.sira_tanimlari.sema_tanimi_id IS 'Ait olduğu şema tanımı.';
COMMENT ON COLUMN akis.sira_tanimlari.ad IS 'Veritabanındaki gerçek sequence adı (ayrı bir kod/etiket tutulmaz).';
COMMENT ON COLUMN akis.sira_tanimlari.aciklama IS 'Sequence''in amacı.';
COMMENT ON COLUMN akis.sira_tanimlari.baslangic_degeri IS 'START WITH değeri.';
COMMENT ON COLUMN akis.sira_tanimlari.artis_miktari IS 'INCREMENT BY değeri.';
COMMENT ON COLUMN akis.sira_tanimlari.min_deger IS 'MINVALUE (varsa).';
COMMENT ON COLUMN akis.sira_tanimlari.max_deger IS 'MAXVALUE (varsa).';
COMMENT ON COLUMN akis.sira_tanimlari.dongusel_mi IS 'CYCLE mi.';
COMMENT ON COLUMN akis.sira_tanimlari.sahibi_kolon_tanimi_id IS 'Bu sequence''i OWNED BY olarak kullanan kolon (identity/serial ise), yoksa NULL.';
COMMENT ON COLUMN akis.sira_tanimlari.uuid IS 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.';
COMMENT ON COLUMN akis.sira_tanimlari.olusturulma_zamani IS 'Kaydın oluşturulma zamanı.';
COMMENT ON COLUMN akis.sira_tanimlari.olusturan_kullanici_id IS 'Kaydı oluşturan kullanıcı.';
COMMENT ON COLUMN akis.sira_tanimlari.guncellenme_zamani IS 'Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).';
COMMENT ON COLUMN akis.sira_tanimlari.guncelleyen_kullanici_id IS 'Kaydı son güncelleyen kullanıcı.';

-- Self-hosting: sira_tanimlari tablosunun kendisi de tablo_tanimlari'na eklenir.
INSERT INTO akis.tablo_tanimlari (sema_tanimi_id, ad, aciklama)
SELECT s.id, 'sira_tanimlari', 'Sistemdeki sequence''lerin (identity/serial kolonların arkasındaki sayaç) metadata tanımını tutar.'
FROM akis.sema_tanimlari s
WHERE s.ad = 'akis';

-- Self-hosting: sira_tanimlari tablosunun kendi kolonları.
INSERT INTO akis.kolon_tanimlari (
    tablo_tanimi_id, ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no
)
SELECT t.id, v.ad, v.aciklama, v.veri_tipi, v.uzunluk, v.zorunlu_mu, v.varsayilan_deger, v.sira_no
FROM akis.tablo_tanimlari t
CROSS JOIN (VALUES
    ('id', 'Yüzeysel (surrogate) birincil anahtar.', 'bigint', NULL::BIGINT, TRUE, 'identity', 1),
    ('sema_tanimi_id', 'Ait olduğu şema tanımı.', 'bigint', NULL, TRUE, NULL, 2),
    ('ad', 'Veritabanındaki gerçek sequence adı.', 'character varying', 200, TRUE, NULL, 3),
    ('aciklama', 'Sequence''in amacı.', 'character varying', 2000, FALSE, NULL, 4),
    ('baslangic_degeri', 'START WITH değeri.', 'bigint', NULL, TRUE, '1', 5),
    ('artis_miktari', 'INCREMENT BY değeri.', 'bigint', NULL, TRUE, '1', 6),
    ('min_deger', 'MINVALUE (varsa).', 'bigint', NULL, FALSE, NULL, 7),
    ('max_deger', 'MAXVALUE (varsa).', 'bigint', NULL, FALSE, NULL, 8),
    ('dongusel_mi', 'CYCLE mi.', 'boolean', NULL, TRUE, 'false', 9),
    ('sahibi_kolon_tanimi_id', 'Bu sequence''i OWNED BY olarak kullanan kolon.', 'bigint', NULL, FALSE, NULL, 10),
    ('uuid', 'Dış sistemlere/API''ye açılan kararlı benzersiz kimlik.', 'uuid', NULL, TRUE, 'gen_random_uuid()', 11),
    ('olusturulma_zamani', 'Kaydın oluşturulma zamanı.', 'timestamptz', NULL, TRUE, 'CURRENT_TIMESTAMP', 12),
    ('olusturan_kullanici_id', 'Kaydı oluşturan kullanıcı.', 'bigint', NULL, FALSE, NULL, 13),
    ('guncellenme_zamani', 'Kaydın son güncellenme zamanı.', 'timestamptz', NULL, FALSE, NULL, 14),
    ('guncelleyen_kullanici_id', 'Kaydı son güncelleyen kullanıcı.', 'bigint', NULL, FALSE, NULL, 15)
) AS v(ad, aciklama, veri_tipi, uzunluk, zorunlu_mu, varsayilan_deger, sira_no)
WHERE t.ad = 'sira_tanimlari';

-- Sistemdeki her tablonun kendi identity sütununu besleyen sequence'i (Postgres
-- adlandırma kuralı: <tablo>_id_seq), sahibi_kolon_tanimi_id ile ilişkili olarak.
INSERT INTO akis.sira_tanimlari (sema_tanimi_id, ad, aciklama, sahibi_kolon_tanimi_id)
SELECT s.id, t.ad || '_id_seq',
       t.ad || ' tablosunun id kolonunu besleyen identity sequence''i.',
       kl.id
FROM akis.tablo_tanimlari t
JOIN akis.sema_tanimlari s ON s.id = t.sema_tanimi_id
JOIN akis.kolon_tanimlari kl ON kl.tablo_tanimi_id = t.id AND kl.ad = 'id'
WHERE s.ad = 'akis';
