SET search_path TO akis, public;

-- Package runtime (ORACLE_PACKAGE_V1). A package run is an ordinary run whose worker walks the pinned step
-- graph: variable steps are refreshed in-process, procedure/mapping steps start a child run of the step's
-- pinned publication and execute it in the same worker before moving on. Child runs point back to the
-- package run; package steps keep their own status rows so the run detail can show the tree.

ALTER TABLE calistirma
    ADD COLUMN ust_calistirma_id BIGINT REFERENCES calistirma(id),
    ADD COLUMN ust_adim_kodu VARCHAR(100);
CREATE INDEX ix_calistirma_ust ON calistirma(ust_calistirma_id);

CREATE TABLE paket_adim_durumu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proje_id BIGINT NOT NULL,
    calistirma_id BIGINT NOT NULL,
    calistirma_adimi_id BIGINT NOT NULL,
    durum VARCHAR(20) NOT NULL DEFAULT 'BEKLIYOR' CHECK(durum IN('BEKLIYOR','CALISIYOR','BASARILI','BASARISIZ','ATLANDI')),
    alt_calistirma_id BIGINT REFERENCES calistirma(id),
    deger TEXT,
    hata_kodu VARCHAR(80),
    baslama_zamani TIMESTAMPTZ,
    bitis_zamani TIMESTAMPTZ,
    guncellenme_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT uq_paket_adim_durumu_adim UNIQUE(calistirma_adimi_id),
    CONSTRAINT fk_paket_adim_durumu_adim FOREIGN KEY(proje_id,calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id,id),
    CONSTRAINT fk_paket_adim_durumu_run FOREIGN KEY(proje_id,calistirma_id) REFERENCES calistirma(proje_id,id)
);

-- Claim one specific queued run (a package child) for the worker that owns the package run.
CREATE OR REPLACE FUNCTION calistirma_belirli_sahiplen(p_calistirma_uuid UUID,p_worker_profili_uuid UUID,p_isleyici_referansi TEXT,p_kiralama_saniyesi INTEGER)
RETURNS TABLE(calistirma_uuid UUID,nesil_no BIGINT,yayin_ozeti TEXT,plan_ozeti TEXT,kiralama_bitis_zamani TIMESTAMPTZ)
LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_worker BIGINT; v_durum calistirma_durumu%ROWTYPE;
BEGIN
 IF p_kiralama_saniyesi NOT BETWEEN 30 AND 300 OR length(btrim(p_isleyici_referansi)) NOT BETWEEN 1 AND 200 THEN RETURN; END IF;
 SELECT id INTO v_worker FROM worker_profili WHERE uuid=p_worker_profili_uuid AND etkin FOR UPDATE;
 IF NOT FOUND THEN RETURN; END IF;
 SELECT cd.* INTO v_durum FROM calistirma_durumu cd JOIN calistirma c ON c.id=cd.calistirma_id
  WHERE c.uuid=p_calistirma_uuid AND cd.durum='BEKLIYOR' AND cd.hedef_kaynagi_id IS NULL FOR UPDATE OF cd SKIP LOCKED;
 IF NOT FOUND THEN RETURN; END IF;
 UPDATE calistirma_durumu cd SET durum='SAHIPLENILDI',worker_profili_id=v_worker,isleyici_referansi=btrim(p_isleyici_referansi),
  nesil_no=cd.nesil_no+1,kiralama_bitis_zamani=clock_timestamp()+make_interval(secs=>p_kiralama_saniyesi),
  yasam_sinyali_zamani=clock_timestamp(),guncellenme_zamani=clock_timestamp(),versiyon_no=cd.versiyon_no+1
  WHERE cd.id=v_durum.id RETURNING cd.* INTO v_durum;
 UPDATE calistirma_durumu cd SET son_olay_no=cd.son_olay_no+1 WHERE cd.id=v_durum.id RETURNING cd.* INTO v_durum;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri)
 VALUES(v_durum.proje_id,v_durum.calistirma_id,v_durum.son_olay_no,'RUN_CLAIMED',clock_timestamp(),jsonb_build_object('generation',v_durum.nesil_no,'workerReference',v_durum.isleyici_referansi,'workerProfileUuid',p_worker_profili_uuid));
 RETURN QUERY SELECT c.uuid,v_durum.nesil_no,c.yayin_ozeti::TEXT,c.plan_ozeti::TEXT,v_durum.kiralama_bitis_zamani FROM calistirma c WHERE c.id=v_durum.calistirma_id;
END $$;

-- SAHIPLENILDI -> CALISIYOR for a package run (no target resource) and register its steps.
-- p_adimlar: [{"id":"STEP_1","name":"...","type":"PROCEDURE"}, ...] in execution order.
CREATE OR REPLACE FUNCTION paket_calistirmayi_baslat(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_nesil_no BIGINT,p_adimlar JSONB)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE; v_d calistirma_durumu%ROWTYPE; v_adim JSONB; v_sira INTEGER:=0; v_adim_id BIGINT;
BEGIN
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid; IF NOT FOUND THEN RETURN FALSE; END IF;
 SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 IF v_d.durum='CALISIYOR' AND v_d.nesil_no=p_nesil_no AND v_d.isleyici_referansi=p_isleyici_referansi THEN RETURN TRUE; END IF;
 IF v_d.durum<>'SAHIPLENILDI' OR v_d.nesil_no<>p_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi OR v_d.kiralama_bitis_zamani<=clock_timestamp() THEN RETURN FALSE; END IF;
 FOR v_adim IN SELECT * FROM jsonb_array_elements(p_adimlar) LOOP
  v_sira:=v_sira+1;
  INSERT INTO calistirma_adimi(proje_id,calistirma_id,adim_kodu,tur,sira_no,ad)
  VALUES(v_c.proje_id,v_c.id,v_adim->>'id','PAKET',v_sira,left(coalesce(v_adim->>'name',v_adim->>'id'),200)) RETURNING id INTO v_adim_id;
  INSERT INTO paket_adim_durumu(proje_id,calistirma_id,calistirma_adimi_id) VALUES(v_c.proje_id,v_c.id,v_adim_id);
 END LOOP;
 UPDATE calistirma_durumu SET durum='CALISIYOR',baslama_zamani=coalesce(baslama_zamani,clock_timestamp()),son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_d.id RETURNING * INTO v_d;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri)
 VALUES(v_c.proje_id,v_c.id,v_d.son_olay_no,'PACKAGE_STARTED',clock_timestamp(),jsonb_build_object('generation',p_nesil_no,'steps',v_sira));
 RETURN TRUE;
END $$;

-- Package step transitions. p_durum: CALISIYOR | BASARILI | BASARISIZ | ATLANDI. Optional child run and value.
CREATE OR REPLACE FUNCTION paket_adimini_guncelle(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_nesil_no BIGINT,p_adim_kodu TEXT,p_durum TEXT,p_alt_calistirma_uuid UUID,p_deger TEXT,p_hata_kodu TEXT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE; v_d calistirma_durumu%ROWTYPE; v_a calistirma_adimi%ROWTYPE; v_alt BIGINT;
BEGIN
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid; IF NOT FOUND THEN RETURN FALSE; END IF;
 SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 IF v_d.durum<>'CALISIYOR' OR v_d.nesil_no<>p_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi OR v_d.kiralama_bitis_zamani<=clock_timestamp() THEN RETURN FALSE; END IF;
 SELECT * INTO v_a FROM calistirma_adimi WHERE calistirma_id=v_c.id AND adim_kodu=p_adim_kodu; IF NOT FOUND THEN RETURN FALSE; END IF;
 IF p_alt_calistirma_uuid IS NOT NULL THEN SELECT id INTO v_alt FROM calistirma WHERE uuid=p_alt_calistirma_uuid; END IF;
 UPDATE paket_adim_durumu SET durum=p_durum,
   alt_calistirma_id=coalesce(v_alt,alt_calistirma_id), deger=coalesce(p_deger,deger), hata_kodu=p_hata_kodu,
   baslama_zamani=CASE WHEN p_durum='CALISIYOR' THEN clock_timestamp() ELSE coalesce(baslama_zamani,clock_timestamp()) END,
   bitis_zamani=CASE WHEN p_durum IN('BASARILI','BASARISIZ','ATLANDI') THEN clock_timestamp() ELSE NULL END,
   guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1
  WHERE calistirma_adimi_id=v_a.id;
 UPDATE calistirma_durumu SET son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp() WHERE id=v_d.id RETURNING * INTO v_d;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,calistirma_adimi_id,olay_no,tur,olay_zamani,veri)
 VALUES(v_c.proje_id,v_c.id,v_a.id,v_d.son_olay_no,'PACKAGE_STEP_'||p_durum,clock_timestamp(),
        jsonb_build_object('stepCode',p_adim_kodu,'childRunUuid',p_alt_calistirma_uuid,'value',p_deger,'errorCode',p_hata_kodu));
 RETURN TRUE;
END $$;

-- Terminal package state: BASARILI or BASARISIZ. Releases the lease.
CREATE OR REPLACE FUNCTION paket_calistirmayi_bitir(p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_nesil_no BIGINT,p_durum TEXT,p_hata_kodu TEXT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE; v_d calistirma_durumu%ROWTYPE;
BEGIN
 IF p_durum NOT IN('BASARILI','BASARISIZ') THEN RETURN FALSE; END IF;
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid; IF NOT FOUND THEN RETURN FALSE; END IF;
 SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 IF v_d.durum=p_durum THEN RETURN TRUE; END IF;
 IF v_d.durum NOT IN('SAHIPLENILDI','CALISIYOR') OR v_d.nesil_no<>p_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi THEN RETURN FALSE; END IF;
 UPDATE calistirma_durumu SET durum=p_durum,kiralama_bitis_zamani=NULL,bitis_zamani=clock_timestamp(),son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_d.id RETURNING * INTO v_d;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri)
 VALUES(v_c.proje_id,v_c.id,v_d.son_olay_no,CASE WHEN p_durum='BASARILI' THEN 'PACKAGE_SUCCEEDED' ELSE 'PACKAGE_FAILED' END,clock_timestamp(),
        jsonb_build_object('generation',p_nesil_no,'workerReference',p_isleyici_referansi,'errorCode',p_hata_kodu));
 RETURN TRUE;
END $$;

REVOKE ALL ON FUNCTION calistirma_belirli_sahiplen(UUID,UUID,TEXT,INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION paket_calistirmayi_baslat(UUID,TEXT,BIGINT,JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION paket_adimini_guncelle(UUID,TEXT,BIGINT,TEXT,TEXT,UUID,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION paket_calistirmayi_bitir(UUID,TEXT,BIGINT,TEXT,TEXT) FROM PUBLIC;
