SET search_path TO akis, public;

-- Column-level data protection on a data store, kept by column name so it survives new schema snapshots.
-- koruma: SIFRELE = the value is encrypted by the runtime while it is read from the source (AES-256-GCM with
-- the deployment key); more policies (MASKELE, HASH) plug into the same table later.
CREATE TABLE veri_nesnesi_kolon_politikasi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proje_id BIGINT NOT NULL,
    veri_nesnesi_id BIGINT NOT NULL,
    kolon_adi VARCHAR(128) NOT NULL CHECK (kolon_adi ~ '^[A-Z][A-Z0-9_$#]{0,127}$'),
    sinif VARCHAR(30) NOT NULL DEFAULT 'HASSAS' CHECK (sinif IN ('HASSAS','KISISEL','FINANSAL','GIZLI')),
    koruma VARCHAR(20) NOT NULL DEFAULT 'SIFRELE' CHECK (koruma IN ('SIFRELE','MASKELE','HASH')),
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT uq_veri_nesnesi_kolon_politikasi UNIQUE (veri_nesnesi_id, kolon_adi),
    CONSTRAINT fk_kolon_politikasi_nesne FOREIGN KEY (proje_id, veri_nesnesi_id) REFERENCES veri_nesnesi(proje_id, id)
);
