SET search_path TO akis, public;

-- Schedule definitions that fire a publication's runs automatically on a cron cadence. Mirrors hedef_saglama_politikasi's
-- minimal shape (V048): no elaborate audit trail, optimistic locking via versiyon_no, app owns cron parsing/validation.
--   AKTIF   — the due-scan poller may fire this schedule.
--   ASKIDA  — paused; the poller skips it (default, so a newly created schedule never fires by accident).
-- cakisma_politikasi (overlap while a previous scheduled run for this schedule is still active):
--   SKIP    — do not create a new job request this tick.
--   QUEUE   — create it anyway; it queues behind the active run like any other job request.
-- kacirma_politikasi (a due time missed because the poller itself was down):
--   SKIP     — never backfill; jump straight to the next future occurrence.
--   RUN_ONCE — fire once for the most recently missed time, then resume the normal cadence.
CREATE TABLE zamanlama (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    yayin_id BIGINT NOT NULL,
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    -- The due-scan poller starts each scheduled run as this user (their permissions authorized the schedule itself;
    -- the run needs some kullanici to attribute olusturan_kullanici_id to, same as any other run).
    olusturan_kullanici_id BIGINT NOT NULL REFERENCES kullanici(id),
    durum_kodu VARCHAR(20) NOT NULL DEFAULT 'ASKIDA',
    cron_ifadesi VARCHAR(120) NOT NULL,
    zaman_dilimi VARCHAR(60) NOT NULL DEFAULT 'UTC',
    cakisma_politikasi VARCHAR(20) NOT NULL DEFAULT 'SKIP',
    kacirma_politikasi VARCHAR(20) NOT NULL DEFAULT 'SKIP',
    sonraki_tetikleme_zamani TIMESTAMPTZ,
    son_tetikleme_zamani TIMESTAMPTZ,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    guncellenme_zamani TIMESTAMPTZ,
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT uq_zamanlama_uuid UNIQUE (uuid),
    CONSTRAINT uq_zamanlama_proje_id UNIQUE (proje_id, id),
    CONSTRAINT uq_zamanlama_kod UNIQUE (proje_id, kod),
    CONSTRAINT fk_zamanlama_yayin FOREIGN KEY (proje_id, yayin_id) REFERENCES yayin(proje_id, id),
    CONSTRAINT ck_zamanlama_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_zamanlama_durum CHECK (durum_kodu IN ('AKTIF', 'ASKIDA')),
    CONSTRAINT ck_zamanlama_cakisma CHECK (cakisma_politikasi IN ('SKIP', 'QUEUE')),
    CONSTRAINT ck_zamanlama_kacirma CHECK (kacirma_politikasi IN ('SKIP', 'RUN_ONCE')),
    CONSTRAINT ck_zamanlama_tetikleme CHECK (durum_kodu = 'ASKIDA' OR sonraki_tetikleme_zamani IS NOT NULL),
    CONSTRAINT ck_zamanlama_audit CHECK (versiyon_no > 0 AND (guncellenme_zamani IS NULL OR guncellenme_zamani >= olusturulma_zamani))
);
CREATE INDEX ix_zamanlama_tetikleme ON zamanlama(durum_kodu, sonraki_tetikleme_zamani);

-- Which schedule (if any) produced a job request; the due-scan poller sets both together and relies on
-- uq_is_talebi_zamanlama to make firing the same occurrence twice (e.g. after a poller crash mid-tick) a no-op conflict
-- rather than a duplicate run.
ALTER TABLE is_talebi ADD COLUMN zamanlama_id BIGINT;
ALTER TABLE is_talebi ADD CONSTRAINT fk_is_talebi_zamanlama FOREIGN KEY (proje_id, zamanlama_id) REFERENCES zamanlama(proje_id, id);
CREATE UNIQUE INDEX uq_is_talebi_zamanlama ON is_talebi(zamanlama_id, planlanan_zaman) WHERE zamanlama_id IS NOT NULL;

-- ZAMANLAMA_YONET already exists (V001); add the matching read permission, granted to the same roles that can already
-- see runs (CALISTIRMA_GORUNTULE), since a schedule's own history is just its runs filtered by trigger source.
INSERT INTO yetki(kapsam, kod, kaynak, eylem, aciklama) VALUES
    ('PROJE', 'ZAMANLAMA_GORUNTULE', 'ZAMANLAMA', 'GORUNTULE', 'Zamanlamaları görüntüler.');

INSERT INTO rol_yetki(rol_id, yetki_id, kapsam)
SELECT r.id, y.id, r.kapsam
  FROM rol r, yetki y
 WHERE y.kod = 'ZAMANLAMA_GORUNTULE' AND y.kapsam = r.kapsam
   AND r.kod IN ('GELISTIRICI', 'OPERASYON', 'YAYIN_ONAYLAYICI', 'GORUNTULEYICI');
