SET search_path TO akis, public;

CREATE TABLE kullanici_guvenlik_durumu (
    kullanici_id BIGINT NOT NULL,
    hata_penceresi_baslangici TIMESTAMPTZ,
    kilit_bitis_zamani TIMESTAMPTZ,
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_kullanici_guvenlik_durumu PRIMARY KEY (kullanici_id),
    CONSTRAINT fk_kullanici_guvenlik_durumu_kullanici
        FOREIGN KEY (kullanici_id) REFERENCES kullanici(id) ON DELETE CASCADE,
    CONSTRAINT ck_kullanici_guvenlik_durumu_versiyon
        CHECK (versiyon_no > 0)
);

CREATE TABLE parola_kurulum_tokeni (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kullanici_id BIGINT NOT NULL REFERENCES kullanici(id) ON DELETE CASCADE,
    token_ozeti VARCHAR(255) NOT NULL,
    gecerlilik_sonu TIMESTAMPTZ NOT NULL,
    kullanilma_zamani TIMESTAMPTZ,
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_parola_kurulum_tokeni PRIMARY KEY (id),
    CONSTRAINT uq_parola_kurulum_tokeni_ozet UNIQUE (token_ozeti),
    CONSTRAINT ck_parola_kurulum_tokeni_gecerlilik
        CHECK (gecerlilik_sonu > olusturulma_zamani),
    CONSTRAINT ck_parola_kurulum_tokeni_kullanim
        CHECK (kullanilma_zamani IS NULL OR kullanilma_zamani >= olusturulma_zamani)
);

CREATE INDEX ix_parola_kurulum_tokeni_aktif
    ON parola_kurulum_tokeni(kullanici_id, gecerlilik_sonu)
    WHERE kullanilma_zamani IS NULL;

CREATE TABLE giris_ip_durumu (
    ip_adresi INET NOT NULL,
    pencere_baslangici TIMESTAMPTZ NOT NULL,
    deneme_sayisi INTEGER NOT NULL DEFAULT 0,
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT pk_giris_ip_durumu PRIMARY KEY (ip_adresi),
    CONSTRAINT ck_giris_ip_durumu_sayac CHECK (deneme_sayisi >= 0),
    CONSTRAINT ck_giris_ip_durumu_versiyon CHECK (versiyon_no > 0)
);

-- Spring Session JDBC şeması uygulamanın Flyway yaşam döngüsünde tutulur;
-- framework'ün otomatik initialize-schema özelliği bilinçli olarak kullanılmaz.
CREATE TABLE spring_session (
    primary_id CHAR(36) NOT NULL,
    session_id CHAR(36) NOT NULL,
    creation_time BIGINT NOT NULL,
    last_access_time BIGINT NOT NULL,
    max_inactive_interval INTEGER NOT NULL,
    expiry_time BIGINT NOT NULL,
    principal_name VARCHAR(100),
    CONSTRAINT pk_spring_session PRIMARY KEY (primary_id),
    CONSTRAINT uq_spring_session_id UNIQUE (session_id)
);

CREATE INDEX ix_spring_session_expiry
    ON spring_session(expiry_time);
CREATE INDEX ix_spring_session_principal
    ON spring_session(principal_name);

CREATE TABLE spring_session_attributes (
    session_primary_id CHAR(36) NOT NULL,
    attribute_name VARCHAR(200) NOT NULL,
    attribute_bytes BYTEA NOT NULL,
    CONSTRAINT pk_spring_session_attributes
        PRIMARY KEY (session_primary_id, attribute_name),
    CONSTRAINT fk_spring_session_attributes_session
        FOREIGN KEY (session_primary_id) REFERENCES spring_session(primary_id)
        ON DELETE CASCADE
);
