SET search_path TO akis, public;

-- Target-project bundle imports are intentionally separate from run idempotency.
-- The unique key makes a completed import replayable while the payload digests
-- prevent the same client key from being reused for different content.
CREATE TABLE proje_paket_ithalati (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    idempotency_key VARCHAR(200) NOT NULL,
    bundle_checksum CHAR(64) NOT NULL,
    plan_digest CHAR(64) NOT NULL,
    hedef_proje_surumu BIGINT NOT NULL,
    sonuc JSONB NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_proje_paket_ithalati PRIMARY KEY (id),
    CONSTRAINT uq_proje_paket_ithalati_uuid UNIQUE (uuid),
    CONSTRAINT uq_proje_paket_ithalati_anahtar UNIQUE (proje_id, idempotency_key),
    CONSTRAINT ck_proje_paket_ithalati_checksum CHECK (
        bundle_checksum ~ '^[0-9a-f]{64}$' AND plan_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_proje_paket_ithalati_surum CHECK (hedef_proje_surumu > 0),
    CONSTRAINT ck_proje_paket_ithalati_sonuc CHECK (jsonb_typeof(sonuc) = 'object')
);

CREATE INDEX ix_proje_paket_ithalati_zaman
    ON proje_paket_ithalati(proje_id, olusturulma_zamani DESC);

-- Imported catalog columns are useful design metadata, but they are never a
-- discovery/runtime proof. A fresh provider discovery must replace this state
-- before a publication can rely on it.
CREATE TABLE ithal_katalog_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    veri_nesnesi_id BIGINT NOT NULL,
    dogrulama_durumu VARCHAR(30) NOT NULL DEFAULT 'IMPORTED_UNVERIFIED',
    kolonlar JSONB NOT NULL DEFAULT '[]'::jsonb,
    kaynak_bundle_checksum CHAR(64) NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_ithal_katalog_metadata PRIMARY KEY (id),
    CONSTRAINT uq_ithal_katalog_metadata_uuid UNIQUE (uuid),
    CONSTRAINT uq_ithal_katalog_metadata_nesne UNIQUE (veri_nesnesi_id),
    CONSTRAINT fk_ithal_katalog_metadata_nesne
        FOREIGN KEY (proje_id, veri_nesnesi_id)
        REFERENCES veri_nesnesi(proje_id, id),
    CONSTRAINT ck_ithal_katalog_metadata_durum CHECK (
        dogrulama_durumu = 'IMPORTED_UNVERIFIED'),
    CONSTRAINT ck_ithal_katalog_metadata_kolonlar CHECK (
        jsonb_typeof(kolonlar) = 'array'),
    CONSTRAINT ck_ithal_katalog_metadata_checksum CHECK (
        kaynak_bundle_checksum ~ '^[0-9a-f]{64}$')
);

CREATE INDEX ix_ithal_katalog_metadata_proje
    ON ithal_katalog_metadata(proje_id);
