SET search_path TO akis, public;

-- Secret-free SQL text persisted with each procedure execution step.
CREATE TABLE prosedur_sql_kaniti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL,
    calistirma_id BIGINT NOT NULL,
    calistirma_adimi_id BIGINT NOT NULL,
    calistirilan_sql JSONB NOT NULL,
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (id),
    CONSTRAINT uq_prosedur_sql_kaniti_adim UNIQUE (calistirma_adimi_id),
    CONSTRAINT fk_prosedur_sql_kaniti_run
        FOREIGN KEY (proje_id, calistirma_id) REFERENCES calistirma(proje_id, id),
    CONSTRAINT fk_prosedur_sql_kaniti_adim
        FOREIGN KEY (proje_id, calistirma_adimi_id) REFERENCES calistirma_adimi(proje_id, id),
    CONSTRAINT ck_prosedur_sql_kaniti_json
        CHECK (jsonb_typeof(calistirilan_sql) = 'array')
);

CREATE INDEX ix_prosedur_sql_kaniti_run
    ON prosedur_sql_kaniti(proje_id, calistirma_id);

CREATE TRIGGER trg_prosedur_sql_kaniti_degismez
    BEFORE UPDATE OR DELETE ON prosedur_sql_kaniti
    FOR EACH ROW EXECUTE FUNCTION degismez_calistirma_kanitini_koru();

COMMENT ON TABLE prosedur_sql_kaniti IS
    'Prosedür çalıştırma adımında saklanan, sır içermeyen SQL kanıtı.';
