SET search_path TO akis, public;

-- Durable staging for a v3 bundle's publication/schedule recipes after import.
-- The bundle carries no source ids, so a recipe is anchored purely to real
-- target-side rows (definition, definition version, environment) created by
-- the same import. This is intentionally NOT a publication: no yayin row, no
-- release manifest, no approval/run evidence. It exists only so a later
-- integration step can create the real yayin/zamanlama once matched, without
-- ever auto-activating a schedule from imported data.
CREATE TABLE ithal_yayin_tarifi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    tanim_id BIGINT NOT NULL,
    tanim_surumu_id BIGINT NOT NULL,
    ortam_id BIGINT NOT NULL REFERENCES ortam(id),
    kaynak_bundle_checksum CHAR(64) NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_ithal_yayin_tarifi PRIMARY KEY (id),
    CONSTRAINT uq_ithal_yayin_tarifi_uuid UNIQUE (uuid),
    CONSTRAINT uq_ithal_yayin_tarifi_proje_id UNIQUE (proje_id, id),
    CONSTRAINT uq_ithal_yayin_tarifi_hedef UNIQUE (proje_id, tanim_surumu_id, ortam_id),
    CONSTRAINT fk_ithal_yayin_tarifi_tanim
        FOREIGN KEY (proje_id, tanim_id) REFERENCES tanim(proje_id, id),
    CONSTRAINT fk_ithal_yayin_tarifi_surum
        FOREIGN KEY (proje_id, tanim_surumu_id) REFERENCES tanim_surumu(proje_id, id),
    CONSTRAINT ck_ithal_yayin_tarifi_checksum CHECK (
        kaynak_bundle_checksum ~ '^[0-9a-f]{64}$')
);

CREATE INDEX ix_ithal_yayin_tarifi_proje ON ithal_yayin_tarifi(proje_id);

-- The two foreign keys above prove project ownership independently. This
-- additional check proves the imported version actually belongs to the
-- imported definition, so a mismatched pair cannot be staged as a recipe.
CREATE FUNCTION ithal_yayin_tarifi_surumu_dogrula() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM akis.tanim_surumu ts
         WHERE ts.id = NEW.tanim_surumu_id
           AND ts.tanim_id = NEW.tanim_id
           AND ts.proje_id = NEW.proje_id
    ) THEN
        RAISE EXCEPTION 'İthal yayın tarifi sürümü hedef tanıma ait olmalıdır.'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER trg_ithal_yayin_tarifi_surumu
    BEFORE INSERT OR UPDATE OF proje_id, tanim_id, tanim_surumu_id
    ON ithal_yayin_tarifi
    FOR EACH ROW EXECUTE FUNCTION ithal_yayin_tarifi_surumu_dogrula();

-- Declarative schedule recipe waiting on ithal_yayin_tarifi. No durum_kodu:
-- an imported schedule recipe is never activated by import alone, and no
-- sonraki/son tetikleme columns: next/last fire time is runtime evidence,
-- never transferred.
CREATE TABLE ithal_zamanlama_tarifi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proje_id BIGINT NOT NULL REFERENCES proje(id),
    yayin_tarifi_id BIGINT NOT NULL,
    kod VARCHAR(100) NOT NULL,
    ad VARCHAR(200) NOT NULL,
    cron_ifadesi VARCHAR(120) NOT NULL,
    zaman_dilimi VARCHAR(60) NOT NULL DEFAULT 'UTC',
    cakisma_politikasi VARCHAR(20) NOT NULL DEFAULT 'SKIP',
    kacirma_politikasi VARCHAR(20) NOT NULL DEFAULT 'SKIP',
    yayin_gorunum_kodu VARCHAR(20) NOT NULL DEFAULT 'LATEST_ACTIVE',
    kaynak_bundle_checksum CHAR(64) NOT NULL,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    olusturulma_zamani TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    olusturan_kullanici_id BIGINT REFERENCES kullanici(id),
    CONSTRAINT pk_ithal_zamanlama_tarifi PRIMARY KEY (id),
    CONSTRAINT uq_ithal_zamanlama_tarifi_uuid UNIQUE (uuid),
    CONSTRAINT uq_ithal_zamanlama_tarifi_kod UNIQUE (proje_id, kod),
    CONSTRAINT fk_ithal_zamanlama_tarifi_yayin_tarifi
        FOREIGN KEY (proje_id, yayin_tarifi_id) REFERENCES ithal_yayin_tarifi(proje_id, id),
    CONSTRAINT ck_ithal_zamanlama_tarifi_kod CHECK (kod ~ '^[A-Z][A-Z0-9_]{0,99}$'),
    CONSTRAINT ck_ithal_zamanlama_tarifi_cakisma CHECK (cakisma_politikasi IN ('SKIP', 'QUEUE')),
    CONSTRAINT ck_ithal_zamanlama_tarifi_kacirma CHECK (kacirma_politikasi IN ('SKIP', 'RUN_ONCE')),
    CONSTRAINT ck_ithal_zamanlama_tarifi_yayin_gorunum CHECK (
        yayin_gorunum_kodu IN ('LATEST_ACTIVE', 'PINNED')),
    CONSTRAINT ck_ithal_zamanlama_tarifi_checksum CHECK (
        kaynak_bundle_checksum ~ '^[0-9a-f]{64}$')
);

CREATE INDEX ix_ithal_zamanlama_tarifi_proje ON ithal_zamanlama_tarifi(proje_id);
CREATE INDEX ix_ithal_zamanlama_tarifi_yayin_tarifi ON ithal_zamanlama_tarifi(yayin_tarifi_id);
