SET search_path TO akis, public;

-- Durable package continuation. A yielded package is returned to BEKLIYOR and
-- is reclaimed by the existing package-child claim path; the cursor prevents
-- replaying already dispatched/completed steps after a worker restart.
CREATE TABLE paket_yurutme_durumu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proje_id BIGINT NOT NULL,
    calistirma_id BIGINT NOT NULL,
    nesil_no BIGINT NOT NULL,
    sonraki_adim_kodu VARCHAR(100),
    guncellenme_zamani TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    versiyon_no BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT uq_paket_yurutme_run UNIQUE (calistirma_id),
    CONSTRAINT fk_paket_yurutme_run FOREIGN KEY (proje_id, calistirma_id)
        REFERENCES calistirma(proje_id, id)
);

ALTER TABLE paket_adim_durumu DROP CONSTRAINT IF EXISTS paket_adim_durumu_durum_check;
ALTER TABLE paket_adim_durumu ADD CONSTRAINT paket_adim_durumu_durum_check
    CHECK (durum IN ('BEKLIYOR','CALISIYOR','DISPATCHED','BASARILI','BASARISIZ','ATLANDI'));

CREATE OR REPLACE FUNCTION paket_yurutme_cursor_guncelle(
    p_calistirma_uuid UUID, p_isleyici_referansi TEXT, p_nesil_no BIGINT,
    p_sonraki_adim_kodu TEXT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE; v_d calistirma_durumu%ROWTYPE;
BEGIN
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid;
 IF NOT FOUND THEN RETURN FALSE; END IF;
 SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 IF v_d.durum <> 'CALISIYOR' OR v_d.nesil_no<>p_nesil_no
    OR v_d.isleyici_referansi<>p_isleyici_referansi
    OR v_d.kiralama_bitis_zamani<=clock_timestamp() THEN RETURN FALSE; END IF;
 INSERT INTO paket_yurutme_durumu(proje_id,calistirma_id,nesil_no,sonraki_adim_kodu)
 VALUES(v_c.proje_id,v_c.id,p_nesil_no,p_sonraki_adim_kodu)
 ON CONFLICT (calistirma_id) DO UPDATE SET
   nesil_no=excluded.nesil_no, sonraki_adim_kodu=excluded.sonraki_adim_kodu,
   guncellenme_zamani=clock_timestamp(), versiyon_no=paket_yurutme_durumu.versiyon_no+1;
 RETURN TRUE;
END $$;

CREATE OR REPLACE FUNCTION paket_yurutme_cursor_get(p_calistirma_uuid UUID)
RETURNS TABLE(nesil_no BIGINT, sonraki_adim_kodu TEXT)
LANGUAGE sql STABLE SET search_path=akis,public AS $$
 SELECT p.nesil_no,p.sonraki_adim_kodu
   FROM paket_yurutme_durumu p JOIN calistirma c ON c.id=p.calistirma_id
  WHERE c.uuid=p_calistirma_uuid;
$$;

CREATE OR REPLACE FUNCTION paket_acik_alt_calistirma_var(p_calistirma_uuid UUID)
RETURNS BOOLEAN LANGUAGE sql STABLE SET search_path=akis,public AS $$
 SELECT EXISTS (
   SELECT 1 FROM calistirma child JOIN calistirma parent ON parent.id=child.ust_calistirma_id
   JOIN calistirma_durumu state ON state.calistirma_id=child.id
  WHERE parent.uuid=p_calistirma_uuid
    AND state.durum NOT IN ('BASARILI','BASARISIZ','IPTAL','SONUC_BELIRSIZ','YENIDEN_DENENEBILIR','MUDAHALE_GEREKLI')
 );
$$;

CREATE OR REPLACE FUNCTION paket_yurutmeyi_beklet(
    p_calistirma_uuid UUID, p_isleyici_referansi TEXT, p_nesil_no BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE; v_d calistirma_durumu%ROWTYPE;
BEGIN
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid;
 IF NOT FOUND THEN RETURN FALSE; END IF;
 SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 IF v_d.durum<>'CALISIYOR' OR v_d.nesil_no<>p_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi THEN RETURN FALSE; END IF;
 UPDATE calistirma_durumu SET durum='BEKLIYOR', isleyici_referansi=NULL, worker_profili_id=NULL,
   kiralama_bitis_zamani=NULL, yasam_sinyali_zamani=NULL, son_olay_no=son_olay_no+1,
   guncellenme_zamani=clock_timestamp(), versiyon_no=versiyon_no+1 WHERE id=v_d.id;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri)
 VALUES(v_c.proje_id,v_c.id,v_d.son_olay_no+1,'PACKAGE_YIELDED',clock_timestamp(),jsonb_build_object('generation',p_nesil_no));
 RETURN TRUE;
END $$;

-- Never acknowledge package success while a dispatched child is unresolved.
CREATE OR REPLACE FUNCTION paket_calistirmayi_bitir(
    p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_nesil_no BIGINT,
    p_durum TEXT,p_hata_kodu TEXT)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE; v_d calistirma_durumu%ROWTYPE;
BEGIN
 IF p_durum NOT IN('BASARILI','BASARISIZ') THEN RETURN FALSE; END IF;
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid; IF NOT FOUND THEN RETURN FALSE; END IF;
 IF p_durum='BASARILI' AND paket_acik_alt_calistirma_var(p_calistirma_uuid) THEN RETURN FALSE; END IF;
 SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 IF v_d.durum=p_durum THEN RETURN TRUE; END IF;
 IF v_d.durum NOT IN('SAHIPLENILDI','CALISIYOR') OR v_d.nesil_no<>p_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi THEN RETURN FALSE; END IF;
 UPDATE calistirma_durumu SET durum=p_durum,kiralama_bitis_zamani=NULL,bitis_zamani=clock_timestamp(),son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1 WHERE id=v_d.id RETURNING * INTO v_d;
 INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri)
 VALUES(v_c.proje_id,v_c.id,v_d.son_olay_no,CASE WHEN p_durum='BASARILI' THEN 'PACKAGE_SUCCEEDED' ELSE 'PACKAGE_FAILED' END,clock_timestamp(),jsonb_build_object('generation',p_nesil_no,'workerReference',p_isleyici_referansi,'errorCode',p_hata_kodu));
 RETURN TRUE;
END $$;

-- Reclaiming a yielded package must not duplicate its step rows.
CREATE OR REPLACE FUNCTION paket_calistirmayi_baslat(
    p_calistirma_uuid UUID,p_isleyici_referansi TEXT,p_nesil_no BIGINT,p_adimlar JSONB)
RETURNS BOOLEAN LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_c calistirma%ROWTYPE; v_d calistirma_durumu%ROWTYPE; v_adim JSONB; v_sira INTEGER:=0; v_adim_id BIGINT;
BEGIN
 SELECT * INTO v_c FROM calistirma WHERE uuid=p_calistirma_uuid; IF NOT FOUND THEN RETURN FALSE; END IF;
 SELECT * INTO v_d FROM calistirma_durumu WHERE calistirma_id=v_c.id FOR UPDATE;
 IF v_d.durum='CALISIYOR' AND v_d.nesil_no=p_nesil_no AND v_d.isleyici_referansi=p_isleyici_referansi THEN RETURN TRUE; END IF;
 IF v_d.durum<>'SAHIPLENILDI' OR v_d.nesil_no<>p_nesil_no OR v_d.isleyici_referansi<>p_isleyici_referansi OR v_d.kiralama_bitis_zamani<=clock_timestamp() THEN RETURN FALSE; END IF;
 IF EXISTS (SELECT 1 FROM calistirma_adimi WHERE calistirma_id=v_c.id AND tur='PAKET') THEN
   UPDATE calistirma_durumu SET durum='CALISIYOR',isleyici_referansi=p_isleyici_referansi,
     kiralama_bitis_zamani=clock_timestamp()+interval '60 seconds',yasam_sinyali_zamani=clock_timestamp(),
      son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1
      WHERE id=v_d.id RETURNING * INTO v_d;
    INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri)
    VALUES(v_c.proje_id,v_c.id,v_d.son_olay_no,'PACKAGE_STARTED',clock_timestamp(),
           jsonb_build_object('generation',p_nesil_no,'steps',(SELECT count(*) FROM calistirma_adimi WHERE calistirma_id=v_c.id AND tur='PAKET'),'reclaimed',true));
   RETURN TRUE;
 END IF;
 FOR v_adim IN SELECT * FROM jsonb_array_elements(p_adimlar) LOOP
  v_sira:=v_sira+1;
  INSERT INTO calistirma_adimi(proje_id,calistirma_id,adim_kodu,tur,sira_no,ad)
  VALUES(v_c.proje_id,v_c.id,v_adim->>'id','PAKET',v_sira,left(coalesce(v_adim->>'name',v_adim->>'id'),200)) RETURNING id INTO v_adim_id;
  INSERT INTO paket_adim_durumu(proje_id,calistirma_id,calistirma_adimi_id) VALUES(v_c.proje_id,v_c.id,v_adim_id);
 END LOOP;
  UPDATE calistirma_durumu SET durum='CALISIYOR',baslama_zamani=coalesce(baslama_zamani,clock_timestamp()),
    son_olay_no=son_olay_no+1,guncellenme_zamani=clock_timestamp(),versiyon_no=versiyon_no+1
    WHERE id=v_d.id RETURNING * INTO v_d;
  INSERT INTO calistirma_olayi(proje_id,calistirma_id,olay_no,tur,olay_zamani,veri)
  VALUES(v_c.proje_id,v_c.id,v_d.son_olay_no,'PACKAGE_STARTED',clock_timestamp(),
         jsonb_build_object('generation',p_nesil_no,'steps',v_sira));
 RETURN TRUE;
END $$;

-- Child creation and the parent stop/lease check must share one row lock.  A
-- checkpoint immediately before dispatch is not sufficient: a stop request
-- may arrive in the gap between the checkpoint and the INSERT.
CREATE OR REPLACE FUNCTION paket_alt_calistirma_olustur(
    p_parent_uuid UUID, p_worker_reference TEXT, p_generation BIGINT,
    p_step_code TEXT, p_publication_uuid UUID, p_job_uuid UUID, p_run_uuid UUID)
RETURNS UUID LANGUAGE plpgsql SET search_path=akis,public AS $$
DECLARE v_parent calistirma%ROWTYPE; v_parent_state calistirma_durumu%ROWTYPE;
        v_publication_id BIGINT; v_request_id BIGINT; v_run_uuid UUID := p_run_uuid;
BEGIN
 SELECT c.* INTO v_parent FROM calistirma c WHERE c.uuid=p_parent_uuid FOR UPDATE;
 IF NOT FOUND THEN RETURN NULL; END IF;
 SELECT * INTO v_parent_state FROM calistirma_durumu
  WHERE calistirma_id=v_parent.id FOR UPDATE;
 IF v_parent_state.durum <> 'CALISIYOR'
    OR v_parent_state.nesil_no<>p_generation
    OR v_parent_state.isleyici_referansi<>p_worker_reference
    OR v_parent_state.kiralama_bitis_zamani<=clock_timestamp() THEN RETURN NULL; END IF;
 SELECT y.id INTO v_publication_id
   FROM yayin y
  WHERE y.uuid=p_publication_uuid AND y.durum='AKTIF';
 IF NOT FOUND THEN RETURN NULL; END IF;
 INSERT INTO is_talebi(proje_id, yayin_id, istek_ozeti, is_turu, oncelik,
        parametre_sema_surumu, parametre, uuid, olusturan_kullanici_id)
 SELECT y.proje_id, y.id,
        encode(sha256(convert_to(p_run_uuid::text || '|' || p_step_code, 'UTF8')), 'hex'),
        'CALISTIR', 60, 1,
        jsonb_build_object('packageRunUuid',p_parent_uuid,'packageStepCode',p_step_code)
          || (parent_job.parametre - 'packageRunUuid' - 'packageStepCode'),
        p_job_uuid, v_parent.olusturan_kullanici_id
   FROM yayin y JOIN is_talebi parent_job ON parent_job.id=v_parent.is_talebi_id
   WHERE y.id=v_publication_id
 RETURNING id INTO v_request_id;
 IF v_request_id IS NULL THEN RETURN NULL; END IF;
 INSERT INTO calistirma(proje_id, is_talebi_id, deneme_no, yayin_ozeti,
        plan_ozeti, baslatma_turu, uuid, olusturan_kullanici_id,
        ust_calistirma_id, ust_adim_kodu)
 SELECT y.proje_id, v_request_id, 1, y.fiziksel_manifesto->>'releaseHash',
        s.plan_ozeti, 'ILK', v_run_uuid, v_parent.olusturan_kullanici_id,
        v_parent.id, p_step_code
   FROM yayin y JOIN senaryo s ON s.id=y.senaryo_id
  WHERE y.id=v_publication_id;
 RETURN v_run_uuid;
EXCEPTION WHEN unique_violation THEN
 RETURN NULL;
END $$;

REVOKE ALL ON FUNCTION paket_yurutme_cursor_guncelle(UUID,TEXT,BIGINT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION paket_yurutme_cursor_get(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION paket_acik_alt_calistirma_var(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION paket_yurutmeyi_beklet(UUID,TEXT,BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION paket_alt_calistirma_olustur(UUID,TEXT,BIGINT,TEXT,UUID,UUID,UUID) FROM PUBLIC;
